export default {
  vocab: [
{ id:"a1x1", de:"Gute Nacht", art:"", pl:"", en:"good night", topic:"greetings", level:"a1" , ex:"Gute Nacht — bis morgen im Kurs.", exEn:"Good night — see you tomorrow in class."},
{ id:"a1x2", de:"Bis bald", art:"", pl:"", en:"see you soon", topic:"greetings", level:"a1" , ex:"Bis bald — bis morgen im Kurs.", exEn:"See you soon — see you tomorrow in class."},
{ id:"a1x3", de:"Bis später", art:"", pl:"", en:"see you later", topic:"greetings", level:"a1" , ex:"Bis später — bis morgen im Kurs.", exEn:"See you later — see you tomorrow in class."},
{ id:"a1x4", de:"Bis morgen", art:"", pl:"", en:"see you tomorrow", topic:"greetings", level:"a1" , ex:"Bis morgen — bis morgen im Kurs.", exEn:"See you tomorrow — see you tomorrow in class."},
{ id:"a1x5", de:"Schön, Sie kennenzulernen", art:"", pl:"", en:"nice to meet you (formal)", topic:"greetings", level:"a1" , ex:"Schön, Sie kennenzulernen — bis morgen im Kurs.", exEn:"Nice to meet you (formal) — see you tomorrow in class."},
{ id:"a1x6", de:"Freut mich", art:"", pl:"", en:"pleased to meet you", topic:"greetings", level:"a1" , ex:"Freut mich — bis morgen im Kurs.", exEn:"Pleased to meet you — see you tomorrow in class."},
{ id:"a1x7", de:"Gleichfalls", art:"", pl:"", en:"likewise", topic:"greetings", level:"a1" , ex:"Gleichfalls — bis morgen im Kurs.", exEn:"Likewise — see you tomorrow in class."},
{ id:"a1x8", de:"Wie bitte?", art:"", pl:"", en:"pardon? / sorry?", topic:"greetings", level:"a1" , ex:"Wie bitte?", exEn:"Pardon? / sorry?"},
{ id:"a1x9", de:"Langsamer bitte", art:"", pl:"", en:"more slowly please", topic:"greetings", level:"a1" , ex:"Langsamer bitte — bis morgen im Kurs.", exEn:"More slowly please — see you tomorrow in class."},
{ id:"a1x10", de:"Ich verstehe nicht", art:"", pl:"", en:"I don't understand", topic:"greetings", level:"a1" , ex:"Ich verstehe nicht — bis morgen im Kurs.", exEn:"I don't understand — see you tomorrow in class."},
{ id:"a1x11", de:"Sprechen Sie Deutsch?", art:"", pl:"", en:"Do you speak German?", topic:"greetings", level:"a1" , ex:"Sprechen Sie Deutsch?", exEn:"Do you speak German?"},
{ id:"a1x12", de:"Ein bisschen", art:"", pl:"", en:"a little", topic:"greetings", level:"a1" , ex:"Ein bisschen — bis morgen im Kurs.", exEn:"A little — see you tomorrow in class."},
{ id:"a1x13", de:"Kein Problem", art:"", pl:"", en:"no problem", topic:"greetings", level:"a1" , ex:"Kein Problem — bis morgen im Kurs.", exEn:"No problem — see you tomorrow in class."},
{ id:"a1x14", de:"Gern geschehen", art:"", pl:"", en:"you're welcome", topic:"greetings", level:"a1" , ex:"Gern geschehen — bis morgen im Kurs.", exEn:"You're welcome — see you tomorrow in class."},
{ id:"a1x15", de:"Mit Vergnügen", art:"", pl:"", en:"with pleasure", topic:"greetings", level:"a1" , ex:"Mit Vergnügen — bis morgen im Kurs.", exEn:"With pleasure — see you tomorrow in class."},
{ id:"a1x16", de:"Alles Gute", art:"", pl:"", en:"all the best", topic:"greetings", level:"a1" , ex:"Alles Gute — bis morgen im Kurs.", exEn:"All the best — see you tomorrow in class."},
{ id:"a1x17", de:"Herzlichen Glückwunsch", art:"", pl:"", en:"congratulations", topic:"greetings", level:"a1" , ex:"Herzlichen Glückwunsch — bis morgen im Kurs.", exEn:"Congratulations — see you tomorrow in class."},
{ id:"a1x18", de:"Prost", art:"", pl:"", en:"cheers", topic:"greetings", level:"a1" , ex:"Prost — bis morgen im Kurs.", exEn:"Cheers — see you tomorrow in class."},
{ id:"a1x19", de:"Gesundheit", art:"", pl:"", en:"bless you / health", topic:"greetings", level:"a1" , ex:"Gesundheit — bis morgen im Kurs.", exEn:"Bless you / health — see you tomorrow in class."},
{ id:"a1x20", de:"Schönen Tag noch", art:"", pl:"", en:"have a nice day", topic:"greetings", level:"a1" , ex:"Schönen Tag noch — bis morgen im Kurs.", exEn:"Have a nice day — see you tomorrow in class."},
{ id:"a1x21", de:"Schönen Abend noch", art:"", pl:"", en:"have a nice evening", topic:"greetings", level:"a1" , ex:"Schönen Abend noch — bis morgen im Kurs.", exEn:"Have a nice evening — see you tomorrow in class."},
{ id:"a1x22", de:"Wie geht es Ihnen?", art:"", pl:"", en:"how are you? (formal)", topic:"greetings", level:"a1" , ex:"Wie geht es Ihnen?", exEn:"How are you? (formal)"},
{ id:"a1x23", de:"Es geht", art:"", pl:"", en:"I'm okay / so-so", topic:"greetings", level:"a1" , ex:"Es geht — bis morgen im Kurs.", exEn:"I'm okay / so-so — see you tomorrow in class."},
{ id:"a1x24", de:"Sehr gut", art:"", pl:"", en:"very good", topic:"greetings", level:"a1" , ex:"Sehr gut — bis morgen im Kurs.", exEn:"Very good — see you tomorrow in class."},
{ id:"a1x25", de:"Natürlich", art:"", pl:"", en:"of course", topic:"greetings", level:"a1" , ex:"Natürlich — bis morgen im Kurs.", exEn:"Of course — see you tomorrow in class."},
{ id:"a1x26", de:"Genau", art:"", pl:"", en:"exactly", topic:"greetings", level:"a1" , ex:"Genau — bis morgen im Kurs.", exEn:"Exactly — see you tomorrow in class."},
{ id:"a1x27", de:"Prima", art:"", pl:"", en:"great", topic:"greetings", level:"a1" , ex:"Prima — bis morgen im Kurs.", exEn:"Great — see you tomorrow in class."},
{ id:"a1x28", de:"Super", art:"", pl:"", en:"super", topic:"greetings", level:"a1" , ex:"Super — bis morgen im Kurs.", exEn:"Super — see you tomorrow in class."},
{ id:"a1x29", de:"Tut mir leid", art:"", pl:"", en:"I'm sorry", topic:"greetings", level:"a1" , ex:"Tut mir leid — bis morgen im Kurs.", exEn:"I'm sorry — see you tomorrow in class."},
{ id:"a1x30", de:"Macht nichts", art:"", pl:"", en:"never mind", topic:"greetings", level:"a1" , ex:"Macht nichts — bis morgen im Kurs.", exEn:"Never mind — see you tomorrow in class."},
{ id:"a1x31", de:"Oma", art:"die", pl:"-s", en:"grandma", topic:"people", level:"a1" , ex:"Das ist die Oma.", exEn:"This is grandma."},
{ id:"a1x32", de:"Opa", art:"der", pl:"-s", en:"grandpa", topic:"people", level:"a1" , ex:"Das ist der Opa.", exEn:"This is grandpa."},
{ id:"a1x33", de:"Onkel", art:"der", pl:"-", en:"uncle", topic:"people", level:"a1" , ex:"Das ist der Onkel.", exEn:"This is uncle."},
{ id:"a1x34", de:"Tante", art:"die", pl:"-n", en:"aunt", topic:"people", level:"a1" , ex:"Das ist die Tante.", exEn:"This is aunt."},
{ id:"a1x35", de:"Cousin", art:"der", pl:"-s", en:"male cousin", topic:"people", level:"a1" , ex:"Das ist der Cousin.", exEn:"This is male cousin."},
{ id:"a1x36", de:"Cousine", art:"die", pl:"-n", en:"female cousin", topic:"people", level:"a1" , ex:"Das ist die Cousine.", exEn:"This is female cousin."},
{ id:"a1x37", de:"Enkel", art:"der", pl:"-", en:"grandson", topic:"people", level:"a1" , ex:"Das ist der Enkel.", exEn:"This is grandson."},
{ id:"a1x38", de:"Enkelin", art:"die", pl:"-nen", en:"granddaughter", topic:"people", level:"a1" , ex:"Das ist die Enkelin.", exEn:"This is granddaughter."},
{ id:"a1x39", de:"Partner", art:"der", pl:"-", en:"partner", topic:"people", level:"a1" , ex:"Das ist der Partner.", exEn:"This is partner."},
{ id:"a1x40", de:"Partnerin", art:"die", pl:"-nen", en:"partner (f)", topic:"people", level:"a1" , ex:"Das ist die Partnerin.", exEn:"This is partner (f)."},
{ id:"a1x41", de:"Mädchen", art:"das", pl:"-", en:"girl", topic:"people", level:"a1" , ex:"Das ist das Mädchen.", exEn:"This is girl."},
{ id:"a1x42", de:"Junge", art:"der", pl:"-n", en:"boy", topic:"people", level:"a1" , ex:"Das ist der Junge.", exEn:"This is boy."},
{ id:"a1x43", de:"Eltern", art:"die", pl:"", en:"parents", topic:"people", level:"a1" , ex:"Hier sind die Eltern.", exEn:"Here are the parents."},
{ id:"a1x44", de:"Großeltern", art:"die", pl:"", en:"grandparents", topic:"people", level:"a1" , ex:"Hier sind die Großeltern.", exEn:"Here are the grandparents."},
{ id:"a1x45", de:"ledig", art:"", pl:"", en:"single (unmarried)", topic:"people", level:"a1" , ex:"Der Termin ist ledig.", exEn:"The appointment is single (unmarried)."},
{ id:"a1x46", de:"verheiratet", art:"", pl:"", en:"married", topic:"people", level:"a1" , ex:"Der Termin ist verheiratet.", exEn:"The appointment is married."},
{ id:"a1x47", de:"geschieden", art:"", pl:"", en:"divorced", topic:"people", level:"a1" , ex:"Ich möchte heute geschieden.", exEn:"I would like divorced today."},
{ id:"a1x48", de:"verwitwet", art:"", pl:"", en:"widowed", topic:"people", level:"a1" , ex:"Der Termin ist verwitwet.", exEn:"The appointment is widowed."},
{ id:"a1x49", de:"Nationalität", art:"die", pl:"-en", en:"nationality", topic:"people", level:"a1" , ex:"Das ist die Nationalität.", exEn:"This is nationality."},
{ id:"a1x50", de:"Land", art:"das", pl:"Länder", en:"country", topic:"people", level:"a1" , ex:"Das ist das Land.", exEn:"This is country."},
{ id:"a1x51", de:"Deutschland", art:"das", pl:"", en:"Germany", topic:"people", level:"a1" , ex:"Das ist das Deutschland.", exEn:"This is Germany."},
{ id:"a1x52", de:"Österreich", art:"das", pl:"", en:"Austria", topic:"people", level:"a1" , ex:"Das ist das Österreich.", exEn:"This is Austria."},
{ id:"a1x53", de:"Schweiz", art:"die", pl:"", en:"Switzerland", topic:"people", level:"a1" , ex:"Das ist die Schweiz.", exEn:"This is Switzerland."},
{ id:"a1x54", de:"Sprache", art:"die", pl:"-n", en:"language", topic:"people", level:"a1" , ex:"Das ist die Sprache.", exEn:"This is language."},
{ id:"a1x55", de:"Deutsch", art:"das", pl:"", en:"German (language)", topic:"people", level:"a1" , ex:"Das ist das Deutsch.", exEn:"This is German (language)."},
{ id:"a1x56", de:"Englisch", art:"das", pl:"", en:"English", topic:"people", level:"a1" , ex:"Das ist das Englisch.", exEn:"This is English."},
{ id:"a1x57", de:"Alter", art:"das", pl:"", en:"age", topic:"people", level:"a1" , ex:"Das ist das Alter.", exEn:"This is age."},
{ id:"a1x58", de:"Jahre alt", art:"", pl:"", en:"years old", topic:"people", level:"a1" , ex:"Jahre alt — das sage ich oft im Amt.", exEn:"Years old — I often say that at the office."},
{ id:"a1x59", de:"Geburtsdatum", art:"das", pl:"-daten", en:"date of birth", topic:"people", level:"a1" , ex:"Das ist das Geburtsdatum.", exEn:"This is date of birth."},
{ id:"a1x60", de:"Geburtsort", art:"der", pl:"-e", en:"place of birth", topic:"people", level:"a1" , ex:"Das ist der Geburtsort.", exEn:"This is place of birth."},
{ id:"a1x61", de:"Geschlecht", art:"das", pl:"-er", en:"gender", topic:"people", level:"a1" , ex:"Das ist das Geschlecht.", exEn:"This is gender."},
{ id:"a1x62", de:"männlich", art:"", pl:"", en:"male", topic:"people", level:"a1" , ex:"Der Termin ist männlich.", exEn:"The appointment is male."},
{ id:"a1x63", de:"weiblich", art:"", pl:"", en:"female", topic:"people", level:"a1" , ex:"Der Termin ist weiblich.", exEn:"The appointment is female."},
{ id:"a1x64", de:"Ich heiße", art:"", pl:"", en:"my name is", topic:"people", level:"a1" , ex:"Ich heiße — das sage ich oft im Amt.", exEn:"My name is — I often say that at the office."},
{ id:"a1x65", de:"Mein Name ist", art:"", pl:"", en:"my name is", topic:"people", level:"a1" , ex:"Mein Name ist — das sage ich oft im Amt.", exEn:"My name is — I often say that at the office."},
{ id:"a1x66", de:"Woher kommen Sie?", art:"", pl:"", en:"where are you from? (formal)", topic:"people", level:"a1" , ex:"Woher kommen Sie?", exEn:"Where are you from? (formal)"},
{ id:"a1x67", de:"Ich komme aus", art:"", pl:"", en:"I come from", topic:"people", level:"a1" , ex:"Ich komme aus — das sage ich oft im Amt.", exEn:"I come from — I often say that at the office."},
{ id:"a1x68", de:"elf", art:"", pl:"", en:"eleven", topic:"numbers", level:"a1" , ex:"Ich brauche elf Fahrkarten bitte.", exEn:"I need eleven tickets please."},
{ id:"a1x69", de:"zwölf", art:"", pl:"", en:"twelve", topic:"numbers", level:"a1" , ex:"Ich brauche zwölf Fahrkarten bitte.", exEn:"I need twelve tickets please."},
{ id:"a1x70", de:"dreizehn", art:"", pl:"", en:"thirteen", topic:"numbers", level:"a1" , ex:"Ich brauche dreizehn Fahrkarten bitte.", exEn:"I need thirteen tickets please."},
{ id:"a1x71", de:"vierzehn", art:"", pl:"", en:"fourteen", topic:"numbers", level:"a1" , ex:"Ich brauche vierzehn Fahrkarten bitte.", exEn:"I need fourteen tickets please."},
{ id:"a1x72", de:"fünfzehn", art:"", pl:"", en:"fifteen", topic:"numbers", level:"a1" , ex:"Ich brauche fünfzehn Fahrkarten bitte.", exEn:"I need fifteen tickets please."},
{ id:"a1x73", de:"sechzehn", art:"", pl:"", en:"sixteen", topic:"numbers", level:"a1" , ex:"Ich brauche sechzehn Fahrkarten bitte.", exEn:"I need sixteen tickets please."},
{ id:"a1x74", de:"siebzehn", art:"", pl:"", en:"seventeen", topic:"numbers", level:"a1" , ex:"Ich brauche siebzehn Fahrkarten bitte.", exEn:"I need seventeen tickets please."},
{ id:"a1x75", de:"achtzehn", art:"", pl:"", en:"eighteen", topic:"numbers", level:"a1" , ex:"Ich brauche achtzehn Fahrkarten bitte.", exEn:"I need eighteen tickets please."},
{ id:"a1x76", de:"neunzehn", art:"", pl:"", en:"nineteen", topic:"numbers", level:"a1" , ex:"Ich brauche neunzehn Fahrkarten bitte.", exEn:"I need nineteen tickets please."},
{ id:"a1x77", de:"zwanzig", art:"", pl:"", en:"twenty", topic:"numbers", level:"a1" , ex:"Ich brauche zwanzig Fahrkarten bitte.", exEn:"I need twenty tickets please."},
{ id:"a1x78", de:"dreißig", art:"", pl:"", en:"thirty", topic:"numbers", level:"a1" , ex:"Ich brauche dreißig Fahrkarten bitte.", exEn:"I need thirty tickets please."},
{ id:"a1x79", de:"vierzig", art:"", pl:"", en:"forty", topic:"numbers", level:"a1" , ex:"Ich brauche vierzig Fahrkarten bitte.", exEn:"I need forty tickets please."},
{ id:"a1x80", de:"fünfzig", art:"", pl:"", en:"fifty", topic:"numbers", level:"a1" , ex:"Ich brauche fünfzig Fahrkarten bitte.", exEn:"I need fifty tickets please."},
{ id:"a1x81", de:"sechzig", art:"", pl:"", en:"sixty", topic:"numbers", level:"a1" , ex:"Ich brauche sechzig Fahrkarten bitte.", exEn:"I need sixty tickets please."},
{ id:"a1x82", de:"siebzig", art:"", pl:"", en:"seventy", topic:"numbers", level:"a1" , ex:"Ich brauche siebzig Fahrkarten bitte.", exEn:"I need seventy tickets please."},
{ id:"a1x83", de:"achtzig", art:"", pl:"", en:"eighty", topic:"numbers", level:"a1" , ex:"Ich brauche achtzig Fahrkarten bitte.", exEn:"I need eighty tickets please."},
{ id:"a1x84", de:"neunzig", art:"", pl:"", en:"ninety", topic:"numbers", level:"a1" , ex:"Ich brauche neunzig Fahrkarten bitte.", exEn:"I need ninety tickets please."},
{ id:"a1x85", de:"tausend", art:"", pl:"", en:"thousand", topic:"numbers", level:"a1" , ex:"Ich brauche tausend Fahrkarten bitte.", exEn:"I need thousand tickets please."},
{ id:"a1x86", de:"halb", art:"", pl:"", en:"half (past) — halb drei = 2:30", topic:"numbers", level:"a1" , ex:"Ich brauche halb Fahrkarten bitte.", exEn:"I need half (past) — halb drei = 2:30 tickets please."},
{ id:"a1x87", de:"Viertel", art:"das", pl:"-", en:"quarter (hour)", topic:"numbers", level:"a1" , ex:"Hier ist das Viertel.", exEn:"Here is the quarter (hour)."},
{ id:"a1x88", de:"Viertel nach", art:"", pl:"", en:"quarter past", topic:"numbers", level:"a1" , ex:"Ich brauche Viertel nach Fahrkarten bitte.", exEn:"I need quarter past tickets please."},
{ id:"a1x89", de:"Viertel vor", art:"", pl:"", en:"quarter to", topic:"numbers", level:"a1" , ex:"Ich brauche Viertel vor Fahrkarten bitte.", exEn:"I need quarter to tickets please."},
{ id:"a1x90", de:"um ... Uhr", art:"", pl:"", en:"at ... o'clock", topic:"numbers", level:"a1" , ex:"Ich brauche um ... Uhr Fahrkarten bitte.", exEn:"I need at ... o'clock tickets please."},
{ id:"a1x91", de:"Montag", art:"der", pl:"-e", en:"Monday", topic:"numbers", level:"a1" , ex:"Hier ist der Montag.", exEn:"Here is the Monday."},
{ id:"a1x92", de:"Dienstag", art:"der", pl:"-e", en:"Tuesday", topic:"numbers", level:"a1" , ex:"Hier ist der Dienstag.", exEn:"Here is the Tuesday."},
{ id:"a1x93", de:"Mittwoch", art:"der", pl:"-e", en:"Wednesday", topic:"numbers", level:"a1" , ex:"Hier ist der Mittwoch.", exEn:"Here is the Wednesday."},
{ id:"a1x94", de:"Donnerstag", art:"der", pl:"-e", en:"Thursday", topic:"numbers", level:"a1" , ex:"Hier ist der Donnerstag.", exEn:"Here is the Thursday."},
{ id:"a1x95", de:"Freitag", art:"der", pl:"-e", en:"Friday", topic:"numbers", level:"a1" , ex:"Hier ist der Freitag.", exEn:"Here is the Friday."},
{ id:"a1x96", de:"Samstag", art:"der", pl:"-e", en:"Saturday", topic:"numbers", level:"a1" , ex:"Hier ist der Samstag.", exEn:"Here is the Saturday."},
{ id:"a1x97", de:"Sonntag", art:"der", pl:"-e", en:"Sunday", topic:"numbers", level:"a1" , ex:"Hier ist der Sonntag.", exEn:"Here is the Sunday."},
{ id:"a1x98", de:"Wochenende", art:"das", pl:"-e", en:"weekend", topic:"numbers", level:"a1" , ex:"Hier ist das Wochenende.", exEn:"Here is the weekend."},
{ id:"a1x99", de:"Januar", art:"der", pl:"", en:"January", topic:"numbers", level:"a1" , ex:"Hier ist der Januar.", exEn:"Here is the January."},
{ id:"a1x100", de:"Februar", art:"der", pl:"", en:"February", topic:"numbers", level:"a1" , ex:"Hier ist der Februar.", exEn:"Here is the February."},
{ id:"a1x101", de:"März", art:"der", pl:"", en:"March", topic:"numbers", level:"a1" , ex:"Hier ist der März.", exEn:"Here is the March."},
{ id:"a1x102", de:"April", art:"der", pl:"", en:"April", topic:"numbers", level:"a1" , ex:"Hier ist der April.", exEn:"Here is the April."},
{ id:"a1x103", de:"Mai", art:"der", pl:"", en:"May", topic:"numbers", level:"a1" , ex:"Hier ist der Mai.", exEn:"Here is the May."},
{ id:"a1x104", de:"Juni", art:"der", pl:"", en:"June", topic:"numbers", level:"a1" , ex:"Hier ist der Juni.", exEn:"Here is the June."},
{ id:"a1x105", de:"Juli", art:"der", pl:"", en:"July", topic:"numbers", level:"a1" , ex:"Hier ist der Juli.", exEn:"Here is the July."},
{ id:"a1x106", de:"August", art:"der", pl:"", en:"August", topic:"numbers", level:"a1" , ex:"Hier ist der August.", exEn:"Here is the August."},
{ id:"a1x107", de:"September", art:"der", pl:"", en:"September", topic:"numbers", level:"a1" , ex:"Hier ist der September.", exEn:"Here is the September."},
{ id:"a1x108", de:"Oktober", art:"der", pl:"", en:"October", topic:"numbers", level:"a1" , ex:"Hier ist der Oktober.", exEn:"Here is the October."},
{ id:"a1x109", de:"November", art:"der", pl:"", en:"November", topic:"numbers", level:"a1" , ex:"Hier ist der November.", exEn:"Here is the November."},
{ id:"a1x110", de:"Dezember", art:"der", pl:"", en:"December", topic:"numbers", level:"a1" , ex:"Hier ist der Dezember.", exEn:"Here is the December."},
{ id:"a1x111", de:"Frühling", art:"der", pl:"-e", en:"spring", topic:"numbers", level:"a1" , ex:"Hier ist der Frühling.", exEn:"Here is the spring."},
{ id:"a1x112", de:"Sommer", art:"der", pl:"", en:"summer", topic:"numbers", level:"a1" , ex:"Hier ist der Sommer.", exEn:"Here is the summer."},
{ id:"a1x113", de:"Herbst", art:"der", pl:"-e", en:"autumn", topic:"numbers", level:"a1" , ex:"Hier ist der Herbst.", exEn:"Here is the autumn."},
{ id:"a1x114", de:"Winter", art:"der", pl:"", en:"winter", topic:"numbers", level:"a1" , ex:"Hier ist der Winter.", exEn:"Here is the winter."},
{ id:"a1x115", de:"Datum", art:"das", pl:"Daten", en:"date", topic:"numbers", level:"a1" , ex:"Hier ist das Datum.", exEn:"Here is the date."},
{ id:"a1x116", de:"Kalender", art:"der", pl:"-", en:"calendar", topic:"numbers", level:"a1" , ex:"Hier ist der Kalender.", exEn:"Here is the calendar."},
{ id:"a1x117", de:"Geburtstag", art:"der", pl:"-e", en:"birthday", topic:"numbers", level:"a1" , ex:"Hier ist der Geburtstag.", exEn:"Here is the birthday."},
{ id:"a1x118", de:"Uhrzeit", art:"die", pl:"-en", en:"time of day", topic:"numbers", level:"a1" , ex:"Hier ist die Uhrzeit.", exEn:"Here is the time of day."},
{ id:"a1x119", de:"Sekunde", art:"die", pl:"-n", en:"second", topic:"numbers", level:"a1" , ex:"Hier ist die Sekunde.", exEn:"Here is the second."},
{ id:"a1x120", de:"pünktlich", art:"", pl:"", en:"on time", topic:"numbers", level:"a1" , ex:"Ich brauche pünktlich Fahrkarten bitte.", exEn:"I need on time tickets please."},
{ id:"a1x121", de:"früh", art:"", pl:"", en:"early", topic:"numbers", level:"a1" , ex:"Ich brauche früh Fahrkarten bitte.", exEn:"I need early tickets please."},
{ id:"a1x122", de:"spät", art:"", pl:"", en:"late", topic:"numbers", level:"a1" , ex:"Ich brauche spät Fahrkarten bitte.", exEn:"I need late tickets please."},
{ id:"a1x123", de:"immer", art:"", pl:"", en:"always", topic:"numbers", level:"a1" , ex:"Ich brauche immer Fahrkarten bitte.", exEn:"I need always tickets please."},
{ id:"a1x124", de:"oft", art:"", pl:"", en:"often", topic:"numbers", level:"a1" , ex:"Ich brauche oft Fahrkarten bitte.", exEn:"I need often tickets please."},
{ id:"a1x125", de:"manchmal", art:"", pl:"", en:"sometimes", topic:"numbers", level:"a1" , ex:"Ich brauche manchmal Fahrkarten bitte.", exEn:"I need sometimes tickets please."},
{ id:"a1x126", de:"nie", art:"", pl:"", en:"never", topic:"numbers", level:"a1" , ex:"Ich brauche nie Fahrkarten bitte.", exEn:"I need never tickets please."},
{ id:"a1x127", de:"jeden Tag", art:"", pl:"", en:"every day", topic:"numbers", level:"a1" , ex:"Ich brauche jeden Tag Fahrkarten bitte.", exEn:"I need every day tickets please."},
{ id:"a1x128", de:"Etage", art:"die", pl:"-n", en:"floor (storey)", topic:"home", level:"a1" , ex:"Wo ist die Etage?", exEn:"Where is the floor (storey)?"},
{ id:"a1x129", de:"Stock", art:"der", pl:"Stöcke", en:"floor / storey", topic:"home", level:"a1" , ex:"Wo ist der Stock?", exEn:"Where is the floor / storey?"},
{ id:"a1x130", de:"Aufzug", art:"der", pl:"Aufzüge", en:"lift / elevator", topic:"home", level:"a1" , ex:"Wo ist der Aufzug?", exEn:"Where is the lift / elevator?"},
{ id:"a1x131", de:"Treppe", art:"die", pl:"-n", en:"stairs", topic:"home", level:"a1" , ex:"Wo ist die Treppe?", exEn:"Where is the stairs?"},
{ id:"a1x132", de:"Keller", art:"der", pl:"-", en:"cellar", topic:"home", level:"a1" , ex:"Wo ist der Keller?", exEn:"Where is the cellar?"},
{ id:"a1x133", de:"Dach", art:"das", pl:"Dächer", en:"roof", topic:"home", level:"a1" , ex:"Wo ist das Dach?", exEn:"Where is the roof?"},
{ id:"a1x134", de:"Garten", art:"der", pl:"Gärten", en:"garden", topic:"home", level:"a1" , ex:"Wo ist der Garten?", exEn:"Where is the garden?"},
{ id:"a1x135", de:"Balkon", art:"der", pl:"-e", en:"balcony", topic:"home", level:"a1" , ex:"Wo ist der Balkon?", exEn:"Where is the balcony?"},
{ id:"a1x136", de:"Flur", art:"der", pl:"-e", en:"hallway", topic:"home", level:"a1" , ex:"Wo ist der Flur?", exEn:"Where is the hallway?"},
{ id:"a1x137", de:"Toilette", art:"die", pl:"-n", en:"toilet", topic:"home", level:"a1" , ex:"Wo ist die Toilette?", exEn:"Where is the toilet?"},
{ id:"a1x138", de:"Sofa", art:"das", pl:"-s", en:"sofa", topic:"home", level:"a1" , ex:"Wo ist das Sofa?", exEn:"Where is the sofa?"},
{ id:"a1x139", de:"Schreibtisch", art:"der", pl:"-e", en:"desk", topic:"home", level:"a1" , ex:"Wo ist der Schreibtisch?", exEn:"Where is the desk?"},
{ id:"a1x140", de:"Lampe", art:"die", pl:"-n", en:"lamp", topic:"home", level:"a1" , ex:"Wo ist die Lampe?", exEn:"Where is the lamp?"},
{ id:"a1x141", de:"Kühlschrank", art:"der", pl:"Kühlschränke", en:"fridge", topic:"home", level:"a1" , ex:"Wo ist der Kühlschrank?", exEn:"Where is the fridge?"},
{ id:"a1x142", de:"Herd", art:"der", pl:"-e", en:"cooker / stove", topic:"home", level:"a1" , ex:"Wo ist der Herd?", exEn:"Where is the cooker / stove?"},
{ id:"a1x143", de:"Spüle", art:"die", pl:"-n", en:"kitchen sink", topic:"home", level:"a1" , ex:"Wo ist die Spüle?", exEn:"Where is the kitchen sink?"},
{ id:"a1x144", de:"Dusche", art:"die", pl:"-n", en:"shower", topic:"home", level:"a1" , ex:"Wo ist die Dusche?", exEn:"Where is the shower?"},
{ id:"a1x145", de:"Badewanne", art:"die", pl:"-n", en:"bathtub", topic:"home", level:"a1" , ex:"Wo ist die Badewanne?", exEn:"Where is the bathtub?"},
{ id:"a1x146", de:"Spiegel", art:"der", pl:"-", en:"mirror", topic:"home", level:"a1" , ex:"Wo ist der Spiegel?", exEn:"Where is the mirror?"},
{ id:"a1x147", de:"Schlüssel", art:"der", pl:"-", en:"key", topic:"home", level:"a1" , ex:"Wo ist der Schlüssel?", exEn:"Where is the key?"},
{ id:"a1x148", de:"Miete", art:"die", pl:"-n", en:"rent", topic:"home", level:"a1" , ex:"Wo ist die Miete?", exEn:"Where is the rent?"},
{ id:"a1x149", de:"Hausnummer", art:"die", pl:"-n", en:"house number", topic:"home", level:"a1" , ex:"Wo ist die Hausnummer?", exEn:"Where is the house number?"},
{ id:"a1x150", de:"Postleitzahl", art:"die", pl:"-en", en:"postcode", topic:"home", level:"a1" , ex:"Wo ist die Postleitzahl?", exEn:"Where is the postcode?"},
{ id:"a1x151", de:"Ort", art:"der", pl:"-e", en:"place / town", topic:"home", level:"a1" , ex:"Wo ist der Ort?", exEn:"Where is the place / town?"},
{ id:"a1x152", de:"Zentrum", art:"das", pl:"Zentren", en:"centre", topic:"home", level:"a1" , ex:"Wo ist das Zentrum?", exEn:"Where is the centre?"},
{ id:"a1x153", de:"Markt", art:"der", pl:"Märkte", en:"market", topic:"home", level:"a1" , ex:"Wo ist der Markt?", exEn:"Where is the market?"},
{ id:"a1x154", de:"Park", art:"der", pl:"-s", en:"park", topic:"home", level:"a1" , ex:"Wo ist der Park?", exEn:"Where is the park?"},
{ id:"a1x155", de:"Kirche", art:"die", pl:"-n", en:"church", topic:"home", level:"a1" , ex:"Wo ist die Kirche?", exEn:"Where is the church?"},
{ id:"a1x156", de:"Museum", art:"das", pl:"Museen", en:"museum", topic:"home", level:"a1" , ex:"Wo ist das Museum?", exEn:"Where is the museum?"},
{ id:"a1x157", de:"Bibliothek", art:"die", pl:"-en", en:"library", topic:"home", level:"a1" , ex:"Wo ist die Bibliothek?", exEn:"Where is the library?"},
{ id:"a1x158", de:"Rathaus", art:"das", pl:"Rathäuser", en:"town hall", topic:"home", level:"a1" , ex:"Wo ist das Rathaus?", exEn:"Where is the town hall?"},
{ id:"a1x159", de:"Polizei", art:"die", pl:"", en:"police", topic:"home", level:"a1" , ex:"Wo ist die Polizei?", exEn:"Where is the police?"},
{ id:"a1x160", de:"Feuerwehr", art:"die", pl:"-en", en:"fire brigade", topic:"home", level:"a1" , ex:"Wo ist die Feuerwehr?", exEn:"Where is the fire brigade?"},
{ id:"a1x161", de:"Bank", art:"die", pl:"-en", en:"bank", topic:"home", level:"a1" , ex:"Wo ist die Bank?", exEn:"Where is the bank?"},
{ id:"a1x162", de:"Post", art:"die", pl:"", en:"post office / mail", topic:"home", level:"a1" , ex:"Wo ist die Post?", exEn:"Where is the post office / mail?"},
{ id:"a1x163", de:"Stadtteil", art:"der", pl:"-e", en:"district", topic:"home", level:"a1" , ex:"Wo ist der Stadtteil?", exEn:"Where is the district?"},
{ id:"a1x164", de:"Kreuzung", art:"die", pl:"-en", en:"crossroads", topic:"home", level:"a1" , ex:"Wo ist die Kreuzung?", exEn:"Where is the crossroads?"},
{ id:"a1x165", de:"Ampel", art:"die", pl:"-n", en:"traffic light", topic:"home", level:"a1" , ex:"Wo ist die Ampel?", exEn:"Where is the traffic light?"},
{ id:"a1x166", de:"Fußgängerzone", art:"die", pl:"-n", en:"pedestrian zone", topic:"home", level:"a1" , ex:"Wo ist die Fußgängerzone?", exEn:"Where is the pedestrian zone?"},
{ id:"a1x167", de:"Brücke", art:"die", pl:"-n", en:"bridge", topic:"home", level:"a1" , ex:"Wo ist die Brücke?", exEn:"Where is the bridge?"},
{ id:"a1x168", de:"Platz", art:"der", pl:"Plätze", en:"square / place", topic:"home", level:"a1" , ex:"Wo ist der Platz?", exEn:"Where is the square / place?"},
{ id:"a1x169", de:"Nachbarin", art:"die", pl:"-nen", en:"neighbour (f)", topic:"home", level:"a1" , ex:"Wo ist die Nachbarin?", exEn:"Where is the neighbour (f)?"},
{ id:"a1x170", de:"Wohnort", art:"der", pl:"-e", en:"place of residence", topic:"home", level:"a1" , ex:"Wo ist der Wohnort?", exEn:"Where is the place of residence?"},
{ id:"a1x171", de:"im Erdgeschoss", art:"", pl:"", en:"on the ground floor", topic:"home", level:"a1" , ex:"Im Erdgeschoss — das sage ich oft im Amt.", exEn:"On the ground floor — I often say that at the office."},
{ id:"a1x172", de:"Butter", art:"die", pl:"", en:"butter", topic:"food", level:"a1" , ex:"Ich kaufe die Butter.", exEn:"I am buying the butter."},
{ id:"a1x173", de:"Ei", art:"das", pl:"-er", en:"egg", topic:"food", level:"a1" , ex:"Ich kaufe das Ei.", exEn:"I am buying the egg."},
{ id:"a1x174", de:"Zucker", art:"der", pl:"", en:"sugar", topic:"food", level:"a1" , ex:"Ich kaufe den Zucker.", exEn:"I am buying the sugar."},
{ id:"a1x175", de:"Salz", art:"das", pl:"", en:"salt", topic:"food", level:"a1" , ex:"Ich kaufe das Salz.", exEn:"I am buying the salt."},
{ id:"a1x176", de:"Pfeffer", art:"der", pl:"", en:"pepper", topic:"food", level:"a1" , ex:"Ich kaufe den Pfeffer.", exEn:"I am buying the pepper."},
{ id:"a1x177", de:"Reis", art:"der", pl:"", en:"rice", topic:"food", level:"a1" , ex:"Ich kaufe den Reis.", exEn:"I am buying the rice."},
{ id:"a1x178", de:"Nudeln", art:"die", pl:"", en:"pasta / noodles", topic:"food", level:"a1" , ex:"Ich kaufe die Nudeln.", exEn:"I am buying the pasta / noodles."},
{ id:"a1x179", de:"Suppe", art:"die", pl:"-n", en:"soup", topic:"food", level:"a1" , ex:"Ich kaufe die Suppe.", exEn:"I am buying the soup."},
{ id:"a1x180", de:"Salat", art:"der", pl:"-e", en:"salad", topic:"food", level:"a1" , ex:"Ich kaufe den Salat.", exEn:"I am buying the salad."},
{ id:"a1x181", de:"Pizza", art:"die", pl:"-s", en:"pizza", topic:"food", level:"a1" , ex:"Ich kaufe die Pizza.", exEn:"I am buying the pizza."},
{ id:"a1x182", de:"Kuchen", art:"der", pl:"-", en:"cake", topic:"food", level:"a1" , ex:"Ich kaufe den Kuchen.", exEn:"I am buying the cake."},
{ id:"a1x183", de:"Eis", art:"das", pl:"", en:"ice cream / ice", topic:"food", level:"a1" , ex:"Ich kaufe das Eis.", exEn:"I am buying the ice cream / ice."},
{ id:"a1x184", de:"Saft", art:"der", pl:"Säfte", en:"juice", topic:"food", level:"a1" , ex:"Ich kaufe den Saft.", exEn:"I am buying the juice."},
{ id:"a1x185", de:"Bier", art:"das", pl:"-e", en:"beer", topic:"food", level:"a1" , ex:"Ich kaufe das Bier.", exEn:"I am buying the beer."},
{ id:"a1x186", de:"Wein", art:"der", pl:"-e", en:"wine", topic:"food", level:"a1" , ex:"Ich kaufe den Wein.", exEn:"I am buying the wine."},
{ id:"a1x187", de:"Cola", art:"die/das", pl:"-s", en:"cola", topic:"food", level:"a1" , ex:"Ich kaufe die Cola.", exEn:"I am buying the cola."},
{ id:"a1x188", de:"Speisekarte", art:"die", pl:"-n", en:"menu", topic:"food", level:"a1" , ex:"Ich kaufe die Speisekarte.", exEn:"I am buying the menu."},
{ id:"a1x189", de:"Bestellung", art:"die", pl:"-en", en:"order", topic:"food", level:"a1" , ex:"Ich kaufe die Bestellung.", exEn:"I am buying the order."},
{ id:"a1x190", de:"Kellner", art:"der", pl:"-", en:"waiter", topic:"food", level:"a1" , ex:"Ich kaufe den Kellner.", exEn:"I am buying the waiter."},
{ id:"a1x191", de:"Kellnerin", art:"die", pl:"-nen", en:"waitress", topic:"food", level:"a1" , ex:"Ich kaufe die Kellnerin.", exEn:"I am buying the waitress."},
{ id:"a1x192", de:"Tasse", art:"die", pl:"-n", en:"cup", topic:"food", level:"a1" , ex:"Ich kaufe die Tasse.", exEn:"I am buying the cup."},
{ id:"a1x193", de:"Glas", art:"das", pl:"Gläser", en:"glass", topic:"food", level:"a1" , ex:"Ich kaufe das Glas.", exEn:"I am buying the glass."},
{ id:"a1x194", de:"Teller", art:"der", pl:"-", en:"plate", topic:"food", level:"a1" , ex:"Ich kaufe den Teller.", exEn:"I am buying the plate."},
{ id:"a1x195", de:"Gabel", art:"die", pl:"-n", en:"fork", topic:"food", level:"a1" , ex:"Ich kaufe die Gabel.", exEn:"I am buying the fork."},
{ id:"a1x196", de:"Messer", art:"das", pl:"-", en:"knife", topic:"food", level:"a1" , ex:"Ich kaufe das Messer.", exEn:"I am buying the knife."},
{ id:"a1x197", de:"Löffel", art:"der", pl:"-", en:"spoon", topic:"food", level:"a1" , ex:"Ich kaufe den Löffel.", exEn:"I am buying the spoon."},
{ id:"a1x198", de:"Hunger", art:"der", pl:"", en:"hunger", topic:"food", level:"a1" , ex:"Ich kaufe den Hunger.", exEn:"I am buying the hunger."},
{ id:"a1x199", de:"Durst", art:"der", pl:"", en:"thirst", topic:"food", level:"a1" , ex:"Ich kaufe den Durst.", exEn:"I am buying the thirst."},
{ id:"a1x200", de:"Ich hätte gerne", art:"", pl:"", en:"I would like", topic:"food", level:"a1" , ex:"Ich hätte gerne — das sage ich oft im Amt.", exEn:"I would like — I often say that at the office."},
{ id:"a1x201", de:"Die Rechnung bitte", art:"", pl:"", en:"the bill please", topic:"food", level:"a1" , ex:"Die Rechnung bitte — das sage ich oft im Amt.", exEn:"The bill please — I often say that at the office."},
{ id:"a1x202", de:"vegetarisch", art:"", pl:"", en:"vegetarian", topic:"food", level:"a1" , ex:"Der Termin ist vegetarisch.", exEn:"The appointment is vegetarian."},
{ id:"a1x203", de:"Café", art:"das", pl:"-s", en:"café", topic:"food", level:"a1" , ex:"Ich kaufe das Café.", exEn:"I am buying the café."},
{ id:"a1x204", de:"Bäckerei", art:"die", pl:"-en", en:"bakery", topic:"food", level:"a1" , ex:"Ich kaufe die Bäckerei.", exEn:"I am buying the bakery."},
{ id:"a1x205", de:"Metzgerei", art:"die", pl:"-en", en:"butcher's", topic:"food", level:"a1" , ex:"Ich kaufe die Metzgerei.", exEn:"I am buying the butcher's."},
{ id:"a1x206", de:"Imbiss", art:"der", pl:"-e", en:"snack bar", topic:"food", level:"a1" , ex:"Ich kaufe den Imbiss.", exEn:"I am buying the snack bar."},
{ id:"a1x207", de:"Restaurant", art:"das", pl:"-s", en:"restaurant", topic:"food", level:"a1" , ex:"Ich kaufe das Restaurant.", exEn:"I am buying the restaurant."},
{ id:"a1x208", de:"Mittagstisch", art:"der", pl:"-e", en:"lunch special", topic:"food", level:"a1" , ex:"Ich kaufe den Mittagstisch.", exEn:"I am buying the lunch special."},
{ id:"a1x209", de:"Trinkgeld", art:"das", pl:"-er", en:"tip", topic:"food", level:"a1" , ex:"Ich kaufe das Trinkgeld.", exEn:"I am buying the tip."},
{ id:"a1x210", de:"ohne Zucker", art:"", pl:"", en:"without sugar", topic:"food", level:"a1" , ex:"Ohne Zucker — das sage ich oft im Amt.", exEn:"Without sugar — I often say that at the office."},
{ id:"a1x211", de:"mit Milch", art:"", pl:"", en:"with milk", topic:"food", level:"a1" , ex:"Mit Milch — das sage ich oft im Amt.", exEn:"With milk — I often say that at the office."},
{ id:"a1x212", de:"zum Mitnehmen", art:"", pl:"", en:"to take away", topic:"food", level:"a1" , ex:"Ich möchte heute zum Mitnehmen.", exEn:"I would like to take away today."},
{ id:"a1x213", de:"hier essen", art:"", pl:"", en:"eat in", topic:"food", level:"a1" , ex:"Hier essen — das sage ich oft im Amt.", exEn:"Eat in — I often say that at the office."},
{ id:"a1x214", de:"lecker", art:"", pl:"", en:"tasty", topic:"food", level:"a1" , ex:"Der Termin ist lecker.", exEn:"The appointment is tasty."},
{ id:"a1x215", de:"scharf", art:"", pl:"", en:"spicy / sharp", topic:"food", level:"a1" , ex:"Der Termin ist scharf.", exEn:"The appointment is spicy / sharp."},
{ id:"a1x216", de:"süß", art:"", pl:"", en:"sweet", topic:"food", level:"a1" , ex:"Der Termin ist süß.", exEn:"The appointment is sweet."},
{ id:"a1x217", de:"aufstehen", art:"", pl:"", en:"to get up", topic:"daily", level:"a1" , ex:"Ich möchte heute aufstehen.", exEn:"I would like to get up today."},
{ id:"a1x218", de:"duschen", art:"", pl:"", en:"to shower", topic:"daily", level:"a1" , ex:"Ich möchte heute duschen.", exEn:"I would like to shower today."},
{ id:"a1x219", de:"frühstücken", art:"", pl:"", en:"to have breakfast", topic:"daily", level:"a1" , ex:"Ich möchte heute frühstücken.", exEn:"I would like to have breakfast today."},
{ id:"a1x220", de:"schlafen", art:"", pl:"", en:"to sleep", topic:"daily", level:"a1" , ex:"Ich möchte heute schlafen.", exEn:"I would like to sleep today."},
{ id:"a1x221", de:"fernsehen", art:"", pl:"", en:"to watch TV", topic:"daily", level:"a1" , ex:"Ich möchte heute fernsehen.", exEn:"I would like to watch TV today."},
{ id:"a1x222", de:"lesen", art:"", pl:"", en:"to read", topic:"daily", level:"a1" , ex:"Ich möchte heute lesen.", exEn:"I would like to read today."},
{ id:"a1x223", de:"schreiben", art:"", pl:"", en:"to write", topic:"daily", level:"a1" , ex:"Ich möchte heute schreiben.", exEn:"I would like to write today."},
{ id:"a1x224", de:"telefonieren", art:"", pl:"", en:"to phone", topic:"daily", level:"a1" , ex:"Ich möchte heute telefonieren.", exEn:"I would like to phone today."},
{ id:"a1x225", de:"einkaufen", art:"", pl:"", en:"to shop", topic:"daily", level:"a1" , ex:"Ich möchte heute einkaufen.", exEn:"I would like to shop today."},
{ id:"a1x226", de:"kochen", art:"", pl:"", en:"to cook", topic:"daily", level:"a1" , ex:"Ich möchte heute kochen.", exEn:"I would like to cook today."},
{ id:"a1x227", de:"putzen", art:"", pl:"", en:"to clean", topic:"daily", level:"a1" , ex:"Ich möchte heute putzen.", exEn:"I would like to clean today."},
{ id:"a1x228", de:"waschen", art:"", pl:"", en:"to wash", topic:"daily", level:"a1" , ex:"Ich möchte heute waschen.", exEn:"I would like to wash today."},
{ id:"a1x229", de:"spazieren gehen", art:"", pl:"", en:"to go for a walk", topic:"daily", level:"a1" , ex:"Ich möchte heute spazieren gehen.", exEn:"I would like to go for a walk today."},
{ id:"a1x230", de:"Sport machen", art:"", pl:"", en:"to do sport", topic:"daily", level:"a1" , ex:"Ich möchte heute Sport machen.", exEn:"I would like to do sport today."},
{ id:"a1x231", de:"Musik hören", art:"", pl:"", en:"to listen to music", topic:"daily", level:"a1" , ex:"Ich möchte heute Musik hören.", exEn:"I would like to listen to music today."},
{ id:"a1x232", de:"Hausaufgabe", art:"die", pl:"-n", en:"homework", topic:"daily", level:"a1" , ex:"Heute geht es um die Hausaufgabe.", exEn:"Today it is about the homework."},
{ id:"a1x233", de:"Feierabend", art:"der", pl:"-e", en:"end of the workday", topic:"daily", level:"a1" , ex:"Heute geht es um den Feierabend.", exEn:"Today it is about the end of the workday."},
{ id:"a1x234", de:"Urlaub", art:"der", pl:"-e", en:"holiday / vacation", topic:"daily", level:"a1" , ex:"Heute geht es um den Urlaub.", exEn:"Today it is about the holiday / vacation."},
{ id:"a1x235", de:"Mittagspause", art:"die", pl:"-n", en:"lunch break", topic:"daily", level:"a1" , ex:"Heute geht es um die Mittagspause.", exEn:"Today it is about the lunch break."},
{ id:"a1x236", de:"Alltag", art:"der", pl:"", en:"everyday life", topic:"daily", level:"a1" , ex:"Heute geht es um den Alltag.", exEn:"Today it is about the everyday life."},
{ id:"a1x237", de:"Routine", art:"die", pl:"-n", en:"routine", topic:"daily", level:"a1" , ex:"Heute geht es um die Routine.", exEn:"Today it is about the routine."},
{ id:"a1x238", de:"aufwachen", art:"", pl:"", en:"to wake up", topic:"daily", level:"a1" , ex:"Ich möchte heute aufwachen.", exEn:"I would like to wake up today."},
{ id:"a1x239", de:"ins Bett gehen", art:"", pl:"", en:"to go to bed", topic:"daily", level:"a1" , ex:"Ich möchte heute ins Bett gehen.", exEn:"I would like to go to bed today."},
{ id:"a1x240", de:"sich anziehen", art:"", pl:"", en:"to get dressed", topic:"daily", level:"a1" , ex:"Wir wollen uns nicht anziehen.", exEn:"We do not want to get dressed."},
{ id:"a1x241", de:"Zähne putzen", art:"", pl:"", en:"to brush one's teeth", topic:"daily", level:"a1" , ex:"Ich möchte heute Zähne putzen.", exEn:"I would like to brush one's teeth today."},
{ id:"a1x242", de:"Haltestelle", art:"die", pl:"-n", en:"stop (bus/tram)", topic:"travel", level:"a1" , ex:"Wo ist die Haltestelle?", exEn:"Where is the stop (bus/tram)?"},
{ id:"a1x243", de:"Gleis", art:"das", pl:"-e", en:"platform / track", topic:"travel", level:"a1" , ex:"Wo ist das Gleis?", exEn:"Where is the platform / track?"},
{ id:"a1x244", de:"Abfahrt", art:"die", pl:"-en", en:"departure", topic:"travel", level:"a1" , ex:"Wo ist die Abfahrt?", exEn:"Where is the departure?"},
{ id:"a1x245", de:"Ankunft", art:"die", pl:"-e", en:"arrival", topic:"travel", level:"a1" , ex:"Wo ist die Ankunft?", exEn:"Where is the arrival?"},
{ id:"a1x246", de:"Verspätung", art:"die", pl:"-en", en:"delay", topic:"travel", level:"a1" , ex:"Wo ist die Verspätung?", exEn:"Where is the delay?"},
{ id:"a1x247", de:"umsteigen", art:"", pl:"", en:"to change (trains)", topic:"travel", level:"a1" , ex:"Ich möchte heute umsteigen.", exEn:"I would like to change (trains) today."},
{ id:"a1x248", de:"einsteigen", art:"", pl:"", en:"to get on", topic:"travel", level:"a1" , ex:"Ich möchte heute einsteigen.", exEn:"I would like to get on today."},
{ id:"a1x249", de:"aussteigen", art:"", pl:"", en:"to get off", topic:"travel", level:"a1" , ex:"Ich möchte heute aussteigen.", exEn:"I would like to get off today."},
{ id:"a1x250", de:"Fahrplan", art:"der", pl:"Fahrpläne", en:"timetable", topic:"travel", level:"a1" , ex:"Wo ist der Fahrplan?", exEn:"Where is the timetable?"},
{ id:"a1x251", de:"Schalter", art:"der", pl:"-", en:"ticket window / counter", topic:"travel", level:"a1" , ex:"Wo ist der Schalter?", exEn:"Where is the ticket window / counter?"},
{ id:"a1x252", de:"Automat", art:"der", pl:"-en", en:"ticket machine", topic:"travel", level:"a1" , ex:"Wo ist der Automat?", exEn:"Where is the ticket machine?"},
{ id:"a1x253", de:"Rückfahrt", art:"die", pl:"-en", en:"return journey", topic:"travel", level:"a1" , ex:"Wo ist die Rückfahrt?", exEn:"Where is the return journey?"},
{ id:"a1x254", de:"hin und zurück", art:"", pl:"", en:"return (ticket)", topic:"travel", level:"a1" , ex:"Hin und zurück — das sage ich oft im Amt.", exEn:"Return (ticket) — I often say that at the office."},
{ id:"a1x255", de:"Taxi", art:"das", pl:"-s", en:"taxi", topic:"travel", level:"a1" , ex:"Wo ist das Taxi?", exEn:"Where is the taxi?"},
{ id:"a1x256", de:"U-Bahn", art:"die", pl:"-en", en:"underground / metro", topic:"travel", level:"a1" , ex:"Wo ist die U-Bahn?", exEn:"Where is the underground / metro?"},
{ id:"a1x257", de:"S-Bahn", art:"die", pl:"-en", en:"suburban train", topic:"travel", level:"a1" , ex:"Wo ist die S-Bahn?", exEn:"Where is the suburban train?"},
{ id:"a1x258", de:"Straßenbahn", art:"die", pl:"-en", en:"tram", topic:"travel", level:"a1" , ex:"Wo ist die Straßenbahn?", exEn:"Where is the tram?"},
{ id:"a1x259", de:"Fahrrad", art:"das", pl:"Fahrräder", en:"bicycle", topic:"travel", level:"a1" , ex:"Wo ist das Fahrrad?", exEn:"Where is the bicycle?"},
{ id:"a1x260", de:"Auto", art:"das", pl:"-s", en:"car", topic:"travel", level:"a1" , ex:"Wo ist das Auto?", exEn:"Where is the car?"},
{ id:"a1x261", de:"Parkplatz", art:"der", pl:"Parkplätze", en:"parking space", topic:"travel", level:"a1" , ex:"Wo ist der Parkplatz?", exEn:"Where is the parking space?"},
{ id:"a1x262", de:"Ausgang", art:"der", pl:"Ausgänge", en:"exit", topic:"travel", level:"a1" , ex:"Wo ist der Ausgang?", exEn:"Where is the exit?"},
{ id:"a1x263", de:"Eingang", art:"der", pl:"Eingänge", en:"entrance", topic:"travel", level:"a1" , ex:"Wo ist der Eingang?", exEn:"Where is the entrance?"},
{ id:"a1x264", de:"Information", art:"die", pl:"-en", en:"information / info desk", topic:"travel", level:"a1" , ex:"Wo ist die Information?", exEn:"Where is the information / info desk?"},
{ id:"a1x265", de:"Fundbüro", art:"das", pl:"-s", en:"lost property", topic:"travel", level:"a1" , ex:"Wo ist das Fundbüro?", exEn:"Where is the lost property?"},
{ id:"a1x266", de:"Richtung", art:"die", pl:"-en", en:"direction", topic:"travel", level:"a1" , ex:"Wo ist die Richtung?", exEn:"Where is the direction?"},
{ id:"a1x267", de:"gegenüber", art:"", pl:"", en:"opposite", topic:"travel", level:"a1" , ex:"Der Termin ist gegenüber.", exEn:"The appointment is opposite."},
{ id:"a1x268", de:"neben", art:"", pl:"", en:"next to", topic:"travel", level:"a1" , ex:"Ich möchte heute neben.", exEn:"I would like next to today."},
{ id:"a1x269", de:"zwischen", art:"", pl:"", en:"between", topic:"travel", level:"a1" , ex:"Ich möchte heute zwischen.", exEn:"I would like between today."},
{ id:"a1x270", de:"hinter", art:"", pl:"", en:"behind", topic:"travel", level:"a1" , ex:"Der Termin ist hinter.", exEn:"The appointment is behind."},
{ id:"a1x271", de:"vor", art:"", pl:"", en:"in front of / before", topic:"travel", level:"a1" , ex:"Der Termin ist vor.", exEn:"The appointment is in front of / before."},
{ id:"a1x272", de:"Notausgang", art:"der", pl:"Notausgänge", en:"emergency exit", topic:"travel", level:"a1" , ex:"Wo ist der Notausgang?", exEn:"Where is the emergency exit?"},
{ id:"a1x273", de:"Rauchen verboten", art:"", pl:"", en:"no smoking", topic:"travel", level:"a1" , ex:"Rauchen verboten — das sage ich oft im Amt.", exEn:"No smoking — I often say that at the office."},
{ id:"a1x274", de:"Vorsicht", art:"die", pl:"", en:"caution", topic:"travel", level:"a1" , ex:"Wo ist die Vorsicht?", exEn:"Where is the caution?"},
{ id:"a1x275", de:"Einbahnstraße", art:"die", pl:"-n", en:"one-way street", topic:"travel", level:"a1" , ex:"Wo ist die Einbahnstraße?", exEn:"Where is the one-way street?"},
{ id:"a1x276", de:"Parkverbot", art:"das", pl:"-e", en:"no parking", topic:"travel", level:"a1" , ex:"Wo ist das Parkverbot?", exEn:"Where is the no parking?"},
{ id:"a1x277", de:"frei", art:"", pl:"", en:"vacant / free", topic:"travel", level:"a1" , ex:"Der Termin ist frei.", exEn:"The appointment is vacant / free."},
{ id:"a1x278", de:"besetzt", art:"", pl:"", en:"occupied / engaged", topic:"travel", level:"a1" , ex:"Der Termin ist besetzt.", exEn:"The appointment is occupied / engaged."},
{ id:"a1x279", de:"geöffnet", art:"", pl:"", en:"open (sign)", topic:"travel", level:"a1" , ex:"Der Termin ist geöffnet.", exEn:"The appointment is open (sign)."},
{ id:"a1x280", de:"WC", art:"das", pl:"-s", en:"toilet (sign)", topic:"travel", level:"a1" , ex:"Wo ist das WC?", exEn:"Where is the toilet (sign)?"},
{ id:"a1x281", de:"Fahrstuhl", art:"der", pl:"Fahrstühle", en:"lift (sign)", topic:"travel", level:"a1" , ex:"Wo ist der Fahrstuhl?", exEn:"Where is the lift (sign)?"},
{ id:"a1x282", de:"Gäste", art:"die", pl:"", en:"guests (sign)", topic:"travel", level:"a1" , ex:"Wo ist die Gäste?", exEn:"Where is the guests (sign)?"},
{ id:"a1x283", de:"Wie komme ich zum …?", art:"", pl:"", en:"how do I get to …?", topic:"travel", level:"a1" , ex:"Wie komme ich zum …?", exEn:"How do I get to …?"},
{ id:"a1x284", de:"Ist das weit?", art:"", pl:"", en:"is that far?", topic:"travel", level:"a1" , ex:"Ist das weit?", exEn:"Is that far?"},
{ id:"a1x285", de:"Wetter", art:"das", pl:"", en:"weather", topic:"travel", level:"a1" , ex:"Wo ist das Wetter?", exEn:"Where is the weather?"},
{ id:"a1x286", de:"Sonne", art:"die", pl:"", en:"sun", topic:"travel", level:"a1" , ex:"Wo ist die Sonne?", exEn:"Where is the sun?"},
{ id:"a1x287", de:"Regen", art:"der", pl:"", en:"rain", topic:"travel", level:"a1" , ex:"Wo ist der Regen?", exEn:"Where is the rain?"},
{ id:"a1x288", de:"Schnee", art:"der", pl:"", en:"snow", topic:"travel", level:"a1" , ex:"Wo ist der Schnee?", exEn:"Where is the snow?"},
{ id:"a1x289", de:"Wind", art:"der", pl:"", en:"wind", topic:"travel", level:"a1" , ex:"Wo ist der Wind?", exEn:"Where is the wind?"},
{ id:"a1x290", de:"Wolke", art:"die", pl:"-n", en:"cloud", topic:"travel", level:"a1" , ex:"Wo ist die Wolke?", exEn:"Where is the cloud?"},
{ id:"a1x291", de:"Gewitter", art:"das", pl:"-", en:"thunderstorm", topic:"travel", level:"a1" , ex:"Wo ist das Gewitter?", exEn:"Where is the thunderstorm?"},
{ id:"a1x292", de:"Nebel", art:"der", pl:"", en:"fog", topic:"travel", level:"a1" , ex:"Wo ist der Nebel?", exEn:"Where is the fog?"},
{ id:"a1x293", de:"Grad", art:"der", pl:"", en:"degree (temperature)", topic:"travel", level:"a1" , ex:"Wo ist der Grad?", exEn:"Where is the degree (temperature)?"},
{ id:"a1x294", de:"sonnig", art:"", pl:"", en:"sunny", topic:"travel", level:"a1" , ex:"Der Termin ist sonnig.", exEn:"The appointment is sunny."},
{ id:"a1x295", de:"regnerisch", art:"", pl:"", en:"rainy", topic:"travel", level:"a1" , ex:"Der Termin ist regnerisch.", exEn:"The appointment is rainy."},
{ id:"a1x296", de:"bewölkt", art:"", pl:"", en:"cloudy", topic:"travel", level:"a1" , ex:"Der Termin ist bewölkt.", exEn:"The appointment is cloudy."},
{ id:"a1x297", de:"windig", art:"", pl:"", en:"windy", topic:"travel", level:"a1" , ex:"Der Termin ist windig.", exEn:"The appointment is windy."},
{ id:"a1x298", de:"Job", art:"der", pl:"-s", en:"job", topic:"work", level:"a1" , ex:"Ich brauche den Job morgen.", exEn:"I need the job tomorrow."},
{ id:"a1x299", de:"Chef", art:"der", pl:"-s", en:"boss", topic:"work", level:"a1" , ex:"Ich brauche den Chef morgen.", exEn:"I need the boss tomorrow."},
{ id:"a1x300", de:"Chefin", art:"die", pl:"-nen", en:"boss (f)", topic:"work", level:"a1" , ex:"Ich brauche die Chefin morgen.", exEn:"I need the boss (f) tomorrow."},
{ id:"a1x301", de:"Kollegin", art:"die", pl:"-nen", en:"colleague (f)", topic:"work", level:"a1" , ex:"Ich brauche die Kollegin morgen.", exEn:"I need the colleague (f) tomorrow."},
{ id:"a1x302", de:"Sekretärin", art:"die", pl:"-nen", en:"secretary", topic:"work", level:"a1" , ex:"Ich brauche die Sekretärin morgen.", exEn:"I need the secretary tomorrow."},
{ id:"a1x303", de:"Verkäufer", art:"der", pl:"-", en:"salesperson", topic:"work", level:"a1" , ex:"Ich brauche den Verkäufer morgen.", exEn:"I need the salesperson tomorrow."},
{ id:"a1x304", de:"Verkäuferin", art:"die", pl:"-nen", en:"salesperson (f)", topic:"work", level:"a1" , ex:"Ich brauche die Verkäuferin morgen.", exEn:"I need the salesperson (f) tomorrow."},
{ id:"a1x305", de:"Koch", art:"der", pl:"Köche", en:"cook", topic:"work", level:"a1" , ex:"Ich brauche den Koch morgen.", exEn:"I need the cook tomorrow."},
{ id:"a1x306", de:"Fahrer", art:"der", pl:"-", en:"driver", topic:"work", level:"a1" , ex:"Ich brauche den Fahrer morgen.", exEn:"I need the driver tomorrow."},
{ id:"a1x307", de:"Mechaniker", art:"der", pl:"-", en:"mechanic", topic:"work", level:"a1" , ex:"Ich brauche den Mechaniker morgen.", exEn:"I need the mechanic tomorrow."},
{ id:"a1x308", de:"Ingenieur", art:"der", pl:"-e", en:"engineer", topic:"work", level:"a1" , ex:"Ich brauche den Ingenieur morgen.", exEn:"I need the engineer tomorrow."},
{ id:"a1x309", de:"Krankenschwester", art:"die", pl:"-n", en:"nurse", topic:"work", level:"a1" , ex:"Ich brauche die Krankenschwester morgen.", exEn:"I need the nurse tomorrow."},
{ id:"a1x310", de:"Polizist", art:"der", pl:"-en", en:"police officer", topic:"work", level:"a1" , ex:"Ich brauche den Polizist morgen.", exEn:"I need the police officer tomorrow."},
{ id:"a1x311", de:"Gehalt", art:"das", pl:"Gehälter", en:"salary", topic:"work", level:"a1" , ex:"Ich brauche das Gehalt morgen.", exEn:"I need the salary tomorrow."},
{ id:"a1x312", de:"Vertrag", art:"der", pl:"Verträge", en:"contract", topic:"work", level:"a1" , ex:"Ich brauche den Vertrag morgen.", exEn:"I need the contract tomorrow."},
{ id:"a1x313", de:"Bewerbung", art:"die", pl:"-en", en:"application", topic:"work", level:"a1" , ex:"Ich brauche die Bewerbung morgen.", exEn:"I need the application tomorrow."},
{ id:"a1x314", de:"Lebenslauf", art:"der", pl:"Lebensläufe", en:"CV", topic:"work", level:"a1" , ex:"Ich brauche den Lebenslauf morgen.", exEn:"I need the CV tomorrow."},
{ id:"a1x315", de:"Praktikum", art:"das", pl:"Praktika", en:"internship", topic:"work", level:"a1" , ex:"Ich brauche das Praktikum morgen.", exEn:"I need the internship tomorrow."},
{ id:"a1x316", de:"Ausbildung", art:"die", pl:"-en", en:"vocational training", topic:"work", level:"a1" , ex:"Ich brauche die Ausbildung morgen.", exEn:"I need the vocational training tomorrow."},
{ id:"a1x317", de:"Formular", art:"das", pl:"-e", en:"form", topic:"work", level:"a1" , ex:"Ich brauche das Formular morgen.", exEn:"I need the form tomorrow."},
{ id:"a1x318", de:"Antrag", art:"der", pl:"Anträge", en:"application (official)", topic:"work", level:"a1" , ex:"Ich brauche den Antrag morgen.", exEn:"I need the application (official) tomorrow."},
{ id:"a1x319", de:"Unterschrift", art:"die", pl:"-en", en:"signature", topic:"work", level:"a1" , ex:"Ich brauche die Unterschrift morgen.", exEn:"I need the signature tomorrow."},
{ id:"a1x320", de:"ausfüllen", art:"", pl:"", en:"to fill in", topic:"work", level:"a1" , ex:"Ich möchte heute ausfüllen.", exEn:"I would like to fill in today."},
{ id:"a1x321", de:"unterschreiben", art:"", pl:"", en:"to sign", topic:"work", level:"a1" , ex:"Ich möchte heute unterschreiben.", exEn:"I would like to sign today."},
{ id:"a1x322", de:"Telefonnummer", art:"die", pl:"-n", en:"phone number", topic:"work", level:"a1" , ex:"Ich brauche die Telefonnummer morgen.", exEn:"I need the phone number tomorrow."},
{ id:"a1x323", de:"E-Mail", art:"die", pl:"-s", en:"email", topic:"work", level:"a1" , ex:"Ich brauche die E-Mail morgen.", exEn:"I need the email tomorrow."},
{ id:"a1x324", de:"Stempel", art:"der", pl:"", en:"stamp (official)", topic:"work", level:"a1" , ex:"Ich brauche den Stempel morgen.", exEn:"I need the stamp (official) tomorrow."},
{ id:"a1x325", de:"Ausweis", art:"der", pl:"-e", en:"ID card", topic:"work", level:"a1" , ex:"Ich brauche den Ausweis morgen.", exEn:"I need the ID card tomorrow."},
{ id:"a1x326", de:"Pass", art:"der", pl:"Pässe", en:"passport", topic:"work", level:"a1" , ex:"Ich brauche den Pass morgen.", exEn:"I need the passport tomorrow."},
{ id:"a1x327", de:"Staatsangehörigkeit", art:"die", pl:"-en", en:"citizenship", topic:"work", level:"a1" , ex:"Ich brauche die Staatsangehörigkeit morgen.", exEn:"I need the citizenship tomorrow."},
{ id:"a1x328", de:"Familienstand", art:"der", pl:"", en:"marital status", topic:"work", level:"a1" , ex:"Ich brauche den Familienstand morgen.", exEn:"I need the marital status tomorrow."},
{ id:"a1x329", de:"Klassenzimmer", art:"das", pl:"-", en:"classroom", topic:"work", level:"a1" , ex:"Ich brauche das Klassenzimmer morgen.", exEn:"I need the classroom tomorrow."},
{ id:"a1x330", de:"Tafel", art:"die", pl:"-n", en:"blackboard", topic:"work", level:"a1" , ex:"Ich brauche die Tafel morgen.", exEn:"I need the blackboard tomorrow."},
{ id:"a1x331", de:"Heft", art:"das", pl:"-e", en:"exercise book", topic:"work", level:"a1" , ex:"Ich brauche das Heft morgen.", exEn:"I need the exercise book tomorrow."},
{ id:"a1x332", de:"Stift", art:"der", pl:"-e", en:"pen", topic:"work", level:"a1" , ex:"Ich brauche den Stift morgen.", exEn:"I need the pen tomorrow."},
{ id:"a1x333", de:"Bleistift", art:"der", pl:"-e", en:"pencil", topic:"work", level:"a1" , ex:"Ich brauche den Bleistift morgen.", exEn:"I need the pencil tomorrow."},
{ id:"a1x334", de:"Prüfung", art:"die", pl:"-en", en:"exam / test", topic:"work", level:"a1" , ex:"Ich brauche die Prüfung morgen.", exEn:"I need the exam / test tomorrow."},
{ id:"a1x335", de:"Hausaufgabe machen", art:"", pl:"", en:"to do homework", topic:"work", level:"a1" , ex:"Ich möchte heute Hausaufgabe machen.", exEn:"I would like to do homework today."},
{ id:"a1x336", de:"Pause haben", art:"", pl:"", en:"to have a break", topic:"work", level:"a1" , ex:"Ich möchte heute Pause haben.", exEn:"I would like to have a break today."},
{ id:"a1x337", de:"Auge", art:"das", pl:"-n", en:"eye", topic:"health", level:"a1" , ex:"Ich suche das Auge.", exEn:"I am looking for the eye."},
{ id:"a1x338", de:"Ohr", art:"das", pl:"-en", en:"ear", topic:"health", level:"a1" , ex:"Ich suche das Ohr.", exEn:"I am looking for the ear."},
{ id:"a1x339", de:"Nase", art:"die", pl:"-n", en:"nose", topic:"health", level:"a1" , ex:"Ich suche die Nase.", exEn:"I am looking for the nose."},
{ id:"a1x340", de:"Mund", art:"der", pl:"Münder", en:"mouth", topic:"health", level:"a1" , ex:"Ich suche den Mund.", exEn:"I am looking for the mouth."},
{ id:"a1x341", de:"Zahn", art:"der", pl:"Zähne", en:"tooth", topic:"health", level:"a1" , ex:"Ich suche den Zahn.", exEn:"I am looking for the tooth."},
{ id:"a1x342", de:"Hals", art:"der", pl:"Hälse", en:"neck / throat", topic:"health", level:"a1" , ex:"Ich suche den Hals.", exEn:"I am looking for the neck / throat."},
{ id:"a1x343", de:"Arm", art:"der", pl:"-e", en:"arm", topic:"health", level:"a1" , ex:"Ich suche den Arm.", exEn:"I am looking for the arm."},
{ id:"a1x344", de:"Hand", art:"die", pl:"Hände", en:"hand", topic:"health", level:"a1" , ex:"Ich suche die Hand.", exEn:"I am looking for the hand."},
{ id:"a1x345", de:"Finger", art:"der", pl:"-", en:"finger", topic:"health", level:"a1" , ex:"Ich suche den Finger.", exEn:"I am looking for the finger."},
{ id:"a1x346", de:"Bein", art:"das", pl:"-e", en:"leg", topic:"health", level:"a1" , ex:"Ich suche das Bein.", exEn:"I am looking for the leg."},
{ id:"a1x347", de:"Fuß", art:"der", pl:"Füße", en:"foot", topic:"health", level:"a1" , ex:"Ich suche den Fuß.", exEn:"I am looking for the foot."},
{ id:"a1x348", de:"Rücken", art:"der", pl:"", en:"back", topic:"health", level:"a1" , ex:"Ich suche den Rücken.", exEn:"I am looking for the back."},
{ id:"a1x349", de:"Herz", art:"das", pl:"-en", en:"heart", topic:"health", level:"a1" , ex:"Ich suche das Herz.", exEn:"I am looking for the heart."},
{ id:"a1x350", de:"Blut", art:"das", pl:"", en:"blood", topic:"health", level:"a1" , ex:"Ich suche das Blut.", exEn:"I am looking for the blood."},
{ id:"a1x351", de:"Fieber", art:"das", pl:"", en:"fever", topic:"health", level:"a1" , ex:"Ich suche das Fieber.", exEn:"I am looking for the fever."},
{ id:"a1x352", de:"Husten", art:"der", pl:"", en:"cough", topic:"health", level:"a1" , ex:"Ich suche den Husten.", exEn:"I am looking for the cough."},
{ id:"a1x353", de:"Schnupfen", art:"der", pl:"", en:"cold (runny nose)", topic:"health", level:"a1" , ex:"Ich suche den Schnupfen.", exEn:"I am looking for the cold (runny nose)."},
{ id:"a1x354", de:"Halsweh", art:"das", pl:"", en:"sore throat", topic:"health", level:"a1" , ex:"Ich suche das Halsweh.", exEn:"I am looking for the sore throat."},
{ id:"a1x355", de:"Kopfschmerzen", art:"die", pl:"", en:"headache", topic:"health", level:"a1" , ex:"Ich suche die Kopfschmerzen.", exEn:"I am looking for the headache."},
{ id:"a1x356", de:"Bauchschmerzen", art:"die", pl:"", en:"stomach ache", topic:"health", level:"a1" , ex:"Ich suche die Bauchschmerzen.", exEn:"I am looking for the stomach ache."},
{ id:"a1x357", de:"Tablette", art:"die", pl:"-n", en:"tablet / pill", topic:"health", level:"a1" , ex:"Ich suche die Tablette.", exEn:"I am looking for the tablet / pill."},
{ id:"a1x358", de:"Tropfen", art:"die", pl:"", en:"drops (medicine)", topic:"health", level:"a1" , ex:"Ich suche die Tropfen.", exEn:"I am looking for the drops (medicine)."},
{ id:"a1x359", de:"Pflaster", art:"das", pl:"-", en:"plaster / band-aid", topic:"health", level:"a1" , ex:"Ich suche das Pflaster.", exEn:"I am looking for the plaster / band-aid."},
{ id:"a1x360", de:"Impfung", art:"die", pl:"-en", en:"vaccination", topic:"health", level:"a1" , ex:"Ich suche die Impfung.", exEn:"I am looking for the vaccination."},
{ id:"a1x361", de:"Allergie", art:"die", pl:"-n", en:"allergy", topic:"health", level:"a1" , ex:"Ich suche die Allergie.", exEn:"I am looking for the allergy."},
{ id:"a1x362", de:"Notaufnahme", art:"die", pl:"-n", en:"A&E / ER", topic:"health", level:"a1" , ex:"Ich suche die Notaufnahme.", exEn:"I am looking for the A&E / ER."},
{ id:"a1x363", de:"Sprechstunde", art:"die", pl:"-n", en:"surgery hours", topic:"health", level:"a1" , ex:"Ich suche die Sprechstunde.", exEn:"I am looking for the surgery hours."},
{ id:"a1x364", de:"Rezept", art:"das", pl:"-e", en:"prescription", topic:"health", level:"a1" , ex:"Ich suche das Rezept.", exEn:"I am looking for the prescription."},
{ id:"a1x365", de:"Versicherung", art:"die", pl:"-en", en:"insurance", topic:"health", level:"a1" , ex:"Ich suche die Versicherung.", exEn:"I am looking for the insurance."},
{ id:"a1x366", de:"Krankenkasse", art:"die", pl:"-n", en:"health insurance fund", topic:"health", level:"a1" , ex:"Ich suche die Krankenkasse.", exEn:"I am looking for the health insurance fund."},
{ id:"a1x367", de:"weh tun", art:"", pl:"", en:"to hurt", topic:"health", level:"a1" , ex:"Ich möchte heute weh tun.", exEn:"I would like to hurt today."},
{ id:"a1x368", de:"Mir ist schlecht", art:"", pl:"", en:"I feel sick", topic:"health", level:"a1" , ex:"Mir ist schlecht — das sage ich oft im Amt.", exEn:"I feel sick — I often say that at the office."},
{ id:"a1x369", de:"Ich habe Schmerzen", art:"", pl:"", en:"I am in pain", topic:"health", level:"a1" , ex:"Ich habe Schmerzen — das sage ich oft im Amt.", exEn:"I am in pain — I often say that at the office."},
{ id:"a1x370", de:"Zahnarzt", art:"der", pl:"Zahnärzte", en:"dentist", topic:"health", level:"a1" , ex:"Ich suche den Zahnarzt.", exEn:"I am looking for the dentist."},
{ id:"a1x371", de:"Augenarzt", art:"der", pl:"Augenärzte", en:"eye doctor", topic:"health", level:"a1" , ex:"Ich suche den Augenarzt.", exEn:"I am looking for the eye doctor."},
{ id:"a1x372", de:"Hemd", art:"das", pl:"-en", en:"shirt", topic:"shopping", level:"a1" , ex:"Ich kaufe das Hemd.", exEn:"I am buying the shirt."},
{ id:"a1x373", de:"T-Shirt", art:"das", pl:"-s", en:"T-shirt", topic:"shopping", level:"a1" , ex:"Ich kaufe das T-Shirt.", exEn:"I am buying the T-shirt."},
{ id:"a1x374", de:"Pullover", art:"der", pl:"-", en:"jumper / sweater", topic:"shopping", level:"a1" , ex:"Ich kaufe den Pullover.", exEn:"I am buying the jumper / sweater."},
{ id:"a1x375", de:"Rock", art:"der", pl:"Röcke", en:"skirt", topic:"shopping", level:"a1" , ex:"Ich kaufe den Rock.", exEn:"I am buying the skirt."},
{ id:"a1x376", de:"Kleid", art:"das", pl:"-er", en:"dress", topic:"shopping", level:"a1" , ex:"Ich kaufe das Kleid.", exEn:"I am buying the dress."},
{ id:"a1x377", de:"Mantel", art:"der", pl:"Mäntel", en:"coat", topic:"shopping", level:"a1" , ex:"Ich kaufe den Mantel.", exEn:"I am buying the coat."},
{ id:"a1x378", de:"Mütze", art:"die", pl:"-n", en:"beanie / cap", topic:"shopping", level:"a1" , ex:"Ich kaufe die Mütze.", exEn:"I am buying the beanie / cap."},
{ id:"a1x379", de:"Schal", art:"der", pl:"-s", en:"scarf", topic:"shopping", level:"a1" , ex:"Ich kaufe den Schal.", exEn:"I am buying the scarf."},
{ id:"a1x380", de:"Handschuh", art:"der", pl:"-e", en:"glove", topic:"shopping", level:"a1" , ex:"Ich kaufe den Handschuh.", exEn:"I am buying the glove."},
{ id:"a1x381", de:"Socke", art:"die", pl:"-n", en:"sock", topic:"shopping", level:"a1" , ex:"Ich kaufe die Socke.", exEn:"I am buying the sock."},
{ id:"a1x382", de:"Unterwäsche", art:"die", pl:"", en:"underwear", topic:"shopping", level:"a1" , ex:"Ich kaufe die Unterwäsche.", exEn:"I am buying the underwear."},
{ id:"a1x383", de:"Brille", art:"die", pl:"-n", en:"glasses", topic:"shopping", level:"a1" , ex:"Ich kaufe die Brille.", exEn:"I am buying the glasses."},
{ id:"a1x384", de:"Armbanduhr", art:"die", pl:"-en", en:"wristwatch", topic:"shopping", level:"a1" , ex:"Ich kaufe die Armbanduhr.", exEn:"I am buying the wristwatch."},
{ id:"a1x385", de:"Gürtel", art:"der", pl:"-", en:"belt", topic:"shopping", level:"a1" , ex:"Ich kaufe den Gürtel.", exEn:"I am buying the belt."},
{ id:"a1x386", de:"rot", art:"", pl:"", en:"red", topic:"shopping", level:"a1" , ex:"Der Termin ist rot.", exEn:"The appointment is red."},
{ id:"a1x387", de:"blau", art:"", pl:"", en:"blue", topic:"shopping", level:"a1" , ex:"Der Termin ist blau.", exEn:"The appointment is blue."},
{ id:"a1x388", de:"grün", art:"", pl:"", en:"green", topic:"shopping", level:"a1" , ex:"Der Termin ist grün.", exEn:"The appointment is green."},
{ id:"a1x389", de:"gelb", art:"", pl:"", en:"yellow", topic:"shopping", level:"a1" , ex:"Der Termin ist gelb.", exEn:"The appointment is yellow."},
{ id:"a1x390", de:"schwarz", art:"", pl:"", en:"black", topic:"shopping", level:"a1" , ex:"Der Termin ist schwarz.", exEn:"The appointment is black."},
{ id:"a1x391", de:"weiß", art:"", pl:"", en:"white", topic:"shopping", level:"a1" , ex:"Der Termin ist weiß.", exEn:"The appointment is white."},
{ id:"a1x392", de:"grau", art:"", pl:"", en:"grey", topic:"shopping", level:"a1" , ex:"Der Termin ist grau.", exEn:"The appointment is grey."},
{ id:"a1x393", de:"braun", art:"", pl:"", en:"brown", topic:"shopping", level:"a1" , ex:"Der Termin ist braun.", exEn:"The appointment is brown."},
{ id:"a1x394", de:"bezahlen", art:"", pl:"", en:"to pay", topic:"shopping", level:"a1" , ex:"Ich möchte heute bezahlen.", exEn:"I would like to pay today."},
{ id:"a1x395", de:"Bargeld", art:"das", pl:"", en:"cash", topic:"shopping", level:"a1" , ex:"Ich kaufe das Bargeld.", exEn:"I am buying the cash."},
{ id:"a1x396", de:"Kreditkarte", art:"die", pl:"-n", en:"credit card", topic:"shopping", level:"a1" , ex:"Ich kaufe die Kreditkarte.", exEn:"I am buying the credit card."},
{ id:"a1x397", de:"Quittung", art:"die", pl:"-en", en:"receipt", topic:"shopping", level:"a1" , ex:"Ich kaufe die Quittung.", exEn:"I am buying the receipt."},
{ id:"a1x398", de:"Wechselgeld", art:"das", pl:"", en:"change (money)", topic:"shopping", level:"a1" , ex:"Ich kaufe das Wechselgeld.", exEn:"I am buying the change (money)."},
{ id:"a1x399", de:"Angebot", art:"das", pl:"-e", en:"offer / special", topic:"shopping", level:"a1" , ex:"Ich kaufe das Angebot.", exEn:"I am buying the offer / special."},
{ id:"a1x400", de:"Umkleide", art:"die", pl:"-n", en:"changing room", topic:"shopping", level:"a1" , ex:"Ich kaufe die Umkleide.", exEn:"I am buying the changing room."},
{ id:"a1x401", de:"Kasse", art:"die", pl:"-n", en:"till / checkout", topic:"shopping", level:"a1" , ex:"Ich kaufe die Kasse.", exEn:"I am buying the till / checkout."},
{ id:"a1x402", de:"Was kostet das?", art:"", pl:"", en:"how much is that?", topic:"shopping", level:"a1" , ex:"Was kostet das?", exEn:"How much is that?"},
{ id:"a1x403", de:"Kann ich mit Karte zahlen?", art:"", pl:"", en:"can I pay by card?", topic:"shopping", level:"a1" , ex:"Kann ich mit Karte zahlen?", exEn:"Can I pay by card?"},
{ id:"a1x404", de:"Haben Sie das in …?", art:"", pl:"", en:"do you have that in …?", topic:"shopping", level:"a1" , ex:"Haben Sie das in …?", exEn:"Do you have that in …?"},
{ id:"a1x405", de:"zu groß", art:"", pl:"", en:"too big", topic:"shopping", level:"a1" , ex:"Zu groß — das sage ich oft im Amt.", exEn:"Too big — I often say that at the office."},
{ id:"a1x406", de:"zu klein", art:"", pl:"", en:"too small", topic:"shopping", level:"a1" , ex:"Zu klein — das sage ich oft im Amt.", exEn:"Too small — I often say that at the office."},
{ id:"a1x407", de:"passt", art:"", pl:"", en:"it fits", topic:"shopping", level:"a1" , ex:"Der Termin ist passt.", exEn:"The appointment is it fits."},
{ id:"a1x408", de:"Drogerie", art:"die", pl:"-n", en:"drugstore", topic:"shopping", level:"a1" , ex:"Ich kaufe die Drogerie.", exEn:"I am buying the drugstore."},
{ id:"a1x409", de:"Marktstand", art:"der", pl:"Marktstände", en:"market stall", topic:"shopping", level:"a1" , ex:"Ich kaufe den Marktstand.", exEn:"I am buying the market stall."},
{ id:"a1x410", de:"sehen", art:"", pl:"", en:"to see", topic:"verbs", level:"a1" , ex:"Ich möchte heute sehen.", exEn:"I would like to see today."},
{ id:"a1x411", de:"hören", art:"", pl:"", en:"to hear", topic:"verbs", level:"a1" , ex:"Ich möchte heute hören.", exEn:"I would like to hear today."},
{ id:"a1x412", de:"sagen", art:"", pl:"", en:"to say", topic:"verbs", level:"a1" , ex:"Ich möchte heute sagen.", exEn:"I would like to say today."},
{ id:"a1x413", de:"fragen", art:"", pl:"", en:"to ask", topic:"verbs", level:"a1" , ex:"Ich möchte heute fragen.", exEn:"I would like to ask today."},
{ id:"a1x414", de:"antworten", art:"", pl:"", en:"to answer", topic:"verbs", level:"a1" , ex:"Ich möchte heute antworten.", exEn:"I would like to answer today."},
{ id:"a1x415", de:"geben", art:"", pl:"", en:"to give", topic:"verbs", level:"a1" , ex:"Ich möchte heute geben.", exEn:"I would like to give today."},
{ id:"a1x416", de:"nehmen", art:"", pl:"", en:"to take", topic:"verbs", level:"a1" , ex:"Ich möchte heute nehmen.", exEn:"I would like to take today."},
{ id:"a1x417", de:"bringen", art:"", pl:"", en:"to bring", topic:"verbs", level:"a1" , ex:"Ich möchte heute bringen.", exEn:"I would like to bring today."},
{ id:"a1x418", de:"holen", art:"", pl:"", en:"to fetch", topic:"verbs", level:"a1" , ex:"Ich möchte heute holen.", exEn:"I would like to fetch today."},
{ id:"a1x419", de:"bleiben", art:"", pl:"", en:"to stay", topic:"verbs", level:"a1" , ex:"Ich möchte heute bleiben.", exEn:"I would like to stay today."},
{ id:"a1x420", de:"fahren", art:"", pl:"", en:"to go (by vehicle)", topic:"verbs", level:"a1" , ex:"Ich möchte heute fahren.", exEn:"I would like to go (by vehicle) today."},
{ id:"a1x421", de:"fliegen", art:"", pl:"", en:"to fly", topic:"verbs", level:"a1" , ex:"Ich möchte heute fliegen.", exEn:"I would like to fly today."},
{ id:"a1x422", de:"laufen", art:"", pl:"", en:"to run / walk", topic:"verbs", level:"a1" , ex:"Ich möchte heute laufen.", exEn:"I would like to run / walk today."},
{ id:"a1x423", de:"stehen", art:"", pl:"", en:"to stand", topic:"verbs", level:"a1" , ex:"Ich möchte heute stehen.", exEn:"I would like to stand today."},
{ id:"a1x424", de:"sitzen", art:"", pl:"", en:"to sit", topic:"verbs", level:"a1" , ex:"Ich möchte heute sitzen.", exEn:"I would like to sit today."},
{ id:"a1x425", de:"liegen", art:"", pl:"", en:"to lie / be lying", topic:"verbs", level:"a1" , ex:"Ich möchte heute liegen.", exEn:"I would like to lie / be lying today."},
{ id:"a1x426", de:"öffnen", art:"", pl:"", en:"to open", topic:"verbs", level:"a1" , ex:"Ich möchte heute öffnen.", exEn:"I would like to open today."},
{ id:"a1x427", de:"schließen", art:"", pl:"", en:"to close", topic:"verbs", level:"a1" , ex:"Ich möchte heute schließen.", exEn:"I would like to close today."},
{ id:"a1x428", de:"beginnen", art:"", pl:"", en:"to begin", topic:"verbs", level:"a1" , ex:"Ich möchte heute beginnen.", exEn:"I would like to begin today."},
{ id:"a1x429", de:"enden", art:"", pl:"", en:"to end", topic:"verbs", level:"a1" , ex:"Ich möchte heute enden.", exEn:"I would like to end today."},
{ id:"a1x430", de:"warten", art:"", pl:"", en:"to wait", topic:"verbs", level:"a1" , ex:"Ich möchte heute warten.", exEn:"I would like to wait today."},
{ id:"a1x431", de:"suchen", art:"", pl:"", en:"to look for", topic:"verbs", level:"a1" , ex:"Ich möchte heute suchen.", exEn:"I would like to look for today."},
{ id:"a1x432", de:"helfen", art:"", pl:"", en:"to help", topic:"verbs", level:"a1" , ex:"Ich möchte heute helfen.", exEn:"I would like to help today."},
{ id:"a1x433", de:"danken", art:"", pl:"", en:"to thank", topic:"verbs", level:"a1" , ex:"Ich möchte heute danken.", exEn:"I would like to thank today."},
{ id:"a1x434", de:"kennen", art:"", pl:"", en:"to know (a person/place)", topic:"verbs", level:"a1" , ex:"Ich möchte heute kennen.", exEn:"I would like to know (a person/place) today."},
{ id:"a1x435", de:"wissen", art:"", pl:"", en:"to know (a fact)", topic:"verbs", level:"a1" , ex:"Ich möchte heute wissen.", exEn:"I would like to know (a fact) today."},
{ id:"a1x436", de:"können", art:"", pl:"", en:"can / to be able", topic:"verbs", level:"a1" , ex:"Ich möchte heute können.", exEn:"I would like can / to be able today."},
{ id:"a1x437", de:"müssen", art:"", pl:"", en:"must / to have to", topic:"verbs", level:"a1" , ex:"Ich möchte heute müssen.", exEn:"I would like must / to have to today."},
{ id:"a1x438", de:"wollen", art:"", pl:"", en:"to want", topic:"verbs", level:"a1" , ex:"Ich möchte heute wollen.", exEn:"I would like to want today."},
{ id:"a1x439", de:"dürfen", art:"", pl:"", en:"may / to be allowed", topic:"verbs", level:"a1" , ex:"Ich möchte heute dürfen.", exEn:"I would like may / to be allowed today."},
{ id:"a1x440", de:"sollen", art:"", pl:"", en:"should / to be supposed to", topic:"verbs", level:"a1" , ex:"Ich möchte heute sollen.", exEn:"I would like should / to be supposed to today."},
{ id:"a1x441", de:"mögen", art:"", pl:"", en:"to like", topic:"verbs", level:"a1" , ex:"Ich möchte heute mögen.", exEn:"I would like to like today."},
{ id:"a1x442", de:"möchten", art:"", pl:"", en:"would like", topic:"verbs", level:"a1" , ex:"Ich möchte heute möchten.", exEn:"I would like would like today."},
{ id:"a1x443", de:"treffen", art:"", pl:"", en:"to meet", topic:"verbs", level:"a1" , ex:"Ich möchte heute treffen.", exEn:"I would like to meet today."},
{ id:"a1x444", de:"besuchen", art:"", pl:"", en:"to visit", topic:"verbs", level:"a1" , ex:"Ich möchte heute besuchen.", exEn:"I would like to visit today."},
{ id:"a1x445", de:"zeigen", art:"", pl:"", en:"to show", topic:"verbs", level:"a1" , ex:"Ich möchte heute zeigen.", exEn:"I would like to show today."},
{ id:"a1x446", de:"erklären", art:"", pl:"", en:"to explain", topic:"verbs", level:"a1" , ex:"Ich möchte heute erklären.", exEn:"I would like to explain today."},
{ id:"a1x447", de:"wiederholen", art:"", pl:"", en:"to repeat", topic:"verbs", level:"a1" , ex:"Ich möchte heute wiederholen.", exEn:"I would like to repeat today."},
{ id:"a1x448", de:"buchstabieren", art:"", pl:"", en:"to spell", topic:"verbs", level:"a1" , ex:"Ich möchte heute buchstabieren.", exEn:"I would like to spell today."},
{ id:"a1x449", de:"kosten", art:"", pl:"", en:"to cost", topic:"verbs", level:"a1" , ex:"Ich möchte heute kosten.", exEn:"I would like to cost today."},
{ id:"a1x450", de:"heiß", art:"", pl:"", en:"hot", topic:"adjectives", level:"a1" , ex:"Der Termin ist heiß.", exEn:"The appointment is hot."},
{ id:"a1x451", de:"kühl", art:"", pl:"", en:"cool", topic:"adjectives", level:"a1" , ex:"Der Termin ist kühl.", exEn:"The appointment is cool."},
{ id:"a1x452", de:"nass", art:"", pl:"", en:"wet", topic:"adjectives", level:"a1" , ex:"Der Termin ist nass.", exEn:"The appointment is wet."},
{ id:"a1x453", de:"trocken", art:"", pl:"", en:"dry", topic:"adjectives", level:"a1" , ex:"Ich möchte heute trocken.", exEn:"I would like dry today."},
{ id:"a1x454", de:"sauber", art:"", pl:"", en:"clean", topic:"adjectives", level:"a1" , ex:"Der Termin ist sauber.", exEn:"The appointment is clean."},
{ id:"a1x455", de:"schmutzig", art:"", pl:"", en:"dirty", topic:"adjectives", level:"a1" , ex:"Der Termin ist schmutzig.", exEn:"The appointment is dirty."},
{ id:"a1x456", de:"voll", art:"", pl:"", en:"full", topic:"adjectives", level:"a1" , ex:"Der Termin ist voll.", exEn:"The appointment is full."},
{ id:"a1x457", de:"leer", art:"", pl:"", en:"empty", topic:"adjectives", level:"a1" , ex:"Der Termin ist leer.", exEn:"The appointment is empty."},
{ id:"a1x458", de:"richtig", art:"", pl:"", en:"correct / right", topic:"adjectives", level:"a1" , ex:"Der Termin ist richtig.", exEn:"The appointment is correct / right."},
{ id:"a1x459", de:"falsch", art:"", pl:"", en:"wrong", topic:"adjectives", level:"a1" , ex:"Der Termin ist falsch.", exEn:"The appointment is wrong."},
{ id:"a1x460", de:"nah", art:"", pl:"", en:"near", topic:"adjectives", level:"a1" , ex:"Der Termin ist nah.", exEn:"The appointment is near."},
{ id:"a1x461", de:"weit", art:"", pl:"", en:"far", topic:"adjectives", level:"a1" , ex:"Der Termin ist weit.", exEn:"The appointment is far."},
{ id:"a1x462", de:"laut", art:"", pl:"", en:"loud", topic:"adjectives", level:"a1" , ex:"Der Termin ist laut.", exEn:"The appointment is loud."},
{ id:"a1x463", de:"leise", art:"", pl:"", en:"quiet", topic:"adjectives", level:"a1" , ex:"Der Termin ist leise.", exEn:"The appointment is quiet."},
{ id:"a1x464", de:"hell", art:"", pl:"", en:"bright", topic:"adjectives", level:"a1" , ex:"Der Termin ist hell.", exEn:"The appointment is bright."},
{ id:"a1x465", de:"dunkel", art:"", pl:"", en:"dark", topic:"adjectives", level:"a1" , ex:"Der Termin ist dunkel.", exEn:"The appointment is dark."},
{ id:"a1x466", de:"hungrig", art:"", pl:"", en:"hungry", topic:"adjectives", level:"a1" , ex:"Der Termin ist hungrig.", exEn:"The appointment is hungry."},
{ id:"a1x467", de:"durstig", art:"", pl:"", en:"thirsty", topic:"adjectives", level:"a1" , ex:"Der Termin ist durstig.", exEn:"The appointment is thirsty."},
{ id:"a1x468", de:"froh", art:"", pl:"", en:"glad", topic:"adjectives", level:"a1" , ex:"Der Termin ist froh.", exEn:"The appointment is glad."},
{ id:"a1x469", de:"traurig", art:"", pl:"", en:"sad", topic:"adjectives", level:"a1" , ex:"Der Termin ist traurig.", exEn:"The appointment is sad."},
{ id:"a1x470", de:"freundlich", art:"", pl:"", en:"friendly", topic:"adjectives", level:"a1" , ex:"Der Termin ist freundlich.", exEn:"The appointment is friendly."},
{ id:"a1x471", de:"nett", art:"", pl:"", en:"nice", topic:"adjectives", level:"a1" , ex:"Der Termin ist nett.", exEn:"The appointment is nice."},
{ id:"a1x472", de:"höflich", art:"", pl:"", en:"polite", topic:"adjectives", level:"a1" , ex:"Der Termin ist höflich.", exEn:"The appointment is polite."},
{ id:"a1x473", de:"wichtig", art:"", pl:"", en:"important", topic:"adjectives", level:"a1" , ex:"Der Termin ist wichtig.", exEn:"The appointment is important."},
{ id:"a1x474", de:"interessant", art:"", pl:"", en:"interesting", topic:"adjectives", level:"a1" , ex:"Der Termin ist interessant.", exEn:"The appointment is interesting."},
{ id:"a1x475", de:"langweilig", art:"", pl:"", en:"boring", topic:"adjectives", level:"a1" , ex:"Der Termin ist langweilig.", exEn:"The appointment is boring."},
{ id:"a1x476", de:"fertig", art:"", pl:"", en:"ready / finished", topic:"adjectives", level:"a1" , ex:"Der Termin ist fertig.", exEn:"The appointment is ready / finished."},
{ id:"a1x477", de:"kaputt", art:"", pl:"", en:"broken", topic:"adjectives", level:"a1" , ex:"Der Termin ist kaputt.", exEn:"The appointment is broken."},
{ id:"a1x478", de:"glücklich", art:"", pl:"", en:"happy", topic:"adjectives", level:"a1" , ex:"Der Termin ist glücklich.", exEn:"The appointment is happy."},
{ id:"a1x479", de:"böse", art:"", pl:"", en:"angry / bad", topic:"adjectives", level:"a1" , ex:"Der Termin ist böse.", exEn:"The appointment is angry / bad."},
{ id:"a1x480", de:"jung", art:"", pl:"", en:"young", topic:"adjectives", level:"a1" , ex:"Der Termin ist jung.", exEn:"The appointment is young."},
{ id:"a1x481", de:"kurz", art:"", pl:"", en:"short", topic:"adjectives", level:"a1" , ex:"Der Termin ist kurz.", exEn:"The appointment is short."},
{ id:"a1x482", de:"lang", art:"", pl:"", en:"long", topic:"adjectives", level:"a1" , ex:"Der Termin ist lang.", exEn:"The appointment is long."},
{ id:"a1x483", de:"breit", art:"", pl:"", en:"wide", topic:"adjectives", level:"a1" , ex:"Der Termin ist breit.", exEn:"The appointment is wide."},
{ id:"a1x484", de:"eng", art:"", pl:"", en:"tight / narrow", topic:"adjectives", level:"a1" , ex:"Der Termin ist eng.", exEn:"The appointment is tight / narrow."},
{ id:"a1x485", de:"Konto", art:"das", pl:"Konten", en:"bank account", topic:"shopping", level:"a1" , ex:"Ich kaufe das Konto.", exEn:"I am buying the bank account."},
{ id:"a1x486", de:"PLZ", art:"die", pl:"", en:"postcode", topic:"shopping", level:"a1" , ex:"Ich kaufe die PLZ.", exEn:"I am buying the postcode."},
{ id:"a1x487", de:"Postleitzahl", art:"die", pl:"-en", en:"postcode (full word)", topic:"shopping", level:"a1" , ex:"Ich kaufe die Postleitzahl.", exEn:"I am buying the postcode (full word)."},
{ id:"a1x488", de:"Möbel", art:"die", pl:"", en:"furniture", topic:"home", level:"a1" , ex:"Hier sind die Möbel.", exEn:"Here are the furniture."},
{ id:"a1x489", de:"Straße", art:"die", pl:"-n", en:"street", topic:"home", level:"a1" , ex:"Wo ist die Straße?", exEn:"Where is the street?"},
{ id:"a1x490", de:"Hausnummer", art:"die", pl:"-n", en:"house number", topic:"home", level:"a1" , ex:"Wo ist die Hausnummer?", exEn:"Where is the house number?"}
  ]
};
