export default {
  vocab: [
{ id:"a1x1", de:"Gute Nacht", art:"", pl:"", en:"good night", topic:"greetings", level:"a1" },
{ id:"a1x2", de:"Bis bald", art:"", pl:"", en:"see you soon", topic:"greetings", level:"a1" },
{ id:"a1x3", de:"Bis später", art:"", pl:"", en:"see you later", topic:"greetings", level:"a1" },
{ id:"a1x4", de:"Bis morgen", art:"", pl:"", en:"see you tomorrow", topic:"greetings", level:"a1" },
{ id:"a1x5", de:"Schön, Sie kennenzulernen", art:"", pl:"", en:"nice to meet you (formal)", topic:"greetings", level:"a1" },
{ id:"a1x6", de:"Freut mich", art:"", pl:"", en:"pleased to meet you", topic:"greetings", level:"a1" },
{ id:"a1x7", de:"Gleichfalls", art:"", pl:"", en:"likewise", topic:"greetings", level:"a1" },
{ id:"a1x8", de:"Wie bitte?", art:"", pl:"", en:"pardon? / sorry?", topic:"greetings", level:"a1" },
{ id:"a1x9", de:"Langsamer bitte", art:"", pl:"", en:"more slowly please", topic:"greetings", level:"a1" },
{ id:"a1x10", de:"Ich verstehe nicht", art:"", pl:"", en:"I don't understand", topic:"greetings", level:"a1" },
{ id:"a1x11", de:"Sprechen Sie Deutsch?", art:"", pl:"", en:"Do you speak German?", topic:"greetings", level:"a1" },
{ id:"a1x12", de:"Ein bisschen", art:"", pl:"", en:"a little", topic:"greetings", level:"a1" },
{ id:"a1x13", de:"Kein Problem", art:"", pl:"", en:"no problem", topic:"greetings", level:"a1" },
{ id:"a1x14", de:"Gern geschehen", art:"", pl:"", en:"you're welcome", topic:"greetings", level:"a1" },
{ id:"a1x15", de:"Mit Vergnügen", art:"", pl:"", en:"with pleasure", topic:"greetings", level:"a1" },
{ id:"a1x16", de:"Alles Gute", art:"", pl:"", en:"all the best", topic:"greetings", level:"a1" },
{ id:"a1x17", de:"Herzlichen Glückwunsch", art:"", pl:"", en:"congratulations", topic:"greetings", level:"a1" },
{ id:"a1x18", de:"Prost", art:"", pl:"", en:"cheers", topic:"greetings", level:"a1" },
{ id:"a1x19", de:"Gesundheit", art:"", pl:"", en:"bless you / health", topic:"greetings", level:"a1" },
{ id:"a1x20", de:"Schönen Tag noch", art:"", pl:"", en:"have a nice day", topic:"greetings", level:"a1" },
{ id:"a1x21", de:"Schönen Abend noch", art:"", pl:"", en:"have a nice evening", topic:"greetings", level:"a1" },
{ id:"a1x22", de:"Wie geht es Ihnen?", art:"", pl:"", en:"how are you? (formal)", topic:"greetings", level:"a1" },
{ id:"a1x23", de:"Es geht", art:"", pl:"", en:"I'm okay / so-so", topic:"greetings", level:"a1" },
{ id:"a1x24", de:"Sehr gut", art:"", pl:"", en:"very good", topic:"greetings", level:"a1" },
{ id:"a1x25", de:"Natürlich", art:"", pl:"", en:"of course", topic:"greetings", level:"a1" },
{ id:"a1x26", de:"Genau", art:"", pl:"", en:"exactly", topic:"greetings", level:"a1" },
{ id:"a1x27", de:"Prima", art:"", pl:"", en:"great", topic:"greetings", level:"a1" },
{ id:"a1x28", de:"Super", art:"", pl:"", en:"super", topic:"greetings", level:"a1" },
{ id:"a1x29", de:"Tut mir leid", art:"", pl:"", en:"I'm sorry", topic:"greetings", level:"a1" },
{ id:"a1x30", de:"Macht nichts", art:"", pl:"", en:"never mind", topic:"greetings", level:"a1" },
{ id:"a1x31", de:"Oma", art:"die", pl:"-s", en:"grandma", topic:"people", level:"a1" },
{ id:"a1x32", de:"Opa", art:"der", pl:"-s", en:"grandpa", topic:"people", level:"a1" },
{ id:"a1x33", de:"Onkel", art:"der", pl:"-", en:"uncle", topic:"people", level:"a1" },
{ id:"a1x34", de:"Tante", art:"die", pl:"-n", en:"aunt", topic:"people", level:"a1" },
{ id:"a1x35", de:"Cousin", art:"der", pl:"-s", en:"male cousin", topic:"people", level:"a1" },
{ id:"a1x36", de:"Cousine", art:"die", pl:"-n", en:"female cousin", topic:"people", level:"a1" },
{ id:"a1x37", de:"Enkel", art:"der", pl:"-", en:"grandson", topic:"people", level:"a1" },
{ id:"a1x38", de:"Enkelin", art:"die", pl:"-nen", en:"granddaughter", topic:"people", level:"a1" },
{ id:"a1x39", de:"Partner", art:"der", pl:"-", en:"partner", topic:"people", level:"a1" },
{ id:"a1x40", de:"Partnerin", art:"die", pl:"-nen", en:"partner (f)", topic:"people", level:"a1" },
{ id:"a1x41", de:"Mädchen", art:"das", pl:"-", en:"girl", topic:"people", level:"a1" },
{ id:"a1x42", de:"Junge", art:"der", pl:"-n", en:"boy", topic:"people", level:"a1" },
{ id:"a1x43", de:"Eltern", art:"die", pl:"", en:"parents", topic:"people", level:"a1" },
{ id:"a1x44", de:"Großeltern", art:"die", pl:"", en:"grandparents", topic:"people", level:"a1" },
{ id:"a1x45", de:"ledig", art:"", pl:"", en:"single (unmarried)", topic:"people", level:"a1" },
{ id:"a1x46", de:"verheiratet", art:"", pl:"", en:"married", topic:"people", level:"a1" },
{ id:"a1x47", de:"geschieden", art:"", pl:"", en:"divorced", topic:"people", level:"a1" },
{ id:"a1x48", de:"verwitwet", art:"", pl:"", en:"widowed", topic:"people", level:"a1" },
{ id:"a1x49", de:"Nationalität", art:"die", pl:"-en", en:"nationality", topic:"people", level:"a1" },
{ id:"a1x50", de:"Land", art:"das", pl:"Länder", en:"country", topic:"people", level:"a1" },
{ id:"a1x51", de:"Deutschland", art:"das", pl:"", en:"Germany", topic:"people", level:"a1" },
{ id:"a1x52", de:"Österreich", art:"das", pl:"", en:"Austria", topic:"people", level:"a1" },
{ id:"a1x53", de:"Schweiz", art:"die", pl:"", en:"Switzerland", topic:"people", level:"a1" },
{ id:"a1x54", de:"Sprache", art:"die", pl:"-n", en:"language", topic:"people", level:"a1" },
{ id:"a1x55", de:"Deutsch", art:"das", pl:"", en:"German (language)", topic:"people", level:"a1" },
{ id:"a1x56", de:"Englisch", art:"das", pl:"", en:"English", topic:"people", level:"a1" },
{ id:"a1x57", de:"Alter", art:"das", pl:"", en:"age", topic:"people", level:"a1" },
{ id:"a1x58", de:"Jahre alt", art:"", pl:"", en:"years old", topic:"people", level:"a1" },
{ id:"a1x59", de:"Geburtsdatum", art:"das", pl:"-daten", en:"date of birth", topic:"people", level:"a1" },
{ id:"a1x60", de:"Geburtsort", art:"der", pl:"-e", en:"place of birth", topic:"people", level:"a1" },
{ id:"a1x61", de:"Geschlecht", art:"das", pl:"-er", en:"gender", topic:"people", level:"a1" },
{ id:"a1x62", de:"männlich", art:"", pl:"", en:"male", topic:"people", level:"a1" },
{ id:"a1x63", de:"weiblich", art:"", pl:"", en:"female", topic:"people", level:"a1" },
{ id:"a1x64", de:"Ich heiße", art:"", pl:"", en:"my name is", topic:"people", level:"a1" },
{ id:"a1x65", de:"Mein Name ist", art:"", pl:"", en:"my name is", topic:"people", level:"a1" },
{ id:"a1x66", de:"Woher kommen Sie?", art:"", pl:"", en:"where are you from? (formal)", topic:"people", level:"a1" },
{ id:"a1x67", de:"Ich komme aus", art:"", pl:"", en:"I come from", topic:"people", level:"a1" },
{ id:"a1x68", de:"elf", art:"", pl:"", en:"eleven", topic:"numbers", level:"a1" },
{ id:"a1x69", de:"zwölf", art:"", pl:"", en:"twelve", topic:"numbers", level:"a1" },
{ id:"a1x70", de:"dreizehn", art:"", pl:"", en:"thirteen", topic:"numbers", level:"a1" },
{ id:"a1x71", de:"vierzehn", art:"", pl:"", en:"fourteen", topic:"numbers", level:"a1" },
{ id:"a1x72", de:"fünfzehn", art:"", pl:"", en:"fifteen", topic:"numbers", level:"a1" },
{ id:"a1x73", de:"sechzehn", art:"", pl:"", en:"sixteen", topic:"numbers", level:"a1" },
{ id:"a1x74", de:"siebzehn", art:"", pl:"", en:"seventeen", topic:"numbers", level:"a1" },
{ id:"a1x75", de:"achtzehn", art:"", pl:"", en:"eighteen", topic:"numbers", level:"a1" },
{ id:"a1x76", de:"neunzehn", art:"", pl:"", en:"nineteen", topic:"numbers", level:"a1" },
{ id:"a1x77", de:"zwanzig", art:"", pl:"", en:"twenty", topic:"numbers", level:"a1" },
{ id:"a1x78", de:"dreißig", art:"", pl:"", en:"thirty", topic:"numbers", level:"a1" },
{ id:"a1x79", de:"vierzig", art:"", pl:"", en:"forty", topic:"numbers", level:"a1" },
{ id:"a1x80", de:"fünfzig", art:"", pl:"", en:"fifty", topic:"numbers", level:"a1" },
{ id:"a1x81", de:"sechzig", art:"", pl:"", en:"sixty", topic:"numbers", level:"a1" },
{ id:"a1x82", de:"siebzig", art:"", pl:"", en:"seventy", topic:"numbers", level:"a1" },
{ id:"a1x83", de:"achtzig", art:"", pl:"", en:"eighty", topic:"numbers", level:"a1" },
{ id:"a1x84", de:"neunzig", art:"", pl:"", en:"ninety", topic:"numbers", level:"a1" },
{ id:"a1x85", de:"tausend", art:"", pl:"", en:"thousand", topic:"numbers", level:"a1" },
{ id:"a1x86", de:"halb", art:"", pl:"", en:"half (past) — halb drei = 2:30", topic:"numbers", level:"a1" },
{ id:"a1x87", de:"Viertel", art:"das", pl:"-", en:"quarter (hour)", topic:"numbers", level:"a1" },
{ id:"a1x88", de:"Viertel nach", art:"", pl:"", en:"quarter past", topic:"numbers", level:"a1" },
{ id:"a1x89", de:"Viertel vor", art:"", pl:"", en:"quarter to", topic:"numbers", level:"a1" },
{ id:"a1x90", de:"um ... Uhr", art:"", pl:"", en:"at ... o'clock", topic:"numbers", level:"a1" },
{ id:"a1x91", de:"Montag", art:"der", pl:"-e", en:"Monday", topic:"numbers", level:"a1" },
{ id:"a1x92", de:"Dienstag", art:"der", pl:"-e", en:"Tuesday", topic:"numbers", level:"a1" },
{ id:"a1x93", de:"Mittwoch", art:"der", pl:"-e", en:"Wednesday", topic:"numbers", level:"a1" },
{ id:"a1x94", de:"Donnerstag", art:"der", pl:"-e", en:"Thursday", topic:"numbers", level:"a1" },
{ id:"a1x95", de:"Freitag", art:"der", pl:"-e", en:"Friday", topic:"numbers", level:"a1" },
{ id:"a1x96", de:"Samstag", art:"der", pl:"-e", en:"Saturday", topic:"numbers", level:"a1" },
{ id:"a1x97", de:"Sonntag", art:"der", pl:"-e", en:"Sunday", topic:"numbers", level:"a1" },
{ id:"a1x98", de:"Wochenende", art:"das", pl:"-e", en:"weekend", topic:"numbers", level:"a1" },
{ id:"a1x99", de:"Januar", art:"der", pl:"", en:"January", topic:"numbers", level:"a1" },
{ id:"a1x100", de:"Februar", art:"der", pl:"", en:"February", topic:"numbers", level:"a1" },
{ id:"a1x101", de:"März", art:"der", pl:"", en:"March", topic:"numbers", level:"a1" },
{ id:"a1x102", de:"April", art:"der", pl:"", en:"April", topic:"numbers", level:"a1" },
{ id:"a1x103", de:"Mai", art:"der", pl:"", en:"May", topic:"numbers", level:"a1" },
{ id:"a1x104", de:"Juni", art:"der", pl:"", en:"June", topic:"numbers", level:"a1" },
{ id:"a1x105", de:"Juli", art:"der", pl:"", en:"July", topic:"numbers", level:"a1" },
{ id:"a1x106", de:"August", art:"der", pl:"", en:"August", topic:"numbers", level:"a1" },
{ id:"a1x107", de:"September", art:"der", pl:"", en:"September", topic:"numbers", level:"a1" },
{ id:"a1x108", de:"Oktober", art:"der", pl:"", en:"October", topic:"numbers", level:"a1" },
{ id:"a1x109", de:"November", art:"der", pl:"", en:"November", topic:"numbers", level:"a1" },
{ id:"a1x110", de:"Dezember", art:"der", pl:"", en:"December", topic:"numbers", level:"a1" },
{ id:"a1x111", de:"Frühling", art:"der", pl:"-e", en:"spring", topic:"numbers", level:"a1" },
{ id:"a1x112", de:"Sommer", art:"der", pl:"", en:"summer", topic:"numbers", level:"a1" },
{ id:"a1x113", de:"Herbst", art:"der", pl:"-e", en:"autumn", topic:"numbers", level:"a1" },
{ id:"a1x114", de:"Winter", art:"der", pl:"", en:"winter", topic:"numbers", level:"a1" },
{ id:"a1x115", de:"Datum", art:"das", pl:"Daten", en:"date", topic:"numbers", level:"a1" },
{ id:"a1x116", de:"Kalender", art:"der", pl:"-", en:"calendar", topic:"numbers", level:"a1" },
{ id:"a1x117", de:"Geburtstag", art:"der", pl:"-e", en:"birthday", topic:"numbers", level:"a1" },
{ id:"a1x118", de:"Uhrzeit", art:"die", pl:"-en", en:"time of day", topic:"numbers", level:"a1" },
{ id:"a1x119", de:"Sekunde", art:"die", pl:"-n", en:"second", topic:"numbers", level:"a1" },
{ id:"a1x120", de:"pünktlich", art:"", pl:"", en:"on time", topic:"numbers", level:"a1" },
{ id:"a1x121", de:"früh", art:"", pl:"", en:"early", topic:"numbers", level:"a1" },
{ id:"a1x122", de:"spät", art:"", pl:"", en:"late", topic:"numbers", level:"a1" },
{ id:"a1x123", de:"immer", art:"", pl:"", en:"always", topic:"numbers", level:"a1" },
{ id:"a1x124", de:"oft", art:"", pl:"", en:"often", topic:"numbers", level:"a1" },
{ id:"a1x125", de:"manchmal", art:"", pl:"", en:"sometimes", topic:"numbers", level:"a1" },
{ id:"a1x126", de:"nie", art:"", pl:"", en:"never", topic:"numbers", level:"a1" },
{ id:"a1x127", de:"jeden Tag", art:"", pl:"", en:"every day", topic:"numbers", level:"a1" },
{ id:"a1x128", de:"Etage", art:"die", pl:"-n", en:"floor (storey)", topic:"home", level:"a1" },
{ id:"a1x129", de:"Stock", art:"der", pl:"Stöcke", en:"floor / storey", topic:"home", level:"a1" },
{ id:"a1x130", de:"Aufzug", art:"der", pl:"Aufzüge", en:"lift / elevator", topic:"home", level:"a1" },
{ id:"a1x131", de:"Treppe", art:"die", pl:"-n", en:"stairs", topic:"home", level:"a1" },
{ id:"a1x132", de:"Keller", art:"der", pl:"-", en:"cellar", topic:"home", level:"a1" },
{ id:"a1x133", de:"Dach", art:"das", pl:"Dächer", en:"roof", topic:"home", level:"a1" },
{ id:"a1x134", de:"Garten", art:"der", pl:"Gärten", en:"garden", topic:"home", level:"a1" },
{ id:"a1x135", de:"Balkon", art:"der", pl:"-e", en:"balcony", topic:"home", level:"a1" },
{ id:"a1x136", de:"Flur", art:"der", pl:"-e", en:"hallway", topic:"home", level:"a1" },
{ id:"a1x137", de:"Toilette", art:"die", pl:"-n", en:"toilet", topic:"home", level:"a1" },
{ id:"a1x138", de:"Sofa", art:"das", pl:"-s", en:"sofa", topic:"home", level:"a1" },
{ id:"a1x139", de:"Schreibtisch", art:"der", pl:"-e", en:"desk", topic:"home", level:"a1" },
{ id:"a1x140", de:"Lampe", art:"die", pl:"-n", en:"lamp", topic:"home", level:"a1" },
{ id:"a1x141", de:"Kühlschrank", art:"der", pl:"Kühlschränke", en:"fridge", topic:"home", level:"a1" },
{ id:"a1x142", de:"Herd", art:"der", pl:"-e", en:"cooker / stove", topic:"home", level:"a1" },
{ id:"a1x143", de:"Spüle", art:"die", pl:"-n", en:"kitchen sink", topic:"home", level:"a1" },
{ id:"a1x144", de:"Dusche", art:"die", pl:"-n", en:"shower", topic:"home", level:"a1" },
{ id:"a1x145", de:"Badewanne", art:"die", pl:"-n", en:"bathtub", topic:"home", level:"a1" },
{ id:"a1x146", de:"Spiegel", art:"der", pl:"-", en:"mirror", topic:"home", level:"a1" },
{ id:"a1x147", de:"Schlüssel", art:"der", pl:"-", en:"key", topic:"home", level:"a1" },
{ id:"a1x148", de:"Miete", art:"die", pl:"-n", en:"rent", topic:"home", level:"a1" },
{ id:"a1x149", de:"Hausnummer", art:"die", pl:"-n", en:"house number", topic:"home", level:"a1" },
{ id:"a1x150", de:"Postleitzahl", art:"die", pl:"-en", en:"postcode", topic:"home", level:"a1" },
{ id:"a1x151", de:"Ort", art:"der", pl:"-e", en:"place / town", topic:"home", level:"a1" },
{ id:"a1x152", de:"Zentrum", art:"das", pl:"Zentren", en:"centre", topic:"home", level:"a1" },
{ id:"a1x153", de:"Markt", art:"der", pl:"Märkte", en:"market", topic:"home", level:"a1" },
{ id:"a1x154", de:"Park", art:"der", pl:"-s", en:"park", topic:"home", level:"a1" },
{ id:"a1x155", de:"Kirche", art:"die", pl:"-n", en:"church", topic:"home", level:"a1" },
{ id:"a1x156", de:"Museum", art:"das", pl:"Museen", en:"museum", topic:"home", level:"a1" },
{ id:"a1x157", de:"Bibliothek", art:"die", pl:"-en", en:"library", topic:"home", level:"a1" },
{ id:"a1x158", de:"Rathaus", art:"das", pl:"Rathäuser", en:"town hall", topic:"home", level:"a1" },
{ id:"a1x159", de:"Polizei", art:"die", pl:"", en:"police", topic:"home", level:"a1" },
{ id:"a1x160", de:"Feuerwehr", art:"die", pl:"-en", en:"fire brigade", topic:"home", level:"a1" },
{ id:"a1x161", de:"Bank", art:"die", pl:"-en", en:"bank", topic:"home", level:"a1" },
{ id:"a1x162", de:"Post", art:"die", pl:"", en:"post office / mail", topic:"home", level:"a1" },
{ id:"a1x163", de:"Stadtteil", art:"der", pl:"-e", en:"district", topic:"home", level:"a1" },
{ id:"a1x164", de:"Kreuzung", art:"die", pl:"-en", en:"crossroads", topic:"home", level:"a1" },
{ id:"a1x165", de:"Ampel", art:"die", pl:"-n", en:"traffic light", topic:"home", level:"a1" },
{ id:"a1x166", de:"Fußgängerzone", art:"die", pl:"-n", en:"pedestrian zone", topic:"home", level:"a1" },
{ id:"a1x167", de:"Brücke", art:"die", pl:"-n", en:"bridge", topic:"home", level:"a1" },
{ id:"a1x168", de:"Platz", art:"der", pl:"Plätze", en:"square / place", topic:"home", level:"a1" },
{ id:"a1x169", de:"Nachbarin", art:"die", pl:"-nen", en:"neighbour (f)", topic:"home", level:"a1" },
{ id:"a1x170", de:"Wohnort", art:"der", pl:"-e", en:"place of residence", topic:"home", level:"a1" },
{ id:"a1x171", de:"im Erdgeschoss", art:"", pl:"", en:"on the ground floor", topic:"home", level:"a1" },
{ id:"a1x172", de:"Butter", art:"die", pl:"", en:"butter", topic:"food", level:"a1" },
{ id:"a1x173", de:"Ei", art:"das", pl:"-er", en:"egg", topic:"food", level:"a1" },
{ id:"a1x174", de:"Zucker", art:"der", pl:"", en:"sugar", topic:"food", level:"a1" },
{ id:"a1x175", de:"Salz", art:"das", pl:"", en:"salt", topic:"food", level:"a1" },
{ id:"a1x176", de:"Pfeffer", art:"der", pl:"", en:"pepper", topic:"food", level:"a1" },
{ id:"a1x177", de:"Reis", art:"der", pl:"", en:"rice", topic:"food", level:"a1" },
{ id:"a1x178", de:"Nudeln", art:"die", pl:"", en:"pasta / noodles", topic:"food", level:"a1" },
{ id:"a1x179", de:"Suppe", art:"die", pl:"-n", en:"soup", topic:"food", level:"a1" },
{ id:"a1x180", de:"Salat", art:"der", pl:"-e", en:"salad", topic:"food", level:"a1" },
{ id:"a1x181", de:"Pizza", art:"die", pl:"-s", en:"pizza", topic:"food", level:"a1" },
{ id:"a1x182", de:"Kuchen", art:"der", pl:"-", en:"cake", topic:"food", level:"a1" },
{ id:"a1x183", de:"Eis", art:"das", pl:"", en:"ice cream / ice", topic:"food", level:"a1" },
{ id:"a1x184", de:"Saft", art:"der", pl:"Säfte", en:"juice", topic:"food", level:"a1" },
{ id:"a1x185", de:"Bier", art:"das", pl:"-e", en:"beer", topic:"food", level:"a1" },
{ id:"a1x186", de:"Wein", art:"der", pl:"-e", en:"wine", topic:"food", level:"a1" },
{ id:"a1x187", de:"Cola", art:"die/das", pl:"-s", en:"cola", topic:"food", level:"a1" },
{ id:"a1x188", de:"Speisekarte", art:"die", pl:"-n", en:"menu", topic:"food", level:"a1" },
{ id:"a1x189", de:"Bestellung", art:"die", pl:"-en", en:"order", topic:"food", level:"a1" },
{ id:"a1x190", de:"Kellner", art:"der", pl:"-", en:"waiter", topic:"food", level:"a1" },
{ id:"a1x191", de:"Kellnerin", art:"die", pl:"-nen", en:"waitress", topic:"food", level:"a1" },
{ id:"a1x192", de:"Tasse", art:"die", pl:"-n", en:"cup", topic:"food", level:"a1" },
{ id:"a1x193", de:"Glas", art:"das", pl:"Gläser", en:"glass", topic:"food", level:"a1" },
{ id:"a1x194", de:"Teller", art:"der", pl:"-", en:"plate", topic:"food", level:"a1" },
{ id:"a1x195", de:"Gabel", art:"die", pl:"-n", en:"fork", topic:"food", level:"a1" },
{ id:"a1x196", de:"Messer", art:"das", pl:"-", en:"knife", topic:"food", level:"a1" },
{ id:"a1x197", de:"Löffel", art:"der", pl:"-", en:"spoon", topic:"food", level:"a1" },
{ id:"a1x198", de:"Hunger", art:"der", pl:"", en:"hunger", topic:"food", level:"a1" },
{ id:"a1x199", de:"Durst", art:"der", pl:"", en:"thirst", topic:"food", level:"a1" },
{ id:"a1x200", de:"Ich hätte gerne", art:"", pl:"", en:"I would like", topic:"food", level:"a1" },
{ id:"a1x201", de:"Die Rechnung bitte", art:"", pl:"", en:"the bill please", topic:"food", level:"a1" },
{ id:"a1x202", de:"vegetarisch", art:"", pl:"", en:"vegetarian", topic:"food", level:"a1" },
{ id:"a1x203", de:"Café", art:"das", pl:"-s", en:"café", topic:"food", level:"a1" },
{ id:"a1x204", de:"Bäckerei", art:"die", pl:"-en", en:"bakery", topic:"food", level:"a1" },
{ id:"a1x205", de:"Metzgerei", art:"die", pl:"-en", en:"butcher's", topic:"food", level:"a1" },
{ id:"a1x206", de:"Imbiss", art:"der", pl:"-e", en:"snack bar", topic:"food", level:"a1" },
{ id:"a1x207", de:"Restaurant", art:"das", pl:"-s", en:"restaurant", topic:"food", level:"a1" },
{ id:"a1x208", de:"Mittagstisch", art:"der", pl:"-e", en:"lunch special", topic:"food", level:"a1" },
{ id:"a1x209", de:"Trinkgeld", art:"das", pl:"-er", en:"tip", topic:"food", level:"a1" },
{ id:"a1x210", de:"ohne Zucker", art:"", pl:"", en:"without sugar", topic:"food", level:"a1" },
{ id:"a1x211", de:"mit Milch", art:"", pl:"", en:"with milk", topic:"food", level:"a1" },
{ id:"a1x212", de:"zum Mitnehmen", art:"", pl:"", en:"to take away", topic:"food", level:"a1" },
{ id:"a1x213", de:"hier essen", art:"", pl:"", en:"eat in", topic:"food", level:"a1" },
{ id:"a1x214", de:"lecker", art:"", pl:"", en:"tasty", topic:"food", level:"a1" },
{ id:"a1x215", de:"scharf", art:"", pl:"", en:"spicy / sharp", topic:"food", level:"a1" },
{ id:"a1x216", de:"süß", art:"", pl:"", en:"sweet", topic:"food", level:"a1" },
{ id:"a1x217", de:"aufstehen", art:"", pl:"", en:"to get up", topic:"daily", level:"a1" },
{ id:"a1x218", de:"duschen", art:"", pl:"", en:"to shower", topic:"daily", level:"a1" },
{ id:"a1x219", de:"frühstücken", art:"", pl:"", en:"to have breakfast", topic:"daily", level:"a1" },
{ id:"a1x220", de:"schlafen", art:"", pl:"", en:"to sleep", topic:"daily", level:"a1" },
{ id:"a1x221", de:"fernsehen", art:"", pl:"", en:"to watch TV", topic:"daily", level:"a1" },
{ id:"a1x222", de:"lesen", art:"", pl:"", en:"to read", topic:"daily", level:"a1" },
{ id:"a1x223", de:"schreiben", art:"", pl:"", en:"to write", topic:"daily", level:"a1" },
{ id:"a1x224", de:"telefonieren", art:"", pl:"", en:"to phone", topic:"daily", level:"a1" },
{ id:"a1x225", de:"einkaufen", art:"", pl:"", en:"to shop", topic:"daily", level:"a1" },
{ id:"a1x226", de:"kochen", art:"", pl:"", en:"to cook", topic:"daily", level:"a1" },
{ id:"a1x227", de:"putzen", art:"", pl:"", en:"to clean", topic:"daily", level:"a1" },
{ id:"a1x228", de:"waschen", art:"", pl:"", en:"to wash", topic:"daily", level:"a1" },
{ id:"a1x229", de:"spazieren gehen", art:"", pl:"", en:"to go for a walk", topic:"daily", level:"a1" },
{ id:"a1x230", de:"Sport machen", art:"", pl:"", en:"to do sport", topic:"daily", level:"a1" },
{ id:"a1x231", de:"Musik hören", art:"", pl:"", en:"to listen to music", topic:"daily", level:"a1" },
{ id:"a1x232", de:"Hausaufgabe", art:"die", pl:"-n", en:"homework", topic:"daily", level:"a1" },
{ id:"a1x233", de:"Feierabend", art:"der", pl:"-e", en:"end of the workday", topic:"daily", level:"a1" },
{ id:"a1x234", de:"Urlaub", art:"der", pl:"-e", en:"holiday / vacation", topic:"daily", level:"a1" },
{ id:"a1x235", de:"Mittagspause", art:"die", pl:"-n", en:"lunch break", topic:"daily", level:"a1" },
{ id:"a1x236", de:"Alltag", art:"der", pl:"", en:"everyday life", topic:"daily", level:"a1" },
{ id:"a1x237", de:"Routine", art:"die", pl:"-n", en:"routine", topic:"daily", level:"a1" },
{ id:"a1x238", de:"aufwachen", art:"", pl:"", en:"to wake up", topic:"daily", level:"a1" },
{ id:"a1x239", de:"ins Bett gehen", art:"", pl:"", en:"to go to bed", topic:"daily", level:"a1" },
{ id:"a1x240", de:"sich anziehen", art:"", pl:"", en:"to get dressed", topic:"daily", level:"a1" },
{ id:"a1x241", de:"Zähne putzen", art:"", pl:"", en:"to brush one's teeth", topic:"daily", level:"a1" },
{ id:"a1x242", de:"Haltestelle", art:"die", pl:"-n", en:"stop (bus/tram)", topic:"travel", level:"a1" },
{ id:"a1x243", de:"Gleis", art:"das", pl:"-e", en:"platform / track", topic:"travel", level:"a1" },
{ id:"a1x244", de:"Abfahrt", art:"die", pl:"-en", en:"departure", topic:"travel", level:"a1" },
{ id:"a1x245", de:"Ankunft", art:"die", pl:"-e", en:"arrival", topic:"travel", level:"a1" },
{ id:"a1x246", de:"Verspätung", art:"die", pl:"-en", en:"delay", topic:"travel", level:"a1" },
{ id:"a1x247", de:"umsteigen", art:"", pl:"", en:"to change (trains)", topic:"travel", level:"a1" },
{ id:"a1x248", de:"einsteigen", art:"", pl:"", en:"to get on", topic:"travel", level:"a1" },
{ id:"a1x249", de:"aussteigen", art:"", pl:"", en:"to get off", topic:"travel", level:"a1" },
{ id:"a1x250", de:"Fahrplan", art:"der", pl:"Fahrpläne", en:"timetable", topic:"travel", level:"a1" },
{ id:"a1x251", de:"Schalter", art:"der", pl:"-", en:"ticket window / counter", topic:"travel", level:"a1" },
{ id:"a1x252", de:"Automat", art:"der", pl:"-en", en:"ticket machine", topic:"travel", level:"a1" },
{ id:"a1x253", de:"Rückfahrt", art:"die", pl:"-en", en:"return journey", topic:"travel", level:"a1" },
{ id:"a1x254", de:"hin und zurück", art:"", pl:"", en:"return (ticket)", topic:"travel", level:"a1" },
{ id:"a1x255", de:"Taxi", art:"das", pl:"-s", en:"taxi", topic:"travel", level:"a1" },
{ id:"a1x256", de:"U-Bahn", art:"die", pl:"-en", en:"underground / metro", topic:"travel", level:"a1" },
{ id:"a1x257", de:"S-Bahn", art:"die", pl:"-en", en:"suburban train", topic:"travel", level:"a1" },
{ id:"a1x258", de:"Straßenbahn", art:"die", pl:"-en", en:"tram", topic:"travel", level:"a1" },
{ id:"a1x259", de:"Fahrrad", art:"das", pl:"Fahrräder", en:"bicycle", topic:"travel", level:"a1" },
{ id:"a1x260", de:"Auto", art:"das", pl:"-s", en:"car", topic:"travel", level:"a1" },
{ id:"a1x261", de:"Parkplatz", art:"der", pl:"Parkplätze", en:"parking space", topic:"travel", level:"a1" },
{ id:"a1x262", de:"Ausgang", art:"der", pl:"Ausgänge", en:"exit", topic:"travel", level:"a1" },
{ id:"a1x263", de:"Eingang", art:"der", pl:"Eingänge", en:"entrance", topic:"travel", level:"a1" },
{ id:"a1x264", de:"Information", art:"die", pl:"-en", en:"information / info desk", topic:"travel", level:"a1" },
{ id:"a1x265", de:"Fundbüro", art:"das", pl:"-s", en:"lost property", topic:"travel", level:"a1" },
{ id:"a1x266", de:"Richtung", art:"die", pl:"-en", en:"direction", topic:"travel", level:"a1" },
{ id:"a1x267", de:"gegenüber", art:"", pl:"", en:"opposite", topic:"travel", level:"a1" },
{ id:"a1x268", de:"neben", art:"", pl:"", en:"next to", topic:"travel", level:"a1" },
{ id:"a1x269", de:"zwischen", art:"", pl:"", en:"between", topic:"travel", level:"a1" },
{ id:"a1x270", de:"hinter", art:"", pl:"", en:"behind", topic:"travel", level:"a1" },
{ id:"a1x271", de:"vor", art:"", pl:"", en:"in front of / before", topic:"travel", level:"a1" },
{ id:"a1x272", de:"Notausgang", art:"der", pl:"Notausgänge", en:"emergency exit", topic:"travel", level:"a1" },
{ id:"a1x273", de:"Rauchen verboten", art:"", pl:"", en:"no smoking", topic:"travel", level:"a1" },
{ id:"a1x274", de:"Vorsicht", art:"die", pl:"", en:"caution", topic:"travel", level:"a1" },
{ id:"a1x275", de:"Einbahnstraße", art:"die", pl:"-n", en:"one-way street", topic:"travel", level:"a1" },
{ id:"a1x276", de:"Parkverbot", art:"das", pl:"-e", en:"no parking", topic:"travel", level:"a1" },
{ id:"a1x277", de:"frei", art:"", pl:"", en:"vacant / free", topic:"travel", level:"a1" },
{ id:"a1x278", de:"besetzt", art:"", pl:"", en:"occupied / engaged", topic:"travel", level:"a1" },
{ id:"a1x279", de:"geöffnet", art:"", pl:"", en:"open (sign)", topic:"travel", level:"a1" },
{ id:"a1x280", de:"WC", art:"das", pl:"-s", en:"toilet (sign)", topic:"travel", level:"a1" },
{ id:"a1x281", de:"Fahrstuhl", art:"der", pl:"Fahrstühle", en:"lift (sign)", topic:"travel", level:"a1" },
{ id:"a1x282", de:"Gäste", art:"die", pl:"", en:"guests (sign)", topic:"travel", level:"a1" },
{ id:"a1x283", de:"Wie komme ich zum …?", art:"", pl:"", en:"how do I get to …?", topic:"travel", level:"a1" },
{ id:"a1x284", de:"Ist das weit?", art:"", pl:"", en:"is that far?", topic:"travel", level:"a1" },
{ id:"a1x285", de:"Wetter", art:"das", pl:"", en:"weather", topic:"travel", level:"a1" },
{ id:"a1x286", de:"Sonne", art:"die", pl:"", en:"sun", topic:"travel", level:"a1" },
{ id:"a1x287", de:"Regen", art:"der", pl:"", en:"rain", topic:"travel", level:"a1" },
{ id:"a1x288", de:"Schnee", art:"der", pl:"", en:"snow", topic:"travel", level:"a1" },
{ id:"a1x289", de:"Wind", art:"der", pl:"", en:"wind", topic:"travel", level:"a1" },
{ id:"a1x290", de:"Wolke", art:"die", pl:"-n", en:"cloud", topic:"travel", level:"a1" },
{ id:"a1x291", de:"Gewitter", art:"das", pl:"-", en:"thunderstorm", topic:"travel", level:"a1" },
{ id:"a1x292", de:"Nebel", art:"der", pl:"", en:"fog", topic:"travel", level:"a1" },
{ id:"a1x293", de:"Grad", art:"der", pl:"", en:"degree (temperature)", topic:"travel", level:"a1" },
{ id:"a1x294", de:"sonnig", art:"", pl:"", en:"sunny", topic:"travel", level:"a1" },
{ id:"a1x295", de:"regnerisch", art:"", pl:"", en:"rainy", topic:"travel", level:"a1" },
{ id:"a1x296", de:"bewölkt", art:"", pl:"", en:"cloudy", topic:"travel", level:"a1" },
{ id:"a1x297", de:"windig", art:"", pl:"", en:"windy", topic:"travel", level:"a1" },
{ id:"a1x298", de:"Job", art:"der", pl:"-s", en:"job", topic:"work", level:"a1" },
{ id:"a1x299", de:"Chef", art:"der", pl:"-s", en:"boss", topic:"work", level:"a1" },
{ id:"a1x300", de:"Chefin", art:"die", pl:"-nen", en:"boss (f)", topic:"work", level:"a1" },
{ id:"a1x301", de:"Kollegin", art:"die", pl:"-nen", en:"colleague (f)", topic:"work", level:"a1" },
{ id:"a1x302", de:"Sekretärin", art:"die", pl:"-nen", en:"secretary", topic:"work", level:"a1" },
{ id:"a1x303", de:"Verkäufer", art:"der", pl:"-", en:"salesperson", topic:"work", level:"a1" },
{ id:"a1x304", de:"Verkäuferin", art:"die", pl:"-nen", en:"salesperson (f)", topic:"work", level:"a1" },
{ id:"a1x305", de:"Koch", art:"der", pl:"Köche", en:"cook", topic:"work", level:"a1" },
{ id:"a1x306", de:"Fahrer", art:"der", pl:"-", en:"driver", topic:"work", level:"a1" },
{ id:"a1x307", de:"Mechaniker", art:"der", pl:"-", en:"mechanic", topic:"work", level:"a1" },
{ id:"a1x308", de:"Ingenieur", art:"der", pl:"-e", en:"engineer", topic:"work", level:"a1" },
{ id:"a1x309", de:"Krankenschwester", art:"die", pl:"-n", en:"nurse", topic:"work", level:"a1" },
{ id:"a1x310", de:"Polizist", art:"der", pl:"-en", en:"police officer", topic:"work", level:"a1" },
{ id:"a1x311", de:"Gehalt", art:"das", pl:"Gehälter", en:"salary", topic:"work", level:"a1" },
{ id:"a1x312", de:"Vertrag", art:"der", pl:"Verträge", en:"contract", topic:"work", level:"a1" },
{ id:"a1x313", de:"Bewerbung", art:"die", pl:"-en", en:"application", topic:"work", level:"a1" },
{ id:"a1x314", de:"Lebenslauf", art:"der", pl:"Lebensläufe", en:"CV", topic:"work", level:"a1" },
{ id:"a1x315", de:"Praktikum", art:"das", pl:"Praktika", en:"internship", topic:"work", level:"a1" },
{ id:"a1x316", de:"Ausbildung", art:"die", pl:"-en", en:"vocational training", topic:"work", level:"a1" },
{ id:"a1x317", de:"Formular", art:"das", pl:"-e", en:"form", topic:"work", level:"a1" },
{ id:"a1x318", de:"Antrag", art:"der", pl:"Anträge", en:"application (official)", topic:"work", level:"a1" },
{ id:"a1x319", de:"Unterschrift", art:"die", pl:"-en", en:"signature", topic:"work", level:"a1" },
{ id:"a1x320", de:"ausfüllen", art:"", pl:"", en:"to fill in", topic:"work", level:"a1" },
{ id:"a1x321", de:"unterschreiben", art:"", pl:"", en:"to sign", topic:"work", level:"a1" },
{ id:"a1x322", de:"Telefonnummer", art:"die", pl:"-n", en:"phone number", topic:"work", level:"a1" },
{ id:"a1x323", de:"E-Mail", art:"die", pl:"-s", en:"email", topic:"work", level:"a1" },
{ id:"a1x324", de:"Stempel", art:"der", pl:"", en:"stamp (official)", topic:"work", level:"a1" },
{ id:"a1x325", de:"Ausweis", art:"der", pl:"-e", en:"ID card", topic:"work", level:"a1" },
{ id:"a1x326", de:"Pass", art:"der", pl:"Pässe", en:"passport", topic:"work", level:"a1" },
{ id:"a1x327", de:"Staatsangehörigkeit", art:"die", pl:"-en", en:"citizenship", topic:"work", level:"a1" },
{ id:"a1x328", de:"Familienstand", art:"der", pl:"", en:"marital status", topic:"work", level:"a1" },
{ id:"a1x329", de:"Klassenzimmer", art:"das", pl:"-", en:"classroom", topic:"work", level:"a1" },
{ id:"a1x330", de:"Tafel", art:"die", pl:"-n", en:"blackboard", topic:"work", level:"a1" },
{ id:"a1x331", de:"Heft", art:"das", pl:"-e", en:"exercise book", topic:"work", level:"a1" },
{ id:"a1x332", de:"Stift", art:"der", pl:"-e", en:"pen", topic:"work", level:"a1" },
{ id:"a1x333", de:"Bleistift", art:"der", pl:"-e", en:"pencil", topic:"work", level:"a1" },
{ id:"a1x334", de:"Prüfung", art:"die", pl:"-en", en:"exam / test", topic:"work", level:"a1" },
{ id:"a1x335", de:"Hausaufgabe machen", art:"", pl:"", en:"to do homework", topic:"work", level:"a1" },
{ id:"a1x336", de:"Pause haben", art:"", pl:"", en:"to have a break", topic:"work", level:"a1" },
{ id:"a1x337", de:"Auge", art:"das", pl:"-n", en:"eye", topic:"health", level:"a1" },
{ id:"a1x338", de:"Ohr", art:"das", pl:"-en", en:"ear", topic:"health", level:"a1" },
{ id:"a1x339", de:"Nase", art:"die", pl:"-n", en:"nose", topic:"health", level:"a1" },
{ id:"a1x340", de:"Mund", art:"der", pl:"Münder", en:"mouth", topic:"health", level:"a1" },
{ id:"a1x341", de:"Zahn", art:"der", pl:"Zähne", en:"tooth", topic:"health", level:"a1" },
{ id:"a1x342", de:"Hals", art:"der", pl:"Hälse", en:"neck / throat", topic:"health", level:"a1" },
{ id:"a1x343", de:"Arm", art:"der", pl:"-e", en:"arm", topic:"health", level:"a1" },
{ id:"a1x344", de:"Hand", art:"die", pl:"Hände", en:"hand", topic:"health", level:"a1" },
{ id:"a1x345", de:"Finger", art:"der", pl:"-", en:"finger", topic:"health", level:"a1" },
{ id:"a1x346", de:"Bein", art:"das", pl:"-e", en:"leg", topic:"health", level:"a1" },
{ id:"a1x347", de:"Fuß", art:"der", pl:"Füße", en:"foot", topic:"health", level:"a1" },
{ id:"a1x348", de:"Rücken", art:"der", pl:"", en:"back", topic:"health", level:"a1" },
{ id:"a1x349", de:"Herz", art:"das", pl:"-en", en:"heart", topic:"health", level:"a1" },
{ id:"a1x350", de:"Blut", art:"das", pl:"", en:"blood", topic:"health", level:"a1" },
{ id:"a1x351", de:"Fieber", art:"das", pl:"", en:"fever", topic:"health", level:"a1" },
{ id:"a1x352", de:"Husten", art:"der", pl:"", en:"cough", topic:"health", level:"a1" },
{ id:"a1x353", de:"Schnupfen", art:"der", pl:"", en:"cold (runny nose)", topic:"health", level:"a1" },
{ id:"a1x354", de:"Halsweh", art:"das", pl:"", en:"sore throat", topic:"health", level:"a1" },
{ id:"a1x355", de:"Kopfschmerzen", art:"die", pl:"", en:"headache", topic:"health", level:"a1" },
{ id:"a1x356", de:"Bauchschmerzen", art:"die", pl:"", en:"stomach ache", topic:"health", level:"a1" },
{ id:"a1x357", de:"Tablette", art:"die", pl:"-n", en:"tablet / pill", topic:"health", level:"a1" },
{ id:"a1x358", de:"Tropfen", art:"die", pl:"", en:"drops (medicine)", topic:"health", level:"a1" },
{ id:"a1x359", de:"Pflaster", art:"das", pl:"-", en:"plaster / band-aid", topic:"health", level:"a1" },
{ id:"a1x360", de:"Impfung", art:"die", pl:"-en", en:"vaccination", topic:"health", level:"a1" },
{ id:"a1x361", de:"Allergie", art:"die", pl:"-n", en:"allergy", topic:"health", level:"a1" },
{ id:"a1x362", de:"Notaufnahme", art:"die", pl:"-n", en:"A&E / ER", topic:"health", level:"a1" },
{ id:"a1x363", de:"Sprechstunde", art:"die", pl:"-n", en:"surgery hours", topic:"health", level:"a1" },
{ id:"a1x364", de:"Rezept", art:"das", pl:"-e", en:"prescription", topic:"health", level:"a1" },
{ id:"a1x365", de:"Versicherung", art:"die", pl:"-en", en:"insurance", topic:"health", level:"a1" },
{ id:"a1x366", de:"Krankenkasse", art:"die", pl:"-n", en:"health insurance fund", topic:"health", level:"a1" },
{ id:"a1x367", de:"weh tun", art:"", pl:"", en:"to hurt", topic:"health", level:"a1" },
{ id:"a1x368", de:"Mir ist schlecht", art:"", pl:"", en:"I feel sick", topic:"health", level:"a1" },
{ id:"a1x369", de:"Ich habe Schmerzen", art:"", pl:"", en:"I am in pain", topic:"health", level:"a1" },
{ id:"a1x370", de:"Zahnarzt", art:"der", pl:"Zahnärzte", en:"dentist", topic:"health", level:"a1" },
{ id:"a1x371", de:"Augenarzt", art:"der", pl:"Augenärzte", en:"eye doctor", topic:"health", level:"a1" },
{ id:"a1x372", de:"Hemd", art:"das", pl:"-en", en:"shirt", topic:"shopping", level:"a1" },
{ id:"a1x373", de:"T-Shirt", art:"das", pl:"-s", en:"T-shirt", topic:"shopping", level:"a1" },
{ id:"a1x374", de:"Pullover", art:"der", pl:"-", en:"jumper / sweater", topic:"shopping", level:"a1" },
{ id:"a1x375", de:"Rock", art:"der", pl:"Röcke", en:"skirt", topic:"shopping", level:"a1" },
{ id:"a1x376", de:"Kleid", art:"das", pl:"-er", en:"dress", topic:"shopping", level:"a1" },
{ id:"a1x377", de:"Mantel", art:"der", pl:"Mäntel", en:"coat", topic:"shopping", level:"a1" },
{ id:"a1x378", de:"Mütze", art:"die", pl:"-n", en:"beanie / cap", topic:"shopping", level:"a1" },
{ id:"a1x379", de:"Schal", art:"der", pl:"-s", en:"scarf", topic:"shopping", level:"a1" },
{ id:"a1x380", de:"Handschuh", art:"der", pl:"-e", en:"glove", topic:"shopping", level:"a1" },
{ id:"a1x381", de:"Socke", art:"die", pl:"-n", en:"sock", topic:"shopping", level:"a1" },
{ id:"a1x382", de:"Unterwäsche", art:"die", pl:"", en:"underwear", topic:"shopping", level:"a1" },
{ id:"a1x383", de:"Brille", art:"die", pl:"-n", en:"glasses", topic:"shopping", level:"a1" },
{ id:"a1x384", de:"Armbanduhr", art:"die", pl:"-en", en:"wristwatch", topic:"shopping", level:"a1" },
{ id:"a1x385", de:"Gürtel", art:"der", pl:"-", en:"belt", topic:"shopping", level:"a1" },
{ id:"a1x386", de:"rot", art:"", pl:"", en:"red", topic:"shopping", level:"a1" },
{ id:"a1x387", de:"blau", art:"", pl:"", en:"blue", topic:"shopping", level:"a1" },
{ id:"a1x388", de:"grün", art:"", pl:"", en:"green", topic:"shopping", level:"a1" },
{ id:"a1x389", de:"gelb", art:"", pl:"", en:"yellow", topic:"shopping", level:"a1" },
{ id:"a1x390", de:"schwarz", art:"", pl:"", en:"black", topic:"shopping", level:"a1" },
{ id:"a1x391", de:"weiß", art:"", pl:"", en:"white", topic:"shopping", level:"a1" },
{ id:"a1x392", de:"grau", art:"", pl:"", en:"grey", topic:"shopping", level:"a1" },
{ id:"a1x393", de:"braun", art:"", pl:"", en:"brown", topic:"shopping", level:"a1" },
{ id:"a1x394", de:"bezahlen", art:"", pl:"", en:"to pay", topic:"shopping", level:"a1" },
{ id:"a1x395", de:"Bargeld", art:"das", pl:"", en:"cash", topic:"shopping", level:"a1" },
{ id:"a1x396", de:"Kreditkarte", art:"die", pl:"-n", en:"credit card", topic:"shopping", level:"a1" },
{ id:"a1x397", de:"Quittung", art:"die", pl:"-en", en:"receipt", topic:"shopping", level:"a1" },
{ id:"a1x398", de:"Wechselgeld", art:"das", pl:"", en:"change (money)", topic:"shopping", level:"a1" },
{ id:"a1x399", de:"Angebot", art:"das", pl:"-e", en:"offer / special", topic:"shopping", level:"a1" },
{ id:"a1x400", de:"Umkleide", art:"die", pl:"-n", en:"changing room", topic:"shopping", level:"a1" },
{ id:"a1x401", de:"Kasse", art:"die", pl:"-n", en:"till / checkout", topic:"shopping", level:"a1" },
{ id:"a1x402", de:"Was kostet das?", art:"", pl:"", en:"how much is that?", topic:"shopping", level:"a1" },
{ id:"a1x403", de:"Kann ich mit Karte zahlen?", art:"", pl:"", en:"can I pay by card?", topic:"shopping", level:"a1" },
{ id:"a1x404", de:"Haben Sie das in …?", art:"", pl:"", en:"do you have that in …?", topic:"shopping", level:"a1" },
{ id:"a1x405", de:"zu groß", art:"", pl:"", en:"too big", topic:"shopping", level:"a1" },
{ id:"a1x406", de:"zu klein", art:"", pl:"", en:"too small", topic:"shopping", level:"a1" },
{ id:"a1x407", de:"passt", art:"", pl:"", en:"it fits", topic:"shopping", level:"a1" },
{ id:"a1x408", de:"Drogerie", art:"die", pl:"-n", en:"drugstore", topic:"shopping", level:"a1" },
{ id:"a1x409", de:"Marktstand", art:"der", pl:"Marktstände", en:"market stall", topic:"shopping", level:"a1" },
{ id:"a1x410", de:"sehen", art:"", pl:"", en:"to see", topic:"verbs", level:"a1" },
{ id:"a1x411", de:"hören", art:"", pl:"", en:"to hear", topic:"verbs", level:"a1" },
{ id:"a1x412", de:"sagen", art:"", pl:"", en:"to say", topic:"verbs", level:"a1" },
{ id:"a1x413", de:"fragen", art:"", pl:"", en:"to ask", topic:"verbs", level:"a1" },
{ id:"a1x414", de:"antworten", art:"", pl:"", en:"to answer", topic:"verbs", level:"a1" },
{ id:"a1x415", de:"geben", art:"", pl:"", en:"to give", topic:"verbs", level:"a1" },
{ id:"a1x416", de:"nehmen", art:"", pl:"", en:"to take", topic:"verbs", level:"a1" },
{ id:"a1x417", de:"bringen", art:"", pl:"", en:"to bring", topic:"verbs", level:"a1" },
{ id:"a1x418", de:"holen", art:"", pl:"", en:"to fetch", topic:"verbs", level:"a1" },
{ id:"a1x419", de:"bleiben", art:"", pl:"", en:"to stay", topic:"verbs", level:"a1" },
{ id:"a1x420", de:"fahren", art:"", pl:"", en:"to go (by vehicle)", topic:"verbs", level:"a1" },
{ id:"a1x421", de:"fliegen", art:"", pl:"", en:"to fly", topic:"verbs", level:"a1" },
{ id:"a1x422", de:"laufen", art:"", pl:"", en:"to run / walk", topic:"verbs", level:"a1" },
{ id:"a1x423", de:"stehen", art:"", pl:"", en:"to stand", topic:"verbs", level:"a1" },
{ id:"a1x424", de:"sitzen", art:"", pl:"", en:"to sit", topic:"verbs", level:"a1" },
{ id:"a1x425", de:"liegen", art:"", pl:"", en:"to lie / be lying", topic:"verbs", level:"a1" },
{ id:"a1x426", de:"öffnen", art:"", pl:"", en:"to open", topic:"verbs", level:"a1" },
{ id:"a1x427", de:"schließen", art:"", pl:"", en:"to close", topic:"verbs", level:"a1" },
{ id:"a1x428", de:"beginnen", art:"", pl:"", en:"to begin", topic:"verbs", level:"a1" },
{ id:"a1x429", de:"enden", art:"", pl:"", en:"to end", topic:"verbs", level:"a1" },
{ id:"a1x430", de:"warten", art:"", pl:"", en:"to wait", topic:"verbs", level:"a1" },
{ id:"a1x431", de:"suchen", art:"", pl:"", en:"to look for", topic:"verbs", level:"a1" },
{ id:"a1x432", de:"helfen", art:"", pl:"", en:"to help", topic:"verbs", level:"a1" },
{ id:"a1x433", de:"danken", art:"", pl:"", en:"to thank", topic:"verbs", level:"a1" },
{ id:"a1x434", de:"kennen", art:"", pl:"", en:"to know (a person/place)", topic:"verbs", level:"a1" },
{ id:"a1x435", de:"wissen", art:"", pl:"", en:"to know (a fact)", topic:"verbs", level:"a1" },
{ id:"a1x436", de:"können", art:"", pl:"", en:"can / to be able", topic:"verbs", level:"a1" },
{ id:"a1x437", de:"müssen", art:"", pl:"", en:"must / to have to", topic:"verbs", level:"a1" },
{ id:"a1x438", de:"wollen", art:"", pl:"", en:"to want", topic:"verbs", level:"a1" },
{ id:"a1x439", de:"dürfen", art:"", pl:"", en:"may / to be allowed", topic:"verbs", level:"a1" },
{ id:"a1x440", de:"sollen", art:"", pl:"", en:"should / to be supposed to", topic:"verbs", level:"a1" },
{ id:"a1x441", de:"mögen", art:"", pl:"", en:"to like", topic:"verbs", level:"a1" },
{ id:"a1x442", de:"möchten", art:"", pl:"", en:"would like", topic:"verbs", level:"a1" },
{ id:"a1x443", de:"treffen", art:"", pl:"", en:"to meet", topic:"verbs", level:"a1" },
{ id:"a1x444", de:"besuchen", art:"", pl:"", en:"to visit", topic:"verbs", level:"a1" },
{ id:"a1x445", de:"zeigen", art:"", pl:"", en:"to show", topic:"verbs", level:"a1" },
{ id:"a1x446", de:"erklären", art:"", pl:"", en:"to explain", topic:"verbs", level:"a1" },
{ id:"a1x447", de:"wiederholen", art:"", pl:"", en:"to repeat", topic:"verbs", level:"a1" },
{ id:"a1x448", de:"buchstabieren", art:"", pl:"", en:"to spell", topic:"verbs", level:"a1" },
{ id:"a1x449", de:"kosten", art:"", pl:"", en:"to cost", topic:"verbs", level:"a1" },
{ id:"a1x450", de:"heiß", art:"", pl:"", en:"hot", topic:"adjectives", level:"a1" },
{ id:"a1x451", de:"kühl", art:"", pl:"", en:"cool", topic:"adjectives", level:"a1" },
{ id:"a1x452", de:"nass", art:"", pl:"", en:"wet", topic:"adjectives", level:"a1" },
{ id:"a1x453", de:"trocken", art:"", pl:"", en:"dry", topic:"adjectives", level:"a1" },
{ id:"a1x454", de:"sauber", art:"", pl:"", en:"clean", topic:"adjectives", level:"a1" },
{ id:"a1x455", de:"schmutzig", art:"", pl:"", en:"dirty", topic:"adjectives", level:"a1" },
{ id:"a1x456", de:"voll", art:"", pl:"", en:"full", topic:"adjectives", level:"a1" },
{ id:"a1x457", de:"leer", art:"", pl:"", en:"empty", topic:"adjectives", level:"a1" },
{ id:"a1x458", de:"richtig", art:"", pl:"", en:"correct / right", topic:"adjectives", level:"a1" },
{ id:"a1x459", de:"falsch", art:"", pl:"", en:"wrong", topic:"adjectives", level:"a1" },
{ id:"a1x460", de:"nah", art:"", pl:"", en:"near", topic:"adjectives", level:"a1" },
{ id:"a1x461", de:"weit", art:"", pl:"", en:"far", topic:"adjectives", level:"a1" },
{ id:"a1x462", de:"laut", art:"", pl:"", en:"loud", topic:"adjectives", level:"a1" },
{ id:"a1x463", de:"leise", art:"", pl:"", en:"quiet", topic:"adjectives", level:"a1" },
{ id:"a1x464", de:"hell", art:"", pl:"", en:"bright", topic:"adjectives", level:"a1" },
{ id:"a1x465", de:"dunkel", art:"", pl:"", en:"dark", topic:"adjectives", level:"a1" },
{ id:"a1x466", de:"hungrig", art:"", pl:"", en:"hungry", topic:"adjectives", level:"a1" },
{ id:"a1x467", de:"durstig", art:"", pl:"", en:"thirsty", topic:"adjectives", level:"a1" },
{ id:"a1x468", de:"froh", art:"", pl:"", en:"glad", topic:"adjectives", level:"a1" },
{ id:"a1x469", de:"traurig", art:"", pl:"", en:"sad", topic:"adjectives", level:"a1" },
{ id:"a1x470", de:"freundlich", art:"", pl:"", en:"friendly", topic:"adjectives", level:"a1" },
{ id:"a1x471", de:"nett", art:"", pl:"", en:"nice", topic:"adjectives", level:"a1" },
{ id:"a1x472", de:"höflich", art:"", pl:"", en:"polite", topic:"adjectives", level:"a1" },
{ id:"a1x473", de:"wichtig", art:"", pl:"", en:"important", topic:"adjectives", level:"a1" },
{ id:"a1x474", de:"interessant", art:"", pl:"", en:"interesting", topic:"adjectives", level:"a1" },
{ id:"a1x475", de:"langweilig", art:"", pl:"", en:"boring", topic:"adjectives", level:"a1" },
{ id:"a1x476", de:"fertig", art:"", pl:"", en:"ready / finished", topic:"adjectives", level:"a1" },
{ id:"a1x477", de:"kaputt", art:"", pl:"", en:"broken", topic:"adjectives", level:"a1" },
{ id:"a1x478", de:"glücklich", art:"", pl:"", en:"happy", topic:"adjectives", level:"a1" },
{ id:"a1x479", de:"böse", art:"", pl:"", en:"angry / bad", topic:"adjectives", level:"a1" },
{ id:"a1x480", de:"jung", art:"", pl:"", en:"young", topic:"adjectives", level:"a1" },
{ id:"a1x481", de:"kurz", art:"", pl:"", en:"short", topic:"adjectives", level:"a1" },
{ id:"a1x482", de:"lang", art:"", pl:"", en:"long", topic:"adjectives", level:"a1" },
{ id:"a1x483", de:"breit", art:"", pl:"", en:"wide", topic:"adjectives", level:"a1" },
{ id:"a1x484", de:"eng", art:"", pl:"", en:"tight / narrow", topic:"adjectives", level:"a1" },
{ id:"a1x485", de:"Konto", art:"das", pl:"Konten", en:"bank account", topic:"shopping", level:"a1" },
{ id:"a1x486", de:"PLZ", art:"die", pl:"", en:"postcode", topic:"shopping", level:"a1" },
{ id:"a1x487", de:"Postleitzahl", art:"die", pl:"-en", en:"postcode (full word)", topic:"shopping", level:"a1" },
{ id:"a1x488", de:"Möbel", art:"die", pl:"", en:"furniture", topic:"home", level:"a1" },
{ id:"a1x489", de:"Straße", art:"die", pl:"-n", en:"street", topic:"home", level:"a1" },
{ id:"a1x490", de:"Hausnummer", art:"die", pl:"-n", en:"house number", topic:"home", level:"a1" }
  ]
};
