export default {
  vocab: [
  {
    "id": "a1v1",
    "de": "Hallo",
    "art": "",
    "pl": "",
    "en": "hello",
    "topic": "greetings",
    "level": "a1",
    "ex": "Hallo, ich heiße Anna.",
    "exEn": "Hello, my name is Anna."
  },
  {
    "id": "a1v2",
    "de": "Guten Tag",
    "art": "",
    "pl": "",
    "en": "good day",
    "topic": "greetings",
    "level": "a1",
    "ex": "Guten Tag, ich suche das Rathaus.",
    "exEn": "Good day, I am looking for the town hall."
  },
  {
    "id": "a1v3",
    "de": "Guten Morgen",
    "art": "",
    "pl": "",
    "en": "good morning",
    "topic": "greetings",
    "level": "a1",
    "ex": "Guten Morgen, der Kurs beginnt um neun.",
    "exEn": "Good morning, the course starts at nine."
  },
  {
    "id": "a1v4",
    "de": "Guten Abend",
    "art": "",
    "pl": "",
    "en": "good evening",
    "topic": "greetings",
    "level": "a1",
    "ex": "Guten Abend, ein Tisch für zwei bitte.",
    "exEn": "Good evening, a table for two please."
  },
  {
    "id": "a1v5",
    "de": "Tschüss",
    "art": "",
    "pl": "",
    "en": "bye",
    "topic": "greetings",
    "level": "a1",
    "ex": "Tschüss, bis morgen im Kurs.",
    "exEn": "Bye, see you tomorrow in class."
  },
  {
    "id": "a1v6",
    "de": "Auf Wiedersehen",
    "art": "",
    "pl": "",
    "en": "goodbye",
    "topic": "greetings",
    "level": "a1",
    "ex": "Auf Wiedersehen und vielen Dank für Ihre Hilfe.",
    "exEn": "Goodbye and thank you for your help."
  },
  {
    "id": "a1v7",
    "de": "Bitte",
    "art": "",
    "pl": "",
    "en": "please / you're welcome",
    "topic": "greetings",
    "level": "a1",
    "ex": "Einen Kaffee bitte.",
    "exEn": "A coffee please."
  },
  {
    "id": "a1v8",
    "de": "Danke",
    "art": "",
    "pl": "",
    "en": "thank you",
    "topic": "greetings",
    "level": "a1",
    "ex": "Danke für den Kaffee.",
    "exEn": "Thank you for the coffee."
  },
  {
    "id": "a1v9",
    "de": "Entschuldigung",
    "art": "",
    "pl": "",
    "en": "excuse me / sorry",
    "topic": "greetings",
    "level": "a1",
    "ex": "Entschuldigung, wo ist der Bahnhof?",
    "exEn": "Excuse me, where is the station?"
  },
  {
    "id": "a1v10",
    "de": "Ja",
    "art": "",
    "pl": "",
    "en": "yes",
    "topic": "greetings",
    "level": "a1",
    "ex": "Ja — bis morgen im Kurs.",
    "exEn": "Yes — see you tomorrow in class."
  },
  {
    "id": "a1v11",
    "de": "Nein",
    "art": "",
    "pl": "",
    "en": "no",
    "topic": "greetings",
    "level": "a1",
    "ex": "Nein — bis morgen im Kurs.",
    "exEn": "No — see you tomorrow in class."
  },
  {
    "id": "a1v12",
    "de": "vielleicht",
    "art": "",
    "pl": "",
    "en": "maybe",
    "topic": "greetings",
    "level": "a1",
    "ex": "Vielleicht — bis morgen im Kurs.",
    "exEn": "Maybe — see you tomorrow in class."
  },
  {
    "id": "a1v13",
    "de": "Wie geht's?",
    "art": "",
    "pl": "",
    "en": "how are you?",
    "topic": "greetings",
    "level": "a1",
    "ex": "Wie geht's?",
    "exEn": "How are you?"
  },
  {
    "id": "a1v14",
    "de": "Gut",
    "art": "",
    "pl": "",
    "en": "good / well",
    "topic": "greetings",
    "level": "a1",
    "ex": "Gut — bis morgen im Kurs.",
    "exEn": "Good / well — see you tomorrow in class."
  },
  {
    "id": "a1v15",
    "de": "Schlecht",
    "art": "",
    "pl": "",
    "en": "bad",
    "topic": "greetings",
    "level": "a1",
    "ex": "Schlecht — bis morgen im Kurs.",
    "exEn": "Bad — see you tomorrow in class."
  },
  {
    "id": "a1v16",
    "de": "Willkommen",
    "art": "",
    "pl": "",
    "en": "welcome",
    "topic": "greetings",
    "level": "a1",
    "ex": "Willkommen — bis morgen im Kurs.",
    "exEn": "Welcome — see you tomorrow in class."
  },
  {
    "id": "a1v17",
    "de": "Name",
    "art": "der",
    "pl": "-n",
    "en": "name",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist der Name.",
    "exEn": "This is name."
  },
  {
    "id": "a1v18",
    "de": "Vorname",
    "art": "der",
    "pl": "-n",
    "en": "first name",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist der Vorname.",
    "exEn": "This is first name."
  },
  {
    "id": "a1v19",
    "de": "Nachname",
    "art": "der",
    "pl": "-n",
    "en": "surname",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist der Nachname.",
    "exEn": "This is surname."
  },
  {
    "id": "a1v20",
    "de": "Mann",
    "art": "der",
    "pl": "Männer",
    "en": "man",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist der Mann.",
    "exEn": "This is man."
  },
  {
    "id": "a1v21",
    "de": "Frau",
    "art": "die",
    "pl": "-en",
    "en": "woman / Mrs",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist die Frau.",
    "exEn": "This is woman / Mrs."
  },
  {
    "id": "a1v22",
    "de": "Kind",
    "art": "das",
    "pl": "-er",
    "en": "child",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist das Kind.",
    "exEn": "This is child."
  },
  {
    "id": "a1v23",
    "de": "Freund",
    "art": "der",
    "pl": "-e",
    "en": "friend (m)",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist der Freund.",
    "exEn": "This is friend (m)."
  },
  {
    "id": "a1v24",
    "de": "Freundin",
    "art": "die",
    "pl": "-nen",
    "en": "friend (f)",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist die Freundin.",
    "exEn": "This is friend (f)."
  },
  {
    "id": "a1v25",
    "de": "Familie",
    "art": "die",
    "pl": "-n",
    "en": "family",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist die Familie.",
    "exEn": "This is family."
  },
  {
    "id": "a1v26",
    "de": "Mutter",
    "art": "die",
    "pl": "Mütter",
    "en": "mother",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist die Mutter.",
    "exEn": "This is mother."
  },
  {
    "id": "a1v27",
    "de": "Vater",
    "art": "der",
    "pl": "Väter",
    "en": "father",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist der Vater.",
    "exEn": "This is father."
  },
  {
    "id": "a1v28",
    "de": "Schwester",
    "art": "die",
    "pl": "-n",
    "en": "sister",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist die Schwester.",
    "exEn": "This is sister."
  },
  {
    "id": "a1v29",
    "de": "Bruder",
    "art": "der",
    "pl": "Brüder",
    "en": "brother",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist der Bruder.",
    "exEn": "This is brother."
  },
  {
    "id": "a1v30",
    "de": "Tochter",
    "art": "die",
    "pl": "Töchter",
    "en": "daughter",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist die Tochter.",
    "exEn": "This is daughter."
  },
  {
    "id": "a1v31",
    "de": "Sohn",
    "art": "der",
    "pl": "Söhne",
    "en": "son",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist der Sohn.",
    "exEn": "This is son."
  },
  {
    "id": "a1v32",
    "de": "Baby",
    "art": "das",
    "pl": "-s",
    "en": "baby",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist das Baby.",
    "exEn": "This is baby."
  },
  {
    "id": "a1v33",
    "de": "Herr",
    "art": "der",
    "pl": "-en",
    "en": "Mr",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist der Herr.",
    "exEn": "This is Mr."
  },
  {
    "id": "a1v34",
    "de": "Person",
    "art": "die",
    "pl": "-en",
    "en": "person",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist die Person.",
    "exEn": "This is person."
  },
  {
    "id": "a1v35",
    "de": "Leute",
    "art": "die",
    "pl": "",
    "en": "people",
    "topic": "people",
    "level": "a1",
    "ex": "Hier sind die Leute.",
    "exEn": "Here are the people."
  },
  {
    "id": "a1v36",
    "de": "Nachbar",
    "art": "der",
    "pl": "-n",
    "en": "neighbour",
    "topic": "people",
    "level": "a1",
    "ex": "Das ist der Nachbar.",
    "exEn": "This is neighbour."
  },
  {
    "id": "a1v37",
    "de": "Null",
    "art": "",
    "pl": "",
    "en": "zero",
    "topic": "numbers",
    "level": "a1",
    "ex": "Die Hausnummer ist Null? Nein, das ist zwölf.",
    "exEn": "The house number is zero? No, it is twelve."
  },
  {
    "id": "a1v38",
    "de": "eins",
    "art": "",
    "pl": "",
    "en": "one",
    "topic": "numbers",
    "level": "a1",
    "ex": "Ich möchte eins, bitte — das kleine Brot.",
    "exEn": "I would like one, please — the small loaf."
  },
  {
    "id": "a1v39",
    "de": "zwei",
    "art": "",
    "pl": "",
    "en": "two",
    "topic": "numbers",
    "level": "a1",
    "ex": "Ich kaufe zwei Fahrkarten nach Köln.",
    "exEn": "I am buying two tickets to Cologne."
  },
  {
    "id": "a1v40",
    "de": "drei",
    "art": "",
    "pl": "",
    "en": "three",
    "topic": "numbers",
    "level": "a1",
    "ex": "Ich brauche drei Fahrkarten bitte.",
    "exEn": "I need three tickets please."
  },
  {
    "id": "a1v41",
    "de": "vier",
    "art": "",
    "pl": "",
    "en": "four",
    "topic": "numbers",
    "level": "a1",
    "ex": "Ich brauche vier Fahrkarten bitte.",
    "exEn": "I need four tickets please."
  },
  {
    "id": "a1v42",
    "de": "fünf",
    "art": "",
    "pl": "",
    "en": "five",
    "topic": "numbers",
    "level": "a1",
    "ex": "Ich brauche fünf Fahrkarten bitte.",
    "exEn": "I need five tickets please."
  },
  {
    "id": "a1v43",
    "de": "sechs",
    "art": "",
    "pl": "",
    "en": "six",
    "topic": "numbers",
    "level": "a1",
    "ex": "Ich brauche sechs Fahrkarten bitte.",
    "exEn": "I need six tickets please."
  },
  {
    "id": "a1v44",
    "de": "sieben",
    "art": "",
    "pl": "",
    "en": "seven",
    "topic": "numbers",
    "level": "a1",
    "ex": "Ich brauche sieben Fahrkarten bitte.",
    "exEn": "I need seven tickets please."
  },
  {
    "id": "a1v45",
    "de": "acht",
    "art": "",
    "pl": "",
    "en": "eight",
    "topic": "numbers",
    "level": "a1",
    "ex": "Ich brauche acht Fahrkarten bitte.",
    "exEn": "I need eight tickets please."
  },
  {
    "id": "a1v46",
    "de": "neun",
    "art": "",
    "pl": "",
    "en": "nine",
    "topic": "numbers",
    "level": "a1",
    "ex": "Ich brauche neun Fahrkarten bitte.",
    "exEn": "I need nine tickets please."
  },
  {
    "id": "a1v47",
    "de": "zehn",
    "art": "",
    "pl": "",
    "en": "ten",
    "topic": "numbers",
    "level": "a1",
    "ex": "Ich brauche zehn Fahrkarten bitte.",
    "exEn": "I need ten tickets please."
  },
  {
    "id": "a1v48",
    "de": "hundert",
    "art": "",
    "pl": "",
    "en": "hundred",
    "topic": "numbers",
    "level": "a1",
    "ex": "Ich brauche hundert Fahrkarten bitte.",
    "exEn": "I need hundred tickets please."
  },
  {
    "id": "a1v49",
    "de": "Uhr",
    "art": "die",
    "pl": "-en",
    "en": "o'clock / clock",
    "topic": "numbers",
    "level": "a1",
    "ex": "Hier ist die Uhr.",
    "exEn": "Here is the o'clock / clock."
  },
  {
    "id": "a1v50",
    "de": "Minute",
    "art": "die",
    "pl": "-n",
    "en": "minute",
    "topic": "numbers",
    "level": "a1",
    "ex": "Hier ist die Minute.",
    "exEn": "Here is the minute."
  },
  {
    "id": "a1v51",
    "de": "Stunde",
    "art": "die",
    "pl": "-n",
    "en": "hour",
    "topic": "numbers",
    "level": "a1",
    "ex": "Hier ist die Stunde.",
    "exEn": "Here is the hour."
  },
  {
    "id": "a1v52",
    "de": "Tag",
    "art": "der",
    "pl": "-e",
    "en": "day",
    "topic": "numbers",
    "level": "a1",
    "ex": "Hier ist der Tag.",
    "exEn": "Here is the day."
  },
  {
    "id": "a1v53",
    "de": "Woche",
    "art": "die",
    "pl": "-n",
    "en": "week",
    "topic": "numbers",
    "level": "a1",
    "ex": "Hier ist die Woche.",
    "exEn": "Here is the week."
  },
  {
    "id": "a1v54",
    "de": "Monat",
    "art": "der",
    "pl": "-e",
    "en": "month",
    "topic": "numbers",
    "level": "a1",
    "ex": "Hier ist der Monat.",
    "exEn": "Here is the month."
  },
  {
    "id": "a1v55",
    "de": "Jahr",
    "art": "das",
    "pl": "-e",
    "en": "year",
    "topic": "numbers",
    "level": "a1",
    "ex": "Hier ist das Jahr.",
    "exEn": "Here is the year."
  },
  {
    "id": "a1v56",
    "de": "heute",
    "art": "",
    "pl": "",
    "en": "today",
    "topic": "numbers",
    "level": "a1",
    "ex": "Ich brauche heute Fahrkarten bitte.",
    "exEn": "I need today tickets please."
  },
  {
    "id": "a1v57",
    "de": "morgen",
    "art": "",
    "pl": "",
    "en": "tomorrow",
    "topic": "numbers",
    "level": "a1",
    "ex": "Ich brauche morgen Fahrkarten bitte.",
    "exEn": "I need tomorrow tickets please."
  },
  {
    "id": "a1v58",
    "de": "gestern",
    "art": "",
    "pl": "",
    "en": "yesterday",
    "topic": "numbers",
    "level": "a1",
    "ex": "Ich brauche gestern Fahrkarten bitte.",
    "exEn": "I need yesterday tickets please."
  },
  {
    "id": "a1v59",
    "de": "Haus",
    "art": "das",
    "pl": "Häuser",
    "en": "house",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist das Haus?",
    "exEn": "Where is the house?"
  },
  {
    "id": "a1v60",
    "de": "Wohnung",
    "art": "die",
    "pl": "-en",
    "en": "apartment",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist die Wohnung?",
    "exEn": "Where is the apartment?"
  },
  {
    "id": "a1v61",
    "de": "Zimmer",
    "art": "das",
    "pl": "-",
    "en": "room",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist das Zimmer?",
    "exEn": "Where is the room?"
  },
  {
    "id": "a1v62",
    "de": "Küche",
    "art": "die",
    "pl": "-n",
    "en": "kitchen",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist die Küche?",
    "exEn": "Where is the kitchen?"
  },
  {
    "id": "a1v63",
    "de": "Bad",
    "art": "das",
    "pl": "Bäder",
    "en": "bathroom",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist das Bad?",
    "exEn": "Where is the bathroom?"
  },
  {
    "id": "a1v64",
    "de": "Schlafzimmer",
    "art": "das",
    "pl": "-",
    "en": "bedroom",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist das Schlafzimmer?",
    "exEn": "Where is the bedroom?"
  },
  {
    "id": "a1v65",
    "de": "Wohnzimmer",
    "art": "das",
    "pl": "-",
    "en": "living room",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist das Wohnzimmer?",
    "exEn": "Where is the living room?"
  },
  {
    "id": "a1v66",
    "de": "Tür",
    "art": "die",
    "pl": "-en",
    "en": "door",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist die Tür?",
    "exEn": "Where is the door?"
  },
  {
    "id": "a1v67",
    "de": "Fenster",
    "art": "das",
    "pl": "-",
    "en": "window",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist das Fenster?",
    "exEn": "Where is the window?"
  },
  {
    "id": "a1v68",
    "de": "Tisch",
    "art": "der",
    "pl": "-e",
    "en": "table",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist der Tisch?",
    "exEn": "Where is the table?"
  },
  {
    "id": "a1v69",
    "de": "Stuhl",
    "art": "der",
    "pl": "Stühle",
    "en": "chair",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist der Stuhl?",
    "exEn": "Where is the chair?"
  },
  {
    "id": "a1v70",
    "de": "Bett",
    "art": "das",
    "pl": "-en",
    "en": "bed",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist das Bett?",
    "exEn": "Where is the bed?"
  },
  {
    "id": "a1v71",
    "de": "Adresse",
    "art": "die",
    "pl": "-n",
    "en": "address",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist die Adresse?",
    "exEn": "Where is the address?"
  },
  {
    "id": "a1v72",
    "de": "Straße",
    "art": "die",
    "pl": "-n",
    "en": "street",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist die Straße?",
    "exEn": "Where is the street?"
  },
  {
    "id": "a1v73",
    "de": "Stadt",
    "art": "die",
    "pl": "Städte",
    "en": "city",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist die Stadt?",
    "exEn": "Where is the city?"
  },
  {
    "id": "a1v74",
    "de": "Dorf",
    "art": "das",
    "pl": "Dörfer",
    "en": "village",
    "topic": "home",
    "level": "a1",
    "ex": "Wo ist das Dorf?",
    "exEn": "Where is the village?"
  },
  {
    "id": "a1v75",
    "de": "Brot",
    "art": "das",
    "pl": "-e",
    "en": "bread",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe das Brot.",
    "exEn": "I am buying the bread."
  },
  {
    "id": "a1v76",
    "de": "Wasser",
    "art": "das",
    "pl": "",
    "en": "water",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe das Wasser.",
    "exEn": "I am buying the water."
  },
  {
    "id": "a1v77",
    "de": "Kaffee",
    "art": "der",
    "pl": "-s",
    "en": "coffee",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe den Kaffee.",
    "exEn": "I am buying the coffee."
  },
  {
    "id": "a1v78",
    "de": "Tee",
    "art": "der",
    "pl": "-s",
    "en": "tea",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe den Tee.",
    "exEn": "I am buying the tea."
  },
  {
    "id": "a1v79",
    "de": "Milch",
    "art": "die",
    "pl": "",
    "en": "milk",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe die Milch.",
    "exEn": "I am buying the milk."
  },
  {
    "id": "a1v80",
    "de": "Apfel",
    "art": "der",
    "pl": "Äpfel",
    "en": "apple",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe den Apfel.",
    "exEn": "I am buying the apple."
  },
  {
    "id": "a1v81",
    "de": "Banane",
    "art": "die",
    "pl": "-n",
    "en": "banana",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe die Banane.",
    "exEn": "I am buying the banana."
  },
  {
    "id": "a1v82",
    "de": "Käse",
    "art": "der",
    "pl": "",
    "en": "cheese",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe den Käse.",
    "exEn": "I am buying the cheese."
  },
  {
    "id": "a1v83",
    "de": "Fleisch",
    "art": "das",
    "pl": "",
    "en": "meat",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe das Fleisch.",
    "exEn": "I am buying the meat."
  },
  {
    "id": "a1v84",
    "de": "Fisch",
    "art": "der",
    "pl": "-e",
    "en": "fish",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe den Fisch.",
    "exEn": "I am buying the fish."
  },
  {
    "id": "a1v85",
    "de": "Gemüse",
    "art": "das",
    "pl": "",
    "en": "vegetables",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe das Gemüse.",
    "exEn": "I am buying the vegetables."
  },
  {
    "id": "a1v86",
    "de": "Obst",
    "art": "das",
    "pl": "",
    "en": "fruit",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe das Obst.",
    "exEn": "I am buying the fruit."
  },
  {
    "id": "a1v87",
    "de": "Frühstück",
    "art": "das",
    "pl": "-e",
    "en": "breakfast",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe das Frühstück.",
    "exEn": "I am buying the breakfast."
  },
  {
    "id": "a1v88",
    "de": "Mittagessen",
    "art": "das",
    "pl": "-",
    "en": "lunch",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe das Mittagessen.",
    "exEn": "I am buying the lunch."
  },
  {
    "id": "a1v89",
    "de": "Abendessen",
    "art": "das",
    "pl": "-",
    "en": "dinner",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe das Abendessen.",
    "exEn": "I am buying the dinner."
  },
  {
    "id": "a1v90",
    "de": "Rechnung",
    "art": "die",
    "pl": "-en",
    "en": "bill",
    "topic": "food",
    "level": "a1",
    "ex": "Ich kaufe die Rechnung.",
    "exEn": "I am buying the bill."
  },
  {
    "id": "a1v91",
    "de": "Morgen",
    "art": "der",
    "pl": "",
    "en": "morning",
    "topic": "daily",
    "level": "a1",
    "ex": "Heute geht es um den Morgen.",
    "exEn": "Today it is about the morning."
  },
  {
    "id": "a1v92",
    "de": "Mittag",
    "art": "der",
    "pl": "",
    "en": "midday",
    "topic": "daily",
    "level": "a1",
    "ex": "Heute geht es um den Mittag.",
    "exEn": "Today it is about the midday."
  },
  {
    "id": "a1v93",
    "de": "Abend",
    "art": "der",
    "pl": "-e",
    "en": "evening",
    "topic": "daily",
    "level": "a1",
    "ex": "Heute geht es um den Abend.",
    "exEn": "Today it is about the evening."
  },
  {
    "id": "a1v94",
    "de": "Nacht",
    "art": "die",
    "pl": "Nächte",
    "en": "night",
    "topic": "daily",
    "level": "a1",
    "ex": "Heute geht es um die Nacht.",
    "exEn": "Today it is about the night."
  },
  {
    "id": "a1v95",
    "de": "Arbeit",
    "art": "die",
    "pl": "-en",
    "en": "work",
    "topic": "daily",
    "level": "a1",
    "ex": "Heute geht es um die Arbeit.",
    "exEn": "Today it is about the work."
  },
  {
    "id": "a1v96",
    "de": "Pause",
    "art": "die",
    "pl": "-n",
    "en": "break",
    "topic": "daily",
    "level": "a1",
    "ex": "Heute geht es um die Pause.",
    "exEn": "Today it is about the break."
  },
  {
    "id": "a1v97",
    "de": "Freizeit",
    "art": "die",
    "pl": "",
    "en": "free time",
    "topic": "daily",
    "level": "a1",
    "ex": "Heute geht es um die Freizeit.",
    "exEn": "Today it is about the free time."
  },
  {
    "id": "a1v98",
    "de": "Hobby",
    "art": "das",
    "pl": "-s",
    "en": "hobby",
    "topic": "daily",
    "level": "a1",
    "ex": "Heute geht es um das Hobby.",
    "exEn": "Today it is about the hobby."
  },
  {
    "id": "a1v99",
    "de": "Fernseher",
    "art": "der",
    "pl": "-",
    "en": "TV",
    "topic": "daily",
    "level": "a1",
    "ex": "Heute geht es um den Fernseher.",
    "exEn": "Today it is about the TV."
  },
  {
    "id": "a1v100",
    "de": "Handy",
    "art": "das",
    "pl": "-s",
    "en": "mobile phone",
    "topic": "daily",
    "level": "a1",
    "ex": "Heute geht es um das Handy.",
    "exEn": "Today it is about the mobile phone."
  },
  {
    "id": "a1v101",
    "de": "Computer",
    "art": "der",
    "pl": "-",
    "en": "computer",
    "topic": "daily",
    "level": "a1",
    "ex": "Heute geht es um den Computer.",
    "exEn": "Today it is about the computer."
  },
  {
    "id": "a1v102",
    "de": "Buch",
    "art": "das",
    "pl": "Bücher",
    "en": "book",
    "topic": "daily",
    "level": "a1",
    "ex": "Heute geht es um das Buch.",
    "exEn": "Today it is about the book."
  },
  {
    "id": "a1v103",
    "de": "Bahnhof",
    "art": "der",
    "pl": "Bahnhöfe",
    "en": "train station",
    "topic": "travel",
    "level": "a1",
    "ex": "Wo ist der Bahnhof?",
    "exEn": "Where is the train station?"
  },
  {
    "id": "a1v104",
    "de": "Zug",
    "art": "der",
    "pl": "Züge",
    "en": "train",
    "topic": "travel",
    "level": "a1",
    "ex": "Wo ist der Zug?",
    "exEn": "Where is the train?"
  },
  {
    "id": "a1v105",
    "de": "Bus",
    "art": "der",
    "pl": "-se",
    "en": "bus",
    "topic": "travel",
    "level": "a1",
    "ex": "Wo ist der Bus?",
    "exEn": "Where is the bus?"
  },
  {
    "id": "a1v106",
    "de": "Ticket",
    "art": "das",
    "pl": "-s",
    "en": "ticket",
    "topic": "travel",
    "level": "a1",
    "ex": "Wo ist das Ticket?",
    "exEn": "Where is the ticket?"
  },
  {
    "id": "a1v107",
    "de": "Fahrkarte",
    "art": "die",
    "pl": "-n",
    "en": "ticket",
    "topic": "travel",
    "level": "a1",
    "ex": "Wo ist die Fahrkarte?",
    "exEn": "Where is the ticket?"
  },
  {
    "id": "a1v108",
    "de": "Flugzeug",
    "art": "das",
    "pl": "-e",
    "en": "plane",
    "topic": "travel",
    "level": "a1",
    "ex": "Wo ist das Flugzeug?",
    "exEn": "Where is the plane?"
  },
  {
    "id": "a1v109",
    "de": "Hotel",
    "art": "das",
    "pl": "-s",
    "en": "hotel",
    "topic": "travel",
    "level": "a1",
    "ex": "Wo ist das Hotel?",
    "exEn": "Where is the hotel?"
  },
  {
    "id": "a1v110",
    "de": "Karte",
    "art": "die",
    "pl": "-n",
    "en": "map / card",
    "topic": "travel",
    "level": "a1",
    "ex": "Wo ist die Karte?",
    "exEn": "Where is the map / card?"
  },
  {
    "id": "a1v111",
    "de": "links",
    "art": "",
    "pl": "",
    "en": "left",
    "topic": "travel",
    "level": "a1",
    "ex": "Der Termin ist links.",
    "exEn": "The appointment is left."
  },
  {
    "id": "a1v112",
    "de": "rechts",
    "art": "",
    "pl": "",
    "en": "right",
    "topic": "travel",
    "level": "a1",
    "ex": "Der Termin ist rechts.",
    "exEn": "The appointment is right."
  },
  {
    "id": "a1v113",
    "de": "geradeaus",
    "art": "",
    "pl": "",
    "en": "straight ahead",
    "topic": "travel",
    "level": "a1",
    "ex": "Der Termin ist geradeaus.",
    "exEn": "The appointment is straight ahead."
  },
  {
    "id": "a1v114",
    "de": "wo",
    "art": "",
    "pl": "",
    "en": "where",
    "topic": "travel",
    "level": "a1",
    "ex": "Der Termin ist wo.",
    "exEn": "The appointment is where."
  },
  {
    "id": "a1v115",
    "de": "Beruf",
    "art": "der",
    "pl": "-e",
    "en": "profession",
    "topic": "work",
    "level": "a1",
    "ex": "Ich brauche den Beruf morgen.",
    "exEn": "I need the profession tomorrow."
  },
  {
    "id": "a1v116",
    "de": "Lehrer",
    "art": "der",
    "pl": "-",
    "en": "teacher (m)",
    "topic": "work",
    "level": "a1",
    "ex": "Ich brauche den Lehrer morgen.",
    "exEn": "I need the teacher (m) tomorrow."
  },
  {
    "id": "a1v117",
    "de": "Lehrerin",
    "art": "die",
    "pl": "-nen",
    "en": "teacher (f)",
    "topic": "work",
    "level": "a1",
    "ex": "Ich brauche die Lehrerin morgen.",
    "exEn": "I need the teacher (f) tomorrow."
  },
  {
    "id": "a1v118",
    "de": "Schüler",
    "art": "der",
    "pl": "-",
    "en": "pupil (m)",
    "topic": "work",
    "level": "a1",
    "ex": "Ich brauche den Schüler morgen.",
    "exEn": "I need the pupil (m) tomorrow."
  },
  {
    "id": "a1v119",
    "de": "Student",
    "art": "der",
    "pl": "-en",
    "en": "student (m)",
    "topic": "work",
    "level": "a1",
    "ex": "Ich brauche den Student morgen.",
    "exEn": "I need the student (m) tomorrow."
  },
  {
    "id": "a1v120",
    "de": "Büro",
    "art": "das",
    "pl": "-s",
    "en": "office",
    "topic": "work",
    "level": "a1",
    "ex": "Ich brauche das Büro morgen.",
    "exEn": "I need the office tomorrow."
  },
  {
    "id": "a1v121",
    "de": "Firma",
    "art": "die",
    "pl": "Firmen",
    "en": "company",
    "topic": "work",
    "level": "a1",
    "ex": "Ich brauche die Firma morgen.",
    "exEn": "I need the company tomorrow."
  },
  {
    "id": "a1v122",
    "de": "Kurs",
    "art": "der",
    "pl": "-e",
    "en": "course",
    "topic": "work",
    "level": "a1",
    "ex": "Ich brauche den Kurs morgen.",
    "exEn": "I need the course tomorrow."
  },
  {
    "id": "a1v123",
    "de": "Schule",
    "art": "die",
    "pl": "-n",
    "en": "school",
    "topic": "work",
    "level": "a1",
    "ex": "Ich brauche die Schule morgen.",
    "exEn": "I need the school tomorrow."
  },
  {
    "id": "a1v124",
    "de": "Universität",
    "art": "die",
    "pl": "-en",
    "en": "university",
    "topic": "work",
    "level": "a1",
    "ex": "Ich brauche die Universität morgen.",
    "exEn": "I need the university tomorrow."
  },
  {
    "id": "a1v125",
    "de": "Pause",
    "art": "die",
    "pl": "-n",
    "en": "break",
    "topic": "work",
    "level": "a1",
    "ex": "Ich brauche die Pause morgen.",
    "exEn": "I need the break tomorrow."
  },
  {
    "id": "a1v126",
    "de": "Kollege",
    "art": "der",
    "pl": "-n",
    "en": "colleague",
    "topic": "work",
    "level": "a1",
    "ex": "Ich brauche den Kollege morgen.",
    "exEn": "I need the colleague tomorrow."
  },
  {
    "id": "a1v127",
    "de": "Arzt",
    "art": "der",
    "pl": "Ärzte",
    "en": "doctor (m)",
    "topic": "health",
    "level": "a1",
    "ex": "Ich suche den Arzt.",
    "exEn": "I am looking for the doctor (m)."
  },
  {
    "id": "a1v128",
    "de": "Ärztin",
    "art": "die",
    "pl": "-nen",
    "en": "doctor (f)",
    "topic": "health",
    "level": "a1",
    "ex": "Ich suche die Ärztin.",
    "exEn": "I am looking for the doctor (f)."
  },
  {
    "id": "a1v129",
    "de": "Krankenhaus",
    "art": "das",
    "pl": "-häuser",
    "en": "hospital",
    "topic": "health",
    "level": "a1",
    "ex": "Ich suche das Krankenhaus.",
    "exEn": "I am looking for the hospital."
  },
  {
    "id": "a1v130",
    "de": "Apotheke",
    "art": "die",
    "pl": "-n",
    "en": "pharmacy",
    "topic": "health",
    "level": "a1",
    "ex": "Ich suche die Apotheke.",
    "exEn": "I am looking for the pharmacy."
  },
  {
    "id": "a1v131",
    "de": "Kopf",
    "art": "der",
    "pl": "Köpfe",
    "en": "head",
    "topic": "health",
    "level": "a1",
    "ex": "Ich suche den Kopf.",
    "exEn": "I am looking for the head."
  },
  {
    "id": "a1v132",
    "de": "Bauch",
    "art": "der",
    "pl": "Bäuche",
    "en": "stomach",
    "topic": "health",
    "level": "a1",
    "ex": "Ich suche den Bauch.",
    "exEn": "I am looking for the stomach."
  },
  {
    "id": "a1v133",
    "de": "Schmerz",
    "art": "der",
    "pl": "-en",
    "en": "pain",
    "topic": "health",
    "level": "a1",
    "ex": "Ich suche den Schmerz.",
    "exEn": "I am looking for the pain."
  },
  {
    "id": "a1v134",
    "de": "krank",
    "art": "",
    "pl": "",
    "en": "ill",
    "topic": "health",
    "level": "a1",
    "ex": "Der Termin ist krank.",
    "exEn": "The appointment is ill."
  },
  {
    "id": "a1v135",
    "de": "gesund",
    "art": "",
    "pl": "",
    "en": "healthy",
    "topic": "health",
    "level": "a1",
    "ex": "Der Termin ist gesund.",
    "exEn": "The appointment is healthy."
  },
  {
    "id": "a1v136",
    "de": "Müde",
    "art": "",
    "pl": "",
    "en": "tired",
    "topic": "health",
    "level": "a1",
    "ex": "Ich suche Müde.",
    "exEn": "I am looking for the tired."
  },
  {
    "id": "a1v137",
    "de": "Medikament",
    "art": "das",
    "pl": "-e",
    "en": "medicine",
    "topic": "health",
    "level": "a1",
    "ex": "Ich suche das Medikament.",
    "exEn": "I am looking for the medicine."
  },
  {
    "id": "a1v138",
    "de": "Termin",
    "art": "der",
    "pl": "-e",
    "en": "appointment",
    "topic": "health",
    "level": "a1",
    "ex": "Ich suche den Termin.",
    "exEn": "I am looking for the appointment."
  },
  {
    "id": "a1v139",
    "de": "Geschäft",
    "art": "das",
    "pl": "-e",
    "en": "shop",
    "topic": "shopping",
    "level": "a1",
    "ex": "Ich kaufe das Geschäft.",
    "exEn": "I am buying the shop."
  },
  {
    "id": "a1v140",
    "de": "Supermarkt",
    "art": "der",
    "pl": "-märkte",
    "en": "supermarket",
    "topic": "shopping",
    "level": "a1",
    "ex": "Ich kaufe den Supermarkt.",
    "exEn": "I am buying the supermarket."
  },
  {
    "id": "a1v141",
    "de": "Preis",
    "art": "der",
    "pl": "-e",
    "en": "price",
    "topic": "shopping",
    "level": "a1",
    "ex": "Ich kaufe den Preis.",
    "exEn": "I am buying the price."
  },
  {
    "id": "a1v142",
    "de": "Euro",
    "art": "der",
    "pl": "-",
    "en": "euro",
    "topic": "shopping",
    "level": "a1",
    "ex": "Ich kaufe den Euro.",
    "exEn": "I am buying the euro."
  },
  {
    "id": "a1v143",
    "de": "billig",
    "art": "",
    "pl": "",
    "en": "cheap",
    "topic": "shopping",
    "level": "a1",
    "ex": "Der Termin ist billig.",
    "exEn": "The appointment is cheap."
  },
  {
    "id": "a1v144",
    "de": "teuer",
    "art": "",
    "pl": "",
    "en": "expensive",
    "topic": "shopping",
    "level": "a1",
    "ex": "Der Termin ist teuer.",
    "exEn": "The appointment is expensive."
  },
  {
    "id": "a1v145",
    "de": "Farbe",
    "art": "die",
    "pl": "-n",
    "en": "colour",
    "topic": "shopping",
    "level": "a1",
    "ex": "Ich kaufe die Farbe.",
    "exEn": "I am buying the colour."
  },
  {
    "id": "a1v146",
    "de": "Größe",
    "art": "die",
    "pl": "-n",
    "en": "size",
    "topic": "shopping",
    "level": "a1",
    "ex": "Ich kaufe die Größe.",
    "exEn": "I am buying the size."
  },
  {
    "id": "a1v147",
    "de": "Jacke",
    "art": "die",
    "pl": "-n",
    "en": "jacket",
    "topic": "shopping",
    "level": "a1",
    "ex": "Ich kaufe die Jacke.",
    "exEn": "I am buying the jacket."
  },
  {
    "id": "a1v148",
    "de": "Hose",
    "art": "die",
    "pl": "-n",
    "en": "trousers",
    "topic": "shopping",
    "level": "a1",
    "ex": "Ich kaufe die Hose.",
    "exEn": "I am buying the trousers."
  },
  {
    "id": "a1v149",
    "de": "Schuh",
    "art": "der",
    "pl": "-e",
    "en": "shoe",
    "topic": "shopping",
    "level": "a1",
    "ex": "Ich kaufe den Schuh.",
    "exEn": "I am buying the shoe."
  },
  {
    "id": "a1v150",
    "de": "Tasche",
    "art": "die",
    "pl": "-n",
    "en": "bag",
    "topic": "shopping",
    "level": "a1",
    "ex": "Ich kaufe die Tasche.",
    "exEn": "I am buying the bag."
  },
  {
    "id": "a1v151",
    "de": "sein",
    "art": "",
    "pl": "",
    "en": "to be",
    "topic": "verbs",
    "level": "a1",
    "ex": "Ich möchte pünktlich sein.",
    "exEn": "I want to be on time."
  },
  {
    "id": "a1v152",
    "de": "haben",
    "art": "",
    "pl": "",
    "en": "to have",
    "topic": "verbs",
    "level": "a1",
    "ex": "Haben Sie Zeit? Ich möchte einen Termin haben.",
    "exEn": "Do you have time? I would like to have an appointment."
  },
  {
    "id": "a1v153",
    "de": "heißen",
    "art": "",
    "pl": "",
    "en": "to be called",
    "topic": "verbs",
    "level": "a1",
    "ex": "Wie heißen Sie? Ich heiße Anna.",
    "exEn": "What is your name? My name is Anna."
  },
  {
    "id": "a1v154",
    "de": "kommen",
    "art": "",
    "pl": "",
    "en": "to come",
    "topic": "verbs",
    "level": "a1",
    "ex": "Können Sie bitte um drei kommen?",
    "exEn": "Can you please come at three?"
  },
  {
    "id": "a1v155",
    "de": "gehen",
    "art": "",
    "pl": "",
    "en": "to go",
    "topic": "verbs",
    "level": "a1",
    "ex": "Ich muss jetzt gehen, der Bus kommt.",
    "exEn": "I have to go now, the bus is coming."
  },
  {
    "id": "a1v156",
    "de": "machen",
    "art": "",
    "pl": "",
    "en": "to do / make",
    "topic": "verbs",
    "level": "a1",
    "ex": "Kann ich bitte ein Foto machen?",
    "exEn": "Can I take a photo please?"
  },
  {
    "id": "a1v157",
    "de": "wohnen",
    "art": "",
    "pl": "",
    "en": "to live",
    "topic": "verbs",
    "level": "a1",
    "ex": "Wo wohnen Sie in der Stadt?",
    "exEn": "Where do you live in the city?"
  },
  {
    "id": "a1v158",
    "de": "arbeiten",
    "art": "",
    "pl": "",
    "en": "to work",
    "topic": "verbs",
    "level": "a1",
    "ex": "Wo arbeiten Sie — im Büro oder zu Hause?",
    "exEn": "Where do you work — in the office or at home?"
  },
  {
    "id": "a1v159",
    "de": "lernen",
    "art": "",
    "pl": "",
    "en": "to learn",
    "topic": "verbs",
    "level": "a1",
    "ex": "Ich möchte heute lernen.",
    "exEn": "I would like to learn today."
  },
  {
    "id": "a1v160",
    "de": "sprechen",
    "art": "",
    "pl": "",
    "en": "to speak",
    "topic": "verbs",
    "level": "a1",
    "ex": "Ich möchte heute sprechen.",
    "exEn": "I would like to speak today."
  },
  {
    "id": "a1v161",
    "de": "essen",
    "art": "",
    "pl": "",
    "en": "to eat",
    "topic": "verbs",
    "level": "a1",
    "ex": "Ich möchte heute essen.",
    "exEn": "I would like to eat today."
  },
  {
    "id": "a1v162",
    "de": "trinken",
    "art": "",
    "pl": "",
    "en": "to drink",
    "topic": "verbs",
    "level": "a1",
    "ex": "Ich möchte heute trinken.",
    "exEn": "I would like to drink today."
  },
  {
    "id": "a1v163",
    "de": "kaufen",
    "art": "",
    "pl": "",
    "en": "to buy",
    "topic": "verbs",
    "level": "a1",
    "ex": "Ich möchte heute kaufen.",
    "exEn": "I would like to buy today."
  },
  {
    "id": "a1v164",
    "de": "brauchen",
    "art": "",
    "pl": "",
    "en": "to need",
    "topic": "verbs",
    "level": "a1",
    "ex": "Ich möchte heute brauchen.",
    "exEn": "I would like to need today."
  },
  {
    "id": "a1v165",
    "de": "finden",
    "art": "",
    "pl": "",
    "en": "to find",
    "topic": "verbs",
    "level": "a1",
    "ex": "Wie finden Sie den Kurs?",
    "exEn": "How do you find the course?"
  },
  {
    "id": "a1v166",
    "de": "verstehen",
    "art": "",
    "pl": "",
    "en": "to understand",
    "topic": "verbs",
    "level": "a1",
    "ex": "Ich möchte heute verstehen.",
    "exEn": "I would like to understand today."
  },
  {
    "id": "a1v167",
    "de": "gut",
    "art": "",
    "pl": "",
    "en": "good",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Der Kurs ist gut, ich lerne viel.",
    "exEn": "The course is good, I am learning a lot."
  },
  {
    "id": "a1v168",
    "de": "schlecht",
    "art": "",
    "pl": "",
    "en": "bad",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Die Verbindung ist schlecht, ich rufe später an.",
    "exEn": "The connection is bad, I will call later."
  },
  {
    "id": "a1v169",
    "de": "groß",
    "art": "",
    "pl": "",
    "en": "big",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Die Wohnung ist groß genug für uns.",
    "exEn": "The flat is big enough for us."
  },
  {
    "id": "a1v170",
    "de": "klein",
    "art": "",
    "pl": "",
    "en": "small",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Das Zimmer ist klein, aber hell.",
    "exEn": "The room is small but bright."
  },
  {
    "id": "a1v171",
    "de": "neu",
    "art": "",
    "pl": "",
    "en": "new",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Ich brauche eine neue Meldebescheinigung.",
    "exEn": "I need a new registration certificate."
  },
  {
    "id": "a1v172",
    "de": "alt",
    "art": "",
    "pl": "",
    "en": "old",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Der Pass ist alt, ich beantrage einen neuen.",
    "exEn": "The passport is old, I am applying for a new one."
  },
  {
    "id": "a1v173",
    "de": "schön",
    "art": "",
    "pl": "",
    "en": "beautiful",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Die Lage ist schön, nah am Park.",
    "exEn": "The location is nice, close to the park."
  },
  {
    "id": "a1v174",
    "de": "hässlich",
    "art": "",
    "pl": "",
    "en": "ugly",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Der Termin ist hässlich.",
    "exEn": "The appointment is ugly."
  },
  {
    "id": "a1v175",
    "de": "warm",
    "art": "",
    "pl": "",
    "en": "warm",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Der Termin ist warm.",
    "exEn": "The appointment is warm."
  },
  {
    "id": "a1v176",
    "de": "kalt",
    "art": "",
    "pl": "",
    "en": "cold",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Der Termin ist kalt.",
    "exEn": "The appointment is cold."
  },
  {
    "id": "a1v177",
    "de": "schnell",
    "art": "",
    "pl": "",
    "en": "fast",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Der Termin ist schnell.",
    "exEn": "The appointment is fast."
  },
  {
    "id": "a1v178",
    "de": "langsam",
    "art": "",
    "pl": "",
    "en": "slow",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Der Termin ist langsam.",
    "exEn": "The appointment is slow."
  },
  {
    "id": "a1v179",
    "de": "leicht",
    "art": "",
    "pl": "",
    "en": "easy / light",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Der Termin ist leicht.",
    "exEn": "The appointment is easy / light."
  },
  {
    "id": "a1v180",
    "de": "schwierig",
    "art": "",
    "pl": "",
    "en": "difficult",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Der Termin ist schwierig.",
    "exEn": "The appointment is difficult."
  },
  {
    "id": "a1v181",
    "de": "offen",
    "art": "",
    "pl": "",
    "en": "open",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Ich möchte heute offen.",
    "exEn": "I would like open today."
  },
  {
    "id": "a1v182",
    "de": "geschlossen",
    "art": "",
    "pl": "",
    "en": "closed",
    "topic": "adjectives",
    "level": "a1",
    "ex": "Ich möchte heute geschlossen.",
    "exEn": "I would like closed today."
  }
],
  vocabTopics: [
  {
    "id": "greetings",
    "title": "Greetings and polite phrases",
    "blurb": "Hallo, Danke, Bitte, Entschuldigung."
  },
  {
    "id": "people",
    "title": "People and family",
    "blurb": "Name, age, family members."
  },
  {
    "id": "numbers",
    "title": "Numbers, time, dates",
    "blurb": "Counting, clock times, days."
  },
  {
    "id": "home",
    "title": "Home and city",
    "blurb": "Rooms, addresses, places in town."
  },
  {
    "id": "food",
    "title": "Food and café",
    "blurb": "Ordering, meals, shopping."
  },
  {
    "id": "daily",
    "title": "Daily routine",
    "blurb": "Verbs for everyday life."
  },
  {
    "id": "travel",
    "title": "Travel and directions",
    "blurb": "Bahnhof, tickets, left/right."
  },
  {
    "id": "work",
    "title": "Work and school",
    "blurb": "Jobs, courses, classroom."
  },
  {
    "id": "health",
    "title": "Body and health",
    "blurb": "Doctor, pain, pharmacy."
  },
  {
    "id": "shopping",
    "title": "Shopping and clothes",
    "blurb": "Sizes, colours, prices."
  },
  {
    "id": "verbs",
    "title": "Must-know verbs",
    "blurb": "sein, haben, gehen, kommen…"
  },
  {
    "id": "adjectives",
    "title": "Simple adjectives",
    "blurb": "gut, klein, teuer, neu."
  }
]
};
