export default {
  questions: [
{ id:"b1qe1", set:"gender", type:"mcq", prompt:"___ Wohnung ist zu teuer.", explain:"-ung → feminine.", level:"b1", options:["Die", "Der", "Das"], answer:"Die" },
{ id:"b1qe2", set:"gender", type:"mcq", prompt:"___ Problem muss man lösen.", explain:"Problem is neuter.", level:"b1", options:["Das", "Der", "Die"], answer:"Das" },
{ id:"b1qe3", set:"gender", type:"mcq", prompt:"___ Freundlichkeit überrascht mich.", explain:"-keit → feminine.", level:"b1", options:["Die", "Der", "Das"], answer:"Die" },
{ id:"b1qe4", set:"gender", type:"mcq", prompt:"___ Mädchen wartet draußen. (-chen)", explain:"Diminutives are neuter.", level:"b1", options:["Das", "Die", "Der"], answer:"Das" },
{ id:"b1qe5", set:"gender", type:"mcq", prompt:"Plural nominative of der Tisch?", explain:"All plurals take die in Nom.", level:"b1", options:["die Tische", "der Tische", "den Tische"], answer:"die Tische" },
{ id:"b1qe6", set:"gender", type:"gap", prompt:"Ich habe ___ Auto. (ein, neuter)", explain:"Neuter Akk of ein stays ein.", level:"b1", answer:["ein"] },
{ id:"b1qe7", set:"gender", type:"mcq", prompt:"kein + masculine Akk: Ich habe ___ Job.", explain:"ein-words: m Akk = -en.", level:"b1", options:["keinen", "kein", "keinem"], answer:"keinen" },
{ id:"b1qe8", set:"gender", type:"tf", prompt:"Days and months are usually masculine.", explain:"der Montag, der Januar.", level:"b1", answer:true },
{ id:"b1qe9", set:"gender", type:"mcq", prompt:"___ Information steht im Brief. (-tion)", explain:"-tion feminine.", level:"b1", options:["Die", "Der", "Das"], answer:"Die" },
{ id:"b1qe10", set:"gender", type:"mcq", prompt:"___ Lehrer erklärt die Aufgabe. (job -er)", explain:"Many -er jobs are masculine.", level:"b1", options:["Der", "Die", "Das"], answer:"Der" },
{ id:"b1qe11", set:"gender", type:"mcq", prompt:"___ Freiheit ist wichtig. (-heit)", explain:"-heit feminine.", level:"b1", options:["Die", "Der", "Das"], answer:"Die" },
{ id:"b1qe12", set:"gender", type:"mcq", prompt:"Infinitive as noun: ___ Lernen macht Spaß.", explain:"Nominalised verbs are neuter.", level:"b1", options:["Das", "Der", "Die"], answer:"Das" },
{ id:"b1qe13", set:"gender", type:"gap", prompt:"___ Anmeldung muss online passieren. (die)", explain:"die Anmeldung (-ung).", level:"b1", answer:["Die", "die"] },
{ id:"b1qe14", set:"gender", type:"tf", prompt:"ein has a plural form.", explain:"Use keine or nothing.", level:"b1", answer:false },
{ id:"b1qe15", set:"akkusativ", type:"mcq", prompt:"Ich sehe ___ Mann am Schalter.", explain:"Direct object masculine.", level:"b1", options:["den", "der", "dem"], answer:"den" },
{ id:"b1qe16", set:"akkusativ", type:"mcq", prompt:"ohne ___ Ticket kommst du nicht weiter.", explain:"Ticket neuter; ohne + Akk.", level:"b1", options:["ein", "einen", "einem"], answer:"ein" },
{ id:"b1qe17", set:"akkusativ", type:"mcq", prompt:"Es gibt ___ Park hinter dem Haus.", explain:"es gibt + Akk; Park masculine.", level:"b1", options:["einen", "ein", "einem"], answer:"einen" },
{ id:"b1qe18", set:"akkusativ", type:"gap", prompt:"Ich kaufe ___ Tisch. (einen)", explain:"m Akk ein-word.", level:"b1", answer:["einen"] },
{ id:"b1qe19", set:"akkusativ", type:"mcq", prompt:"Das Paket ist ___ dich.", explain:"für + Akk.", level:"b1", options:["für", "mit", "bei"], answer:"für" },
{ id:"b1qe20", set:"akkusativ", type:"mcq", prompt:"Ich gehe ___ die Stadt. (into)", explain:"Wechsel + Akk for motion.", level:"b1", options:["in", "im", "bei"], answer:"in" },
{ id:"b1qe21", set:"akkusativ", type:"mcq", prompt:"Replace: Ich sehe die Nachbarin. → Ich sehe ___ .", explain:"Feminine Akk pronoun.", level:"b1", options:["sie", "ihr", "ihn"], answer:"sie" },
{ id:"b1qe22", set:"akkusativ", type:"tf", prompt:"für always takes the dative.", explain:"für is always accusative.", level:"b1", answer:false },
{ id:"b1qe23", set:"akkusativ", type:"mcq", prompt:"durch, für, gegen, ohne, um take", explain:"Memorise the set.", level:"b1", options:["Akkusativ", "Dativ", "Genitiv"], answer:"Akkusativ" },
{ id:"b1qe24", set:"akkusativ", type:"mcq", prompt:"Ich habe ___ Zeit verloren.", explain:"Zeit feminine Akk = Nom.", level:"b1", options:["keine", "kein", "keinen"], answer:"keine" },
{ id:"b1qe25", set:"akkusativ", type:"mcq", prompt:"n-noun: Ich kenne ___ Kollegen.", explain:"weak masculine Akk.", level:"b1", options:["einen", "ein", "einem"], answer:"einen" },
{ id:"b1qe26", set:"akkusativ", type:"gap", prompt:"Wir brauchen ___ Termin beim Amt. (einen)", explain:"Termin masculine.", level:"b1", answer:["einen"] },
{ id:"b1qe27", set:"akkusativ", type:"mcq", prompt:"Ich stelle das Glas ___ den Tisch.", explain:"Placement = Akk.", level:"b1", options:["auf", "auf dem", "an dem"], answer:"auf" },
{ id:"b1qe28", set:"akkusativ", type:"mcq", prompt:"man in accusative is", explain:"Man darf einen hier nicht stören — actually 'einen' as Akk of man.", level:"b1", options:["einen", "man", "einem"], answer:"einen" },
{ id:"b1qe29", set:"dativ", type:"mcq", prompt:"Ich helfe ___ Nachbarin.", explain:"helfen + Dat feminine.", level:"b1", options:["der", "die", "den"], answer:"der" },
{ id:"b1qe30", set:"dativ", type:"mcq", prompt:"Ich fahre ___ Zug.", explain:"Zug masculine.", level:"b1", options:["mit dem", "mit den", "mit der"], answer:"mit dem" },
{ id:"b1qe31", set:"dativ", type:"gap", prompt:"Das gehört ___ . (to me)", explain:"gehören + Dat.", level:"b1", answer:["mir"] },
{ id:"b1qe32", set:"dativ", type:"mcq", prompt:"Wir wohnen ___ unseren Freunden.", explain:"bei + Dat.", level:"b1", options:["bei", "zu", "nach"], answer:"bei" },
{ id:"b1qe33", set:"dativ", type:"mcq", prompt:"Ich danke ___ für die Hilfe. (formal)", explain:"danken + Dat; formal Ihnen.", level:"b1", options:["Ihnen", "Sie", "euch"], answer:"Ihnen" },
{ id:"b1qe34", set:"dativ", type:"mcq", prompt:"Das gefällt ___ nicht. (the children)", explain:"plural Dat den + n.", level:"b1", options:["den Kindern", "die Kinder", "der Kinder"], answer:"den Kindern" },
{ id:"b1qe35", set:"dativ", type:"mcq", prompt:"seit ___ Jahr warte ich auf den Bescheid.", explain:"seit + Dat; present/Perfekt with seit.", level:"b1", options:["einem", "ein", "einen"], answer:"einem" },
{ id:"b1qe36", set:"dativ", type:"tf", prompt:"aus, bei, mit, nach, seit, von, zu always take dative.", explain:"No exceptions in standard B1.", level:"b1", answer:true },
{ id:"b1qe37", set:"dativ", type:"mcq", prompt:"Ich gebe ___ Mann das Formular.", explain:"Person = Dat, thing = Akk.", level:"b1", options:["dem", "den", "der"], answer:"dem" },
{ id:"b1qe38", set:"dativ", type:"mcq", prompt:"Antworten Sie bitte ___ Sachbearbeiterin.", explain:"antworten + Dat.", level:"b1", options:["der", "die", "den"], answer:"der" },
{ id:"b1qe39", set:"dativ", type:"gap", prompt:"Kannst du ___ kurz helfen?", explain:"helfen + Dat.", level:"b1", answer:["mir"] },
{ id:"b1qe40", set:"dativ", type:"mcq", prompt:"zu Hause uses", explain:"zu + Dat; zu Hause is a fixed chunk.", level:"b1", options:["Dativ idea with zu", "Akkusativ", "Genitiv"], answer:"Dativ idea with zu" },
{ id:"b1qe41", set:"dativ", type:"mcq", prompt:"wo? with Wechselpräpositionen takes", explain:"Location.", level:"b1", options:["Dativ", "Akkusativ", "Nominativ"], answer:"Dativ" },
{ id:"b1qe42", set:"dativ", type:"mcq", prompt:"Ich bin ___ Kino. (location)", explain:"im = in dem.", level:"b1", options:["im", "ins", "in das"], answer:"im" },
{ id:"b1qe43", set:"perfekt", type:"mcq", prompt:"Gestern ___ ich nach Hause ___ . (gehen)", explain:"gehen + sein.", level:"b1", options:["bin / gegangen", "habe / gegangen", "bin / gegeht"], answer:"bin / gegangen" },
{ id:"b1qe44", set:"perfekt", type:"mcq", prompt:"Ich ___ das Buch ___ . (lesen)", explain:"lesen strong + haben.", level:"b1", options:["habe / gelesen", "bin / gelesen", "habe / gelest"], answer:"habe / gelesen" },
{ id:"b1qe45", set:"perfekt", type:"mcq", prompt:"Wir ___ uns um 6 ___ . (treffen)", explain:"sich treffen + haben.", level:"b1", options:["haben / getroffen", "sind / getroffen", "haben / getrefft"], answer:"haben / getroffen" },
{ id:"b1qe46", set:"perfekt", type:"gap", prompt:"Partizip of aufstehen?", explain:"separable: auf + ge + standen.", level:"b1", answer:["aufgestanden"] },
{ id:"b1qe47", set:"perfekt", type:"mcq", prompt:"Ich ___ meine Tante ___ . (besuchen)", explain:"be- → no ge-.", level:"b1", options:["habe / besucht", "habe / gebesucht", "bin / besucht"], answer:"habe / besucht" },
{ id:"b1qe48", set:"perfekt", type:"mcq", prompt:"Es ___ ein Unfall ___ .", explain:"passieren + sein.", level:"b1", options:["ist / passiert", "hat / passiert", "ist / gepassiert"], answer:"ist / passiert" },
{ id:"b1qe49", set:"perfekt", type:"tf", prompt:"Ich habe nach Berlin gefahren is correct.", explain:"Ich bin nach Berlin gefahren.", level:"b1", answer:false },
{ id:"b1qe50", set:"perfekt", type:"mcq", prompt:"Sie ___ das Hotel ___ . (reservieren)", explain:"-ieren: no ge-.", level:"b1", options:["hat / reserviert", "hat / gereserviert", "ist / reserviert"], answer:"hat / reserviert" },
{ id:"b1qe51", set:"perfekt", type:"mcq", prompt:"bleiben takes", explain:"change-of-state family.", level:"b1", options:["sein", "haben", "werden"], answer:"sein" },
{ id:"b1qe52", set:"perfekt", type:"mcq", prompt:"Ich ___ das Auto nach Köln ___ . (fahren + object)", explain:"object → haben.", level:"b1", options:["habe / gefahren", "bin / gefahren", "habe / gefahrt"], answer:"habe / gefahren" },
{ id:"b1qe53", set:"perfekt", type:"gap", prompt:"Wir ___ Pizza gegessen.", explain:"haben + gegessen.", level:"b1", answer:["haben"] },
{ id:"b1qe54", set:"perfekt", type:"mcq", prompt:"Partizip of anrufen?", explain:"an + ge + rufen.", level:"b1", options:["angerufen", "geanrufen", "angeruft"], answer:"angerufen" },
{ id:"b1qe55", set:"perfekt", type:"mcq", prompt:"werden as 'become': Er ___ Lehrer ___ .", explain:"sein + geworden.", level:"b1", options:["ist / geworden", "hat / geworden", "ist / gewerden"], answer:"ist / geworden" },
{ id:"b1qe56", set:"perfekt", type:"mcq", prompt:"Inseparable ver-: Ich ___ den Schlüssel ___ .", explain:"no ge-.", level:"b1", options:["habe / verloren", "habe / geverloren", "bin / verloren"], answer:"habe / verloren" },
{ id:"b1qe57", set:"wordorder", type:"mcq", prompt:"Heute ___ ich Deutsch.", explain:"Heute pos 1.", level:"b1", options:["lerne", "ich lerne", "lernen"], answer:"lerne" },
{ id:"b1qe58", set:"wordorder", type:"mcq", prompt:"Um 8 Uhr ___ der Kurs.", explain:"Phrase = one unit.", level:"b1", options:["beginnt", "der beginnt", "beginnen"], answer:"beginnt" },
{ id:"b1qe59", set:"wordorder", type:"mcq", prompt:"Yes/no:", explain:"Verb first.", level:"b1", options:["Kommst du mit?", "Du kommst mit?", "Mit kommst du?"], answer:"Kommst du mit?" },
{ id:"b1qe60", set:"wordorder", type:"tf", prompt:"Heute in Berlin fahre ich is correct (two ideas before the verb).", explain:"Only one unit in position 1.", level:"b1", answer:false },
{ id:"b1qe61", set:"wordorder", type:"mcq", prompt:"TMP default:", explain:"Time manner place.", level:"b1", options:["Ich fahre morgen mit dem Zug nach Hamburg.", "Ich fahre nach Hamburg morgen mit dem Zug.", "Mit dem Zug ich fahre morgen."], answer:"Ich fahre morgen mit dem Zug nach Hamburg." },
{ id:"b1qe62", set:"wordorder", type:"gap", prompt:"Gestern ___ ich meinem Chef eine Mail geschrieben. (habe)", explain:"Auxiliary in pos 2.", level:"b1", answer:["habe"] },
{ id:"b1qe63", set:"wordorder", type:"mcq", prompt:"weil-clause: Ich bleibe, weil ich ___ .", explain:"verb last.", level:"b1", options:["krank bin", "bin krank", "krank ich bin"], answer:"krank bin" },
{ id:"b1qe64", set:"wordorder", type:"mcq", prompt:"deshalb ___ ich zu Hause.", explain:"deshalb + V2.", level:"b1", options:["bleibe", "ich bleibe", "bleiben"], answer:"bleibe" },
{ id:"b1qe65", set:"wordorder", type:"mcq", prompt:"W-question:", explain:"W then verb.", level:"b1", options:["Wann beginnt der Kurs?", "Wann der Kurs beginnt?", "Der Kurs wann beginnt?"], answer:"Wann beginnt der Kurs?" },
{ id:"b1qe66", set:"wordorder", type:"mcq", prompt:"Den Antrag ___ ich morgen ab.", explain:"Fronted object; verb still 2; separable ab.", level:"b1", options:["gebe", "ich gebe", "geben"], answer:"gebe" },
{ id:"b1qe67", set:"wordorder", type:"tf", prompt:"In a statement the conjugated verb is in position 2.", explain:"Core B1 rule.", level:"b1", answer:true },
{ id:"b1qe68", set:"wordorder", type:"mcq", prompt:"After a subordinate clause, the main clause often starts with the ___ .", explain:"Weil ich krank bin, bleibe ich …", level:"b1", options:["verb", "subject always", "weil"], answer:"verb" },
{ id:"b1qe69", set:"wordorder", type:"gap", prompt:"Am Montag ___ der Kurs um 18 Uhr. (beginnen)", explain:"Am Montag beginnt …", level:"b1", answer:["beginnt"] },
{ id:"b1qe70", set:"wordorder", type:"mcq", prompt:"nicht in: Ich komme heute nicht mit.", explain:"Place nicht before the extra you negate.", level:"b1", options:["negates mitkommen, near the end", "must be first", "must follow ich"], answer:"negates mitkommen, near the end" },
{ id:"b1qe71", set:"connectors", type:"mcq", prompt:"Ich bleibe zu Hause, ___ ich Fieber habe.", explain:"verb last already.", level:"b1", options:["weil", "denn", "deshalb"], answer:"weil" },
{ id:"b1qe72", set:"connectors", type:"mcq", prompt:"Ich habe Fieber. ___ bleibe ich zu Hause.", explain:"V2 adverb.", level:"b1", options:["Deshalb", "Weil", "Dass"], answer:"Deshalb" },
{ id:"b1qe73", set:"connectors", type:"mcq", prompt:"Ich bleibe zu Hause, ___ ich habe Fieber.", explain:"denn keeps V2.", level:"b1", options:["denn", "weil", "obwohl"], answer:"denn" },
{ id:"b1qe74", set:"connectors", type:"mcq", prompt:"___ ich Kind war, wohnten wir auf dem Land.", explain:"one past period.", level:"b1", options:["Als", "Wenn", "Wann"], answer:"Als" },
{ id:"b1qe75", set:"connectors", type:"mcq", prompt:"___ ich Zeit habe, rufe ich an.", explain:"if / whenever.", level:"b1", options:["Wenn", "Als", "Wann"], answer:"Wenn" },
{ id:"b1qe76", set:"connectors", type:"mcq", prompt:"Ich weiß nicht, ___ der Zug kommt.", explain:"indirect question.", level:"b1", options:["wann", "wenn", "als"], answer:"wann" },
{ id:"b1qe77", set:"connectors", type:"mcq", prompt:"___ es geregnet hat, sind wir spazieren gegangen.", explain:"obwohl + verb last.", level:"b1", options:["Obwohl", "Trotzdem", "Weil"], answer:"Obwohl" },
{ id:"b1qe78", set:"connectors", type:"mcq", prompt:"Es hat geregnet. ___ sind wir spazieren gegangen.", explain:"trotzdem + V2.", level:"b1", options:["Trotzdem", "Obwohl", "Weil"], answer:"Trotzdem" },
{ id:"b1qe79", set:"connectors", type:"mcq", prompt:"Ich lerne Deutsch, ___ in Deutschland zu arbeiten.", explain:"same subject → um … zu.", level:"b1", options:["um", "damit", "weil"], answer:"um" },
{ id:"b1qe80", set:"connectors", type:"mcq", prompt:"Ich erkläre das langsam, ___ alle verstehen.", explain:"different subject possible.", level:"b1", options:["damit", "um", "denn"], answer:"damit" },
{ id:"b1qe81", set:"connectors", type:"gap", prompt:"Ich denke, ___ die Wohnung zu teuer ist.", explain:"dass + verb last.", level:"b1", answer:["dass"] },
{ id:"b1qe82", set:"connectors", type:"mcq", prompt:"nicht teuer, ___ unbezahlbar", explain:"correction after nicht.", level:"b1", options:["sondern", "aber", "oder"], answer:"sondern" },
{ id:"b1qe83", set:"connectors", type:"tf", prompt:"weil and denn mean similar 'because' but word order differs.", explain:"weil verb last; denn no move.", level:"b1", answer:true },
{ id:"b1qe84", set:"connectors", type:"mcq", prompt:"Ich frage, ___ der Antrag schon da ist.", explain:"whether.", level:"b1", options:["ob", "wenn", "als"], answer:"ob" },
{ id:"b1qe85", set:"modals", type:"mcq", prompt:"Hier ___ man nicht parken.", explain:"dürfen = allowed.", level:"b1", options:["darf", "muss", "will"], answer:"darf" },
{ id:"b1qe86", set:"modals", type:"mcq", prompt:"nicht müssen means", explain:"Trap vs nicht dürfen.", level:"b1", options:["don't have to", "must not", "cannot"], answer:"don't have to" },
{ id:"b1qe87", set:"modals", type:"mcq", prompt:"nicht dürfen means", explain:"Prohibition.", level:"b1", options:["must not", "don't have to", "might"], answer:"must not" },
{ id:"b1qe88", set:"modals", type:"mcq", prompt:"Gestern ___ ich länger bleiben.", explain:"Präteritum of modal.", level:"b1", options:["musste", "müssen", "gemusst"], answer:"musste" },
{ id:"b1qe89", set:"modals", type:"gap", prompt:"Ich ___ heute nicht kommen. (können)", explain:"ich kann nicht kommen.", level:"b1", answer:["kann"] },
{ id:"b1qe90", set:"modals", type:"mcq", prompt:"Du ___ den Vermieter anrufen. (supposed to)", explain:"sollen.", level:"b1", options:["sollst", "darfst", "willst"], answer:"sollst" },
{ id:"b1qe91", set:"modals", type:"tf", prompt:"No zu after a modal.", explain:"Ich muss gehen.", level:"b1", answer:true },
{ id:"b1qe92", set:"modals", type:"mcq", prompt:"Ich ___ gerne eine Bescheinigung. (polite)", explain:"polite wish.", level:"b1", options:["möchte", "will", "muss"], answer:"möchte" },
{ id:"b1qe93", set:"modals", type:"mcq", prompt:"Past spoken: Ich wollte kommen, aber ich ___ nicht.", explain:"pair of Präteritum modals.", level:"b1", options:["konnte", "kann", "gekonnt"], answer:"konnte" },
{ id:"b1qe94", set:"modals", type:"mcq", prompt:"The infinitive sits", explain:"Modal conjugated pos 2.", level:"b1", options:["at the end", "in position 2", "before the modal"], answer:"at the end" },
{ id:"b1qe95", set:"modals", type:"mcq", prompt:"Man ___ den Antrag online ausfüllen. (necessary)", explain:"müssen.", level:"b1", options:["muss", "darf", "will"], answer:"muss" },
{ id:"b1qe96", set:"modals", type:"gap", prompt:"___ ich das Fenster öffnen? (dürfen, ich)", explain:"Darf ich …?", level:"b1", answer:["Darf", "darf"] },
{ id:"b1qe97", set:"modals", type:"mcq", prompt:"soll in a rumour (B2 stretch) means they say; at B1 sollen more often means", explain:"Keep B1 meaning first.", level:"b1", options:["ought to / is supposed to", "is allowed", "wants"], answer:"ought to / is supposed to" },
{ id:"b1qe98", set:"modals", type:"tf", prompt:"möchten is the Konjunktiv-II polite form used as a present wish.", explain:"Treat it as a modal.", level:"b1", answer:true },
{ id:"b1qe99", set:"separable", type:"mcq", prompt:"Ich ___ um 6 ___ . (aufstehen)", explain:"prefix to the end.", level:"b1", options:["stehe / auf", "aufstehe / .", "stehe auf / auf"], answer:"stehe / auf" },
{ id:"b1qe100", set:"separable", type:"mcq", prompt:"…, weil ich um 6 ___ .", explain:"attached in subordinate clause.", level:"b1", options:["aufstehe", "stehe auf", "auf stehe"], answer:"aufstehe" },
{ id:"b1qe101", set:"separable", type:"mcq", prompt:"Partizip of ankommen?", explain:"prefix+ge.", level:"b1", options:["angekommen", "geankommen", "angekommt"], answer:"angekommen" },
{ id:"b1qe102", set:"separable", type:"mcq", prompt:"besuchen Partizip?", explain:"inseparable be-.", level:"b1", options:["besucht", "gebesucht", "besuchen"], answer:"besucht" },
{ id:"b1qe103", set:"separable", type:"tf", prompt:"ver-, be-, er-, ent-, emp-, zer- do not take ge-.", explain:"inseparable.", level:"b1", answer:true },
{ id:"b1qe104", set:"separable", type:"gap", prompt:"Ich ___ meine Chefin ___ . (anrufen, present: rufe/an)", explain:"Ich rufe meine Chefin an.", level:"b1", answer:["rufe an", "rufe ... an"] },
{ id:"b1qe105", set:"separable", type:"mcq", prompt:"Wir haben um 9 ___ . (anfangen)", explain:"an + ge + fangen.", level:"b1", options:["angefangen", "geanfangen", "anfangt"], answer:"angefangen" },
{ id:"b1qe106", set:"separable", type:"mcq", prompt:"zurückkommen Perfekt:", explain:"sein + zurückgekommen.", level:"b1", options:["ist zurückgekommen", "hat zurückgekommen", "ist gekommen zurück"], answer:"ist zurückgekommen" },
{ id:"b1qe107", set:"separable", type:"mcq", prompt:"In Perfekt the prefix is", explain:"aufgestanden.", level:"b1", options:["on the participle", "still at sentence end alone", "deleted"], answer:"on the participle" },
{ id:"b1qe108", set:"separable", type:"mcq", prompt:"einkaufen: Gestern ___ wir ___ .", explain:"haben + eingekauft.", level:"b1", options:["haben / eingekauft", "sind / eingekauft", "haben / gekauft ein"], answer:"haben / eingekauft" },
{ id:"b1qe109", set:"separable", type:"mcq", prompt:"zu + separable: It's hard ___ um 6.", explain:"zu tucks in.", level:"b1", options:["aufzustehen", "zu aufstehen", "auf zu stehen"], answer:"aufzustehen" },
{ id:"b1qe110", set:"separable", type:"gap", prompt:"Mach bitte das Fenster ___ ! (zu)", explain:"zumachen command: Mach … zu.", level:"b1", answer:["zu"] },
{ id:"b1qe111", set:"separable", type:"tf", prompt:"Stress on the prefix often signals separable.", explain:"ÁNkommen vs beSUchen.", level:"b1", answer:true },
{ id:"b1qe112", set:"separable", type:"mcq", prompt:"mitbringen present: Bringt ihr eure Ausweise ___ ?", explain:"prefix at end.", level:"b1", options:["mit", "an", "ein"], answer:"mit" },
{ id:"b1qe113", set:"adjectives", type:"mcq", prompt:"ein ___ Job (neu, Nom m)", explain:"ein-word shows gender on adjective.", level:"b1", options:["neuer", "neue", "neues"], answer:"neuer" },
{ id:"b1qe114", set:"adjectives", type:"mcq", prompt:"ein ___ Auto (neu, Nom n)", explain:"-es after ein neuter.", level:"b1", options:["neues", "neuer", "neue"], answer:"neues" },
{ id:"b1qe115", set:"adjectives", type:"mcq", prompt:"eine ___ Stelle (neu, Nom f)", explain:"-e.", level:"b1", options:["neue", "neuer", "neues"], answer:"neue" },
{ id:"b1qe116", set:"adjectives", type:"mcq", prompt:"der ___ Vertrag (neu, Nom)", explain:"after der: Nom m -e.", level:"b1", options:["neue", "neuer", "neuen"], answer:"neue" },
{ id:"b1qe117", set:"adjectives", type:"mcq", prompt:"Ich unterschreibe den ___ Vertrag.", explain:"Akk m after der: -en.", level:"b1", options:["neuen", "neue", "neuer"], answer:"neuen" },
{ id:"b1qe118", set:"adjectives", type:"mcq", prompt:"bei ___ Wetter bleiben wir daheim. (gut, no article)", explain:"no article: adjective plays der-word; Dat n -em.", level:"b1", options:["gutem", "guten", "guter"], answer:"gutem" },
{ id:"b1qe119", set:"adjectives", type:"mcq", prompt:"nach ___ Zeit (kurz, f Dat, no article)", explain:"feminine Dat -er.", level:"b1", options:["kurzer", "kurzen", "kurze"], answer:"kurzer" },
{ id:"b1qe120", set:"adjectives", type:"tf", prompt:"After der/dieser you mostly see -e or -en.", explain:"Five -e slots in Nom/Akk.", level:"b1", answer:true },
{ id:"b1qe121", set:"adjectives", type:"gap", prompt:"mein ___ Chef (nett, Nom m)", explain:"mein like ein.", level:"b1", answer:["netter"] },
{ id:"b1qe122", set:"adjectives", type:"mcq", prompt:"die ___ Wohnungen (teuer, Nom pl after die)", explain:"plural after die: -en.", level:"b1", options:["teuren", "teure", "teurer"], answer:"teuren" },
{ id:"b1qe123", set:"adjectives", type:"mcq", prompt:"gut – besser – ", explain:"irregular superlative.", level:"b1", options:["am besten", "am guter", "am gutesten"], answer:"am besten" },
{ id:"b1qe124", set:"adjectives", type:"mcq", prompt:"gern – lieber – ", explain:"irregular.", level:"b1", options:["am liebsten", "am gerner", "am lieber"], answer:"am liebsten" },
{ id:"b1qe125", set:"adjectives", type:"mcq", prompt:"Ich kaufe einen ___ Tisch. (groß, Akk m ein-word)", explain:"-en.", level:"b1", options:["großen", "große", "großer"], answer:"großen" },
{ id:"b1qe126", set:"adjectives", type:"mcq", prompt:"mit dem ___ Zug (schnell, Dat m after dem)", explain:"after dem: -en.", level:"b1", options:["schnellen", "schnelle", "schneller"], answer:"schnellen" },
{ id:"b1qe127", set:"prepositions", type:"mcq", prompt:"Ich warte ___ den Bus.", explain:"warten auf + Akk.", level:"b1", options:["auf", "an", "für"], answer:"auf" },
{ id:"b1qe128", set:"prepositions", type:"mcq", prompt:"Ich freue mich ___ den Urlaub. (looking forward)", explain:"future event.", level:"b1", options:["auf", "über", "an"], answer:"auf" },
{ id:"b1qe129", set:"prepositions", type:"mcq", prompt:"Er hat sich ___ das Geschenk gefreut.", explain:"past fact.", level:"b1", options:["über", "auf", "für"], answer:"über" },
{ id:"b1qe130", set:"prepositions", type:"gap", prompt:"Ich bewerbe mich ___ die Stelle.", explain:"sich bewerben um.", level:"b1", answer:["um"] },
{ id:"b1qe131", set:"prepositions", type:"mcq", prompt:"Ich interessiere mich ___ Sprachen.", explain:"sich interessieren für.", level:"b1", options:["für", "an", "über"], answer:"für" },
{ id:"b1qe132", set:"prepositions", type:"mcq", prompt:"Ich habe Angst ___ der Prüfung.", explain:"Angst vor + Dat.", level:"b1", options:["vor", "für", "über"], answer:"vor" },
{ id:"b1qe133", set:"prepositions", type:"mcq", prompt:"nach Hause vs zu Hause:", explain:"Classic pair.", level:"b1", options:["nach = direction, zu = location", "same", "zu = direction"], answer:"nach = direction, zu = location" },
{ id:"b1qe134", set:"prepositions", type:"mcq", prompt:"Ich gehe ___ Arzt.", explain:"zum Arzt.", level:"b1", options:["zum", "nach", "ins"], answer:"zum" },
{ id:"b1qe135", set:"prepositions", type:"mcq", prompt:"Ich bin ___ Stadt. (already there)", explain:"wo? Dat.", level:"b1", options:["in der", "in die", "nach der"], answer:"in der" },
{ id:"b1qe136", set:"prepositions", type:"tf", prompt:"seit takes dative and usually the present tense.", explain:"seit einem Jahr lerne ich …", level:"b1", answer:true },
{ id:"b1qe137", set:"prepositions", type:"mcq", prompt:"am Montag, um 8 Uhr: articles are", explain:"Time chunks.", level:"b1", options:["am = an dem; um + clock", "am = auf dem", "um = in dem"], answer:"am = an dem; um + clock" },
{ id:"b1qe138", set:"prepositions", type:"mcq", prompt:"auf die Post / zur Bank are", explain:"Learn as chunks.", level:"b1", options:["direction chunks", "random", "Genitiv"], answer:"direction chunks" },
{ id:"b1qe139", set:"prepositions", type:"gap", prompt:"Wir treffen uns ___ dem Café. (in front)", explain:"vor + Dat location.", level:"b1", answer:["vor"] },
{ id:"b1qe140", set:"prepositions", type:"mcq", prompt:"ohne ___ Ausweis kommst du nicht rein.", explain:"Ausweis masculine; ohne + Akk.", level:"b1", options:["einen", "einem", "ein"], answer:"einen" },
{ id:"b1qe141", set:"konjunktiv2", type:"mcq", prompt:"Polite: ___ Sie mir bitte helfen?", explain:"Könnten Sie …", level:"b1", options:["Könnten", "Können müssen", "Hat"], answer:"Könnten" },
{ id:"b1qe142", set:"konjunktiv2", type:"mcq", prompt:"Ich ___ gerne kürzer arbeiten.", explain:"würde + infinitive.", level:"b1", options:["würde", "werde", "wurde"], answer:"würde" },
{ id:"b1qe143", set:"konjunktiv2", type:"mcq", prompt:"Wenn ich Zeit ___, würde ich dich besuchen.", explain:"unreal present.", level:"b1", options:["hätte", "habe", "hatte"], answer:"hätte" },
{ id:"b1qe144", set:"konjunktiv2", type:"gap", prompt:"Ich ___ mehr Geduld. (hätte)", explain:"hätte = would have.", level:"b1", answer:["hätte"] },
{ id:"b1qe145", set:"konjunktiv2", type:"mcq", prompt:"Das ___ sehr nett. (wäre)", explain:"polite / unreal.", level:"b1", options:["wäre", "ist", "war"], answer:"wäre" },
{ id:"b1qe146", set:"konjunktiv2", type:"mcq", prompt:"Past unreal: Wenn ich das gewusst hätte, ___ ich früher gekommen.", explain:"wäre + Partizip.", level:"b1", options:["wäre", "würde", "habe"], answer:"wäre" },
{ id:"b1qe147", set:"konjunktiv2", type:"tf", prompt:"Konjunktiv II is high value in letters and speaking.", explain:"Politeness + unreal.", level:"b1", answer:true },
{ id:"b1qe148", set:"konjunktiv2", type:"mcq", prompt:"sollte in a request often means", explain:"Sie sollten den Antrag kopieren.", level:"b1", options:["ought to / should (soft)", "was allowed", "became"], answer:"ought to / should (soft)" },
{ id:"b1qe149", set:"konjunktiv2", type:"mcq", prompt:"Ich ___ Sie bitten, den Lärm zu reduzieren.", explain:"letter formula.", level:"b1", options:["möchte", "muss", "darf"], answer:"möchte" },
{ id:"b1qe150", set:"konjunktiv2", type:"mcq", prompt:"dürfte here is polite: Das ___ ein Irrtum sein.", explain:"soft deduction / politeness.", level:"b1", options:["dürfte", "darf", "muss nicht"], answer:"dürfte" },
{ id:"b1qe151", set:"konjunktiv2", type:"gap", prompt:"___ Sie so freundlich sein, mir zu antworten? (Würden)", explain:"Würden Sie so freundlich sein …", level:"b1", answer:["Würden", "würden"] },
{ id:"b1qe152", set:"konjunktiv2", type:"mcq", prompt:"müsste =", explain:"KII of müssen.", level:"b1", options:["would have to", "was allowed", "became"], answer:"would have to" },
{ id:"b1qe153", set:"konjunktiv2", type:"mcq", prompt:"An offer: Ich ___ Ihnen auch um 17 Uhr kommen.", explain:"flexible suggestion.", level:"b1", options:["könnte", "kannte", "gekonnt"], answer:"könnte" },
{ id:"b1qe154", set:"konjunktiv2", type:"tf", prompt:"würde + infinitive is the safe productive form for most verbs.", explain:"Use wäre/hätte/könnte as extras.", level:"b1", answer:true },
{ id:"b1qe155", set:"relative", type:"mcq", prompt:"Das ist der Mann, ___ nebenan wohnt.", explain:"Nom in the extra clause.", level:"b1", options:["der", "den", "dem"], answer:"der" },
{ id:"b1qe156", set:"relative", type:"mcq", prompt:"Das ist der Mann, ___ ich gesehen habe.", explain:"Akk object.", level:"b1", options:["den", "der", "dem"], answer:"den" },
{ id:"b1qe157", set:"relative", type:"mcq", prompt:"Das ist der Mann, ___ ich das Buch gegeben habe.", explain:"Dat receiver.", level:"b1", options:["dem", "den", "der"], answer:"dem" },
{ id:"b1qe158", set:"relative", type:"mcq", prompt:"Das ist der Kollege, mit ___ ich arbeite.", explain:"mit + Dat.", level:"b1", options:["dem", "den", "der"], answer:"dem" },
{ id:"b1qe159", set:"relative", type:"mcq", prompt:"After alles / etwas / nichts use", explain:"indefinite.", level:"b1", options:["was", "das", "welches"], answer:"was" },
{ id:"b1qe160", set:"relative", type:"tf", prompt:"Relative clauses need commas.", explain:"Required in German.", level:"b1", answer:true },
{ id:"b1qe161", set:"relative", type:"gap", prompt:"Die Frau, ___ ich kenne, wohnt in Köln.", explain:"Akk feminine die.", level:"b1", answer:["die"] },
{ id:"b1qe162", set:"relative", type:"mcq", prompt:"Verb in the relative clause is", explain:"subordinate.", level:"b1", options:["last", "second", "first"], answer:"last" },
{ id:"b1qe163", set:"relative", type:"mcq", prompt:"Gender/number come from the ___ ; case from the inner role.", explain:"Match then case.", level:"b1", options:["noun", "verb", "preposition always"], answer:"noun" },
{ id:"b1qe164", set:"relative", type:"mcq", prompt:"Das Beste, ___ du tun kannst, ist üben.", explain:"after superlative/indefinite.", level:"b1", options:["was", "das", "welches"], answer:"was" },
{ id:"b1qe165", set:"relative", type:"mcq", prompt:"Die Wohnung, in ___ wir wohnen, ist hell.", explain:"in + Dat feminine.", level:"b1", options:["der", "die", "dem"], answer:"der" },
{ id:"b1qe166", set:"relative", type:"mcq", prompt:"Die Kinder, ___ im Hof spielen, sind laut.", explain:"plural Nom.", level:"b1", options:["die", "der", "den"], answer:"die" },
{ id:"b1qe167", set:"relative", type:"gap", prompt:"Das Formular, ___ Sie ausfüllen müssen, liegt dort.", explain:"Akk/Nom neuter das.", level:"b1", answer:["das"] },
{ id:"b1qe168", set:"relative", type:"mcq", prompt:"Preposition + relative: the preposition sits", explain:"mit dem, auf die.", level:"b1", options:["before the pronoun", "after the verb", "omitted"], answer:"before the pronoun" },
{ id:"b1qe169", set:"zu", type:"mcq", prompt:"Ich versuche, pünktlich ___ kommen.", explain:"zu + infinitive.", level:"b1", options:["zu", "zum", "für"], answer:"zu" },
{ id:"b1qe170", set:"zu", type:"mcq", prompt:"Es ist wichtig, Deutsch ___ lernen.", explain:"es ist + adj + zu.", level:"b1", options:["zu", "für", "um"], answer:"zu" },
{ id:"b1qe171", set:"zu", type:"mcq", prompt:"same subject purpose:", explain:"um in Deutschland zu arbeiten.", level:"b1", options:["um … zu", "damit", "weil"], answer:"um … zu" },
{ id:"b1qe172", set:"zu", type:"mcq", prompt:"without doing:", explain:"ohne zu fragen.", level:"b1", options:["ohne … zu", "um … zu", "statt weil"], answer:"ohne … zu" },
{ id:"b1qe173", set:"zu", type:"gap", prompt:"It's hard ___ um 6. (aufzustehen)", explain:"zu tucks into separable verbs.", level:"b1", answer:["aufzustehen"] },
{ id:"b1qe174", set:"zu", type:"tf", prompt:"No zu after modals.", explain:"Ich kann kommen.", level:"b1", answer:true },
{ id:"b1qe175", set:"zu", type:"mcq", prompt:"Ich gehe ___ . (swim — no zu)", explain:"gehen + sport infinitive.", level:"b1", options:["schwimmen", "zu schwimmen", "zum schwimmen nur"], answer:"schwimmen" },
{ id:"b1qe176", set:"zu", type:"mcq", prompt:"sehen/hören/lassen take", explain:"Ich höre ihn kommen.", level:"b1", options:["bare infinitive, no zu", "zu always", "dass only"], answer:"bare infinitive, no zu" },
{ id:"b1qe177", set:"zu", type:"mcq", prompt:"statt … zu means", explain:"statt anzurufen, schreibt er.", level:"b1", options:["instead of doing", "in order to", "without"], answer:"instead of doing" },
{ id:"b1qe178", set:"zu", type:"mcq", prompt:"Comma before zu-infinitive clauses is", explain:"Ich versuche, pünktlich zu kommen.", level:"b1", options:["usual when extra info is long", "never", "only in English"], answer:"usual when extra info is long" },
{ id:"b1qe179", set:"zu", type:"gap", prompt:"Er geht, ohne ___ zu sagen. (etwas / uns)", explain:"ohne etwas zu sagen.", level:"b1", answer:["etwas", "uns etwas"] },
{ id:"b1qe180", set:"zu", type:"mcq", prompt:"Need different subject for purpose → prefer", explain:"damit alle verstehen.", level:"b1", options:["damit", "um zu", "ohne zu"], answer:"damit" },
{ id:"b1qe181", set:"zu", type:"mcq", prompt:"anfangen zu: Wir fangen an, den Antrag ___ .", explain:"zu inside separable.", level:"b1", options:["auszufüllen", "ausfüllen", "zu ausfüllen"], answer:"auszufüllen" },
{ id:"b1qe182", set:"zu", type:"tf", prompt:"um … zu needs the same subject in both parts.", explain:"Otherwise damit.", level:"b1", answer:true },
{ id:"b1qe183", set:"passive", type:"mcq", prompt:"Die Tür ___ um 9 Uhr geöffnet.", explain:"process: werden + Partizip.", level:"b1", options:["wird", "hat", "ist nur"], answer:"wird" },
{ id:"b1qe184", set:"passive", type:"mcq", prompt:"Das Formular muss ausgefüllt ___ .", explain:"modal + passive.", level:"b1", options:["werden", "sein", "haben"], answer:"werden" },
{ id:"b1qe185", set:"passive", type:"mcq", prompt:"Der Laden ___ geschlossen. (state)", explain:"sein + Partizip.", level:"b1", options:["ist", "wird", "hat"], answer:"ist" },
{ id:"b1qe186", set:"passive", type:"mcq", prompt:"Agent:", explain:"von der Behörde.", level:"b1", options:["von + Dat", "für + Akk", "aus + Dat"], answer:"von + Dat" },
{ id:"b1qe187", set:"passive", type:"gap", prompt:"Hier ___ Deutsch gesprochen.", explain:"wird + gesprochen.", level:"b1", answer:["wird"] },
{ id:"b1qe188", set:"passive", type:"tf", prompt:"hat gemacht is passive.", explain:"Active Perfekt.", level:"b1", answer:false },
{ id:"b1qe189", set:"passive", type:"mcq", prompt:"Die E-Mails ___ gestern gelesen.", explain:"past process wurde/n.", level:"b1", options:["wurden", "haben", "waren gemacht"], answer:"wurden" },
{ id:"b1qe190", set:"passive", type:"mcq", prompt:"Man öffnet die Tür. → Die Tür ___ .", explain:"object becomes subject.", level:"b1", options:["wird geöffnet", "hat geöffnet", "ist öffnen"], answer:"wird geöffnet" },
{ id:"b1qe191", set:"passive", type:"mcq", prompt:"werden in position 2, Partizip", explain:"Die Tür wird um 9 geöffnet.", level:"b1", options:["last", "first", "deleted"], answer:"last" },
{ id:"b1qe192", set:"passive", type:"mcq", prompt:"is being repaired: Die Heizung ___ repariert.", explain:"process.", level:"b1", options:["wird", "hat", "kann ohne werden"], answer:"wird" },
{ id:"b1qe193", set:"passive", type:"gap", prompt:"Der Antrag ___ bearbeitet. (wird)", explain:"Amt German loves passive.", level:"b1", answer:["wird"] },
{ id:"b1qe194", set:"passive", type:"mcq", prompt:"Avoid overproducing passive in Sprechen; still ___ it in Lesen.", explain:"B1 reading.", level:"b1", options:["recognise", "delete", "translate word for word"], answer:"recognise" },
{ id:"b1qe195", set:"passive", type:"mcq", prompt:"wurde gemacht vs ist gemacht:", explain:"wurde = event; ist = result.", level:"b1", options:["process past vs state", "same", "both wrong"], answer:"process past vs state" },
{ id:"b1qe196", set:"passive", type:"tf", prompt:"Modal + passive: Der Brief muss geschickt werden.", explain:"müssen + Partizip + werden.", level:"b1", answer:true },
{ id:"b1qe197", set:"reflexive", type:"mcq", prompt:"Ich freue ___ auf das Wochenende.", explain:"Akk reflexive, no other object.", level:"b1", options:["mich", "mir", "sich"], answer:"mich" },
{ id:"b1qe198", set:"reflexive", type:"mcq", prompt:"Ich erinnere ___ nicht an den Termin.", explain:"sich erinnern + Akk.", level:"b1", options:["mich", "mir", "mein"], answer:"mich" },
{ id:"b1qe199", set:"reflexive", type:"mcq", prompt:"Ich wasche ___ die Hände.", explain:"Dat if there is already an Akk object.", level:"b1", options:["mir", "mich", "mein"], answer:"mir" },
{ id:"b1qe200", set:"reflexive", type:"gap", prompt:"Setz ___ bitte. (du, Akk)", explain:"sich setzen → Setz dich.", level:"b1", answer:["dich"] },
{ id:"b1qe201", set:"reflexive", type:"mcq", prompt:"Wir treffen ___ um 18 Uhr.", explain:"sich treffen.", level:"b1", options:["uns", "wir", "euch uns"], answer:"uns" },
{ id:"b1qe202", set:"reflexive", type:"tf", prompt:"Akk if no other object; Dat if there is already an Akk object (body part, clothes).", explain:"Ich wasche mich vs mir die Hände.", level:"b1", answer:true },
{ id:"b1qe203", set:"reflexive", type:"mcq", prompt:"formal: Setzen ___ bitte.", explain:"sich stays sich with Sie.", level:"b1", options:["Sie sich", "Sie dich", "Ihnen"], answer:"Sie sich" },
{ id:"b1qe204", set:"reflexive", type:"mcq", prompt:"Ich kaufe ___ eine Fahrkarte.", explain:"beneficiary Dat.", level:"b1", options:["mir", "mich", "mein"], answer:"mir" },
{ id:"b1qe205", set:"reflexive", type:"mcq", prompt:"sich bewerben: Ich bewerbe ___ um die Stelle.", explain:"Akk.", level:"b1", options:["mich", "mir", "sich ich"], answer:"mich" },
{ id:"b1qe206", set:"reflexive", type:"mcq", prompt:"sich interessieren für: Interessierst du ___ für Sport?", explain:"du → dich.", level:"b1", options:["dich", "dir", "sich"], answer:"dich" },
{ id:"b1qe207", set:"reflexive", type:"gap", prompt:"Hast du ___ schon angemeldet? (dich)", explain:"sich anmelden.", level:"b1", answer:["dich"] },
{ id:"b1qe208", set:"reflexive", type:"mcq", prompt:"ihr: Wasch ___ die Hände!", explain:"ihr → euch.", level:"b1", options:["euch", "uns", "sich"], answer:"euch" },
{ id:"b1qe209", set:"reflexive", type:"mcq", prompt:"Past: Ich habe ___ sehr gefreut.", explain:"Perfekt with haben.", level:"b1", options:["mich", "mir", "mein"], answer:"mich" },
{ id:"b1qe210", set:"reflexive", type:"tf", prompt:"All German verbs need a reflexive pronoun.", explain:"Only the sich-verbs and optional Dat.", level:"b1", answer:false },
{ id:"b1qe211", set:"k1", type:"mcq", prompt:"Die Ministerin sagte, das Problem ___ gelöst.", explain:"Konjunktiv I of sein.", level:"b1", options:["sei", "ist immer", "war nur"], answer:"sei" },
{ id:"b1qe212", set:"k1", type:"mcq", prompt:"Der Sprecher erklärte, man ___ genug Geld.", explain:"K I of haben.", level:"b1", options:["habe", "hat nur", "hätte immer falsch"], answer:"habe" },
{ id:"b1qe213", set:"k1", type:"tf", prompt:"Konjunktiv I is mainly for reported speech in news German.", explain:"Recognise at B1; produce at B2+.", level:"b1", answer:true },
{ id:"b1qe214", set:"k1", type:"mcq", prompt:"If K I looks like the indicative, German often uses ___ instead.", explain:"sie hätten not sie haben.", level:"b1", options:["Konjunktiv II", "Perfekt only", "English"], answer:"Konjunktiv II" },
{ id:"b1qe215", set:"k1", type:"mcq", prompt:"er sei ≈", explain:"News style.", level:"b1", options:["he is (reported)", "he was allowed", "he becomes"], answer:"he is (reported)" },
{ id:"b1qe216", set:"k1", type:"gap", prompt:"Sie sagte, sie ___ morgen. (komme)", explain:"K I of kommen looks like indicative — context marks it.", level:"b1", answer:["komme"] },
{ id:"b1qe217", set:"k1", type:"mcq", prompt:"sie würden kommen is used when", explain:"Avoid clash with indicative.", level:"b1", options:["K I würde look-alike needs a clearer form", "it is always wrong", "it is Perfekt"], answer:"K I würde look-alike needs a clearer form" },
{ id:"b1qe218", set:"k1", type:"mcq", prompt:"For telc B1 you mainly ___ Konjunktiv I.", explain:"Lesen skill.", level:"b1", options:["recognise", "write long speeches in", "ignore"], answer:"recognise" },
{ id:"b1qe219", set:"k1", type:"mcq", prompt:"er habe verstanden signals", explain:"habe = K I.", level:"b1", options:["reported speech", "a command", "a question word"], answer:"reported speech" },
{ id:"b1qe220", set:"k1", type:"tf", prompt:"sei is Konjunktiv I of sein.", explain:"er sei krank.", level:"b1", answer:true },
{ id:"b1qe221", set:"k1", type:"mcq", prompt:"man müsse den Antrag stellen uses K I of", explain:"rumour/report of obligation.", level:"b1", options:["müssen", "dürfen", "wollen"], answer:"müssen" },
{ id:"b1qe222", set:"k1", type:"mcq", prompt:"Quote vs report: Direct: „Ich bin fertig.“ Report:", explain:"Shift person + K I.", level:"b1", options:["Er sagte, er sei fertig.", "Er sagte, er ist immer falsch.", "Er sagte fertig ich."], answer:"Er sagte, er sei fertig." },
{ id:"b1qe223", set:"k1", type:"gap", prompt:"Die Polizei mitteilte, niemand ___ verletzt. (sei)", explain:"sei verletzt.", level:"b1", answer:["sei"] },
{ id:"b1qe224", set:"k1", type:"mcq", prompt:"News verb that often introduces K I:", explain:"Reporting verbs.", level:"b1", options:["sagte / erklärte / berichtete", "kochte", "schlief"], answer:"sagte / erklärte / berichtete" },
{ id:"b1qe225", set:"nominal", type:"mcq", prompt:"wegen des ___ (regnen)", explain:"wegen + Genitiv.", level:"b1", options:["Regens", "Regnen", "regnend"], answer:"Regens" },
{ id:"b1qe226", set:"nominal", type:"mcq", prompt:"bei der ___ der Probleme (lösen)", explain:"die Lösung.", level:"b1", options:["Lösung", "Lösen", "gelöst"], answer:"Lösung" },
{ id:"b1qe227", set:"nominal", type:"mcq", prompt:"entscheiden →", explain:"-ung nominalisation.", level:"b1", options:["die Entscheidung", "der Entscheidigung", "das Entscheidenheit"], answer:"die Entscheidung" },
{ id:"b1qe228", set:"nominal", type:"mcq", prompt:"teilnehmen →", explain:"die Teilnahme am Kurs.", level:"b1", options:["die Teilnahme", "der Teilnehmung", "das Teilnehms"], answer:"die Teilnahme" },
{ id:"b1qe229", set:"nominal", type:"tf", prompt:"B2 texts pack verbs into nouns; unpack them when you read.", explain:"die Lösung des Problems = man löst das Problem.", level:"b1", answer:true },
{ id:"b1qe230", set:"nominal", type:"gap", prompt:"entwickeln → die ___", explain:"-ung.", level:"b1", answer:["Entwicklung"] },
{ id:"b1qe231", set:"nominal", type:"mcq", prompt:"Wegen der Erhöhung der Miete ≈", explain:"Unpack.", level:"b1", options:["Weil die Miete steigt", "Obwohl die Miete fällt", "Damit die Miete tanzt"], answer:"Weil die Miete steigt" },
{ id:"b1qe232", set:"nominal", type:"mcq", prompt:"die Anmeldung des Kindes =", explain:"Genitiv = object of the action.", level:"b1", options:["man meldet das Kind an", "das Kind meldet die Stadt", "anmelden is adjective"], answer:"man meldet das Kind an" },
{ id:"b1qe233", set:"nominal", type:"mcq", prompt:"Infinitive as noun is ___ gender.", explain:"das Lernen, das Warten.", level:"b1", options:["neuter", "feminine", "masculine always"], answer:"neuter" },
{ id:"b1qe234", set:"nominal", type:"mcq", prompt:"bei + nominalisation often means", explain:"bei der Bearbeitung des Antrags.", level:"b1", options:["when/while doing", "never", "only location of a house"], answer:"when/while doing" },
{ id:"b1qe235", set:"nominal", type:"gap", prompt:"anmelden → die ___", explain:"die Anmeldung.", level:"b1", answer:["Anmeldung"] },
{ id:"b1qe236", set:"nominal", type:"mcq", prompt:"nach + noun: nach Abschluss des Kurses ≈", explain:"Time unpack.", level:"b1", options:["after the course ends", "before it starts", "instead of the course"], answer:"after the course ends" },
{ id:"b1qe237", set:"nominal", type:"mcq", prompt:"Useful B1 Lesen move:", explain:"Unpack.", level:"b1", options:["turn the noun back into a verb", "skip the noun", "translate ending only"], answer:"turn the noun back into a verb" },
{ id:"b1qe238", set:"nominal", type:"tf", prompt:"wegen in careful written German takes Genitiv.", explain:"wegen des Regens (spoken: wegen dem also heard).", level:"b1", answer:true },
{ id:"b1qe239", set:"advconn", type:"mcq", prompt:"___, muss man früher kommen. (consequently)", explain:"Folglich + V2.", level:"b1", options:["Folglich", "Weil", "Denn"], answer:"Folglich" },
{ id:"b1qe240", set:"advconn", type:"mcq", prompt:"___, war der Zug pünktlich. (nevertheless)", explain:"Trotzdem + V2.", level:"b1", options:["Trotzdem", "Weil", "Dass"], answer:"Trotzdem" },
{ id:"b1qe241", set:"advconn", type:"mcq", prompt:"Je mehr ich lerne, ___ sicherer werde ich.", explain:"je … desto.", level:"b1", options:["desto", "weil", "ob"], answer:"desto" },
{ id:"b1qe242", set:"advconn", type:"mcq", prompt:"Die Stadt ist teuer. ___ bleibt sie beliebt.", explain:"dennoch + V2.", level:"b1", options:["Dennoch", "Weil", "Dass"], answer:"Dennoch" },
{ id:"b1qe243", set:"advconn", type:"tf", prompt:"sofern / zumal / indem send the verb last.", explain:"Subordinating set.", level:"b1", answer:true },
{ id:"b1qe244", set:"advconn", type:"mcq", prompt:"Verb-second group:", explain:"Adverb connectors.", level:"b1", options:["dennoch, infolgedessen, hingegen, stattdessen", "weil, dass, obwohl", "um zu"], answer:"dennoch, infolgedessen, hingegen, stattdessen" },
{ id:"b1qe245", set:"advconn", type:"gap", prompt:"Ich bleibe daheim, ___ es stürmt. (sofern / falls)", explain:"condition, verb last.", level:"b1", answer:["sofern", "falls"] },
{ id:"b1qe246", set:"advconn", type:"mcq", prompt:"stattdessen means", explain:"V2.", level:"b1", options:["instead", "therefore", "because"], answer:"instead" },
{ id:"b1qe247", set:"advconn", type:"mcq", prompt:"infolgedessen ≈", explain:"V2.", level:"b1", options:["as a result", "although", "whether"], answer:"as a result" },
{ id:"b1qe248", set:"advconn", type:"mcq", prompt:"während can mean while (time) or", explain:"Context.", level:"b1", options:["whereas (contrast)", "because", "never"], answer:"whereas (contrast)" },
{ id:"b1qe249", set:"advconn", type:"mcq", prompt:"indem often means", explain:"indem man den Antrag online stellt.", level:"b1", options:["by doing", "without doing", "after doing"], answer:"by doing" },
{ id:"b1qe250", set:"advconn", type:"mcq", prompt:"sodass sends the verb", explain:"result clause.", level:"b1", options:["last", "second", "first"], answer:"last" },
{ id:"b1qe251", set:"advconn", type:"gap", prompt:"Ich habe keine Zeit. ___ fahre ich nicht mit.", explain:"V2 adverb (several possible; pick common).", level:"b1", answer:["Deshalb", "Deswegen", "Darum", "Trotzdem"] },
{ id:"b1qe252", set:"advconn", type:"tf", prompt:"hingegen contrasts two ideas and takes verb-second.", explain:"Die Miete stieg. Die Löhne hingegen blieben gleich.", level:"b1", answer:true },
{ id:"b1qe253", set:"subjmodals", type:"mcq", prompt:"Er ___ krank sein. (they say)", explain:"rumour soll.", level:"b1", options:["soll", "will", "darf"], answer:"soll" },
{ id:"b1qe254", set:"subjmodals", type:"mcq", prompt:"Sie ___ nichts gesehen haben. (claims — doubt)", explain:"will = claims.", level:"b1", options:["will", "soll", "muss"], answer:"will" },
{ id:"b1qe255", set:"subjmodals", type:"mcq", prompt:"Das ___ ein Irrtum sein. (logical must)", explain:"deduction.", level:"b1", options:["muss", "soll", "will"], answer:"muss" },
{ id:"b1qe256", set:"subjmodals", type:"mcq", prompt:"kann / könnte for rumours means", explain:"possibility.", level:"b1", options:["might", "must", "is not allowed"], answer:"might" },
{ id:"b1qe257", set:"subjmodals", type:"tf", prompt:"Subjective modals talk about how sure we are, not about ability/permission in the usual sense.", explain:"B2 rumour/deduction.", level:"b1", answer:true },
{ id:"b1qe258", set:"subjmodals", type:"gap", prompt:"Er ___ den Termin vergessen haben. (must have — deduction)", explain:"muss … haben.", level:"b1", answer:["muss"] },
{ id:"b1qe259", set:"subjmodals", type:"mcq", prompt:"soll + infinitive in news headlines often =", explain:"Der Minister soll zurücktreten.", level:"b1", options:["reportedly", "is allowed to", "wants to definitely"], answer:"reportedly" },
{ id:"b1qe260", set:"subjmodals", type:"mcq", prompt:"will here is not 'wants': Er will nichts gewusst haben means", explain:"doubt.", level:"b1", options:["he claims he knew nothing", "he wants knowledge", "he is allowed"], answer:"he claims he knew nothing" },
{ id:"b1qe261", set:"subjmodals", type:"mcq", prompt:"Double infinitive: Er soll den Zug verpasst haben.", explain:"soll + inf + haben.", level:"b1", options:["rumour about a past event", "he is allowed to miss trains", "command"], answer:"rumour about a past event" },
{ id:"b1qe262", set:"subjmodals", type:"mcq", prompt:"müsste here: Das müsste klappen ≈", explain:"soft deduction.", level:"b1", options:["that ought to work", "that is forbidden", "that is a rumour from the press"], answer:"that ought to work" },
{ id:"b1qe263", set:"subjmodals", type:"mcq", prompt:"dürfte: Das dürfte teuer werden ≈", explain:"soft probability.", level:"b1", options:["that's likely to get expensive", "that's allowed to be expensive", "that's a want"], answer:"that's likely to get expensive" },
{ id:"b1qe264", set:"subjmodals", type:"gap", prompt:"Sie ___ die Prüfung bestanden haben. (they say)", explain:"soll/sollen + Partizip + haben.", level:"b1", answer:["soll", "sollen"] },
{ id:"b1qe265", set:"subjmodals", type:"tf", prompt:"Objective können (ability) and subjective können (possibility) look the same; context decides.", explain:"Er kann krank sein vs Er kann schwimmen.", level:"b1", answer:true },
{ id:"b1qe266", set:"subjmodals", type:"mcq", prompt:"Best B1 strategy:", explain:"Production can wait.", level:"b1", options:["recognise rumour vs deduction in Lesen", "use will-rumour in every letter", "ignore all modals"], answer:"recognise rumour vs deduction in Lesen" },
{ id:"b1qe267", set:"partizip", type:"mcq", prompt:"die steigenden Mieten means", explain:"Partizip I as adjective.", level:"b1", options:["the rising rents", "the risen people", "to rise rents"], answer:"the rising rents" },
{ id:"b1qe268", set:"partizip", type:"mcq", prompt:"der geschriebene Brief means", explain:"Partizip II as adjective.", level:"b1", options:["the written letter", "the writing person", "write!"], answer:"the written letter" },
{ id:"b1qe269", set:"partizip", type:"mcq", prompt:"eine überzeugende Lösung uses Partizip", explain:"-end = -ing feel.", level:"b1", options:["I (ongoing)", "II (finished)", "III"], answer:"I (ongoing)" },
{ id:"b1qe270", set:"partizip", type:"mcq", prompt:"die im Zentrum gelegene Wohnung =", explain:"Unpack to a relative clause.", level:"b1", options:["the flat that lies in the centre", "the centre that lies in a flat", "lying is a person"], answer:"the flat that lies in the centre" },
{ id:"b1qe271", set:"partizip", type:"tf", prompt:"B2 packs relative clauses into participles; B1 reading: strip to a verb.", explain:"Exam strategy.", level:"b1", answer:true },
{ id:"b1qe272", set:"partizip", type:"gap", prompt:"der ___ Zug (verspäten → verspätet)", explain:"der verspätete Zug.", level:"b1", answer:["verspätete", "verspätet"] },
{ id:"b1qe273", set:"partizip", type:"mcq", prompt:"Partizip I of laufen as adjective:", explain:"stem + -end.", level:"b1", options:["laufend", "gelaufen", "läuftend"], answer:"laufend" },
{ id:"b1qe274", set:"partizip", type:"mcq", prompt:"Partizip II as adjective still needs", explain:"der geschriebene Brief, ein geschriebenes Wort.", level:"b1", options:["adjective endings", "no ending ever", "zu"], answer:"adjective endings" },
{ id:"b1qe275", set:"partizip", type:"mcq", prompt:"die gestern angekommene Post ≈", explain:"Unpack.", level:"b1", options:["the mail that arrived yesterday", "the post that will arrive", "ankommen as modal"], answer:"the mail that arrived yesterday" },
{ id:"b1qe276", set:"partizip", type:"mcq", prompt:"ein zu bearbeitender Antrag is a", explain:"B2; recognise: the application that must be processed.", level:"b1", options:["gerundive (to be processed)", "simple Perfekt", "Konjunktiv I"], answer:"gerundive (to be processed)" },
{ id:"b1qe277", set:"partizip", type:"mcq", prompt:"Best unpack question: which noun is described, and is the action ___ ?", explain:"II vs I.", level:"b1", options:["finished or ongoing", "English", "a preposition"], answer:"finished or ongoing" },
{ id:"b1qe278", set:"partizip", type:"gap", prompt:"die ___ Kosten (steigen)", explain:"die steigenden Kosten.", level:"b1", answer:["steigenden"] },
{ id:"b1qe279", set:"partizip", type:"tf", prompt:"Participles as adjectives take the same endings as normal adjectives.", explain:"der neue / der geschriebene.", level:"b1", answer:true },
{ id:"b1qe280", set:"partizip", type:"mcq", prompt:"vom Amt ausgefüllte Formulare are forms", explain:"von + agent + Partizip II.", level:"b1", options:["filled in by the office", "that fill the office", "future forms"], answer:"filled in by the office" }
  ],
  drills: [
{ id:"b1-exam-mix", title:"B1 Sprachbausteine mix", blurb:"Connectors, KII, adjectives, prepositions.", sets:["connectors", "konjunktiv2", "adjectives", "prepositions", "wordorder", "relative"] }
  ]
};
