export default {
  vocab: [
  // function words — grammar that is also vocab
  { id:"b1f1", de:"jemand", art:"", pl:"", en:"someone", topic:"function", level:"b1", ex:"Hat jemand den Hausmeister gesehen?" },
  { id:"b1f2", de:"niemand", art:"", pl:"", en:"no one", topic:"function", level:"b1", ex:"Niemand hat auf die Beschwerde geantwortet." },
  { id:"b1f3", de:"irgendwann", art:"", pl:"", en:"sometime / at some point", topic:"function", level:"b1", ex:"Irgendwann müssen wir uns schriftlich beschweren — am besten Montag." },
  { id:"b1f4", de:"irgendwo", art:"", pl:"", en:"somewhere", topic:"function", level:"b1", ex:"Der Schlüssel liegt irgendwo in der Küche." },
  { id:"b1f5", de:"irgendwie", art:"", pl:"", en:"somehow", topic:"function", level:"b1", ex:"Irgendwie müssen wir die Frist noch schaffen." },
  { id:"b1f6", de:"irgendwas", art:"", pl:"", en:"something or other", topic:"function", level:"b1", ex:"Im Brief fehlt irgendwas — die Unterschrift oder das Datum." },
  { id:"b1f7", de:"darauf", art:"", pl:"", en:"on it / for it (thing)", topic:"function", level:"b1", ex:"Der Bescheid kommt per Post. Ich warte darauf." },
  { id:"b1f8", de:"darüber", art:"", pl:"", en:"about it / over it", topic:"function", level:"b1", ex:"Wir haben lange über die Miete gesprochen. Wir sprechen immer noch darüber." },
  { id:"b1f9", de:"damit", art:"", pl:"", en:"with it / so that (context)", topic:"function", level:"b1", ex:"Ich öffne die Datei. Damit kann ich den Antrag stellen." },
  { id:"b1f10", de:"daran", art:"", pl:"", en:"of it / about it (an)", topic:"function", level:"b1", ex:"Ich denke oft an die Prüfung. Ich denke oft daran." },
  { id:"b1f11", de:"davon", art:"", pl:"", en:"of it / about that", topic:"function", level:"b1", ex:"Von der Verspätung habe ich nichts gewusst. Davon wusste ich nichts." },
  { id:"b1f12", de:"dazu", art:"", pl:"", en:"in addition / to that", topic:"function", level:"b1", ex:"Ich brauche den Ausweis und dazu ein aktuelles Foto." },
  { id:"b1f13", de:"dafür", art:"", pl:"", en:"for it / in favour", topic:"function", level:"b1", ex:"Ich interessiere mich für den Kurs. Ich interessiere mich dafür." },
  { id:"b1f14", de:"dagegen", art:"", pl:"", en:"against it", topic:"function", level:"b1", ex:"Ich bin dagegen, den Vertrag so zu unterschreiben." },
  { id:"b1f15", de:"darum", art:"", pl:"", en:"about it / that's why", topic:"function", level:"b1", ex:"Die Stelle klingt gut. Ich bewerbe mich darum." },
  { id:"b1f16", de:"worauf", art:"", pl:"", en:"on what / for what", topic:"function", level:"b1", ex:"Worauf warten Sie — auf den Bus oder auf den Kollegen?" },
  { id:"b1f17", de:"worüber", art:"", pl:"", en:"about what", topic:"function", level:"b1", ex:"Worüber haben sich die Nachbarn beschwert?" },
  { id:"b1f18", de:"womit", art:"", pl:"", en:"with what", topic:"function", level:"b1", ex:"Womit kann ich Ihnen helfen?" },
  { id:"b1f19", de:"worum", art:"", pl:"", en:"about what (es geht um)", topic:"function", level:"b1", ex:"Worum geht es in dem Brief — um die Miete oder um die Heizung?" },
  { id:"b1f20", de:"warum", art:"", pl:"", en:"why", topic:"function", level:"b1", ex:"Warum kommt niemand? Worum geht es? — zwei verschiedene Wörter." },
  { id:"b1f21", de:"weder … noch", art:"", pl:"", en:"neither … nor", topic:"function", level:"b1", ex:"Ich habe weder den Vertrag noch die Rechnung erhalten." },
  { id:"b1f22", de:"entweder … oder", art:"", pl:"", en:"either … or", topic:"function", level:"b1", ex:"Entweder nehmen wir den Zug, oder wir fahren mit dem Auto." },
  { id:"b1f23", de:"sowohl … als auch", art:"", pl:"", en:"both … and", topic:"function", level:"b1", ex:"Sowohl die Miete als auch die Nebenkosten sind gestiegen." },
  { id:"b1f24", de:"zwar … aber", art:"", pl:"", en:"admittedly … but", topic:"function", level:"b1", ex:"Die Wohnung ist zwar klein, aber die Lage ist gut." },
  { id:"b1f25", de:"nicht nur … sondern auch", art:"", pl:"", en:"not only … but also", topic:"function", level:"b1", ex:"Ich brauche nicht nur das Formular, sondern auch den Ausweis." },
  { id:"b1f26", de:"je … desto", art:"", pl:"", en:"the more … the more", topic:"function", level:"b1", ex:"Je früher wir schreiben, desto besser sind die Chancen." },
  { id:"b1f27", de:"einander", art:"", pl:"", en:"each other", topic:"function", level:"b1", ex:"Wir helfen einander bei den Anträgen." },
  { id:"b1f28", de:"miteinander", art:"", pl:"", en:"with each other", topic:"function", level:"b1", ex:"Wir sollten miteinander sprechen, nicht nur E-Mails schreiben." },
  { id:"b1f29", de:"erst", art:"", pl:"", en:"not until / first", topic:"function", level:"b1", ex:"Der Kurs beginnt erst um 18 Uhr, nicht schon um 17." },
  { id:"b1f30", de:"schon", art:"", pl:"", en:"already / it'll be fine (tone)", topic:"function", level:"b1", ex:"Er ist schon da. — Das wird schon." },
  { id:"b1f31", de:"doch", art:"", pl:"", en:"yes (after a negative) / contrary", topic:"function", level:"b1", ex:"Hast du keine Zeit? — Doch, ich habe Zeit." },
  { id:"b1f32", de:"wohl", art:"", pl:"", en:"probably", topic:"function", level:"b1", ex:"Das wird wohl teuer. Es ist noch nicht sicher." },
  { id:"b1f33", de:"eigentlich", art:"", pl:"", en:"actually / originally", topic:"function", level:"b1", ex:"Ich wollte eigentlich anrufen, aber ich hatte keine Zeit." },
  { id:"b1f34", de:"kaum", art:"", pl:"", en:"hardly", topic:"function", level:"b1", ex:"Ich habe kaum Zeit vor der Prüfung." },
  { id:"b1f35", de:"noch nicht", art:"", pl:"", en:"not yet", topic:"function", level:"b1", ex:"Die Bestätigung ist noch nicht da." },
  { id:"b1f36", de:"nicht mehr", art:"", pl:"", en:"no longer", topic:"function", level:"b1", ex:"Ich warte nicht mehr — ich schreibe heute." },
  { id:"b1f37", de:"meines", art:"", pl:"", en:"mine (neuter pronoun)", topic:"function", level:"b1", ex:"Wessen Formular ist das? — Das ist meines." },
  { id:"b1f38", de:"stellen", art:"", pl:"", en:"to put (upright)", topic:"function", level:"b1", ex:"Bitte stellen Sie das Glas auf den Tisch." },
  { id:"b1f39", de:"legen", art:"", pl:"", en:"to lay / put (flat)", topic:"function", level:"b1", ex:"Legen Sie den Ausweis auf den Schalter." },
  { id:"b1f40", de:"liegen", art:"", pl:"", en:"to lie / be lying", topic:"function", level:"b1", ex:"Der Ausweis liegt auf dem Schalter." },

  // civic / Gesellschaft — B1 personal, not political theory
  { id:"b1c1", de:"Ehrenamt", art:"das", pl:"Ehrenämter", en:"voluntary work", topic:"civic", level:"b1", ex:"Ich mache ein Ehrenamt in der Nachbarschaftshilfe, zwei Stunden pro Woche." },
  { id:"b1c2", de:"Verein", art:"der", pl:"-e", en:"club / association", topic:"civic", level:"b1", ex:"Im Sportverein brauche ich eine Mitgliedsbescheinigung für die Versicherung." },
  { id:"b1c3", de:"Mitglied", art:"das", pl:"-er", en:"member", topic:"civic", level:"b1", ex:"Als Mitglied zahle ich 8 Euro im Monat und helfe beim Fest." },
  { id:"b1c4", de:"Gemeinde", art:"die", pl:"-n", en:"municipality / parish", topic:"civic", level:"b1", ex:"Die Gemeinde hat die Bücherei am Mittwoch geschlossen." },
  { id:"b1c5", de:"Stadtteil", art:"der", pl:"-e", en:"neighbourhood / district", topic:"civic", level:"b1", ex:"In unserem Stadtteil gibt es einen Flohmarkt und eine Tafel." },
  { id:"b1c6", de:"Nachbarschaftshilfe", art:"die", pl:"-n", en:"neighbourhood help", topic:"civic", level:"b1", ex:"Die Nachbarschaftshilfe sucht Leute, die Einkäufe für Ältere erledigen." },
  { id:"b1c7", de:"Tandem", art:"das", pl:"-s", en:"language tandem", topic:"civic", level:"b1", ex:"Im Tandem übe ich Deutsch, mein Partner übt Arabisch." },
  { id:"b1c8", de:"Wahl", art:"die", pl:"-en", en:"election / choice", topic:"civic", level:"b1", ex:"Bei der Wahl der Kita war uns die Lage wichtiger als der Preis." },
  { id:"b1c9", de:"Bürgeramt", art:"das", pl:"Bürgerämter", en:"citizens’ office", topic:"civic", level:"b1", ex:"Das Bürgeramt hat nur mit Termin geöffnet." },
  { id:"b1c10", de:"Meldebescheinigung", art:"die", pl:"-en", en:"registration certificate", topic:"civic", level:"b1", ex:"Für die Anmeldung in der Schule brauche ich eine Meldebescheinigung." },
  { id:"b1c11", de:"Aufenthaltstitel", art:"der", pl:"-", en:"residence title / permit", topic:"civic", level:"b1", ex:"Ohne gültigen Aufenthaltstitel bekomme ich keinen neuen Ausweis." },
  { id:"b1c12", de:"Einbürgerung", art:"die", pl:"-en", en:"naturalisation", topic:"civic", level:"b1", ex:"Für die Einbürgerung verlangen sie oft ein B1-Zertifikat." },
  { id:"b1c13", de:"Integration", art:"die", pl:"-en", en:"integration", topic:"civic", level:"b1", ex:"Der Integrationskurs endet mit dem Deutsch-Test; danach kommt B1." },
  { id:"b1c14", de:"Zusammenleben", art:"das", pl:"", en:"living together", topic:"civic", level:"b1", ex:"Zusammenleben im Haus heißt: leise sein nach 22 Uhr und den Hof sauber halten." },
  { id:"b1c15", de:"Hausordnung", art:"die", pl:"-en", en:"house rules", topic:"civic", level:"b1", ex:"In der Hausordnung steht, dass man den Müll trennen muss." },
  { id:"b1c16", de:"Mülltrennung", art:"die", pl:"-en", en:"waste separation", topic:"civic", level:"b1", ex:"Mülltrennung ist Pflicht: Papier, Bio, Restmüll, Gelber Sack." },
  { id:"b1c17", de:"Tafel", art:"die", pl:"-n", en:"food bank (Tafel)", topic:"civic", level:"b1", ex:"An der Tafel helfe ich samstags beim Verteilen." },
  { id:"b1c18", de:"Spende", art:"die", pl:"-n", en:"donation", topic:"civic", level:"b1", ex:"Wir sammeln Spenden für das Stadtteilfest, keine großen Beträge." },
  { id:"b1c19", de:"ehrenamtlich", art:"", pl:"", en:"on a voluntary basis", topic:"civic", level:"b1", ex:"Die Beratung ist ehrenamtlich und kostenlos." },
  { id:"b1c20", de:"Bürger", art:"der", pl:"-", en:"citizen / resident", topic:"civic", level:"b1", ex:"Als Bürger dieser Stadt kann ich Sprechstunden im Rathaus nutzen." },
  { id:"b1c21", de:"Rathaus", art:"das", pl:"Rathäuser", en:"town hall", topic:"civic", level:"b1", ex:"Das Rathaus liegt am Markt; der Kurs findet im zweiten Stock statt." },
  { id:"b1c22", de:"Sprechstunde", art:"die", pl:"-n", en:"office hour / surgery hour", topic:"civic", level:"b1", ex:"Die Sprechstunde des Bürgermeisters ist dienstags von 16 bis 18." },
  { id:"b1c23", de:"Einladung", art:"die", pl:"-en", en:"invitation (also for a visa)", topic:"civic", level:"b1", ex:"Für das Visum meiner Mutter brauche ich eine formelle Einladung." },
  { id:"b1c24", de:"Führungszeugnis", art:"das", pl:"-se", en:"police clearance certificate", topic:"civic", level:"b1", ex:"Für das Ehrenamt in der Kita verlangen sie ein Führungszeugnis." },
  { id:"b1c25", de:"Gemeinschaft", art:"die", pl:"-en", en:"community", topic:"civic", level:"b1", ex:"In der Hausgemeinschaft teilen wir uns den Waschkeller." },

  // world knowledge groups telc/Goethe list as Wortgruppen
  { id:"b1w1", de:"Norden", art:"der", pl:"", en:"north", topic:"world", level:"b1", ex:"Die Wohnung liegt im Norden der Stadt, der Bahnhof ist näher im Süden." },
  { id:"b1w2", de:"Süden", art:"der", pl:"", en:"south", topic:"world", level:"b1", ex:"Im Süden ist es im Sommer oft zu heiß für uns." },
  { id:"b1w3", de:"Osten", art:"der", pl:"", en:"east", topic:"world", level:"b1", ex:"Der Betrieb liegt im Osten, ich brauche 40 Minuten mit der S-Bahn." },
  { id:"b1w4", de:"Westen", art:"der", pl:"", en:"west", topic:"world", level:"b1", ex:"Im Westen der Stadt sind die Mieten höher." },
  { id:"b1w5", de:"Weihnachten", art:"das", pl:"", en:"Christmas", topic:"world", level:"b1", ex:"Zwischen Weihnachten und Neujahr ist das Amt geschlossen." },
  { id:"b1w6", de:"Ostern", art:"das", pl:"", en:"Easter", topic:"world", level:"b1", ex:"Über Ostern fahren wir zu den Schwiegereltern, vier Tage." },
  { id:"b1w7", de:"Silvester", art:"das", pl:"", en:"New Year’s Eve", topic:"world", level:"b1", ex:"An Silvester ist der letzte Bus früher, das steht im Aushang." },
  { id:"b1w8", de:"Neujahr", art:"das", pl:"", en:"New Year’s Day", topic:"world", level:"b1", ex:"Neujahr ist ein Feiertag; Apotheken haben Notdienst." },
  { id:"b1w9", de:"Feiertag", art:"der", pl:"-e", en:"public holiday", topic:"world", level:"b1", ex:"An Feiertagen kommt keine Post, die Frist verschiebt sich." },
  { id:"b1w10", de:"Kilometer", art:"der", pl:"-", en:"kilometre", topic:"world", level:"b1", ex:"Die Arbeit ist acht Kilometer entfernt, zu weit zum Radfahren bei Regen." },
  { id:"b1w11", de:"Kilogramm", art:"das", pl:"-", en:"kilogram", topic:"world", level:"b1", ex:"Das Paket wiegt drei Kilogramm, die Nachnahme ist teuer." },
  { id:"b1w12", de:"Liter", art:"der", pl:"-", en:"litre", topic:"world", level:"b1", ex:"Die Milch im Angebot kostet 89 Cent pro Liter." },
  { id:"b1w13", de:"Grad", art:"der", pl:"-", en:"degree (temperature)", topic:"world", level:"b1", ex:"In der Wohnung sind nur 16 Grad, die Kinder können nicht lernen." },
  { id:"b1w14", de:"Prozent", art:"das", pl:"-", en:"percent", topic:"world", level:"b1", ex:"Die Miete soll um fünf Prozent steigen, das steht im Schreiben." },
  { id:"b1w15", de:"Euro", art:"der", pl:"-", en:"euro", topic:"world", level:"b1", ex:"Die Gebühr beträgt 12 Euro, bar oder mit Karte." },
  { id:"b1w16", de:"Cent", art:"der", pl:"-", en:"cent", topic:"world", level:"b1", ex:"Auf dem Ticket steht 2,80 Euro, nicht 280 Cent — trotzdem derselbe Betrag." },
  { id:"b1w17", de:"Mathematik", art:"die", pl:"", en:"mathematics", topic:"world", level:"b1", ex:"Mein Sohn braucht Nachhilfe in Mathematik, zweimal die Woche." },
  { id:"b1w18", de:"Deutschunterricht", art:"der", pl:"", en:"German class", topic:"world", level:"b1", ex:"Der Deutschunterricht fällt Donnerstag aus, der Stoff kommt per Mail." },
  { id:"b1w19", de:"Geschichte", art:"die", pl:"-n", en:"history / story", topic:"world", level:"b1", ex:"In Geschichte hat sie eine Vier, wir suchen Nachhilfe." },
  { id:"b1w20", de:"Biologie", art:"die", pl:"", en:"biology", topic:"world", level:"b1", ex:"Biologie ist ihr bestes Fach, Deutsch noch nicht." },
  { id:"b1w21", de:"Note", art:"die", pl:"-n", en:"school grade / mark", topic:"world", level:"b1", ex:"Mit dieser Note in Deutsch bekommt er den Realschulabschluss nicht." },
  { id:"b1w22", de:"Hund", art:"der", pl:"-e", en:"dog", topic:"world", level:"b1", ex:"Hunde sind im Mietvertrag nicht erlaubt, das stand klein gedruckt." },
  { id:"b1w23", de:"Katze", art:"die", pl:"-n", en:"cat", topic:"world", level:"b1", ex:"Eine Katze wäre erlaubt, ein Hund nicht." },
  { id:"b1w24", de:"Haustier", art:"das", pl:"-e", en:"pet", topic:"world", level:"b1", ex:"Bitte klären Sie schriftlich, ob Haustiere in der Wohnung erlaubt sind." },
  { id:"b1w25", de:"rot", art:"", pl:"", en:"red", topic:"world", level:"b1", ex:"Bitte nehmen Sie das rote Formular, nicht das gelbe." },
  { id:"b1w26", de:"gelb", art:"", pl:"", en:"yellow", topic:"world", level:"b1", ex:"Der gelbe Sack ist für Verpackungen, nicht für Biomüll." },
  { id:"b1w27", de:"grün", art:"", pl:"", en:"green", topic:"world", level:"b1", ex:"Die grüne Tonne ist für Bioabfall." },
  { id:"b1w28", de:"blau", art:"", pl:"", en:"blue", topic:"world", level:"b1", ex:"Die blaue Tonne ist Papier; der Deckel muss zu sein." },
  { id:"b1w29", de:"schwarz", art:"", pl:"", en:"black", topic:"world", level:"b1", ex:"Restmüll kommt in die schwarze Tonne." },
  { id:"b1w30", de:"weiß", art:"", pl:"", en:"white", topic:"world", level:"b1", ex:"Bringen Sie ein weißes Passfoto mit, kein Selfie." },
  { id:"b1w31", de:"die Schweiz", art:"", pl:"", en:"Switzerland", topic:"world", level:"b1", ex:"Ich fahre in die Schweiz, nicht nach Schweiz." },
  { id:"b1w32", de:"die Türkei", art:"", pl:"", en:"Turkey", topic:"world", level:"b1", ex:"Meine Eltern fliegen in die Türkei, ich bleibe wegen der Prüfung hier." },
  { id:"b1w33", de:"die USA", art:"", pl:"", en:"the USA", topic:"world", level:"b1", ex:"Für die USA brauche ich ein Visum; nach Spanien reicht der Ausweis oft nicht." },
  { id:"b1w34", de:"Österreich", art:"das", pl:"", en:"Austria", topic:"world", level:"b1", ex:"Nach Österreich fahre ich mit dem Zug, ohne Artikel vor dem Land." },
  { id:"b1w35", de:"Viertel", art:"das", pl:"-", en:"quarter / neighbourhood", topic:"world", level:"b1", ex:"Ein Viertel der Miete sind Nebenkosten — das hatte ich unterschätzt." },
  { id:"b1w36", de:"Hälfte", art:"die", pl:"-n", en:"half", topic:"world", level:"b1", ex:"Die Hälfte der Kollegen arbeitet im Homeoffice, die andere Hälfte in der Schicht." },
  { id:"b1w37", de:"Doppelstunde", art:"die", pl:"-n", en:"double period", topic:"world", level:"b1", ex:"Der Kurs ist eine Doppelstunde, von 18 bis 19:30." },
  { id:"b1w38", de:"Wochentag", art:"der", pl:"-e", en:"weekday", topic:"world", level:"b1", ex:"An Wochentagen arbeite ich, am Wochenende lerne ich." },
  { id:"b1w39", de:"Jahreszeit", art:"die", pl:"-en", en:"season", topic:"world", level:"b1", ex:"In welcher Jahreszeit ist die Heizung kaputt? — Im Winter, natürlich." },
  { id:"b1w40", de:"Frühling", art:"der", pl:"-e", en:"spring", topic:"world", level:"b1", ex:"Im Frühling wollen wir umziehen, vor der nächsten Mieterhöhung." },
  { id:"b1w41", de:"Sommer", art:"der", pl:"", en:"summer", topic:"world", level:"b1", ex:"Im Sommer fällt die Heizung aus — dann merkt man es nicht sofort." },
  { id:"b1w42", de:"Herbst", art:"der", pl:"-e", en:"autumn", topic:"world", level:"b1", ex:"Im Herbst beginnen die Kurse, die Plätze sind schnell weg." },
  { id:"b1w43", de:"Winter", art:"der", pl:"", en:"winter", topic:"world", level:"b1", ex:"Im Winter war die Wohnung 16 Grad, wir haben schriftlich reklamiert." },
  { id:"b1w44", de:"Pfingsten", art:"das", pl:"", en:"Whitsun / Pentecost", topic:"world", level:"b1", ex:"Über Pfingsten bleibt die Kita zu, ich brauche zwei Urlaubstage." },
  { id:"b1w45", de:"Tag der Deutschen Einheit", art:"der", pl:"", en:"German Unity Day (3 Oct)", topic:"world", level:"b1", ex:"Am 3. Oktober ist Tag der Deutschen Einheit, das Amt ist geschlossen." },

  { id:"b1feel1", de:"Angst", art:"die", pl:"Ängste", en:"fear / anxiety", topic:"feelings", level:"b1", ex:"Ich habe Angst vor der mündlichen Prüfung, deshalb übe ich mit einem Tandem." },
  { id:"b1feel2", de:"Sorge", art:"die", pl:"-n", en:"worry", topic:"feelings", level:"b1", ex:"Meine größte Sorge ist die Miete, nicht die Note in Deutsch." },
  { id:"b1feel3", de:"Freude", art:"die", pl:"-n", en:"joy", topic:"feelings", level:"b1", ex:"Es war eine große Freude, als der Bescheid positiv kam." },
  { id:"b1feel4", de:"Wut", art:"die", pl:"", en:"anger", topic:"feelings", level:"b1", ex:"Ich schreibe den Brief erst morgen, sonst steht die Wut zwischen den Zeilen." },
  { id:"b1feel5", de:"Trauer", art:"die", pl:"", en:"sadness / grief", topic:"feelings", level:"b1", ex:"Nach der Absage war Trauer da, aber ich bewerbe mich weiter." },
  { id:"b1feel6", de:"Hoffnung", art:"die", pl:"-en", en:"hope", topic:"feelings", level:"b1", ex:"Ich habe noch Hoffnung, dass der Vermieter die Heizung reparieren lässt." },
  { id:"b1feel7", de:"Geduld", art:"die", pl:"", en:"patience", topic:"feelings", level:"b1", ex:"Im Amt braucht man Geduld: Nummern, Warten, oft ein zweiter Termin." },
  { id:"b1feel8", de:"Mut", art:"der", pl:"", en:"courage", topic:"feelings", level:"b1", ex:"Es gehört Mut dazu, im Teil 2 zwei Minuten allein zu sprechen." },
  { id:"b1feel9", de:"Stolz", art:"der", pl:"", en:"pride", topic:"feelings", level:"b1", ex:"Ich bin stolz, dass ich den Brief ohne Übersetzung geschrieben habe." },
  { id:"b1feel10", de:"Scham", art:"die", pl:"", en:"shame / embarrassment", topic:"feelings", level:"b1", ex:"Es ist mir peinlich, aber Scham hilft nicht — ich frage trotzdem nach." },
  { id:"b1feel11", de:"Überraschung", art:"die", pl:"-en", en:"surprise", topic:"feelings", level:"b1", ex:"Die Absage war eine Überraschung, die Begründung fehlte." },
  { id:"b1feel12", de:"Enttäuschung", art:"die", pl:"-en", en:"disappointment", topic:"feelings", level:"b1", ex:"Die Enttäuschung war groß, als der Kurs ausfiel." },
  { id:"b1feel13", de:"Erleichterung", art:"die", pl:"-en", en:"relief", topic:"feelings", level:"b1", ex:"Als der Techniker kam, war die Erleichterung riesig." },
  { id:"b1feel14", de:"Langeweile", art:"die", pl:"", en:"boredom", topic:"feelings", level:"b1", ex:"Im Wartezimmer ist Langeweile, ich lerne Vokabeln auf dem Handy." },
  { id:"b1feel15", de:"Neid", art:"der", pl:"", en:"envy", topic:"feelings", level:"b1", ex:"Kein Neid: die Kollegin hat die Stelle, weil sie früher geschrieben hat." },
  { id:"b1feel16", de:"sich ärgern", art:"", pl:"hat sich geärgert", en:"to be annoyed", topic:"feelings", level:"b1", ex:"Ich ärgere mich über den Lärm, deshalb schreibe ich höflich, nicht laut." },
  { id:"b1feel17", de:"sich freuen auf", art:"", pl:"hat sich gefreut", en:"to look forward to", topic:"feelings", level:"b1", ex:"Ich freue mich auf Ihre Antwort und auf den neuen Termin." },
  { id:"b1feel18", de:"sich freuen über", art:"", pl:"hat sich gefreut", en:"to be glad about (past/present fact)", topic:"feelings", level:"b1", ex:"Ich habe mich über die Zusage sehr gefreut." },
  { id:"b1feel19", de:"sich schämen", art:"", pl:"hat sich geschämt", en:"to be ashamed / embarrassed", topic:"feelings", level:"b1", ex:"Ich schäme mich nicht, nachzufragen, wenn ich das Formular nicht verstehe." },
  { id:"b1feel20", de:"sich Sorgen machen", art:"", pl:"hat sich Sorgen gemacht", en:"to worry", topic:"feelings", level:"b1", ex:"Ich mache mir Sorgen um die Kinder, wenn die Wohnung so kalt bleibt." },
  { id:"b1feel21", de:"sich langweilen", art:"", pl:"hat sich gelangweilt", en:"to be bored", topic:"feelings", level:"b1", ex:"Im Kurs langweile ich mich nicht — wir schreiben echte Briefe." },
  { id:"b1feel22", de:"sich entspannen", art:"", pl:"hat sich entspannt", en:"to relax", topic:"feelings", level:"b1", ex:"Am Wochenende entspanne ich im Park, sonst halte ich die Woche nicht durch." },
  { id:"b1feel23", de:"zufrieden sein", art:"", pl:"ist zufrieden gewesen", en:"to be satisfied", topic:"feelings", level:"b1", ex:"Mit der Lösung bin ich zufrieden, auch wenn sie nicht perfekt ist." },
  { id:"b1feel24", de:"enttäuscht sein", art:"", pl:"ist enttäuscht gewesen", en:"to be disappointed", topic:"feelings", level:"b1", ex:"Ich bin enttäuscht, dass niemand zurückgerufen hat." },
  { id:"b1feel25", de:"nervös", art:"", pl:"", en:"nervous", topic:"feelings", level:"b1", ex:"Vor dem Sprechen bin ich nervös, deshalb atme ich und starte mit dem Chunk." },
  { id:"b1feel26", de:"ruhig", art:"", pl:"", en:"calm / quiet", topic:"feelings", level:"b1", ex:"Bleiben Sie ruhig am Schalter, auch wenn die Nummer lange dauert." },
  { id:"b1feel27", de:"glücklich", art:"", pl:"", en:"happy", topic:"feelings", level:"b1", ex:"Ich bin glücklich über die Wohnung, trotz der kleinen Küche." },
  { id:"b1feel28", de:"traurig", art:"", pl:"", en:"sad", topic:"feelings", level:"b1", ex:"Die Kinder sind traurig, weil der Ausflug ausgefallen ist." },
  { id:"b1feel29", de:"wütend", art:"", pl:"", en:"angry", topic:"feelings", level:"b1", ex:"Ich war wütend, habe den Brief aber erst nach einer Nacht geschrieben." },
  { id:"b1feel30", de:"überrascht", art:"", pl:"", en:"surprised", topic:"feelings", level:"b1", ex:"Ich war überrascht, dass der Kurs schon voll war." },

  { id:"b1body1", de:"Kopf", art:"der", pl:"Köpfe", en:"head", topic:"body", level:"b1", ex:"Ich habe Kopfschmerzen, ich komme trotzdem — oder ich melde mich krank." },
  { id:"b1body2", de:"Kopfschmerzen", art:"die", pl:"", en:"headache", topic:"body", level:"b1", ex:"Bei starken Kopfschmerzen hole ich eine AU, ich arbeite nicht weiter." },
  { id:"b1body3", de:"Rücken", art:"der", pl:"", en:"back", topic:"body", level:"b1", ex:"Mein Rücken tut weh vom Stehen an der Kasse, ich brauche einen anderen Job." },
  { id:"b1body4", de:"Bauch", art:"der", pl:"Bäuche", en:"stomach / belly", topic:"body", level:"b1", ex:"Die Kinder haben Bauchschmerzen, wir bleiben heute zu Hause." },
  { id:"b1body5", de:"Hals", art:"der", pl:"Hälse", en:"throat / neck", topic:"body", level:"b1", ex:"Ich habe Halsschmerzen und Fieber, die Praxis gibt mir eine AU." },
  { id:"b1body6", de:"Halsentzündung", art:"die", pl:"-en", en:"sore throat / tonsillitis", topic:"body", level:"b1", ex:"Wegen der Halsentzündung darf ich nicht in die Kita." },
  { id:"b1body7", de:"Auge", art:"das", pl:"-n", en:"eye", topic:"body", level:"b1", ex:"Ich brauche eine Brille, die Augen werden beim Lernen müde." },
  { id:"b1body8", de:"Ohr", art:"das", pl:"Ohren", en:"ear", topic:"body", level:"b1", ex:"Das Kind hört auf dem linken Ohr schlecht, wir brauchen einen Termin beim HNO." },
  { id:"b1body9", de:"Zahn", art:"der", pl:"Zähne", en:"tooth", topic:"body", level:"b1", ex:"Zahnschmerzen: Notdienst am Wochenende, die normale Praxis ist zu." },
  { id:"b1body10", de:"Zahnarzt", art:"der", pl:"Zahnärzte", en:"dentist", topic:"body", level:"b1", ex:"Der Zahnarzt hat erst in drei Wochen einen Termin, außer Schmerzfall." },
  { id:"b1body11", de:"Herz", art:"das", pl:"-en", en:"heart", topic:"body", level:"b1", ex:"Bei Herzproblemen rufe ich 112, ich warte nicht auf den Hausarzt." },
  { id:"b1body12", de:"Blut", art:"das", pl:"", en:"blood", topic:"body", level:"b1", ex:"Ich muss Blut abgeben, nüchtern, um 7 Uhr im Labor." },
  { id:"b1body13", de:"Fieber", art:"das", pl:"", en:"fever", topic:"body", level:"b1", ex:"Über 38,5 Grad Fieber: Kind bleibt zu Hause, Kita-Regeln." },
  { id:"b1body14", de:"Husten", art:"der", pl:"", en:"cough", topic:"body", level:"b1", ex:"Der Husten stört nachts, ich hole Hustensaft in der Apotheke." },
  { id:"b1body15", de:"Schnupfen", art:"der", pl:"", en:"cold (runny nose)", topic:"body", level:"b1", ex:"Nur Schnupfen ohne Fieber — trotzdem Abstand im Kurs." },
  { id:"b1body16", de:"Allergie", art:"die", pl:"-n", en:"allergy", topic:"body", level:"b1", ex:"Ich habe eine Allergie gegen Penicillin, das steht auf dem Ausweis." },
  { id:"b1body17", de:"Arm", art:"der", pl:"-e", en:"arm", topic:"body", level:"b1", ex:"Ich kann den Arm nicht heben, nach dem Sturz auf der Treppe." },
  { id:"b1body18", de:"Bein", art:"das", pl:"-e", en:"leg", topic:"body", level:"b1", ex:"Mit dem verletzten Bein komme ich nicht in den zweiten Stock ohne Aufzug." },
  { id:"b1body19", de:"Knie", art:"das", pl:"", en:"knee", topic:"body", level:"b1", ex:"Das Knie ist dick, ich brauche eine Krankengymnastik-Verordnung." },
  { id:"b1body20", de:"Fuß", art:"der", pl:"Füße", en:"foot", topic:"body", level:"b1", ex:"Ich habe mir den Fuß verdreht, auf der Arbeit, Unfallanzeige." },
  { id:"b1body21", de:"Hand", art:"die", pl:"Hände", en:"hand", topic:"body", level:"b1", ex:"Ich kann mit der rechten Hand nicht schreiben, die Prüfung braucht Zeitausgleich." },
  { id:"b1body22", de:"Finger", art:"der", pl:"", en:"finger", topic:"body", level:"b1", ex:"Ein Finger ist gebrochen, die Schiene bleibt drei Wochen." },
  { id:"b1body23", de:"Haut", art:"die", pl:"Häute", en:"skin", topic:"body", level:"b1", ex:"Die Haut juckt seit dem neuen Waschmittel, ich wechsle das Produkt." },
  { id:"b1body24", de:"Knochen", art:"der", pl:"", en:"bone", topic:"body", level:"b1", ex:"Kein Knochenbruch, nur eine Prellung, sagt das Röntgen." },
  { id:"b1body25", de:"nüchtern", art:"", pl:"", en:"fasting (no food before a test)", topic:"body", level:"b1", ex:"Bitte nüchtern kommen, nur Wasser, steht auf dem Laborzettel." },

  { id:"b1cl1", de:"Kleidung", art:"die", pl:"-en", en:"clothing", topic:"clothing", level:"b1", ex:"Für das Vorstellungsgespräch brauche ich ordentliche Kleidung, kein Hoodie." },
  { id:"b1cl2", de:"Jacke", art:"die", pl:"-n", en:"jacket", topic:"clothing", level:"b1", ex:"Ich habe die Jacke in der Bahn liegen lassen, Fundsachen am Hauptbahnhof." },
  { id:"b1cl3", de:"Mantel", art:"der", pl:"Mäntel", en:"coat", topic:"clothing", level:"b1", ex:"Im Fundbüro liegt ein schwarzer Mantel, ist das Ihrer?" },
  { id:"b1cl4", de:"Hose", art:"die", pl:"-n", en:"trousers", topic:"clothing", level:"b1", ex:"Die Hose aus der Wäscherei ist eingelaufen, ich reklamiere." },
  { id:"b1cl5", de:"Rock", art:"der", pl:"Röcke", en:"skirt", topic:"clothing", level:"b1", ex:"Für die Prüfung ist ein Rock egal — wichtig sind der Ausweis und der Stift." },
  { id:"b1cl6", de:"Kleid", art:"das", pl:"-er", en:"dress", topic:"clothing", level:"b1", ex:"Das Kleid war zu klein, ich habe es umgetauscht mit Kassenbon." },
  { id:"b1cl7", de:"Pullover", art:"der", pl:"", en:"sweater", topic:"clothing", level:"b1", ex:"In der Wohnung sind 16 Grad, wir sitzen mit Pullover am Tisch." },
  { id:"b1cl8", de:"T-Shirt", art:"das", pl:"-s", en:"T-shirt", topic:"clothing", level:"b1", ex:"Bitte kein bedrucktes T-Shirt auf dem Passfoto, sagt das Amt." },
  { id:"b1cl9", de:"Hemd", art:"das", pl:"-en", en:"shirt", topic:"clothing", level:"b1", ex:"Ein Hemd reicht für das Gespräch, kein Anzug nötig in dieser Firma." },
  { id:"b1cl10", de:"Schuhe", art:"die", pl:"", en:"shoes", topic:"clothing", level:"b1", ex:"Die Schuhe sind nach zwei Wochen kaputt, Garantie im Laden." },
  { id:"b1cl11", de:"Stiefel", art:"der", pl:"", en:"boot(s)", topic:"clothing", level:"b1", ex:"Bei Schnee brauche ich Stiefel, sonst komme ich nicht zur Haltestelle." },
  { id:"b1cl12", de:"Socken", art:"die", pl:"", en:"socks", topic:"clothing", level:"b1", ex:"Warme Socken helfen nicht, wenn die Heizung zwei Wochen tot ist." },
  { id:"b1cl13", de:"Unterwäsche", art:"die", pl:"", en:"underwear", topic:"clothing", level:"b1", ex:"Im Waschkeller fehlt ein Beutel Unterwäsche, ich hänge einen Zettel auf." },
  { id:"b1cl14", de:"Mütze", art:"die", pl:"-n", en:"hat / beanie", topic:"clothing", level:"b1", ex:"Kind ohne Mütze im Winter — die Erzieherin hat uns geschrieben." },
  { id:"b1cl15", de:"Schal", art:"der", pl:"-s / Schals", en:"scarf", topic:"clothing", level:"b1", ex:"Den Schal habe ich im Kurs liegen lassen, die Dozentin hat ihn." },
  { id:"b1cl16", de:"Handschuhe", art:"die", pl:"", en:"gloves", topic:"clothing", level:"b1", ex:"Ohne Handschuhe kann ich den Briefkasten im Januar kaum öffnen." },
  { id:"b1cl17", de:"Brille", art:"die", pl:"-n", en:"glasses", topic:"clothing", level:"b1", ex:"Ohne Brille kann ich die Lesetexte nicht schaffen, ich beantrage Zeit." },
  { id:"b1cl18", de:"Tasche", art:"die", pl:"-n", en:"bag", topic:"clothing", level:"b1", ex:"In der Tasche: Ausweis, Einladung, Stifte, Wasser — mehr braucht die Prüfung nicht." },
  { id:"b1cl19", de:"Größe", art:"die", pl:"-n", en:"size", topic:"clothing", level:"b1", ex:"Größe 40 ist zu klein, ich tausche um, der Bon ist noch da." },
  { id:"b1cl20", de:"umtauschen", art:"", pl:"hat umgetauscht", en:"to exchange (goods)", topic:"clothing", level:"b1", ex:"Kann ich die Hose umtauschen? Ich habe den Kassenbon." },
  { id:"b1cl21", de:"Kassenbon", art:"der", pl:"-s", en:"till receipt", topic:"clothing", level:"b1", ex:"Ohne Kassenbon kein Umtausch, das steht an der Kasse." },
  { id:"b1cl22", de:"Mode", art:"die", pl:"-n", en:"fashion", topic:"clothing", level:"b1", ex:"Mode ist mir egal, ich brauche etwas Waschbares für die Schicht." },

  { id:"b1let1", de:"Sehr geehrte Damen und Herren", art:"", pl:"", en:"Dear Sir or Madam", topic:"letters", level:"b1", ex:"Sehr geehrte Damen und Herren, ich schreibe wegen der Heizung." },
  { id:"b1let2", de:"Sehr geehrte Frau … / Sehr geehrter Herr …", art:"", pl:"", en:"Dear Ms / Mr …", topic:"letters", level:"b1", ex:"Sehr geehrte Frau Berg, vielen Dank für Ihr Schreiben vom 3. Mai." },
  { id:"b1let3", de:"Liebe / Lieber …", art:"", pl:"", en:"Dear … (informal)", topic:"letters", level:"b1", ex:"Liebe Anna, danke für deine Nachricht, leider kann ich am Samstag nicht." },
  { id:"b1let4", de:"Mit freundlichen Grüßen", art:"", pl:"", en:"Yours sincerely", topic:"letters", level:"b1", ex:"Mit freundlichen Grüßen plus Vor- und Nachname, keine Küsse ans Amt." },
  { id:"b1let5", de:"Viele Grüße", art:"", pl:"", en:"Best wishes (informal)", topic:"letters", level:"b1", ex:"Viele Grüße, Mustafa — das reicht an Freunde, nicht an die Bank." },
  { id:"b1let6", de:"ich schreibe Ihnen, weil", art:"", pl:"", en:"I am writing to you because", topic:"letters", level:"b1", ex:"Ich schreibe Ihnen, weil die Heizung seit Montag nicht funktioniert." },
  { id:"b1let7", de:"vielen Dank im Voraus", art:"", pl:"", en:"thank you in advance", topic:"letters", level:"b1", ex:"Vielen Dank im Voraus für Ihre Mühe." },
  { id:"b1let8", de:"ich freue mich auf Ihre Antwort", art:"", pl:"", en:"I look forward to your reply", topic:"letters", level:"b1", ex:"Ich freue mich auf Ihre baldige Antwort." },
  { id:"b1let9", de:"ich bitte um Verständnis", art:"", pl:"", en:"I ask for your understanding", topic:"letters", level:"b1", ex:"Ich bitte um Verständnis und um eine kurze Rückmeldung." },
  { id:"b1let10", de:"ich wäre Ihnen dankbar, wenn", art:"", pl:"", en:"I would be grateful if", topic:"letters", level:"b1", ex:"Ich wäre Ihnen dankbar, wenn Sie den Termin schriftlich bestätigen könnten." },
  { id:"b1let11", de:"hiermit kündige ich", art:"", pl:"", en:"I hereby give notice", topic:"letters", level:"b1", ex:"Hiermit kündige ich den Vertrag zum 30. Juni." },
  { id:"b1let12", de:"in der Anlage", art:"", pl:"", en:"enclosed / attached", topic:"letters", level:"b1", ex:"In der Anlage sende ich den Mietvertrag und die Fotos der Schimmelstelle." },
  { id:"b1let13", de:"Bezug nehmend auf", art:"", pl:"", en:"with reference to", topic:"letters", level:"b1", ex:"Bezug nehmend auf Ihr Schreiben vom 12. März teile ich Ihnen mit, …" },
  { id:"b1let14", de:"ich möchte mich beschweren über", art:"", pl:"", en:"I would like to complain about", topic:"letters", level:"b1", ex:"Ich möchte mich über den Lärm nach 22 Uhr beschweren." },
  { id:"b1let15", de:"bitte teilen Sie mir mit, ob", art:"", pl:"", en:"please let me know whether", topic:"letters", level:"b1", ex:"Bitte teilen Sie mir mit, ob der Termin noch frei ist." },
  { id:"b1let16", de:"für Rückfragen stehe ich gerne zur Verfügung", art:"", pl:"", en:"I am happy to answer further questions", topic:"letters", level:"b1", ex:"Für Rückfragen stehe ich Ihnen gerne telefonisch zur Verfügung." },
  { id:"b1let17", de:"leider muss ich absagen", art:"", pl:"", en:"unfortunately I have to cancel", topic:"letters", level:"b1", ex:"Leider muss ich den Termin am Freitag absagen, ich bin krank." },
  { id:"b1let18", de:"könnten Sie mir bitte …?", art:"", pl:"", en:"could you please …?", topic:"letters", level:"b1", ex:"Könnten Sie mir bitte einen neuen Termin nach 16 Uhr nennen?" },
  { id:"b1let19", de:"ich bestätige hiermit", art:"", pl:"", en:"I hereby confirm", topic:"letters", level:"b1", ex:"Ich bestätige hiermit den Termin am 3. Mai um 9 Uhr." },
  { id:"b1let20", de:"Betreff", art:"der", pl:"-e", en:"subject line", topic:"letters", level:"b1", ex:"Betreff: Kündigung Mietvertrag, Wohnung 12, zum 30.06." },

  { id:"b1pv1", de:"warten auf", art:"", pl:"hat gewartet", en:"to wait for", topic:"verbs", level:"b1", ex:"Ich warte auf den Bescheid. Ich warte darauf." },
  { id:"b1pv2", de:"sich bewerben um", art:"", pl:"hat sich beworben", en:"to apply for", topic:"verbs", level:"b1", ex:"Ich bewerbe mich um die Stelle. Ich bewerbe mich darum." },
  { id:"b1pv3", de:"sich interessieren für", art:"", pl:"hat sich interessiert", en:"to be interested in", topic:"verbs", level:"b1", ex:"Ich interessiere mich für den Kurs. Ich interessiere mich dafür." },
  { id:"b1pv4", de:"sich beschweren über", art:"", pl:"hat sich beschwert", en:"to complain about", topic:"verbs", level:"b1", ex:"Wir beschweren uns über den Lärm. Wir beschweren uns darüber." },
  { id:"b1pv5", de:"sich erinnern an", art:"", pl:"hat sich erinnert", en:"to remember", topic:"verbs", level:"b1", ex:"Erinnern Sie sich an den Termin? Erinnern Sie sich daran?" },
  { id:"b1pv6", de:"denken an", art:"", pl:"hat gedacht", en:"to think of / about", topic:"verbs", level:"b1", ex:"Ich denke oft an die Prüfung. Ich denke oft daran." },
  { id:"b1pv7", de:"teilnehmen an", art:"", pl:"hat teilgenommen", en:"to take part in", topic:"verbs", level:"b1", ex:"Ich möchte am Kurs teilnehmen. Ich möchte daran teilnehmen." },
  { id:"b1pv8", de:"sich gewöhnen an", art:"", pl:"hat sich gewöhnt", en:"to get used to", topic:"verbs", level:"b1", ex:"Ich gewöhne mich an die Schicht. Ich gewöhne mich daran." },
  { id:"b1pv9", de:"Angst haben vor", art:"", pl:"hat Angst gehabt", en:"to be afraid of", topic:"verbs", level:"b1", ex:"Ich habe Angst vor dem Sprechen. Ich habe Angst davor." },
  { id:"b1pv10", de:"sich kümmern um", art:"", pl:"hat sich gekümmert", en:"to take care of / deal with", topic:"verbs", level:"b1", ex:"Ich kümmere mich um die Unterlagen. Ich kümmere mich darum." },
  { id:"b1pv11", de:"sich verlassen auf", art:"", pl:"hat sich verlassen", en:"to rely on", topic:"verbs", level:"b1", ex:"Ich verlasse mich auf Ihre Zusage. Ich verlasse mich darauf." },
  { id:"b1pv12", de:"bestehen auf", art:"", pl:"hat bestanden", en:"to insist on", topic:"verbs", level:"b1", ex:"Ich bestehe auf einer schriftlichen Bestätigung. Ich bestehe darauf." },
  { id:"b1pv13", de:"abhängen von", art:"", pl:"hat abgehangen", en:"to depend on", topic:"verbs", level:"b1", ex:"Das hängt vom Wetter ab. Das hängt davon ab." },
  { id:"b1pv14", de:"sich anmelden zu / für", art:"", pl:"hat sich angemeldet", en:"to register for", topic:"verbs", level:"b1", ex:"Ich habe mich für den Kurs angemeldet. Ich habe mich dafür angemeldet." },
  { id:"b1pv15", de:"bitten um", art:"", pl:"hat gebeten", en:"to ask for", topic:"verbs", level:"b1", ex:"Ich bitte um eine Rückmeldung. Ich bitte darum." },
]
};
