export default {
  vocab: [
  // people
  { id:"v1", de:"Mensch", art:"der", pl:"-en", en:"human / person", topic:"people", level:"b1" , ex:"Das ist der Mensch.", exEn:"This is human / person."},
  { id:"v2", de:"Name", art:"der", pl:"-n", en:"name", topic:"people", level:"a2" , ex:"Das ist der Name.", exEn:"This is name."},
  { id:"v3", de:"Vorname", art:"der", pl:"-n", en:"first name", topic:"people", level:"a2" , ex:"Das ist der Vorname.", exEn:"This is first name."},
  { id:"v4", de:"Nachname", art:"der", pl:"-n", en:"surname", topic:"people", level:"a2" , ex:"Das ist der Nachname.", exEn:"This is surname."},
  { id:"v5", de:"Adresse", art:"die", pl:"-n", en:"address", topic:"people", level:"a2" , ex:"Das ist die Adresse.", exEn:"This is address."},
  { id:"v6", de:"Geburtstag", art:"der", pl:"-e", en:"birthday", topic:"people", level:"a2" , ex:"Das ist der Geburtstag.", exEn:"This is birthday."},
  { id:"v7", de:"Familie", art:"die", pl:"-n", en:"family", topic:"people", level:"a2" , ex:"Das ist die Familie.", exEn:"This is family."},
  { id:"v8", de:"Eltern", art:"die", pl:"", en:"parents", topic:"people", level:"a2" , ex:"Hier sind die Eltern.", exEn:"Here are the parents."},
  { id:"v9", de:"Vater", art:"der", pl:"Väter", en:"father", topic:"people", level:"a2" , ex:"Das ist der Vater.", exEn:"This is father."},
  { id:"v10", de:"Mutter", art:"die", pl:"Mütter", en:"mother", topic:"people", level:"a2" , ex:"Das ist die Mutter.", exEn:"This is mother."},
  { id:"v11", de:"Kind", art:"das", pl:"-er", en:"child", topic:"people", level:"a2" , ex:"Das ist das Kind.", exEn:"This is child."},
  { id:"v12", de:"Sohn", art:"der", pl:"Söhne", en:"son", topic:"people", level:"a2" , ex:"Das ist der Sohn.", exEn:"This is son."},
  { id:"v13", de:"Tochter", art:"die", pl:"Töchter", en:"daughter", topic:"people", level:"a2" , ex:"Das ist die Tochter.", exEn:"This is daughter."},
  { id:"v14", de:"Bruder", art:"der", pl:"Brüder", en:"brother", topic:"people", level:"a2" , ex:"Das ist der Bruder.", exEn:"This is brother."},
  { id:"v15", de:"Schwester", art:"die", pl:"-n", en:"sister", topic:"people", level:"a2" , ex:"Das ist die Schwester.", exEn:"This is sister."},
  { id:"v16", de:"Freund", art:"der", pl:"-e", en:"friend / boyfriend", topic:"people", level:"a2" , ex:"Das ist der Freund.", exEn:"This is friend / boyfriend."},
  { id:"v17", de:"Freundin", art:"die", pl:"-nen", en:"friend / girlfriend", topic:"people", level:"a2" , ex:"Das ist die Freundin.", exEn:"This is friend / girlfriend."},
  { id:"v18", de:"Nachbar", art:"der", pl:"-n", en:"neighbour", topic:"people", level:"a2" , ex:"Das ist der Nachbar.", exEn:"This is neighbour."},
  { id:"v19", de:"Kollege", art:"der", pl:"-n", en:"colleague", topic:"people", level:"b1" , ex:"Das ist der Kollege.", exEn:"This is colleague."},
  { id:"v20", de:"Beziehung", art:"die", pl:"-en", en:"relationship", topic:"people", level:"b1" , ex:"Das ist die Beziehung.", exEn:"This is relationship."},
  { id:"v21", de:"Hochzeit", art:"die", pl:"-en", en:"wedding", topic:"people", level:"b1" , ex:"Das ist die Hochzeit.", exEn:"This is wedding."},
  { id:"v22", de:"Nationalität", art:"die", pl:"-en", en:"nationality", topic:"people", level:"b1" , ex:"Das ist die Nationalität.", exEn:"This is nationality."},
  { id:"v23", de:"Ausweis", art:"der", pl:"-e", en:"ID card", topic:"people", level:"b1" , ex:"Das ist der Ausweis.", exEn:"This is ID card."},
  { id:"v24", de:"Pass", art:"der", pl:"Pässe", en:"passport", topic:"people", level:"b1" , ex:"Das ist der Pass.", exEn:"This is passport."},
  { id:"v25", de:"Herkunft", art:"die", pl:"", en:"origin", topic:"people", level:"b1" , ex:"Das ist die Herkunft.", exEn:"This is origin."},
  { id:"v26", de:"Wohnort", art:"der", pl:"-e", en:"place of residence", topic:"people", level:"b1" , ex:"Das ist der Wohnort.", exEn:"This is place of residence."},
  { id:"v27", de:"Vertrauen", art:"das", pl:"", en:"trust", topic:"people", level:"b2" , ex:"Das ist das Vertrauen.", exEn:"This is trust."},
  { id:"v28", de:"Vorurteil", art:"das", pl:"-e", en:"prejudice", topic:"people", level:"b2" , ex:"Das ist das Vorurteil.", exEn:"This is prejudice."},
  { id:"v29", de:"Identität", art:"die", pl:"-en", en:"identity", topic:"people", level:"b2" , ex:"Das ist die Identität.", exEn:"This is identity."},
  { id:"v30", de:"Generation", art:"die", pl:"-en", en:"generation", topic:"people", level:"b2" , ex:"Das ist die Generation.", exEn:"This is generation."},

  // home
  { id:"h1", de:"Wohnung", art:"die", pl:"-en", en:"apartment", topic:"home", level:"a2" , ex:"Wo ist die Wohnung?", exEn:"Where is the apartment?"},
  { id:"h2", de:"Haus", art:"das", pl:"Häuser", en:"house", topic:"home", level:"a2" , ex:"Wo ist das Haus?", exEn:"Where is the house?"},
  { id:"h3", de:"Zimmer", art:"das", pl:"-", en:"room", topic:"home", level:"a2" , ex:"Wo ist das Zimmer?", exEn:"Where is the room?"},
  { id:"h4", de:"Küche", art:"die", pl:"-n", en:"kitchen", topic:"home", level:"a2" , ex:"Wo ist die Küche?", exEn:"Where is the kitchen?"},
  { id:"h5", de:"Badezimmer", art:"das", pl:"-", en:"bathroom", topic:"home", level:"a2" , ex:"Wo ist das Badezimmer?", exEn:"Where is the bathroom?"},
  { id:"h6", de:"Miete", art:"die", pl:"-n", en:"rent", topic:"home", level:"b1" , ex:"Wo ist die Miete?", exEn:"Where is the rent?"},
  { id:"h7", de:"Nebenkosten", art:"die", pl:"", en:"utilities", topic:"home", level:"b1" , ex:"Hier sind die Nebenkosten.", exEn:"Here are the utilities."},
  { id:"h8", de:"Kaution", art:"die", pl:"-en", en:"deposit", topic:"home", level:"b1" , ex:"Wo ist die Kaution?", exEn:"Where is the deposit?"},
  { id:"h9", de:"Vermieter", art:"der", pl:"-", en:"landlord", topic:"home", level:"b1" , ex:"Wo ist der Vermieter?", exEn:"Where is the landlord?"},
  { id:"h10", de:"Mieter", art:"der", pl:"-", en:"tenant", topic:"home", level:"b1" , ex:"Wo ist der Mieter?", exEn:"Where is the tenant?"},
  { id:"h11", de:"Mietvertrag", art:"der", pl:"Mietverträge", en:"rental contract", topic:"home", level:"b1" , ex:"Wo ist der Mietvertrag?", exEn:"Where is the rental contract?"},
  { id:"h12", de:"Heizung", art:"die", pl:"-en", en:"heating", topic:"home", level:"b1" , ex:"Wo ist die Heizung?", exEn:"Where is the heating?"},
  { id:"h13", de:"Umzug", art:"der", pl:"Umzüge", en:"house move", topic:"home", level:"b1" , ex:"Wo ist der Umzug?", exEn:"Where is the house move?"},
  { id:"h14", de:"Möbel", art:"die", pl:"", en:"furniture", topic:"home", level:"a2" , ex:"Hier sind die Möbel.", exEn:"Here are the furniture."},
  { id:"h15", de:"Schrank", art:"der", pl:"Schränke", en:"cupboard", topic:"home", level:"a2" , ex:"Wo ist der Schrank?", exEn:"Where is the cupboard?"},
  { id:"h16", de:"Kühlschrank", art:"der", pl:"Kühlschränke", en:"fridge", topic:"home", level:"a2" , ex:"Wo ist der Kühlschrank?", exEn:"Where is the fridge?"},
  { id:"h17", de:"Nachbarschaft", art:"die", pl:"-en", en:"neighbourhood", topic:"home", level:"b1" , ex:"Wo ist die Nachbarschaft?", exEn:"Where is the neighbourhood?"},
  { id:"h18", de:"Lage", art:"die", pl:"-n", en:"location", topic:"home", level:"b1" , ex:"Wo ist die Lage?", exEn:"Where is the location?"},
  { id:"h19", de:"Lärm", art:"der", pl:"", en:"noise", topic:"home", level:"b1" , ex:"Wo ist der Lärm?", exEn:"Where is the noise?"},
  { id:"h20", de:"Reparatur", art:"die", pl:"-en", en:"repair", topic:"home", level:"b1" , ex:"Wo ist die Reparatur?", exEn:"Where is the repair?"},
  { id:"h21", de:"Kündigung", art:"die", pl:"-en", en:"notice (terminate)", topic:"home", level:"b1" , ex:"Wo ist die Kündigung?", exEn:"Where is the notice (terminate)?"},
  { id:"h22", de:"Wohnfläche", art:"die", pl:"-n", en:"living space", topic:"home", level:"b2" , ex:"Wo ist die Wohnfläche?", exEn:"Where is the living space?"},
  { id:"h23", de:"Wohnungsnot", art:"die", pl:"", en:"housing shortage", topic:"home", level:"b2" , ex:"Wo ist die Wohnungsnot?", exEn:"Where is the housing shortage?"},
  { id:"h24", de:"Eigentum", art:"das", pl:"", en:"property / ownership", topic:"home", level:"b2" , ex:"Wo ist das Eigentum?", exEn:"Where is the property / ownership?"},
  { id:"h25", de:"Sanierung", art:"die", pl:"-en", en:"renovation (major)", topic:"home", level:"b2" , ex:"Wo ist die Sanierung?", exEn:"Where is the renovation (major)?"},

  // daily
  { id:"d1", de:"Alltag", art:"der", pl:"", en:"everyday life", topic:"daily", level:"b1" , ex:"Heute geht es um den Alltag.", exEn:"Today it is about the everyday life."},
  { id:"d2", de:"Termin", art:"der", pl:"-e", en:"appointment", topic:"daily", level:"a2" , ex:"Heute geht es um den Termin.", exEn:"Today it is about the appointment."},
  { id:"d3", de:"Uhrzeit", art:"die", pl:"-en", en:"time of day", topic:"daily", level:"a2" , ex:"Heute geht es um die Uhrzeit.", exEn:"Today it is about the time of day."},
  { id:"d4", de:"Pause", art:"die", pl:"-n", en:"break", topic:"daily", level:"a2" , ex:"Heute geht es um die Pause.", exEn:"Today it is about the break."},
  { id:"d5", de:"Freizeit", art:"die", pl:"", en:"free time", topic:"daily", level:"a2" , ex:"Heute geht es um die Freizeit.", exEn:"Today it is about the free time."},
  { id:"d6", de:"Wochenende", art:"das", pl:"-n", en:"weekend", topic:"daily", level:"a2" , ex:"Heute geht es um das Wochenende.", exEn:"Today it is about the weekend."},
  { id:"d7", de:"Feiertag", art:"der", pl:"-e", en:"public holiday", topic:"daily", level:"b1" , ex:"Heute geht es um den Feiertag.", exEn:"Today it is about the public holiday."},
  { id:"d8", de:"Verspätung", art:"die", pl:"-en", en:"delay", topic:"daily", level:"b1" , ex:"Heute geht es um die Verspätung.", exEn:"Today it is about the delay."},
  { id:"d9", de:"Gewohnheit", art:"die", pl:"-en", en:"habit", topic:"daily", level:"b1" , ex:"Heute geht es um die Gewohnheit.", exEn:"Today it is about the habit."},
  { id:"d10", de:"Stress", art:"der", pl:"", en:"stress", topic:"daily", level:"b1" , ex:"Heute geht es um den Stress.", exEn:"Today it is about the stress."},
  { id:"d11", de:"Routine", art:"die", pl:"-n", en:"routine", topic:"daily", level:"b1" , ex:"Heute geht es um die Routine.", exEn:"Today it is about the routine."},
  { id:"d12", de:"Haushaltsarbeit", art:"die", pl:"-en", en:"housework", topic:"daily", level:"b1" , ex:"Heute geht es um die Haushaltsarbeit.", exEn:"Today it is about the housework."},
  { id:"d13", de:"Zeitdruck", art:"der", pl:"", en:"time pressure", topic:"daily", level:"b2" , ex:"Heute geht es um den Zeitdruck.", exEn:"Today it is about the time pressure."},
  { id:"d14", de:"Work-Life-Balance", art:"die", pl:"", en:"work-life balance", topic:"daily", level:"b2" , ex:"Heute geht es um die Work-Life-Balance.", exEn:"Today it is about the work-life balance."},
  { id:"d15", de:"Erholung", art:"die", pl:"-en", en:"recovery / rest", topic:"daily", level:"b2" , ex:"Heute geht es um die Erholung.", exEn:"Today it is about the recovery / rest."},

  // food
  { id:"f1", de:"Mahlzeit", art:"die", pl:"-en", en:"meal", topic:"food", level:"b1" , ex:"Ich kaufe die Mahlzeit.", exEn:"I am buying the meal."},
  { id:"f2", de:"Frühstück", art:"das", pl:"-e", en:"breakfast", topic:"food", level:"a2" , ex:"Ich kaufe das Frühstück.", exEn:"I am buying the breakfast."},
  { id:"f3", de:"Gemüse", art:"das", pl:"", en:"vegetables", topic:"food", level:"a2" , ex:"Ich kaufe das Gemüse.", exEn:"I am buying the vegetables."},
  { id:"f4", de:"Obst", art:"das", pl:"", en:"fruit", topic:"food", level:"a2" , ex:"Ich kaufe das Obst.", exEn:"I am buying the fruit."},
  { id:"f5", de:"Fleisch", art:"das", pl:"", en:"meat", topic:"food", level:"a2" , ex:"Ich kaufe das Fleisch.", exEn:"I am buying the meat."},
  { id:"f6", de:"Rechnung", art:"die", pl:"-en", en:"bill", topic:"food", level:"a2" , ex:"Ich kaufe die Rechnung.", exEn:"I am buying the bill."},
  { id:"f7", de:"Preis", art:"der", pl:"-e", en:"price", topic:"food", level:"a2" , ex:"Ich kaufe den Preis.", exEn:"I am buying the price."},
  { id:"f8", de:"Rabatt", art:"der", pl:"-e", en:"discount", topic:"food", level:"b1" , ex:"Ich kaufe den Rabatt.", exEn:"I am buying the discount."},
  { id:"f9", de:"Qualität", art:"die", pl:"-en", en:"quality", topic:"food", level:"b1" , ex:"Ich kaufe die Qualität.", exEn:"I am buying the quality."},
  { id:"f10", de:"Zutat", art:"die", pl:"-en", en:"ingredient", topic:"food", level:"b1" , ex:"Ich kaufe die Zutat.", exEn:"I am buying the ingredient."},
  { id:"f11", de:"Rezept", art:"das", pl:"-e", en:"recipe / prescription", topic:"food", level:"b1" , ex:"Ich kaufe das Rezept.", exEn:"I am buying the recipe / prescription."},
  { id:"f12", de:"Geschmack", art:"der", pl:"Geschmäcker", en:"taste", topic:"food", level:"b1" , ex:"Ich kaufe den Geschmack.", exEn:"I am buying the taste."},
  { id:"f13", de:"Ernährung", art:"die", pl:"-en", en:"nutrition / diet", topic:"food", level:"b1" , ex:"Ich kaufe die Ernährung.", exEn:"I am buying the nutrition / diet."},
  { id:"f14", de:"Lebensmittelverschwendung", art:"die", pl:"", en:"food waste", topic:"food", level:"b2" , ex:"Ich kaufe die Lebensmittelverschwendung.", exEn:"I am buying the food waste."},
  { id:"f15", de:"Nachhaltigkeit", art:"die", pl:"-en", en:"sustainability", topic:"food", level:"b2" , ex:"Ich kaufe die Nachhaltigkeit.", exEn:"I am buying the sustainability."},
  { id:"f16", de:"Bio-Produkt", art:"das", pl:"-e", en:"organic product", topic:"food", level:"b2" , ex:"Ich kaufe das Bio-Produkt.", exEn:"I am buying the organic product."},
  { id:"f17", de:"Supermarkt", art:"der", pl:"Supermärkte", en:"supermarket", topic:"food", level:"a2" , ex:"Ich kaufe den Supermarkt.", exEn:"I am buying the supermarket."},
  { id:"f18", de:"Kundin", art:"die", pl:"-nen", en:"customer (f)", topic:"food", level:"a2" , ex:"Ich kaufe die Kundin.", exEn:"I am buying the customer (f)."},

  // work
  { id:"w1", de:"Beruf", art:"der", pl:"-e", en:"profession", topic:"work", level:"a2" , ex:"Ich brauche den Beruf morgen.", exEn:"I need the profession tomorrow."},
  { id:"w2", de:"Stelle", art:"die", pl:"-n", en:"job / position", topic:"work", level:"b1" , ex:"Ich brauche die Stelle morgen.", exEn:"I need the job / position tomorrow."},
  { id:"w3", de:"Bewerbung", art:"die", pl:"-en", en:"application", topic:"work", level:"b1" , ex:"Ich brauche die Bewerbung morgen.", exEn:"I need the application tomorrow."},
  { id:"w4", de:"Lebenslauf", art:"der", pl:"Lebensläufe", en:"CV", topic:"work", level:"b1" , ex:"Ich brauche den Lebenslauf morgen.", exEn:"I need the CV tomorrow."},
  { id:"w5", de:"Vorstellungsgespräch", art:"das", pl:"-e", en:"job interview", topic:"work", level:"b1" , ex:"Ich brauche das Vorstellungsgespräch morgen.", exEn:"I need the job interview tomorrow."},
  { id:"w6", de:"Arbeitgeber", art:"der", pl:"-", en:"employer", topic:"work", level:"b1" , ex:"Ich brauche den Arbeitgeber morgen.", exEn:"I need the employer tomorrow."},
  { id:"w7", de:"Arbeitnehmer", art:"der", pl:"-", en:"employee", topic:"work", level:"b1" , ex:"Ich brauche den Arbeitnehmer morgen.", exEn:"I need the employee tomorrow."},
  { id:"w8", de:"Gehalt", art:"das", pl:"Gehälter", en:"salary", topic:"work", level:"b1" , ex:"Ich brauche das Gehalt morgen.", exEn:"I need the salary tomorrow."},
  { id:"w9", de:"Vertrag", art:"der", pl:"Verträge", en:"contract", topic:"work", level:"b1" , ex:"Ich brauche den Vertrag morgen.", exEn:"I need the contract tomorrow."},
  { id:"w10", de:"Ausbildung", art:"die", pl:"-en", en:"apprenticeship / training", topic:"work", level:"b1" , ex:"Ich brauche die Ausbildung morgen.", exEn:"I need the apprenticeship / training tomorrow."},
  { id:"w11", de:"Erfahrung", art:"die", pl:"-en", en:"experience", topic:"work", level:"b1" , ex:"Ich brauche die Erfahrung morgen.", exEn:"I need the experience tomorrow."},
  { id:"w12", de:"Fähigkeit", art:"die", pl:"-en", en:"ability / skill", topic:"work", level:"b1" , ex:"Ich brauche die Fähigkeit morgen.", exEn:"I need the ability / skill tomorrow."},
  { id:"w13", de:"Verantwortung", art:"die", pl:"-en", en:"responsibility", topic:"work", level:"b1" , ex:"Ich brauche die Verantwortung morgen.", exEn:"I need the responsibility tomorrow."},
  { id:"w14", de:"Kündigung", art:"die", pl:"-en", en:"dismissal / resignation", topic:"work", level:"b1" , ex:"Ich brauche die Kündigung morgen.", exEn:"I need the dismissal / resignation tomorrow."},
  { id:"w15", de:"Arbeitslosigkeit", art:"die", pl:"", en:"unemployment", topic:"work", level:"b1" , ex:"Ich brauche die Arbeitslosigkeit morgen.", exEn:"I need the unemployment tomorrow."},
  { id:"w16", de:"Praktikum", art:"das", pl:"Praktika", en:"internship", topic:"work", level:"b1" , ex:"Ich brauche das Praktikum morgen.", exEn:"I need the internship tomorrow."},
  { id:"w17", de:"Fortbildung", art:"die", pl:"-en", en:"further training", topic:"work", level:"b1" , ex:"Ich brauche die Fortbildung morgen.", exEn:"I need the further training tomorrow."},
  { id:"w18", de:"Probezeit", art:"die", pl:"-en", en:"probation period", topic:"work", level:"b1" , ex:"Ich brauche die Probezeit morgen.", exEn:"I need the probation period tomorrow."},
  { id:"w19", de:"Beförderung", art:"die", pl:"-en", en:"promotion", topic:"work", level:"b2" , ex:"Ich brauche die Beförderung morgen.", exEn:"I need the promotion tomorrow."},
  { id:"w20", de:"Tarifvertrag", art:"der", pl:"Tarifverträge", en:"collective agreement", topic:"work", level:"b2" , ex:"Ich brauche den Tarifvertrag morgen.", exEn:"I need the collective agreement tomorrow."},
  { id:"w21", de:"Work-Life-Balance", art:"die", pl:"", en:"work-life balance", topic:"work", level:"b2" , ex:"Ich brauche die Work-Life-Balance morgen.", exEn:"I need the work-life balance tomorrow."},
  { id:"w22", de:"Fachkräftemangel", art:"der", pl:"", en:"skilled labour shortage", topic:"work", level:"b2" , ex:"Ich brauche den Fachkräftemangel morgen.", exEn:"I need the skilled labour shortage tomorrow."},
  { id:"w23", de:"Selbstständigkeit", art:"die", pl:"", en:"self-employment", topic:"work", level:"b2" , ex:"Ich brauche die Selbstständigkeit morgen.", exEn:"I need the self-employment tomorrow."},
  { id:"w24", de:"Überstunden", art:"die", pl:"", en:"overtime", topic:"work", level:"b1" , ex:"Ich brauche die Überstunden morgen.", exEn:"I need the overtime tomorrow."},
  { id:"w25", de:"Abteilung", art:"die", pl:"-en", en:"department", topic:"work", level:"b1" , ex:"Ich brauche die Abteilung morgen.", exEn:"I need the department tomorrow."},

  // health
  { id:"he1", de:"Gesundheit", art:"die", pl:"", en:"health", topic:"health", level:"b1" , ex:"Ich suche die Gesundheit.", exEn:"I am looking for the health."},
  { id:"he2", de:"Krankheit", art:"die", pl:"-en", en:"illness", topic:"health", level:"a2" , ex:"Ich suche die Krankheit.", exEn:"I am looking for the illness."},
  { id:"he3", de:"Arzt", art:"der", pl:"Ärzte", en:"doctor", topic:"health", level:"a2" , ex:"Ich suche den Arzt.", exEn:"I am looking for the doctor."},
  { id:"he4", de:"Apotheke", art:"die", pl:"-n", en:"pharmacy", topic:"health", level:"a2" , ex:"Ich suche die Apotheke.", exEn:"I am looking for the pharmacy."},
  { id:"he5", de:"Medikament", art:"das", pl:"-e", en:"medicine", topic:"health", level:"b1" , ex:"Ich suche das Medikament.", exEn:"I am looking for the medicine."},
  { id:"he6", de:"Rezept", art:"das", pl:"-e", en:"prescription", topic:"health", level:"b1" , ex:"Ich suche das Rezept.", exEn:"I am looking for the prescription."},
  { id:"he7", de:"Schmerz", art:"der", pl:"-en", en:"pain", topic:"health", level:"a2" , ex:"Ich suche den Schmerz.", exEn:"I am looking for the pain."},
  { id:"he8", de:"Untersuchung", art:"die", pl:"-en", en:"examination", topic:"health", level:"b1" , ex:"Ich suche die Untersuchung.", exEn:"I am looking for the examination."},
  { id:"he9", de:"Krankenkasse", art:"die", pl:"-n", en:"health insurance fund", topic:"health", level:"b1" , ex:"Ich suche die Krankenkasse.", exEn:"I am looking for the health insurance fund."},
  { id:"he10", de:"Unfall", art:"der", pl:"Unfälle", en:"accident", topic:"health", level:"b1" , ex:"Ich suche den Unfall.", exEn:"I am looking for the accident."},
  { id:"he11", de:"Verletzung", art:"die", pl:"-en", en:"injury", topic:"health", level:"b1" , ex:"Ich suche die Verletzung.", exEn:"I am looking for the injury."},
  { id:"he12", de:"Impfung", art:"die", pl:"-en", en:"vaccination", topic:"health", level:"b1" , ex:"Ich suche die Impfung.", exEn:"I am looking for the vaccination."},
  { id:"he13", de:"Krankschreibung", art:"die", pl:"-en", en:"sick note", topic:"health", level:"b1" , ex:"Ich suche die Krankschreibung.", exEn:"I am looking for the sick note."},
  { id:"he14", de:"Prävention", art:"die", pl:"-en", en:"prevention", topic:"health", level:"b2" , ex:"Ich suche die Prävention.", exEn:"I am looking for the prevention."},
  { id:"he15", de:"Diagnose", art:"die", pl:"-n", en:"diagnosis", topic:"health", level:"b2" , ex:"Ich suche die Diagnose.", exEn:"I am looking for the diagnosis."},
  { id:"he16", de:"Behandlung", art:"die", pl:"-en", en:"treatment", topic:"health", level:"b2" , ex:"Ich suche die Behandlung.", exEn:"I am looking for the treatment."},
  { id:"he17", de:"Sucht", art:"die", pl:"Süchte", en:"addiction", topic:"health", level:"b2" , ex:"Ich suche die Sucht.", exEn:"I am looking for the addiction."},
  { id:"he18", de:"psychische Gesundheit", art:"die", pl:"", en:"mental health", topic:"health", level:"b2" , ex:"Ich suche die psychische Gesundheit.", exEn:"I am looking for the mental health."},

  // travel
  { id:"t1", de:"Reise", art:"die", pl:"-n", en:"trip", topic:"travel", level:"a2" , ex:"Wo ist die Reise?", exEn:"Where is the trip?"},
  { id:"t2", de:"Fahrkarte", art:"die", pl:"-n", en:"ticket", topic:"travel", level:"a2" , ex:"Wo ist die Fahrkarte?", exEn:"Where is the ticket?"},
  { id:"t3", de:"Bahnhof", art:"der", pl:"Bahnhöfe", en:"station", topic:"travel", level:"a2" , ex:"Wo ist der Bahnhof?", exEn:"Where is the station?"},
  { id:"t4", de:"Flugzeug", art:"das", pl:"-e", en:"plane", topic:"travel", level:"a2" , ex:"Wo ist das Flugzeug?", exEn:"Where is the plane?"},
  { id:"t5", de:"Verspätung", art:"die", pl:"-en", en:"delay", topic:"travel", level:"b1" , ex:"Wo ist die Verspätung?", exEn:"Where is the delay?"},
  { id:"t6", de:"Anschluss", art:"der", pl:"Anschlüsse", en:"connection", topic:"travel", level:"b1" , ex:"Wo ist der Anschluss?", exEn:"Where is the connection?"},
  { id:"t7", de:"Unterkunft", art:"die", pl:"Unterkünfte", en:"accommodation", topic:"travel", level:"b1" , ex:"Wo ist die Unterkunft?", exEn:"Where is the accommodation?"},
  { id:"t8", de:"Buchung", art:"die", pl:"-en", en:"booking", topic:"travel", level:"b1" , ex:"Wo ist die Buchung?", exEn:"Where is the booking?"},
  { id:"t9", de:"Gepäck", art:"das", pl:"", en:"luggage", topic:"travel", level:"b1" , ex:"Wo ist das Gepäck?", exEn:"Where is the luggage?"},
  { id:"t10", de:"Sehenswürdigkeit", art:"die", pl:"-en", en:"sight", topic:"travel", level:"b1" , ex:"Wo ist die Sehenswürdigkeit?", exEn:"Where is the sight?"},
  { id:"t11", de:"Wetter", art:"das", pl:"", en:"weather", topic:"travel", level:"a2" , ex:"Wo ist das Wetter?", exEn:"Where is the weather?"},
  { id:"t12", de:"Stau", art:"der", pl:"-s", en:"traffic jam", topic:"travel", level:"b1" , ex:"Wo ist der Stau?", exEn:"Where is the traffic jam?"},
  { id:"t13", de:"Führerschein", art:"der", pl:"-e", en:"driving licence", topic:"travel", level:"b1" , ex:"Wo ist der Führerschein?", exEn:"Where is the driving licence?"},
  { id:"t14", de:"Nachhaltiger Tourismus", art:"der", pl:"", en:"sustainable tourism", topic:"travel", level:"b2" , ex:"Wo ist der Nachhaltiger Tourismus?", exEn:"Where is the sustainable tourism?"},
  { id:"t15", de:"Fernverkehr", art:"der", pl:"", en:"long-distance transport", topic:"travel", level:"b2" , ex:"Wo ist der Fernverkehr?", exEn:"Where is the long-distance transport?"},
  { id:"t16", de:"Haltestelle", art:"die", pl:"-n", en:"stop", topic:"travel", level:"a2" , ex:"Wo ist die Haltestelle?", exEn:"Where is the stop?"},

  // school
  { id:"s1", de:"Kurs", art:"der", pl:"-e", en:"course", topic:"school", level:"a2" , ex:"Der Kurs ist wichtig.", exEn:"The course is important."},
  { id:"s2", de:"Prüfung", art:"die", pl:"-en", en:"exam", topic:"school", level:"a2" , ex:"Die Prüfung ist wichtig.", exEn:"The exam is important."},
  { id:"s3", de:"Anmeldung", art:"die", pl:"-en", en:"registration", topic:"school", level:"b1" , ex:"Die Anmeldung ist wichtig.", exEn:"The registration is important."},
  { id:"s4", de:"Gebühr", art:"die", pl:"-en", en:"fee", topic:"school", level:"b1" , ex:"Die Gebühr ist wichtig.", exEn:"The fee is important."},
  { id:"s5", de:"Wortschatz", art:"der", pl:"Wortschätze", en:"vocabulary", topic:"school", level:"b1" , ex:"Der Wortschatz ist wichtig.", exEn:"The vocabulary is important."},
  { id:"s6", de:"Grammatik", art:"die", pl:"-en", en:"grammar", topic:"school", level:"b1" , ex:"Die Grammatik ist wichtig.", exEn:"The grammar is important."},
  { id:"s7", de:"Aussprache", art:"die", pl:"-n", en:"pronunciation", topic:"school", level:"b1" , ex:"Die Aussprache ist wichtig.", exEn:"The pronunciation is important."},
  { id:"s8", de:"Niveau", art:"das", pl:"-s", en:"level", topic:"school", level:"b1" , ex:"Das Niveau ist wichtig.", exEn:"The level is important."},
  { id:"s9", de:"Abschluss", art:"der", pl:"Abschlüsse", en:"qualification", topic:"school", level:"b1" , ex:"Der Abschluss ist wichtig.", exEn:"The qualification is important."},
  { id:"s10", de:"Volkshochschule", art:"die", pl:"-n", en:"adult education centre", topic:"school", level:"b1" , ex:"Die Volkshochschule ist wichtig.", exEn:"The adult education centre is important."},
  { id:"s11", de:"Integrationskurs", art:"der", pl:"-e", en:"integration course", topic:"school", level:"b1" , ex:"Der Integrationskurs ist wichtig.", exEn:"The integration course is important."},
  { id:"s12", de:"Zertifikat", art:"das", pl:"-e", en:"certificate", topic:"school", level:"b1" , ex:"Das Zertifikat ist wichtig.", exEn:"The certificate is important."},
  { id:"s13", de:"Bildungschance", art:"die", pl:"-n", en:"educational opportunity", topic:"school", level:"b2" , ex:"Die Bildungschance ist wichtig.", exEn:"The educational opportunity is important."},
  { id:"s14", de:"Hochschulzugang", art:"der", pl:"Hochschulzugänge", en:"university entrance", topic:"school", level:"b2" , ex:"Der Hochschulzugang ist wichtig.", exEn:"The university entrance is important."},
  { id:"s15", de:"Lebenslanges Lernen", art:"das", pl:"", en:"lifelong learning", topic:"school", level:"b2" , ex:"Das Lebenslanges Lernen ist wichtig.", exEn:"The lifelong learning is important."},

  // services
  { id:"sv1", de:"Behörde", art:"die", pl:"-n", en:"authority / office", topic:"services", level:"b1" , ex:"Bitte bringen Sie die Behörde mit.", exEn:"Please bring the authority / office with you."},
  { id:"sv2", de:"Antrag", art:"der", pl:"Anträge", en:"application / form", topic:"services", level:"b1" , ex:"Bitte bringen Sie den Antrag mit.", exEn:"Please bring the application / form with you."},
  { id:"sv3", de:"Formular", art:"das", pl:"-e", en:"form", topic:"services", level:"b1" , ex:"Bitte bringen Sie das Formular mit.", exEn:"Please bring the form with you."},
  { id:"sv4", de:"Konto", art:"das", pl:"Konten", en:"account", topic:"services", level:"b1" , ex:"Bitte bringen Sie das Konto mit.", exEn:"Please bring the account with you."},
  { id:"sv5", de:"Überweisung", art:"die", pl:"-en", en:"bank transfer", topic:"services", level:"b1" , ex:"Bitte bringen Sie die Überweisung mit.", exEn:"Please bring the bank transfer with you."},
  { id:"sv6", de:"Versicherung", art:"die", pl:"-en", en:"insurance", topic:"services", level:"b1" , ex:"Bitte bringen Sie die Versicherung mit.", exEn:"Please bring the insurance with you."},
  { id:"sv7", de:"Paket", art:"das", pl:"-e", en:"parcel", topic:"services", level:"a2" , ex:"Bitte bringen Sie das Paket mit.", exEn:"Please bring the parcel with you."},
  { id:"sv8", de:"Steuer", art:"die", pl:"-n", en:"tax", topic:"services", level:"b1" , ex:"Bitte bringen Sie die Steuer mit.", exEn:"Please bring the tax with you."},
  { id:"sv9", de:"Bürgeramt", art:"das", pl:"Bürgerämter", en:"citizens' office", topic:"services", level:"b1" , ex:"Bitte bringen Sie das Bürgeramt mit.", exEn:"Please bring the citizens' office with you."},
  { id:"sv10", de:"Meldebescheinigung", art:"die", pl:"-en", en:"registration certificate", topic:"services", level:"b1" , ex:"Bitte bringen Sie die Meldebescheinigung mit.", exEn:"Please bring the registration certificate with you."},
  { id:"sv11", de:"Datenschutz", art:"der", pl:"", en:"data protection", topic:"services", level:"b2" , ex:"Bitte bringen Sie den Datenschutz mit.", exEn:"Please bring the data protection with you."},
  { id:"sv12", de:"Bürokratie", art:"die", pl:"-n", en:"bureaucracy", topic:"services", level:"b2" , ex:"Bitte bringen Sie die Bürokratie mit.", exEn:"Please bring the bureaucracy with you."},
  { id:"sv13", de:"Anspruch", art:"der", pl:"Ansprüche", en:"entitlement / claim", topic:"services", level:"b2" , ex:"Bitte bringen Sie den Anspruch mit.", exEn:"Please bring the entitlement / claim with you."},
  { id:"sv14", de:"Bescheid", art:"der", pl:"-e", en:"official notice", topic:"services", level:"b2" , ex:"Bitte bringen Sie den Bescheid mit.", exEn:"Please bring the official notice with you."},

  // opinions
  { id:"o1", de:"Meinung", art:"die", pl:"-en", en:"opinion", topic:"opinions", level:"b1" , ex:"Die Meinung ist wichtig.", exEn:"The opinion is important."},
  { id:"o2", de:"Vorschlag", art:"der", pl:"Vorschläge", en:"suggestion", topic:"opinions", level:"b1" , ex:"Der Vorschlag ist wichtig.", exEn:"The suggestion is important."},
  { id:"o3", de:"Grund", art:"der", pl:"Gründe", en:"reason", topic:"opinions", level:"b1" , ex:"Der Grund ist wichtig.", exEn:"The reason is important."},
  { id:"o4", de:"Vorteil", art:"der", pl:"-e", en:"advantage", topic:"opinions", level:"b1" , ex:"Der Vorteil ist wichtig.", exEn:"The advantage is important."},
  { id:"o5", de:"Nachteil", art:"der", pl:"-e", en:"disadvantage", topic:"opinions", level:"b1" , ex:"Der Nachteil ist wichtig.", exEn:"The disadvantage is important."},
  { id:"o6", de:"Lösung", art:"die", pl:"-en", en:"solution", topic:"opinions", level:"b1" , ex:"Die Lösung ist wichtig.", exEn:"The solution is important."},
  { id:"o7", de:"Möglichkeit", art:"die", pl:"-en", en:"possibility", topic:"opinions", level:"b1" , ex:"Die Möglichkeit ist wichtig.", exEn:"The possibility is important."},
  { id:"o8", de:"Entscheidung", art:"die", pl:"-en", en:"decision", topic:"opinions", level:"b1" , ex:"Die Entscheidung ist wichtig.", exEn:"The decision is important."},
  { id:"o9", de:"Entwicklung", art:"die", pl:"-en", en:"development", topic:"opinions", level:"b1" , ex:"Die Entwicklung ist wichtig.", exEn:"The development is important."},
  { id:"o10", de:"Unterschied", art:"der", pl:"-e", en:"difference", topic:"opinions", level:"b1" , ex:"Der Unterschied ist wichtig.", exEn:"The difference is important."},
  { id:"o11", de:"Vergleich", art:"der", pl:"-e", en:"comparison", topic:"opinions", level:"b1" , ex:"Der Vergleich ist wichtig.", exEn:"The comparison is important."},
  { id:"o12", de:"Ziel", art:"das", pl:"-e", en:"goal", topic:"opinions", level:"b1" , ex:"Das Ziel ist wichtig.", exEn:"The goal is important."},
  { id:"o13", de:"Erfolg", art:"der", pl:"-e", en:"success", topic:"opinions", level:"b1" , ex:"Der Erfolg ist wichtig.", exEn:"The success is important."},
  { id:"o14", de:"Hoffnung", art:"die", pl:"-en", en:"hope", topic:"opinions", level:"b1" , ex:"Die Hoffnung ist wichtig.", exEn:"The hope is important."},
  { id:"o15", de:"Argument", art:"das", pl:"-e", en:"argument", topic:"opinions", level:"b2" , ex:"Das Argument ist wichtig.", exEn:"The argument is important."},
  { id:"o16", de:"Standpunkt", art:"der", pl:"-e", en:"point of view", topic:"opinions", level:"b2" , ex:"Der Standpunkt ist wichtig.", exEn:"The point of view is important."},
  { id:"o17", de:"Kompromiss", art:"der", pl:"-e", en:"compromise", topic:"opinions", level:"b2" , ex:"Der Kompromiss ist wichtig.", exEn:"The compromise is important."},
  { id:"o18", de:"Auswirkung", art:"die", pl:"-en", en:"effect / impact", topic:"opinions", level:"b2" , ex:"Die Auswirkung ist wichtig.", exEn:"The effect / impact is important."},

  // media
  { id:"m1", de:"Nachricht", art:"die", pl:"-en", en:"message / news item", topic:"media", level:"b1" , ex:"Die Nachricht ist wichtig.", exEn:"The message / news item is important."},
  { id:"m2", de:"Zeitung", art:"die", pl:"-en", en:"newspaper", topic:"media", level:"a2" , ex:"Die Zeitung ist wichtig.", exEn:"The newspaper is important."},
  { id:"m3", de:"Werbung", art:"die", pl:"-en", en:"advertising", topic:"media", level:"b1" , ex:"Die Werbung ist wichtig.", exEn:"The advertising is important."},
  { id:"m4", de:"Privatsphäre", art:"die", pl:"-n", en:"privacy", topic:"media", level:"b1" , ex:"Die Privatsphäre ist wichtig.", exEn:"The privacy is important."},
  { id:"m5", de:"Umwelt", art:"die", pl:"-en", en:"environment", topic:"media", level:"b1" , ex:"Die Umwelt ist wichtig.", exEn:"The environment is important."},
  { id:"m6", de:"Klimawandel", art:"der", pl:"", en:"climate change", topic:"media", level:"b1" , ex:"Der Klimawandel ist wichtig.", exEn:"The climate change is important."},
  { id:"m7", de:"Müll", art:"der", pl:"", en:"rubbish", topic:"media", level:"b1" , ex:"Der Müll ist wichtig.", exEn:"The rubbish is important."},
  { id:"m8", de:"Abhängigkeit", art:"die", pl:"-en", en:"addiction / dependence", topic:"media", level:"b2" , ex:"Die Abhängigkeit ist wichtig.", exEn:"The addiction / dependence is important."},
  { id:"m9", de:"Meinungsfreiheit", art:"die", pl:"-en", en:"freedom of opinion", topic:"media", level:"b2" , ex:"Die Meinungsfreiheit ist wichtig.", exEn:"The freedom of opinion is important."},
  { id:"m10", de:"Desinformation", art:"die", pl:"-en", en:"disinformation", topic:"media", level:"b2" , ex:"Die Desinformation ist wichtig.", exEn:"The disinformation is important."},
  { id:"m11", de:"Öffentlichkeit", art:"die", pl:"-en", en:"the public", topic:"media", level:"b2" , ex:"Die Öffentlichkeit ist wichtig.", exEn:"The the public is important."},
  { id:"m12", de:"Verbraucher", art:"der", pl:"-", en:"consumer", topic:"media", level:"b2" , ex:"Der Verbraucher ist wichtig.", exEn:"The consumer is important."},

  // b2 abstract
  { id:"b21", de:"Gesellschaft", art:"die", pl:"-en", en:"society", topic:"b2-abstract", level:"b2" , ex:"Die Gesellschaft steht im Brief vom Amt.", exEn:"The society is in the letter from the office."},
  { id:"b22", de:"Gleichberechtigung", art:"die", pl:"-en", en:"equal rights", topic:"b2-abstract", level:"b2" , ex:"Die Gleichberechtigung steht im Brief vom Amt.", exEn:"The equal rights is in the letter from the office."},
  { id:"b23", de:"Integration", art:"die", pl:"-en", en:"integration", topic:"b2-abstract", level:"b2" , ex:"Die Integration steht im Brief vom Amt.", exEn:"The integration is in the letter from the office."},
  { id:"b24", de:"Migration", art:"die", pl:"-en", en:"migration", topic:"b2-abstract", level:"b2" , ex:"Die Migration steht im Brief vom Amt.", exEn:"The migration is in the letter from the office."},
  { id:"b25", de:"Demokratie", art:"die", pl:"-n", en:"democracy", topic:"b2-abstract", level:"b2" , ex:"Die Demokratie steht im Brief vom Amt.", exEn:"The democracy is in the letter from the office."},
  { id:"b26", de:"Wahl", art:"die", pl:"-en", en:"election / choice", topic:"b2-abstract", level:"b2" , ex:"Die Wahl steht im Brief vom Amt.", exEn:"The election / choice is in the letter from the office."},
  { id:"b27", de:"Gesetz", art:"das", pl:"-e", en:"law", topic:"b2-abstract", level:"b2" , ex:"Das Gesetz steht im Brief vom Amt.", exEn:"The law is in the letter from the office."},
  { id:"b28", de:"Recht", art:"das", pl:"-e", en:"right / law", topic:"b2-abstract", level:"b2" , ex:"Das Recht steht im Brief vom Amt.", exEn:"The right / law is in the letter from the office."},
  { id:"b29", de:"Pflicht", art:"die", pl:"-en", en:"duty", topic:"b2-abstract", level:"b1" , ex:"Die Pflicht steht im Brief vom Amt.", exEn:"The duty is in the letter from the office."},
  { id:"b210", de:"Freiheit", art:"die", pl:"-en", en:"freedom", topic:"b2-abstract", level:"b2" , ex:"Die Freiheit steht im Brief vom Amt.", exEn:"The freedom is in the letter from the office."},
  { id:"b211", de:"Gerechtigkeit", art:"die", pl:"-en", en:"justice", topic:"b2-abstract", level:"b2" , ex:"Die Gerechtigkeit steht im Brief vom Amt.", exEn:"The justice is in the letter from the office."},
  { id:"b212", de:"Forschung", art:"die", pl:"-en", en:"research", topic:"b2-abstract", level:"b2" , ex:"Die Forschung steht im Brief vom Amt.", exEn:"The research is in the letter from the office."},
  { id:"b213", de:"Wissenschaft", art:"die", pl:"-en", en:"science", topic:"b2-abstract", level:"b2" , ex:"Die Wissenschaft steht im Brief vom Amt.", exEn:"The science is in the letter from the office."},
  { id:"b214", de:"Technologie", art:"die", pl:"-n", en:"technology", topic:"b2-abstract", level:"b2" , ex:"Die Technologie steht im Brief vom Amt.", exEn:"The technology is in the letter from the office."},
  { id:"b215", de:"künstliche Intelligenz", art:"die", pl:"", en:"artificial intelligence", topic:"b2-abstract", level:"b2" , ex:"Die künstliche Intelligenz steht im Brief vom Amt.", exEn:"The artificial intelligence is in the letter from the office."},
  { id:"b216", de:"Herausforderung", art:"die", pl:"-en", en:"challenge", topic:"b2-abstract", level:"b2" , ex:"Die Herausforderung steht im Brief vom Amt.", exEn:"The challenge is in the letter from the office."},
  { id:"b217", de:"Voraussetzung", art:"die", pl:"-en", en:"prerequisite", topic:"b2-abstract", level:"b2" , ex:"Die Voraussetzung steht im Brief vom Amt.", exEn:"The prerequisite is in the letter from the office."},
  { id:"b218", de:"Zusammenhang", art:"der", pl:"Zusammenhänge", en:"connection / context", topic:"b2-abstract", level:"b2" , ex:"Der Zusammenhang steht im Brief vom Amt.", exEn:"The connection / context is in the letter from the office."},
  { id:"b219", de:"Maßnahme", art:"die", pl:"-n", en:"measure (action)", topic:"b2-abstract", level:"b2" , ex:"Die Maßnahme steht im Brief vom Amt.", exEn:"The measure (action) is in the letter from the office."},
  { id:"b220", de:"Bedeutung", art:"die", pl:"-en", en:"meaning / importance", topic:"b2-abstract", level:"b2" , ex:"Die Bedeutung steht im Brief vom Amt.", exEn:"The meaning / importance is in the letter from the office."},

  // b2 society
  { id:"bs1", de:"Bevölkerung", art:"die", pl:"-en", en:"population", topic:"b2-society", level:"b2" , ex:"Die Bevölkerung steht im Brief vom Amt.", exEn:"The population is in the letter from the office."},
  { id:"bs2", de:"Rente", art:"die", pl:"-n", en:"pension", topic:"b2-society", level:"b2" , ex:"Die Rente steht im Brief vom Amt.", exEn:"The pension is in the letter from the office."},
  { id:"bs3", de:"Kinderbetreuung", art:"die", pl:"-en", en:"childcare", topic:"b2-society", level:"b2" , ex:"Die Kinderbetreuung steht im Brief vom Amt.", exEn:"The childcare is in the letter from the office."},
  { id:"bs4", de:"Mindestlohn", art:"der", pl:"Mindestlöhne", en:"minimum wage", topic:"b2-society", level:"b2" , ex:"Der Mindestlohn steht im Brief vom Amt.", exEn:"The minimum wage is in the letter from the office."},
  { id:"bs5", de:"Wohnungsbau", art:"der", pl:"", en:"housing construction", topic:"b2-society", level:"b2" , ex:"Der Wohnungsbau steht im Brief vom Amt.", exEn:"The housing construction is in the letter from the office."},
  { id:"bs6", de:"Öffentlicher Nahverkehr", art:"der", pl:"", en:"local public transport", topic:"b2-society", level:"b1" , ex:"Der Öffentlicher Nahverkehr steht im Brief vom Amt.", exEn:"The local public transport is in the letter from the office."},
  { id:"bs7", de:"Energiewende", art:"die", pl:"-n", en:"energy transition", topic:"b2-society", level:"b2" , ex:"Die Energiewende steht im Brief vom Amt.", exEn:"The energy transition is in the letter from the office."},
  { id:"bs8", de:"Treibhausgas", art:"das", pl:"-e", en:"greenhouse gas", topic:"b2-society", level:"b2" , ex:"Das Treibhausgas steht im Brief vom Amt.", exEn:"The greenhouse gas is in the letter from the office."},
  { id:"bs9", de:"Ehrenamt", art:"das", pl:"Ehrenämter", en:"volunteering", topic:"b2-society", level:"b2" , ex:"Das Ehrenamt steht im Brief vom Amt.", exEn:"The volunteering is in the letter from the office."},
  { id:"bs10", de:"Chancengleichheit", art:"die", pl:"", en:"equal opportunity", topic:"b2-society", level:"b2" , ex:"Die Chancengleichheit steht im Brief vom Amt.", exEn:"The equal opportunity is in the letter from the office."},
  { id:"bs11", de:"Diskriminierung", art:"die", pl:"-en", en:"discrimination", topic:"b2-society", level:"b2" , ex:"Die Diskriminierung steht im Brief vom Amt.", exEn:"The discrimination is in the letter from the office."},
  { id:"bs12", de:"Globalisierung", art:"die", pl:"-en", en:"globalisation", topic:"b2-society", level:"b2" , ex:"Die Globalisierung steht im Brief vom Amt.", exEn:"The globalisation is in the letter from the office."},
  { id:"bs13", de:"Wirtschaft", art:"die", pl:"-en", en:"economy", topic:"b2-society", level:"b2" , ex:"Die Wirtschaft steht im Brief vom Amt.", exEn:"The economy is in the letter from the office."},
  { id:"bs14", de:"Arbeitsmarkt", art:"der", pl:"Arbeitsmärkte", en:"labour market", topic:"b2-society", level:"b2" , ex:"Der Arbeitsmarkt steht im Brief vom Amt.", exEn:"The labour market is in the letter from the office."},
  { id:"bs15", de:"Inflation", art:"die", pl:"-en", en:"inflation", topic:"b2-society", level:"b2" , ex:"Die Inflation steht im Brief vom Amt.", exEn:"The inflation is in the letter from the office."},
  { id:"cv1", de:"anfangen", art:"", pl:"hat angefangen", en:"to begin", topic:"verbs", level:"a2" , ex:"Ich möchte heute anfangen.", exEn:"I would like to begin today."},
  { id:"cv2", de:"aufhören", art:"", pl:"hat aufgehört", en:"to stop", topic:"verbs", level:"a2" , ex:"Ich möchte heute aufhören.", exEn:"I would like to stop today."},
  { id:"cv3", de:"bekommen", art:"", pl:"hat bekommen", en:"to receive / get", topic:"verbs", level:"a2" , ex:"Ich möchte heute bekommen.", exEn:"I would like to receive / get today."},
  { id:"cv4", de:"besuchen", art:"", pl:"hat besucht", en:"to visit", topic:"verbs", level:"a2" , ex:"Ich möchte heute besuchen.", exEn:"I would like to visit today."},
  { id:"cv5", de:"bestehen", art:"", pl:"hat bestanden", en:"to pass (an exam)", topic:"verbs", level:"b1" , ex:"Ich möchte heute bestehen.", exEn:"I would like to pass (an exam) today."},
  { id:"cv6", de:"erzählen", art:"", pl:"hat erzählt", en:"to tell (a story)", topic:"verbs", level:"a2" , ex:"Ich möchte heute erzählen.", exEn:"I would like to tell (a story) today."},
  { id:"cv7", de:"erklären", art:"", pl:"hat erklärt", en:"to explain", topic:"verbs", level:"b1" , ex:"Ich möchte heute erklären.", exEn:"I would like to explain today."},
  { id:"cv8", de:"empfehlen", art:"", pl:"hat empfohlen", en:"to recommend", topic:"verbs", level:"b1" , ex:"Ich möchte heute empfehlen.", exEn:"I would like to recommend today."},
  { id:"cv9", de:"entscheiden", art:"", pl:"hat entschieden", en:"to decide", topic:"verbs", level:"b1" , ex:"Ich möchte heute entscheiden.", exEn:"I would like to decide today."},
  { id:"cv10", de:"gefallen", art:"", pl:"hat gefallen", en:"to please / like", topic:"verbs", level:"a2" , ex:"Ich möchte heute gefallen.", exEn:"I would like to please / like today."},
  { id:"cv11", de:"gehören", art:"", pl:"hat gehört", en:"to belong", topic:"verbs", level:"a2" , ex:"Ich möchte heute gehören.", exEn:"I would like to belong today."},
  { id:"cv12", de:"hoffen", art:"", pl:"hat gehofft", en:"to hope", topic:"verbs", level:"a2" , ex:"Ich möchte heute hoffen.", exEn:"I would like to hope today."},
  { id:"cv13", de:"kennen", art:"", pl:"hat gekannt", en:"to know a person/place", topic:"verbs", level:"a2" , ex:"Ich möchte heute kennen.", exEn:"I would like to know a person/place today."},
  { id:"cv14", de:"wissen", art:"", pl:"hat gewusst", en:"to know a fact", topic:"verbs", level:"a2" , ex:"Ich möchte heute wissen.", exEn:"I would like to know a fact today."},
  { id:"cv15", de:"lassen", art:"", pl:"hat gelassen", en:"to let / have something done", topic:"verbs", level:"b1" , ex:"Ich möchte heute lassen.", exEn:"I would like to let / have something done today."},
  { id:"cv16", de:"passieren", art:"", pl:"ist passiert", en:"to happen", topic:"verbs", level:"a2" , ex:"Ich möchte heute passieren.", exEn:"I would like to happen today."},
  { id:"cv17", de:"schaffen", art:"", pl:"hat geschafft", en:"to manage / succeed", topic:"verbs", level:"b1" , ex:"Ich möchte heute schaffen.", exEn:"I would like to manage / succeed today."},
  { id:"cv18", de:"stattfinden", art:"", pl:"hat stattgefunden", en:"to take place", topic:"verbs", level:"b1" , ex:"Ich möchte heute stattfinden.", exEn:"I would like to take place today."},
  { id:"cv19", de:"vereinbaren", art:"", pl:"hat vereinbart", en:"to arrange / agree", topic:"verbs", level:"b1" , ex:"Ich möchte heute vereinbaren.", exEn:"I would like to arrange / agree today."},
  { id:"cv20", de:"vergleichen", art:"", pl:"hat verglichen", en:"to compare", topic:"verbs", level:"b1" , ex:"Ich möchte heute vergleichen.", exEn:"I would like to compare today."},
  { id:"cv21", de:"verlieren", art:"", pl:"hat verloren", en:"to lose", topic:"verbs", level:"a2" , ex:"Ich möchte heute verlieren.", exEn:"I would like to lose today."},
  { id:"cv22", de:"vermeiden", art:"", pl:"hat vermieden", en:"to avoid", topic:"verbs", level:"b1" , ex:"Ich möchte heute vermeiden.", exEn:"I would like to avoid today."},
  { id:"cv23", de:"versuchen", art:"", pl:"hat versucht", en:"to try", topic:"verbs", level:"a2" , ex:"Ich möchte heute versuchen.", exEn:"I would like to try today."},
  { id:"cv24", de:"vorschlagen", art:"", pl:"hat vorgeschlagen", en:"to suggest", topic:"verbs", level:"b1" , ex:"Ich möchte heute vorschlagen.", exEn:"I would like to suggest today."},
  { id:"cv25", de:"umziehen", art:"", pl:"ist umgezogen", en:"to move house", topic:"verbs", level:"b1" , ex:"Ich möchte heute umziehen.", exEn:"I would like to move house today."},
  { id:"cv26", de:"sich bewerben", art:"", pl:"hat sich beworben", en:"to apply (for a job)", topic:"verbs", level:"b1" , ex:"Wir wollen uns nicht bewerben.", exEn:"We do not want to apply (for a job)."},
  { id:"cv27", de:"sich erinnern", art:"", pl:"hat sich erinnert", en:"to remember", topic:"verbs", level:"b1" , ex:"Wir wollen uns nicht erinnern.", exEn:"We do not want to remember."},
  { id:"cv28", de:"sich freuen", art:"", pl:"hat sich gefreut", en:"to be glad", topic:"verbs", level:"a2" , ex:"Wir wollen uns nicht freuen.", exEn:"We do not want to be glad."},
  { id:"cv29", de:"sich interessieren", art:"", pl:"hat sich interessiert", en:"to be interested", topic:"verbs", level:"b1" , ex:"Wir wollen uns nicht interessieren.", exEn:"We do not want to be interested."},
  { id:"cv30", de:"überzeugen", art:"", pl:"hat überzeugt", en:"to convince", topic:"verbs", level:"b2" , ex:"Ich möchte heute überzeugen.", exEn:"I would like to convince today."},
  { id:"cv31", de:"berücksichtigen", art:"", pl:"hat berücksichtigt", en:"to take into account", topic:"verbs", level:"b2" , ex:"Ich möchte heute berücksichtigen.", exEn:"I would like to take into account today."},
  { id:"cv32", de:"verursachen", art:"", pl:"hat verursacht", en:"to cause", topic:"verbs", level:"b2" , ex:"Ich möchte heute verursachen.", exEn:"I would like to cause today."},
  { id:"aj1", de:"wichtig", art:"", pl:"wichtiger / am wichtigsten", en:"important", topic:"adjectives", level:"a2" , ex:"Der Termin ist wichtig.", exEn:"The appointment is important."},
  { id:"aj2", de:"möglich", art:"", pl:"", en:"possible", topic:"adjectives", level:"a2" , ex:"Der Termin ist möglich.", exEn:"The appointment is possible."},
  { id:"aj3", de:"nötig", art:"", pl:"", en:"necessary", topic:"adjectives", level:"b1" , ex:"Der Termin ist nötig.", exEn:"The appointment is necessary."},
  { id:"aj4", de:"günstig", art:"", pl:"", en:"good value / favourable", topic:"adjectives", level:"b1" , ex:"Der Termin ist günstig.", exEn:"The appointment is good value / favourable."},
  { id:"aj5", de:"zuverlässig", art:"", pl:"", en:"reliable", topic:"adjectives", level:"b1" , ex:"Der Termin ist zuverlässig.", exEn:"The appointment is reliable."},
  { id:"aj6", de:"pünktlich", art:"", pl:"", en:"punctual / on time", topic:"adjectives", level:"a2" , ex:"Der Termin ist pünktlich.", exEn:"The appointment is punctual / on time."},
  { id:"aj7", de:"geeignet", art:"", pl:"", en:"suitable", topic:"adjectives", level:"b1" , ex:"Der Termin ist geeignet.", exEn:"The appointment is suitable."},
  { id:"aj8", de:"erforderlich", art:"", pl:"", en:"required", topic:"adjectives", level:"b2" , ex:"Der Termin ist erforderlich.", exEn:"The appointment is required."},
  { id:"aj9", de:"umweltfreundlich", art:"", pl:"", en:"environmentally friendly", topic:"adjectives", level:"b1" , ex:"Der Termin ist umweltfreundlich.", exEn:"The appointment is environmentally friendly."},
  { id:"aj10", de:"überzeugt", art:"", pl:"", en:"convinced", topic:"adjectives", level:"b2" , ex:"Der Termin ist überzeugt.", exEn:"The appointment is convinced."},
  { id:"aj11", de:"verantwortlich", art:"", pl:"", en:"responsible", topic:"adjectives", level:"b1" , ex:"Der Termin ist verantwortlich.", exEn:"The appointment is responsible."},
  { id:"aj12", de:"selbstständig", art:"", pl:"", en:"independent / self-employed", topic:"adjectives", level:"b1" , ex:"Der Termin ist selbstständig.", exEn:"The appointment is independent / self-employed."},
  { id:"aj13", de:"belastbar", art:"", pl:"", en:"resilient", topic:"adjectives", level:"b2" , ex:"Der Termin ist belastbar.", exEn:"The appointment is resilient."},
  { id:"aj14", de:"spannend", art:"", pl:"", en:"exciting", topic:"adjectives", level:"a2" , ex:"Der Termin ist spannend.", exEn:"The appointment is exciting."},
  { id:"aj15", de:"langweilig", art:"", pl:"", en:"boring", topic:"adjectives", level:"a2" , ex:"Der Termin ist langweilig.", exEn:"The appointment is boring."},
  { id:"aj16", de:"zufrieden", art:"", pl:"", en:"satisfied", topic:"adjectives", level:"b1" , ex:"Ich möchte heute zufrieden.", exEn:"I would like satisfied today."},
  { id:"aj17", de:"enttäuscht", art:"", pl:"", en:"disappointed", topic:"adjectives", level:"b1" , ex:"Der Termin ist enttäuscht.", exEn:"The appointment is disappointed."},
  { id:"aj18", de:"wahrscheinlich", art:"", pl:"", en:"probable", topic:"adjectives", level:"b2" , ex:"Der Termin ist wahrscheinlich.", exEn:"The appointment is probable."},
  { id:"aj19", de:"notwendig", art:"", pl:"", en:"necessary", topic:"adjectives", level:"b2" , ex:"Der Termin ist notwendig.", exEn:"The appointment is necessary."},
  { id:"aj20", de:"erfolgreich", art:"", pl:"", en:"successful", topic:"adjectives", level:"b1" , ex:"Der Termin ist erfolgreich.", exEn:"The appointment is successful."},

  // exam-day / Amt survival (high yield for B1 letters + Lesen)
  { id:"ex1", de:"Ausweis", art:"der", pl:"-e", en:"ID card", topic:"examday", level:"a2" , ex:"Bitte bringen Sie den Ausweis mit.", exEn:"Please bring the ID card with you."},
  { id:"ex2", de:"Anmeldung", art:"die", pl:"-en", en:"registration / sign-up", topic:"examday", level:"b1" , ex:"Bitte bringen Sie die Anmeldung mit.", exEn:"Please bring the registration / sign-up with you."},
  { id:"ex3", de:"Termin", art:"der", pl:"-e", en:"appointment", topic:"examday", level:"a2" , ex:"Bitte bringen Sie den Termin mit.", exEn:"Please bring the appointment with you."},
  { id:"ex4", de:"Wartezimmer", art:"das", pl:"-", en:"waiting room", topic:"examday", level:"a2" , ex:"Bitte bringen Sie das Wartezimmer mit.", exEn:"Please bring the waiting room with you."},
  { id:"ex5", de:"Prüfungsordnung", art:"die", pl:"-en", en:"exam regulations", topic:"examday", level:"b1" , ex:"Bitte bringen Sie die Prüfungsordnung mit.", exEn:"Please bring the exam regulations with you."},
  { id:"ex6", de:"Antwortbogen", art:"der", pl:"-bögen", en:"answer sheet", topic:"examday", level:"b1" , ex:"Bitte bringen Sie den Antwortbogen mit.", exEn:"Please bring the answer sheet with you."},
  { id:"ex7", de:"Durchschlag", art:"der", pl:"-schläge", en:"carbon copy / duplicate", topic:"examday", level:"b2" , ex:"Bitte bringen Sie den Durchschlag mit.", exEn:"Please bring the carbon copy / duplicate with you."},
  { id:"ex8", de:"Bearbeitungszeit", art:"die", pl:"-en", en:"processing / working time", topic:"examday", level:"b1" , ex:"Bitte bringen Sie die Bearbeitungszeit mit.", exEn:"Please bring the processing / working time with you."},
  { id:"ex9", de:"Hilfsmittel", art:"das", pl:"-", en:"aids / allowed materials", topic:"examday", level:"b1" , ex:"Bitte bringen Sie das Hilfsmittel mit.", exEn:"Please bring the aids / allowed materials with you."},
  { id:"ex10", de:"Bestehen", art:"das", pl:"", en:"passing (an exam)", topic:"examday", level:"b1" , ex:"Bitte bringen Sie das Bestehen mit.", exEn:"Please bring the passing (an exam) with you."},
  { id:"ex11", de:"Durchfallen", art:"das", pl:"", en:"failing", topic:"examday", level:"b1" , ex:"Bitte bringen Sie das Durchfallen mit.", exEn:"Please bring the failing with you."},
  { id:"ex12", de:"Mündliche Prüfung", art:"die", pl:"-en", en:"oral exam", topic:"examday", level:"b1" , ex:"Bitte bringen Sie die Mündliche Prüfung mit.", exEn:"Please bring the oral exam with you."},
  { id:"ex13", de:"Schriftliche Prüfung", art:"die", pl:"-en", en:"written exam", topic:"examday", level:"b1" , ex:"Bitte bringen Sie die Schriftliche Prüfung mit.", exEn:"Please bring the written exam with you."},
  { id:"ex14", de:"Punktzahl", art:"die", pl:"-en", en:"score / points", topic:"examday", level:"b1" , ex:"Bitte bringen Sie die Punktzahl mit.", exEn:"Please bring the score / points with you."},
  { id:"ex15", de:"Zertifikat", art:"das", pl:"-e", en:"certificate", topic:"examday", level:"b1" , ex:"Bitte bringen Sie das Zertifikat mit.", exEn:"Please bring the certificate with you."},
  { id:"ex16", de:"Personalausweis", art:"der", pl:"-e", en:"national ID card", topic:"examday", level:"a2" , ex:"Bitte bringen Sie den Personalausweis mit.", exEn:"Please bring the national ID card with you."},
  { id:"ex17", de:"Passfoto", art:"das", pl:"-s", en:"passport photo", topic:"examday", level:"a2" , ex:"Bitte bringen Sie das Passfoto mit.", exEn:"Please bring the passport photo with you."},
  { id:"ex18", de:"Behörde", art:"die", pl:"-n", en:"authority / office", topic:"examday", level:"b1" , ex:"Bitte bringen Sie die Behörde mit.", exEn:"Please bring the authority / office with you."},
  { id:"ex19", de:"Formular", art:"das", pl:"-e", en:"form", topic:"examday", level:"a2" , ex:"Bitte bringen Sie das Formular mit.", exEn:"Please bring the form with you."},
  { id:"ex20", de:"Unterschrift", art:"die", pl:"-en", en:"signature", topic:"examday", level:"a2" , ex:"Bitte bringen Sie die Unterschrift mit.", exEn:"Please bring the signature with you."},
  { id:"ex21", de:"Frist", art:"die", pl:"-en", en:"deadline", topic:"examday", level:"b1" , ex:"Bitte bringen Sie die Frist mit.", exEn:"Please bring the deadline with you."},
  { id:"ex22", de:"Verlängerung", art:"die", pl:"-en", en:"extension", topic:"examday", level:"b1" , ex:"Bitte bringen Sie die Verlängerung mit.", exEn:"Please bring the extension with you."},
  { id:"ex23", de:"Bescheinigung", art:"die", pl:"-en", en:"certificate / confirmation", topic:"examday", level:"b1" , ex:"Bitte bringen Sie die Bescheinigung mit.", exEn:"Please bring the certificate / confirmation with you."},
  { id:"ex24", de:"Krankheit", art:"die", pl:"-en", en:"illness", topic:"examday", level:"a2" , ex:"Bitte bringen Sie die Krankheit mit.", exEn:"Please bring the illness with you."},
  { id:"ex25", de:"Attest", art:"das", pl:"-e", en:"doctor's note", topic:"examday", level:"b1" , ex:"Bitte bringen Sie das Attest mit.", exEn:"Please bring the doctor's note with you."},

  // extra housing / Amt / work high-frequency
  { id:"hx1", de:"Kaution", art:"die", pl:"-en", en:"deposit (rent)", topic:"home", level:"b1" , ex:"Wo ist die Kaution?", exEn:"Where is the deposit (rent)?"},
  { id:"hx2", de:"Nebenkosten", art:"die", pl:"", en:"additional rent costs", topic:"home", level:"b1" , ex:"Hier sind die Nebenkosten.", exEn:"Here are the additional rent costs."},
  { id:"hx3", de:"Vermieter", art:"der", pl:"-", en:"landlord", topic:"home", level:"b1" , ex:"Wo ist der Vermieter?", exEn:"Where is the landlord?"},
  { id:"hx4", de:"Mieter", art:"der", pl:"-", en:"tenant", topic:"home", level:"b1" , ex:"Wo ist der Mieter?", exEn:"Where is the tenant?"},
  { id:"hx5", de:"Kündigung", art:"die", pl:"-en", en:"notice / termination", topic:"home", level:"b1" , ex:"Wo ist die Kündigung?", exEn:"Where is the notice / termination?"},
  { id:"hx6", de:"Renovierung", art:"die", pl:"-en", en:"renovation", topic:"home", level:"b1" , ex:"Wo ist die Renovierung?", exEn:"Where is the renovation?"},
  { id:"hx7", de:"Hausverwaltung", art:"die", pl:"-en", en:"property management", topic:"home", level:"b1" , ex:"Wo ist die Hausverwaltung?", exEn:"Where is the property management?"},
  { id:"hx8", de:"Stockwerk", art:"das", pl:"-e", en:"floor / storey", topic:"home", level:"a2" , ex:"Wo ist das Stockwerk?", exEn:"Where is the floor / storey?"},
  { id:"hx9", de:"Keller", art:"der", pl:"-", en:"basement", topic:"home", level:"a2" , ex:"Wo ist der Keller?", exEn:"Where is the basement?"},
  { id:"hx10", de:"Dachboden", art:"der", pl:"-böden", en:"attic", topic:"home", level:"b1" , ex:"Wo ist der Dachboden?", exEn:"Where is the attic?"},

  { id:"wx1", de:"Bewerbung", art:"die", pl:"-en", en:"application", topic:"work", level:"b1" , ex:"Ich brauche die Bewerbung morgen.", exEn:"I need the application tomorrow."},
  { id:"wx2", de:"Lebenslauf", art:"der", pl:"-läufe", en:"CV / résumé", topic:"work", level:"b1" , ex:"Ich brauche den Lebenslauf morgen.", exEn:"I need the CV / résumé tomorrow."},
  { id:"wx3", de:"Vorstellungsgespräch", art:"das", pl:"-e", en:"job interview", topic:"work", level:"b1" , ex:"Ich brauche das Vorstellungsgespräch morgen.", exEn:"I need the job interview tomorrow."},
  { id:"wx4", de:"Probezeit", art:"die", pl:"-en", en:"probation period", topic:"work", level:"b1" , ex:"Ich brauche die Probezeit morgen.", exEn:"I need the probation period tomorrow."},
  { id:"wx5", de:"Überstunde", art:"die", pl:"-n", en:"overtime hour", topic:"work", level:"b1" , ex:"Ich brauche die Überstunde morgen.", exEn:"I need the overtime hour tomorrow."},
  { id:"wx6", de:"Gehalt", art:"das", pl:"Gehälter", en:"salary", topic:"work", level:"b1" , ex:"Ich brauche das Gehalt morgen.", exEn:"I need the salary tomorrow."},
  { id:"wx7", de:"Kündigungsschutz", art:"der", pl:"", en:"employment protection", topic:"work", level:"b2" , ex:"Ich brauche den Kündigungsschutz morgen.", exEn:"I need the employment protection tomorrow."},
  { id:"wx8", de:"Teilzeit", art:"die", pl:"", en:"part-time work", topic:"work", level:"b1" , ex:"Ich brauche die Teilzeit morgen.", exEn:"I need the part-time work tomorrow."},
  { id:"wx9", de:"Vollzeit", art:"die", pl:"", en:"full-time work", topic:"work", level:"b1" , ex:"Ich brauche die Vollzeit morgen.", exEn:"I need the full-time work tomorrow."},
  { id:"wx10", de:"Zeugnis", art:"das", pl:"-se", en:"reference / report", topic:"work", level:"b1" , ex:"Ich brauche das Zeugnis morgen.", exEn:"I need the reference / report tomorrow."},

  { id:"sx1", de:"Überweisung", art:"die", pl:"-en", en:"bank transfer", topic:"services", level:"b1" , ex:"Bitte bringen Sie die Überweisung mit.", exEn:"Please bring the bank transfer with you."},
  { id:"sx2", de:"Lastschrift", art:"die", pl:"-en", en:"direct debit", topic:"services", level:"b1" , ex:"Bitte bringen Sie die Lastschrift mit.", exEn:"Please bring the direct debit with you."},
  { id:"sx3", de:"Konto", art:"das", pl:"Konten", en:"account", topic:"services", level:"a2" , ex:"Bitte bringen Sie das Konto mit.", exEn:"Please bring the account with you."},
  { id:"sx4", de:"PIN", art:"die", pl:"-s", en:"PIN code", topic:"services", level:"a2" , ex:"Bitte bringen Sie die PIN mit.", exEn:"Please bring the PIN code with you."},
  { id:"sx5", de:"Steuererklärung", art:"die", pl:"-en", en:"tax return", topic:"services", level:"b2" , ex:"Bitte bringen Sie die Steuererklärung mit.", exEn:"Please bring the tax return with you."},
  { id:"sx6", de:"Kindergeld", art:"das", pl:"", en:"child benefit", topic:"services", level:"b1" , ex:"Bitte bringen Sie das Kindergeld mit.", exEn:"Please bring the child benefit with you."},
  { id:"sx7", de:"Wohngeld", art:"das", pl:"", en:"housing benefit", topic:"services", level:"b1" , ex:"Bitte bringen Sie das Wohngeld mit.", exEn:"Please bring the housing benefit with you."},
  { id:"sx8", de:"Bürgeramt", art:"das", pl:"-ämter", en:"citizens' office", topic:"services", level:"b1" , ex:"Bitte bringen Sie das Bürgeramt mit.", exEn:"Please bring the citizens' office with you."},
  { id:"sx9", de:"Meldebescheinigung", art:"die", pl:"-en", en:"registration certificate", topic:"services", level:"b1" , ex:"Bitte bringen Sie die Meldebescheinigung mit.", exEn:"Please bring the registration certificate with you."},
  { id:"sx10", de:"Krankenkasse", art:"die", pl:"-n", en:"health insurance fund", topic:"services", level:"b1" , ex:"Bitte bringen Sie die Krankenkasse mit.", exEn:"Please bring the health insurance fund with you."},

  { id:"tx1", de:"Verspätung", art:"die", pl:"-en", en:"delay", topic:"travel", level:"a2" , ex:"Wo ist die Verspätung?", exEn:"Where is the delay?"},
  { id:"tx2", de:"Umleitung", art:"die", pl:"-en", en:"detour / diversion", topic:"travel", level:"b1" , ex:"Wo ist die Umleitung?", exEn:"Where is the detour / diversion?"},
  { id:"tx3", de:"Gleis", art:"das", pl:"-e", en:"platform / track", topic:"travel", level:"a2" , ex:"Wo ist das Gleis?", exEn:"Where is the platform / track?"},
  { id:"tx4", de:"Fahrkarte", art:"die", pl:"-n", en:"ticket", topic:"travel", level:"a2" , ex:"Wo ist die Fahrkarte?", exEn:"Where is the ticket?"},
  { id:"tx5", de:"Reservierung", art:"die", pl:"-en", en:"reservation", topic:"travel", level:"b1" , ex:"Wo ist die Reservierung?", exEn:"Where is the reservation?"},
  { id:"tx6", de:"Anschluss", art:"der", pl:"Anschlüsse", en:"connection (train)", topic:"travel", level:"b1" , ex:"Wo ist der Anschluss?", exEn:"Where is the connection (train)?"},
  { id:"tx7", de:"Streik", art:"der", pl:"-s", en:"strike", topic:"travel", level:"b1" , ex:"Wo ist der Streik?", exEn:"Where is the strike?"},
  { id:"tx8", de:"Stau", art:"der", pl:"-s", en:"traffic jam", topic:"travel", level:"a2" , ex:"Wo ist der Stau?", exEn:"Where is the traffic jam?"},

  { id:"ox1", de:"Vorteil", art:"der", pl:"-e", en:"advantage", topic:"opinions", level:"b1" , ex:"Der Vorteil ist wichtig.", exEn:"The advantage is important."},
  { id:"ox2", de:"Nachteil", art:"der", pl:"-e", en:"disadvantage", topic:"opinions", level:"b1" , ex:"Der Nachteil ist wichtig.", exEn:"The disadvantage is important."},
  { id:"ox3", de:"Meinung", art:"die", pl:"-en", en:"opinion", topic:"opinions", level:"a2" , ex:"Die Meinung ist wichtig.", exEn:"The opinion is important."},
  { id:"ox4", de:"Vorschlag", art:"der", pl:"Vorschläge", en:"suggestion", topic:"opinions", level:"b1" , ex:"Der Vorschlag ist wichtig.", exEn:"The suggestion is important."},
  { id:"ox5", de:"Einigung", art:"die", pl:"-en", en:"agreement", topic:"opinions", level:"b1" , ex:"Die Einigung ist wichtig.", exEn:"The agreement is important."},
  { id:"ox6", de:"Kompromiss", art:"der", pl:"-e", en:"compromise", topic:"opinions", level:"b1" , ex:"Der Kompromiss ist wichtig.", exEn:"The compromise is important."},
  { id:"ox7", de:"Argument", art:"das", pl:"-e", en:"argument", topic:"opinions", level:"b1" , ex:"Das Argument ist wichtig.", exEn:"The argument is important."},
  { id:"ox8", de:"Standpunkt", art:"der", pl:"-e", en:"point of view", topic:"opinions", level:"b2" , ex:"Der Standpunkt ist wichtig.", exEn:"The point of view is important."},

  { id:"b2x1", de:"Nachhaltigkeit", art:"die", pl:"", en:"sustainability", topic:"b2-abstract", level:"b2" , ex:"Die Nachhaltigkeit steht im Brief vom Amt.", exEn:"The sustainability is in the letter from the office."},
  { id:"b2x2", de:"Gleichberechtigung", art:"die", pl:"", en:"equal rights", topic:"b2-abstract", level:"b2" , ex:"Die Gleichberechtigung steht im Brief vom Amt.", exEn:"The equal rights is in the letter from the office."},
  { id:"b2x3", de:"Digitalisierung", art:"die", pl:"", en:"digitalisation", topic:"b2-abstract", level:"b2" , ex:"Die Digitalisierung steht im Brief vom Amt.", exEn:"The digitalisation is in the letter from the office."},
  { id:"b2x4", de:"Fachkräftemangel", art:"der", pl:"", en:"skilled-labour shortage", topic:"b2-society", level:"b2" , ex:"Der Fachkräftemangel steht im Brief vom Amt.", exEn:"The skilled-labour shortage is in the letter from the office."},
  { id:"b2x5", de:"Mindestlohn", art:"der", pl:"-löhne", en:"minimum wage", topic:"b2-society", level:"b2" , ex:"Der Mindestlohn steht im Brief vom Amt.", exEn:"The minimum wage is in the letter from the office."},
  { id:"b2x6", de:"Wohnungsnot", art:"die", pl:"", en:"housing shortage", topic:"b2-society", level:"b2" , ex:"Die Wohnungsnot steht im Brief vom Amt.", exEn:"The housing shortage is in the letter from the office."},
  { id:"b2x7", de:"Energiewende", art:"die", pl:"", en:"energy transition", topic:"b2-society", level:"b2" , ex:"Die Energiewende steht im Brief vom Amt.", exEn:"The energy transition is in the letter from the office."},
  { id:"b2x8", de:"Rente", art:"die", pl:"-n", en:"pension", topic:"b2-society", level:"b2" , ex:"Die Rente steht im Brief vom Amt.", exEn:"The pension is in the letter from the office."},
  { id:"b2x9", de:"Inflation", art:"die", pl:"-en", en:"inflation", topic:"b2-society", level:"b2" , ex:"Die Inflation steht im Brief vom Amt.", exEn:"The inflation is in the letter from the office."},
  { id:"b2x10", de:"Klimawandel", art:"der", pl:"", en:"climate change", topic:"b2-society", level:"b2" , ex:"Der Klimawandel steht im Brief vom Amt.", exEn:"The climate change is in the letter from the office."},
  { id:"hx11", de:"Schimmel", art:"der", pl:"", en:"mould", topic:"home", level:"b1" , ex:"Wo ist der Schimmel?", exEn:"Where is the mould?"},
  { id:"hx12", de:"Hausmeister", art:"der", pl:"-", en:"caretaker / janitor", topic:"home", level:"b1" , ex:"Wo ist der Hausmeister?", exEn:"Where is the caretaker / janitor?"},
  { id:"hx13", de:"Wohngemeinschaft", art:"die", pl:"-en", en:"shared flat (WG)", topic:"home", level:"b1" , ex:"Wo ist die Wohngemeinschaft?", exEn:"Where is the shared flat (WG)?"},
  { id:"hx14", de:"Balkon", art:"der", pl:"-e", en:"balcony", topic:"home", level:"a2" , ex:"Wo ist der Balkon?", exEn:"Where is the balcony?"},
  { id:"hx15", de:"Treppenhaus", art:"das", pl:"Treppenhäuser", en:"stairwell", topic:"home", level:"b1" , ex:"Wo ist das Treppenhaus?", exEn:"Where is the stairwell?"},
  { id:"hx16", de:"Mülltrennung", art:"die", pl:"", en:"waste separation", topic:"home", level:"b1" , ex:"Wo ist die Mülltrennung?", exEn:"Where is the waste separation?"},
  { id:"hx17", de:"Wohnungsbesichtigung", art:"die", pl:"-en", en:"flat viewing", topic:"home", level:"b1" , ex:"Wo ist die Wohnungsbesichtigung?", exEn:"Where is the flat viewing?"},
  { id:"hx18", de:"Nachmieter", art:"der", pl:"-", en:"follow-on tenant", topic:"home", level:"b1" , ex:"Wo ist der Nachmieter?", exEn:"Where is the follow-on tenant?"},
  { id:"hx19", de:"Heizkosten", art:"die", pl:"", en:"heating costs", topic:"home", level:"b1" , ex:"Hier sind die Heizkosten.", exEn:"Here are the heating costs."},
  { id:"hx20", de:"Einbauküche", art:"die", pl:"-n", en:"fitted kitchen", topic:"home", level:"b1" , ex:"Wo ist die Einbauküche?", exEn:"Where is the fitted kitchen?"},

  { id:"wx10b", de:"Schicht", art:"die", pl:"-en", en:"shift", topic:"work", level:"b1" , ex:"Ich brauche die Schicht morgen.", exEn:"I need the shift tomorrow."},
  { id:"wx11", de:"Arbeitszeugnis", art:"das", pl:"-se", en:"employment reference", topic:"work", level:"b1" , ex:"Ich brauche das Arbeitszeugnis morgen.", exEn:"I need the employment reference tomorrow."},
  { id:"wx12", de:"Minijob", art:"der", pl:"-s", en:"mini-job", topic:"work", level:"b1" , ex:"Ich brauche den Minijob morgen.", exEn:"I need the mini-job tomorrow."},
  { id:"wx13", de:"Krankmeldung", art:"die", pl:"-en", en:"sick-leave notification", topic:"work", level:"b1" , ex:"Ich brauche die Krankmeldung morgen.", exEn:"I need the sick-leave notification tomorrow."},
  { id:"wx14", de:"Arbeitsvertrag", art:"der", pl:"Arbeitsverträge", en:"employment contract", topic:"work", level:"b1" , ex:"Ich brauche den Arbeitsvertrag morgen.", exEn:"I need the employment contract tomorrow."},
  { id:"wx15", de:"Bewerbungsfrist", art:"die", pl:"-en", en:"application deadline", topic:"work", level:"b1" , ex:"Ich brauche die Bewerbungsfrist morgen.", exEn:"I need the application deadline tomorrow."},
  { id:"wx16", de:"Qualifikation", art:"die", pl:"-en", en:"qualification", topic:"work", level:"b1" , ex:"Ich brauche die Qualifikation morgen.", exEn:"I need the qualification tomorrow."},
  { id:"wx17", de:"Aushilfe", art:"die", pl:"-n", en:"temp / helper", topic:"work", level:"b1" , ex:"Ich brauche die Aushilfe morgen.", exEn:"I need the temp / helper tomorrow."},
  { id:"wx18", de:"Schichtarbeit", art:"die", pl:"", en:"shift work", topic:"work", level:"b1" , ex:"Ich brauche die Schichtarbeit morgen.", exEn:"I need the shift work tomorrow."},
  { id:"wx19", de:"Betriebsrat", art:"der", pl:"Betriebsräte", en:"works council", topic:"work", level:"b2" , ex:"Ich brauche den Betriebsrat morgen.", exEn:"I need the works council tomorrow."},

  { id:"he19", de:"Hausarzt", art:"der", pl:"Hausärzte", en:"GP / family doctor", topic:"health", level:"b1" , ex:"Ich suche den Hausarzt.", exEn:"I am looking for the GP / family doctor."},
  { id:"he20", de:"Notaufnahme", art:"die", pl:"-n", en:"A&E / ER", topic:"health", level:"b1" , ex:"Ich suche die Notaufnahme.", exEn:"I am looking for the A&E / ER."},
  { id:"he21", de:"Allergie", art:"die", pl:"-n", en:"allergy", topic:"health", level:"b1" , ex:"Ich suche die Allergie.", exEn:"I am looking for the allergy."},
  { id:"he22", de:"Fieber", art:"das", pl:"", en:"fever", topic:"health", level:"a2" , ex:"Ich suche das Fieber.", exEn:"I am looking for the fever."},
  { id:"he23", de:"Blutdruck", art:"der", pl:"", en:"blood pressure", topic:"health", level:"b1" , ex:"Ich suche den Blutdruck.", exEn:"I am looking for the blood pressure."},
  { id:"he24", de:"Sprechstunde", art:"die", pl:"-n", en:"surgery hours / clinic", topic:"health", level:"b1" , ex:"Ich suche die Sprechstunde.", exEn:"I am looking for the surgery hours / clinic."},
  { id:"he25", de:"Wartezeit", art:"die", pl:"-en", en:"waiting time", topic:"health", level:"b1" , ex:"Ich suche die Wartezeit.", exEn:"I am looking for the waiting time."},
  { id:"he26", de:"Tablette", art:"die", pl:"-n", en:"tablet / pill", topic:"health", level:"a2" , ex:"Ich suche die Tablette.", exEn:"I am looking for the tablet / pill."},
  { id:"he27", de:"Krankengymnastik", art:"die", pl:"-en", en:"physiotherapy", topic:"health", level:"b1" , ex:"Ich suche die Krankengymnastik.", exEn:"I am looking for the physiotherapy."},
  { id:"he28", de:"Überweisung", art:"die", pl:"-en", en:"referral (doctor)", topic:"health", level:"b1" , ex:"Ich suche die Überweisung.", exEn:"I am looking for the referral (doctor)."},

  { id:"s16", de:"Prüfungsangst", art:"die", pl:"", en:"exam nerves", topic:"school", level:"b1" , ex:"Die Prüfungsangst ist wichtig.", exEn:"The exam nerves is important."},
  { id:"s17", de:"Nachhilfe", art:"die", pl:"-n", en:"tutoring", topic:"school", level:"b1" , ex:"Die Nachhilfe ist wichtig.", exEn:"The tutoring is important."},
  { id:"s18", de:"Unterricht", art:"der", pl:"", en:"lessons / teaching", topic:"school", level:"a2" , ex:"Der Unterricht ist wichtig.", exEn:"The lessons / teaching is important."},
  { id:"s19", de:"Hausaufgabe", art:"die", pl:"-n", en:"homework", topic:"school", level:"a2" , ex:"Die Hausaufgabe ist wichtig.", exEn:"The homework is important."},
  { id:"s20", de:"Dozent", art:"der", pl:"-en", en:"lecturer / course tutor", topic:"school", level:"b1" , ex:"Der Dozent ist wichtig.", exEn:"The lecturer / course tutor is important."},
  { id:"s21", de:"Anmeldefrist", art:"die", pl:"-en", en:"registration deadline", topic:"school", level:"b1" , ex:"Die Anmeldefrist ist wichtig.", exEn:"The registration deadline is important."},
  { id:"s22", de:"Teilnahmebescheinigung", art:"die", pl:"-en", en:"certificate of attendance", topic:"school", level:"b1" , ex:"Die Teilnahmebescheinigung ist wichtig.", exEn:"The certificate of attendance is important."},
  { id:"s23", de:"Vokabelheft", art:"das", pl:"-e", en:"vocab notebook", topic:"school", level:"a2" , ex:"Das Vokabelheft ist wichtig.", exEn:"The vocab notebook is important."},
  { id:"s24", de:"Sprachstand", art:"der", pl:"", en:"language level (status)", topic:"school", level:"b1" , ex:"Der Sprachstand ist wichtig.", exEn:"The language level (status) is important."},
  { id:"s25", de:"Modelltest", art:"der", pl:"-s", en:"practice / model exam", topic:"school", level:"b1" , ex:"Der Modelltest ist wichtig.", exEn:"The practice / model exam is important."},

  { id:"sv15", de:"Führerschein", art:"der", pl:"-e", en:"driving licence", topic:"services", level:"b1" , ex:"Bitte bringen Sie den Führerschein mit.", exEn:"Please bring the driving licence with you."},
  { id:"sv16", de:"Kindergeld", art:"das", pl:"", en:"child benefit", topic:"services", level:"b1" , ex:"Bitte bringen Sie das Kindergeld mit.", exEn:"Please bring the child benefit with you."},
  { id:"sv17", de:"Wohngeld", art:"das", pl:"", en:"housing benefit", topic:"services", level:"b1" , ex:"Bitte bringen Sie das Wohngeld mit.", exEn:"Please bring the housing benefit with you."},
  { id:"sv18", de:"Jobcenter", art:"das", pl:"-", en:"job centre", topic:"services", level:"b1" , ex:"Bitte bringen Sie das Jobcenter mit.", exEn:"Please bring the job centre with you."},
  { id:"sv19", de:"Ausländerbehörde", art:"die", pl:"-n", en:"immigration office", topic:"services", level:"b1" , ex:"Bitte bringen Sie die Ausländerbehörde mit.", exEn:"Please bring the immigration office with you."},
  { id:"sv20", de:"Terminvereinbarung", art:"die", pl:"-en", en:"appointment booking", topic:"services", level:"b1" , ex:"Bitte bringen Sie die Terminvereinbarung mit.", exEn:"Please bring the appointment booking with you."},
  { id:"sv21", de:"Kontoauszug", art:"der", pl:"Kontoauszüge", en:"bank statement", topic:"services", level:"b1" , ex:"Bitte bringen Sie den Kontoauszug mit.", exEn:"Please bring the bank statement with you."},
  { id:"sv22", de:"Lastschrift", art:"die", pl:"-en", en:"direct debit", topic:"services", level:"b1" , ex:"Bitte bringen Sie die Lastschrift mit.", exEn:"Please bring the direct debit with you."},
  { id:"sv23", de:"Beschwerde", art:"die", pl:"-n", en:"complaint", topic:"services", level:"b1" , ex:"Bitte bringen Sie die Beschwerde mit.", exEn:"Please bring the complaint with you."},
  { id:"sv24", de:"Kulanz", art:"die", pl:"", en:"goodwill (customer service)", topic:"services", level:"b1" , ex:"Bitte bringen Sie die Kulanz mit.", exEn:"Please bring the goodwill (customer service) with you."},

  { id:"ex26", de:"Bestehensgrenze", art:"die", pl:"-n", en:"pass mark", topic:"examday", level:"b1" , ex:"Bitte bringen Sie die Bestehensgrenze mit.", exEn:"Please bring the pass mark with you."},
  { id:"ex27", de:"Leitpunkt", art:"der", pl:"-e", en:"bullet / content point (letter)", topic:"examday", level:"b1" , ex:"Bitte bringen Sie den Leitpunkt mit.", exEn:"Please bring the bullet / content point (letter) with you."},
  { id:"ex28", de:"Prüfungszentrum", art:"das", pl:"Prüfungszentren", en:"exam centre", topic:"examday", level:"b1" , ex:"Bitte bringen Sie das Prüfungszentrum mit.", exEn:"Please bring the exam centre with you."},
  { id:"ex29", de:"Einlass", art:"der", pl:"Einlässe", en:"admission / entry", topic:"examday", level:"b1" , ex:"Bitte bringen Sie den Einlass mit.", exEn:"Please bring the admission / entry with you."},
  { id:"ex30", de:"Bewertung", art:"die", pl:"-en", en:"marking / assessment", topic:"examday", level:"b1" , ex:"Bitte bringen Sie die Bewertung mit.", exEn:"Please bring the marking / assessment with you."},
  { id:"ex31", de:"Täuschungsversuch", art:"der", pl:"-e", en:"cheating attempt", topic:"examday", level:"b1" , ex:"Bitte bringen Sie den Täuschungsversuch mit.", exEn:"Please bring the cheating attempt with you."},

],
  vocabTopics: [
  { id: "people", title: "People and family", blurb: "Personal data, relatives, character." },
  { id: "home", title: "Housing", blurb: "Rent, rooms, repairs, moving." },
  { id: "daily", title: "Daily life and time", blurb: "Routine, appointments, stress." },
  { id: "food", title: "Food and shopping", blurb: "Meals, shops, quality, nutrition." },
  { id: "work", title: "Work", blurb: "Jobs, applications, contracts." },
  { id: "health", title: "Health", blurb: "Doctor, insurance, body, prevention." },
  { id: "travel", title: "Travel and city", blurb: "Tickets, hotel, weather, delays." },
  { id: "school", title: "School and courses", blurb: "Exams, VHS, certificates." },
  { id: "services", title: "Money, Amt, services", blurb: "Bank, forms, post, tax." },
  { id: "opinions", title: "Opinions and abstract B1", blurb: "Advantage, decision, goal." },
  { id: "media", title: "Media and environment", blurb: "News, privacy, climate." },
  { id: "examday", title: "Exam day and Amt", blurb: "Answer sheet, ID, deadlines, certificates." },
  { id: "b2-abstract", title: "B2 abstract", blurb: "Society, law, science, AI." },
  { id: "b2-society", title: "B2 society and news", blurb: "Pension, energy, labour market." },
  { id: "verbs", title: "Power verbs", blurb: "The verbs you must produce automatically." },
  { id: "adjectives", title: "High-value adjectives", blurb: "wichtig, geeignet, zuverlässig…" },
  { id: "function", title: "Function words (grammar vocab)", blurb: "da-/wo-compounds, jemand/niemand, two-part connectors, erst/schon." },
  { id: "civic", title: "Society and volunteering (B1)", blurb: "Ehrenamt, Verein, Bürgeramt, house rules — personal, not theory." },
  { id: "world", title: "World knowledge groups", blurb: "Directions, holidays, measures, school subjects, colours, article-countries." },
  { id: "feelings", title: "Feelings and attitudes", blurb: "Angst, Sorge, sich ärgern, sich freuen auf/über — Sprechen and letters." },
  { id: "body", title: "Body and symptoms", blurb: "Kopf, Rücken, Fieber, AU — doctor letters and Hören." },
  { id: "clothing", title: "Clothes and shopping returns", blurb: "Jacke, Größe, umtauschen, Kassenbon." },
  { id: "letters", title: "Letter formulas", blurb: "Anrede, weil-opener, Könnten Sie, Mit freundlichen Grüßen." },
]
};
