export default {
  vocab: [
{ id:"b1x1", de:"Familienstand", art:"der", pl:"", en:"marital status", topic:"people", level:"b1" },
{ id:"b1x2", de:"ledig", art:"", pl:"", en:"unmarried", topic:"people", level:"b1" },
{ id:"b1x3", de:"geschieden", art:"", pl:"", en:"divorced", topic:"people", level:"b1" },
{ id:"b1x4", de:"verwitwet", art:"", pl:"", en:"widowed", topic:"people", level:"b1" },
{ id:"b1x5", de:"Lebenspartner", art:"der", pl:"-", en:"life partner", topic:"people", level:"b1" },
{ id:"b1x6", de:"Alleinerziehende", art:"der/die", pl:"-n", en:"single parent", topic:"people", level:"b1" },
{ id:"b1x7", de:"Betreuungszeit", art:"die", pl:"-en", en:"care hours", topic:"people", level:"b1" },
{ id:"b1x8", de:"Sorgerecht", art:"das", pl:"", en:"custody", topic:"people", level:"b1" },
{ id:"b1x9", de:"Unterhalt", art:"der", pl:"", en:"maintenance / alimony", topic:"people", level:"b1" },
{ id:"b1x10", de:"Verwandtschaftsgrad", art:"der", pl:"-e", en:"degree of kinship", topic:"people", level:"b1" },
{ id:"b1x11", de:"Bekanntschaft", art:"die", pl:"-en", en:"acquaintance", topic:"people", level:"b1" },
{ id:"b1x12", de:"Zusammenhalt", art:"der", pl:"", en:"cohesion", topic:"people", level:"b1" },
{ id:"b1x13", de:"Höflichkeit", art:"die", pl:"", en:"politeness", topic:"people", level:"b1" },
{ id:"b1x14", de:"Rücksicht", art:"die", pl:"", en:"consideration", topic:"people", level:"b1" },
{ id:"b1x15", de:"Missverständnis", art:"das", pl:"-se", en:"misunderstanding", topic:"people", level:"b1" },
{ id:"b1x16", de:"Vorstellungsgespräch führen", art:"", pl:"", en:"to conduct an interview (people context: intro)", topic:"people", level:"b1" },
{ id:"b1x17", de:"sich vorstellen", art:"", pl:"", en:"to introduce oneself", topic:"people", level:"b1" },
{ id:"b1x18", de:"aufeinander zugehen", art:"", pl:"", en:"to approach one another", topic:"people", level:"b1" },
{ id:"b1x19", de:"gemeinsame Sache machen", art:"", pl:"", en:"to join forces", topic:"people", level:"b1" },
{ id:"b1x20", de:"eine Beziehung führen", art:"", pl:"", en:"to be in a relationship", topic:"people", level:"b1" },
{ id:"b1x21", de:"sich trennen", art:"", pl:"", en:"to split up", topic:"people", level:"b1" },
{ id:"b1x22", de:"Heiratsurkunde", art:"die", pl:"-n", en:"marriage certificate", topic:"people", level:"b1" },
{ id:"b1x23", de:"Geburtsurkunde", art:"die", pl:"-n", en:"birth certificate", topic:"people", level:"b1" },
{ id:"b1x24", de:"Staatsangehörigkeit", art:"die", pl:"-en", en:"citizenship", topic:"people", level:"b1" },
{ id:"b1x25", de:"Aufenthaltstitel", art:"der", pl:"-", en:"residence title", topic:"people", level:"b1" },
{ id:"b1x26", de:"Niederlassungserlaubnis", art:"die", pl:"-se", en:"settlement permit", topic:"people", level:"b1" },
{ id:"b1x27", de:"Visum", art:"das", pl:"Visa", en:"visa", topic:"people", level:"b1" },
{ id:"b1x28", de:"Einbürgerung", art:"die", pl:"-en", en:"naturalisation", topic:"people", level:"b1" },
{ id:"b1x29", de:"Sprachzertifikat", art:"das", pl:"-e", en:"language certificate", topic:"people", level:"b1" },
{ id:"b1x30", de:"Integrationskursbescheinigung", art:"die", pl:"-en", en:"integration course certificate", topic:"people", level:"b1" },
{ id:"b1x31", de:"Wohnungsanzeige", art:"die", pl:"-n", en:"housing advert", topic:"home", level:"b1" },
{ id:"b1x32", de:"Mietinserat", art:"das", pl:"-e", en:"rental listing", topic:"home", level:"b1" },
{ id:"b1x33", de:"Wohnungsbesichtigungstermin", art:"der", pl:"-e", en:"viewing appointment", topic:"home", level:"b1" },
{ id:"b1x34", de:"Übergabeprotokoll", art:"das", pl:"-e", en:"handover protocol", topic:"home", level:"b1" },
{ id:"b1x35", de:"Zählerstand", art:"der", pl:"Zählerstände", en:"meter reading", topic:"home", level:"b1" },
{ id:"b1x36", de:"Stromzähler", art:"der", pl:"-", en:"electricity meter", topic:"home", level:"b1" },
{ id:"b1x37", de:"Wasserzähler", art:"der", pl:"-", en:"water meter", topic:"home", level:"b1" },
{ id:"b1x38", de:"Gaszähler", art:"der", pl:"-", en:"gas meter", topic:"home", level:"b1" },
{ id:"b1x39", de:"Kaltmiete", art:"die", pl:"-n", en:"cold rent", topic:"home", level:"b1" },
{ id:"b1x40", de:"Warmmiete", art:"die", pl:"-n", en:"warm rent", topic:"home", level:"b1" },
{ id:"b1x41", de:"Betriebskosten", art:"die", pl:"", en:"operating costs", topic:"home", level:"b1" },
{ id:"b1x42", de:"Heizkostenabrechnung", art:"die", pl:"-en", en:"heating bill", topic:"home", level:"b1" },
{ id:"b1x43", de:"Nebenkostenabrechnung", art:"die", pl:"-en", en:"service-charge statement", topic:"home", level:"b1" },
{ id:"b1x44", de:"Mietspiegel", art:"der", pl:"", en:"local rent index", topic:"home", level:"b1" },
{ id:"b1x45", de:"Mietpreisbremse", art:"die", pl:"-n", en:"rent control", topic:"home", level:"b1" },
{ id:"b1x46", de:"Staffelmiete", art:"die", pl:"-n", en:"stepped rent", topic:"home", level:"b1" },
{ id:"b1x47", de:"Indexmiete", art:"die", pl:"-n", en:"indexed rent", topic:"home", level:"b1" },
{ id:"b1x48", de:"Eigenbedarf", art:"der", pl:"", en:"owner's own use (notice)", topic:"home", level:"b1" },
{ id:"b1x49", de:"Kündigungsfrist", art:"die", pl:"-en", en:"notice period", topic:"home", level:"b1" },
{ id:"b1x50", de:"Mieterschutz", art:"der", pl:"", en:"tenant protection", topic:"home", level:"b1" },
{ id:"b1x51", de:"Hausordnung", art:"die", pl:"-en", en:"house rules", topic:"home", level:"b1" },
{ id:"b1x52", de:"Ruhezeit", art:"die", pl:"-en", en:"quiet hours", topic:"home", level:"b1" },
{ id:"b1x53", de:"Hausfrieden", art:"der", pl:"", en:"peace in the building", topic:"home", level:"b1" },
{ id:"b1x54", de:"Lärmbelästigung", art:"die", pl:"-en", en:"noise nuisance", topic:"home", level:"b1" },
{ id:"b1x55", de:"Feuchtigkeit", art:"die", pl:"", en:"damp", topic:"home", level:"b1" },
{ id:"b1x56", de:"Schimmelfleck", art:"der", pl:"-e", en:"mould stain", topic:"home", level:"b1" },
{ id:"b1x57", de:"Schimmelpilz", art:"der", pl:"-e", en:"mould fungus", topic:"home", level:"b1" },
{ id:"b1x58", de:"Stoßlüften", art:"das", pl:"", en:"burst ventilation", topic:"home", level:"b1" },
{ id:"b1x59", de:"Querlüften", art:"das", pl:"", en:"cross-ventilation", topic:"home", level:"b1" },
{ id:"b1x60", de:"Heizkörper entlüften", art:"", pl:"", en:"to bleed a radiator", topic:"home", level:"b1" },
{ id:"b1x61", de:"Thermostatventil", art:"das", pl:"-e", en:"thermostat valve", topic:"home", level:"b1" },
{ id:"b1x62", de:"Warmwasser", art:"das", pl:"", en:"hot water", topic:"home", level:"b1" },
{ id:"b1x63", de:"Kaltwasser", art:"das", pl:"", en:"cold water", topic:"home", level:"b1" },
{ id:"b1x64", de:"Rohrbruch", art:"der", pl:"Rohrbrüche", en:"burst pipe", topic:"home", level:"b1" },
{ id:"b1x65", de:"Verstopfung", art:"die", pl:"-en", en:"blockage", topic:"home", level:"b1" },
{ id:"b1x66", de:"Handwerker", art:"der", pl:"-", en:"tradesperson", topic:"home", level:"b1" },
{ id:"b1x67", de:"Klempner", art:"der", pl:"-", en:"plumber", topic:"home", level:"b1" },
{ id:"b1x68", de:"Elektriker", art:"der", pl:"-", en:"electrician", topic:"home", level:"b1" },
{ id:"b1x69", de:"Maler", art:"der", pl:"-", en:"painter", topic:"home", level:"b1" },
{ id:"b1x70", de:"Schönheitsreparatur", art:"die", pl:"-en", en:"decorative repair", topic:"home", level:"b1" },
{ id:"b1x71", de:"Renovierungsklausel", art:"die", pl:"-n", en:"renovation clause", topic:"home", level:"b1" },
{ id:"b1x72", de:"Mängelanzeige", art:"die", pl:"-n", en:"defect notice", topic:"home", level:"b1" },
{ id:"b1x73", de:"Mietminderung", art:"die", pl:"-en", en:"rent reduction", topic:"home", level:"b1" },
{ id:"b1x74", de:"Makler", art:"der", pl:"-", en:"estate agent", topic:"home", level:"b1" },
{ id:"b1x75", de:"Maklergebühr", art:"die", pl:"-en", en:"agent's fee", topic:"home", level:"b1" },
{ id:"b1x76", de:"Provision", art:"die", pl:"-en", en:"commission", topic:"home", level:"b1" },
{ id:"b1x77", de:"Wohnberechtigungsschein", art:"der", pl:"-e", en:"social-housing permit", topic:"home", level:"b1" },
{ id:"b1x78", de:"Sozialwohnung", art:"die", pl:"-en", en:"social housing", topic:"home", level:"b1" },
{ id:"b1x79", de:"Genossenschaft", art:"die", pl:"-en", en:"housing cooperative", topic:"home", level:"b1" },
{ id:"b1x80", de:"möbliert", art:"", pl:"", en:"furnished", topic:"home", level:"b1" },
{ id:"b1x81", de:"teilmöbliert", art:"", pl:"", en:"partly furnished", topic:"home", level:"b1" },
{ id:"b1x82", de:"unmöbliert", art:"", pl:"", en:"unfurnished", topic:"home", level:"b1" },
{ id:"b1x83", de:"Zwischenmiete", art:"die", pl:"-n", en:"interim tenancy", topic:"home", level:"b1" },
{ id:"b1x84", de:"Untermietvertrag", art:"der", pl:"Untermietverträge", en:"sublease", topic:"home", level:"b1" },
{ id:"b1x85", de:"WG-Zimmer", art:"das", pl:"-", en:"room in a shared flat", topic:"home", level:"b1" },
{ id:"b1x86", de:"Kaution zurückfordern", art:"", pl:"", en:"to reclaim the deposit", topic:"home", level:"b1" },
{ id:"b1x87", de:"Wohnungsübergabe", art:"die", pl:"-n", en:"flat handover", topic:"home", level:"b1" },
{ id:"b1x88", de:"Einzugsbestätigung", art:"die", pl:"-en", en:"move-in confirmation", topic:"home", level:"b1" },
{ id:"b1x89", de:"Ummeldung", art:"die", pl:"-en", en:"re-registration of address", topic:"home", level:"b1" },
{ id:"b1x90", de:"Erstwohnsitz", art:"der", pl:"-e", en:"primary residence", topic:"home", level:"b1" },
{ id:"b1x91", de:"Zweitwohnsitz", art:"der", pl:"-e", en:"second home", topic:"home", level:"b1" },
{ id:"b1x92", de:"Hausratversicherung", art:"die", pl:"-en", en:"contents insurance", topic:"home", level:"b1" },
{ id:"b1x93", de:"Haftpflichtversicherung", art:"die", pl:"-en", en:"liability insurance", topic:"home", level:"b1" },
{ id:"b1x94", de:"Rollladen", art:"der", pl:"Rollläden", en:"roller shutter", topic:"home", level:"b1" },
{ id:"b1x95", de:"Briefkasten", art:"der", pl:"Briefkästen", en:"letterbox", topic:"home", level:"b1" },
{ id:"b1x96", de:"Klingelschild", art:"das", pl:"-er", en:"doorbell nameplate", topic:"home", level:"b1" },
{ id:"b1x97", de:"Mülltonne", art:"die", pl:"-n", en:"wheelie bin", topic:"home", level:"b1" },
{ id:"b1x98", de:"Sperrmüll", art:"der", pl:"", en:"bulky waste", topic:"home", level:"b1" },
{ id:"b1x99", de:"Wertstoffhof", art:"der", pl:"Wertstoffhöfe", en:"recycling centre", topic:"home", level:"b1" },
{ id:"b1x100", de:"Aufzug defekt", art:"", pl:"", en:"lift out of order", topic:"home", level:"b1" },
{ id:"b1x101", de:"Kellerabteil", art:"das", pl:"-e", en:"cellar compartment", topic:"home", level:"b1" },
{ id:"b1x102", de:"Fahrradkeller", art:"der", pl:"", en:"bike cellar", topic:"home", level:"b1" },
{ id:"b1x103", de:"Waschküche", art:"die", pl:"-n", en:"laundry room", topic:"home", level:"b1" },
{ id:"b1x104", de:"Trockner", art:"der", pl:"-", en:"tumble dryer", topic:"home", level:"b1" },
{ id:"b1x105", de:"Heizungsausfall", art:"der", pl:"Heizungsausfälle", en:"heating failure", topic:"home", level:"b1" },
{ id:"b1x106", de:"Wohnungsgeberbestätigung", art:"die", pl:"-en", en:"landlord confirmation (Anmeldung)", topic:"home", level:"b1" },
{ id:"b1x107", de:"Mietschulden", art:"die", pl:"", en:"rent arrears", topic:"home", level:"b1" },
{ id:"b1x108", de:"Mahnung vom Vermieter", art:"die", pl:"-en", en:"landlord reminder", topic:"home", level:"b1" },
{ id:"b1x109", de:"Alltagsstress", art:"der", pl:"", en:"everyday stress", topic:"daily", level:"b1" },
{ id:"b1x110", de:"Zeitmanagement", art:"das", pl:"", en:"time management", topic:"daily", level:"b1" },
{ id:"b1x111", de:"To-do-Liste", art:"die", pl:"-n", en:"to-do list", topic:"daily", level:"b1" },
{ id:"b1x112", de:"Erinnerung stellen", art:"", pl:"", en:"to set a reminder", topic:"daily", level:"b1" },
{ id:"b1x113", de:"verschieben", art:"", pl:"", en:"to postpone", topic:"daily", level:"b1" },
{ id:"b1x114", de:"absagen", art:"", pl:"", en:"to cancel", topic:"daily", level:"b1" },
{ id:"b1x115", de:"zusagen", art:"", pl:"", en:"to accept (an invitation)", topic:"daily", level:"b1" },
{ id:"b1x116", de:"sich verspäten", art:"", pl:"", en:"to be late", topic:"daily", level:"b1" },
{ id:"b1x117", de:"pünktlich erscheinen", art:"", pl:"", en:"to arrive punctually", topic:"daily", level:"b1" },
{ id:"b1x118", de:"Freizeitgestaltung", art:"die", pl:"-en", en:"how one spends free time", topic:"daily", level:"b1" },
{ id:"b1x119", de:"Vereinsleben", art:"das", pl:"", en:"club life", topic:"daily", level:"b1" },
{ id:"b1x120", de:"Ehrenamtliche", art:"der/die", pl:"-n", en:"volunteer", topic:"daily", level:"b1" },
{ id:"b1x121", de:"Nachbarschaftshilfe", art:"die", pl:"", en:"neighbourhood help", topic:"daily", level:"b1" },
{ id:"b1x122", de:"Hort", art:"der", pl:"-e", en:"after-school care", topic:"daily", level:"b1" },
{ id:"b1x123", de:"Kita", art:"die", pl:"-s", en:"day-care centre", topic:"daily", level:"b1" },
{ id:"b1x124", de:"Elternabend", art:"der", pl:"-e", en:"parents' evening", topic:"daily", level:"b1" },
{ id:"b1x125", de:"Haushalt führen", art:"", pl:"", en:"to run a household", topic:"daily", level:"b1" },
{ id:"b1x126", de:"putzen", art:"", pl:"", en:"to clean", topic:"daily", level:"b1" },
{ id:"b1x127", de:"Wäsche waschen", art:"", pl:"", en:"to do the laundry", topic:"daily", level:"b1" },
{ id:"b1x128", de:"Einkaufsliste", art:"die", pl:"-n", en:"shopping list", topic:"daily", level:"b1" },
{ id:"b1x129", de:"Vorräte", art:"die", pl:"", en:"supplies", topic:"daily", level:"b1" },
{ id:"b1x130", de:"Wochenmarkt", art:"der", pl:"Wochenmärkte", en:"weekly market", topic:"daily", level:"b1" },
{ id:"b1x131", de:"Feierabendgestaltung", art:"die", pl:"-en", en:"evening after work", topic:"daily", level:"b1" },
{ id:"b1x132", de:"Wochenendausflug", art:"der", pl:"Wochenendausflüge", en:"weekend trip", topic:"daily", level:"b1" },
{ id:"b1x133", de:"Familienfeier", art:"die", pl:"-n", en:"family celebration", topic:"daily", level:"b1" },
{ id:"b1x134", de:"Einladung absagen", art:"", pl:"", en:"to decline an invitation", topic:"daily", level:"b1" },
{ id:"b1x135", de:"sich Zeit nehmen", art:"", pl:"", en:"to take time", topic:"daily", level:"b1" },
{ id:"b1x136", de:"in Eile sein", art:"", pl:"", en:"to be in a hurry", topic:"daily", level:"b1" },
{ id:"b1x137", de:"ausspannen", art:"", pl:"", en:"to unwind", topic:"daily", level:"b1" },
{ id:"b1x138", de:"Lebensmittel", art:"das", pl:"-", en:"foodstuff", topic:"food", level:"b1" },
{ id:"b1x139", de:"Haltbarkeit", art:"die", pl:"", en:"shelf life", topic:"food", level:"b1" },
{ id:"b1x140", de:"Mindesthaltbarkeitsdatum", art:"das", pl:"-daten", en:"best-before date", topic:"food", level:"b1" },
{ id:"b1x141", de:"Verbrauchsdatum", art:"das", pl:"-daten", en:"use-by date", topic:"food", level:"b1" },
{ id:"b1x142", de:"unverpackt", art:"", pl:"", en:"unpackaged", topic:"food", level:"b1" },
{ id:"b1x143", de:"Bio-Siegel", art:"das", pl:"-", en:"organic label", topic:"food", level:"b1" },
{ id:"b1x144", de:"Fairtrade", art:"", pl:"", en:"fair trade", topic:"food", level:"b1" },
{ id:"b1x145", de:"Regionalität", art:"die", pl:"", en:"local origin", topic:"food", level:"b1" },
{ id:"b1x146", de:"Saisongemüse", art:"das", pl:"", en:"seasonal vegetables", topic:"food", level:"b1" },
{ id:"b1x147", de:"Fertiggericht", art:"das", pl:"-e", en:"ready meal", topic:"food", level:"b1" },
{ id:"b1x148", de:"Tiefkühlkost", art:"die", pl:"", en:"frozen food", topic:"food", level:"b1" },
{ id:"b1x149", de:"Allergen", art:"das", pl:"-e", en:"allergen", topic:"food", level:"b1" },
{ id:"b1x150", de:"Zusatzstoff", art:"der", pl:"-e", en:"additive", topic:"food", level:"b1" },
{ id:"b1x151", de:"Nährwertangabe", art:"die", pl:"-n", en:"nutrition label", topic:"food", level:"b1" },
{ id:"b1x152", de:"Kalorien", art:"die", pl:"", en:"calories", topic:"food", level:"b1" },
{ id:"b1x153", de:"zuckerarm", art:"", pl:"", en:"low in sugar", topic:"food", level:"b1" },
{ id:"b1x154", de:"salzarm", art:"", pl:"", en:"low in salt", topic:"food", level:"b1" },
{ id:"b1x155", de:"vollwertig", art:"", pl:"", en:"wholefood", topic:"food", level:"b1" },
{ id:"b1x156", de:"Lebensmittelverschwendung vermeiden", art:"", pl:"", en:"to avoid food waste", topic:"food", level:"b1" },
{ id:"b1x157", de:"Reste verwerten", art:"", pl:"", en:"to use leftovers", topic:"food", level:"b1" },
{ id:"b1x158", de:"Einkaufswagen", art:"der", pl:"Einkaufswägen", en:"shopping trolley", topic:"food", level:"b1" },
{ id:"b1x159", de:"Kassenbon", art:"der", pl:"-s", en:"till receipt", topic:"food", level:"b1" },
{ id:"b1x160", de:"Pfandbon", art:"der", pl:"-s", en:"bottle-deposit slip", topic:"food", level:"b1" },
{ id:"b1x161", de:"Selbstbedienung", art:"die", pl:"", en:"self-service", topic:"food", level:"b1" },
{ id:"b1x162", de:"Bedienung", art:"die", pl:"-en", en:"service / waiter", topic:"food", level:"b1" },
{ id:"b1x163", de:"Beschwerde über das Essen", art:"die", pl:"-n", en:"complaint about the food", topic:"food", level:"b1" },
{ id:"b1x164", de:"nachwürzen", art:"", pl:"", en:"to add more seasoning", topic:"food", level:"b1" },
{ id:"b1x165", de:"durchgebraten", art:"", pl:"", en:"well done", topic:"food", level:"b1" },
{ id:"b1x166", de:"medium", art:"", pl:"", en:"medium (steak)", topic:"food", level:"b1" },
{ id:"b1x167", de:"ohne Zusätze", art:"", pl:"", en:"no extras", topic:"food", level:"b1" },
{ id:"b1x168", de:"Stellenausschreibung", art:"die", pl:"-en", en:"job posting", topic:"work", level:"b1" },
{ id:"b1x169", de:"Anforderungsprofil", art:"das", pl:"-e", en:"requirements profile", topic:"work", level:"b1" },
{ id:"b1x170", de:"Bewerbungsmappe", art:"die", pl:"-n", en:"application folder", topic:"work", level:"b1" },
{ id:"b1x171", de:"Anschreiben", art:"das", pl:"-", en:"cover letter", topic:"work", level:"b1" },
{ id:"b1x172", de:"Motivationsschreiben", art:"das", pl:"-", en:"motivation letter", topic:"work", level:"b1" },
{ id:"b1x173", de:"Zwischenzeugnis", art:"das", pl:"-se", en:"interim reference", topic:"work", level:"b1" },
{ id:"b1x174", de:"Qualifikationsnachweis", art:"der", pl:"-e", en:"proof of qualification", topic:"work", level:"b1" },
{ id:"b1x175", de:"Eingangsbestätigung", art:"die", pl:"-en", en:"acknowledgement of receipt", topic:"work", level:"b1" },
{ id:"b1x176", de:"Absage", art:"die", pl:"-n", en:"rejection", topic:"work", level:"b1" },
{ id:"b1x177", de:"Zusage", art:"die", pl:"-n", en:"offer / acceptance", topic:"work", level:"b1" },
{ id:"b1x178", de:"Einstellung", art:"die", pl:"-en", en:"hiring", topic:"work", level:"b1" },
{ id:"b1x179", de:"Einarbeitungszeit", art:"die", pl:"-en", en:"induction period", topic:"work", level:"b1" },
{ id:"b1x180", de:"Probezeit verlängern", art:"", pl:"", en:"to extend probation", topic:"work", level:"b1" },
{ id:"b1x181", de:"Befristung", art:"die", pl:"-en", en:"fixed-term status", topic:"work", level:"b1" },
{ id:"b1x182", de:"unbefristet", art:"", pl:"", en:"permanent (contract)", topic:"work", level:"b1" },
{ id:"b1x183", de:"befristet", art:"", pl:"", en:"fixed-term", topic:"work", level:"b1" },
{ id:"b1x184", de:"Teilzeitstelle", art:"die", pl:"-n", en:"part-time post", topic:"work", level:"b1" },
{ id:"b1x185", de:"Vollzeitstelle", art:"die", pl:"-n", en:"full-time post", topic:"work", level:"b1" },
{ id:"b1x186", de:"Minijobgrenze", art:"die", pl:"-n", en:"mini-job earnings cap", topic:"work", level:"b1" },
{ id:"b1x187", de:"Midijob", art:"der", pl:"-s", en:"midi-job", topic:"work", level:"b1" },
{ id:"b1x188", de:"Schichtzulage", art:"die", pl:"-n", en:"shift allowance", topic:"work", level:"b1" },
{ id:"b1x189", de:"Nachtzuschlag", art:"der", pl:"Nachtzuschläge", en:"night bonus", topic:"work", level:"b1" },
{ id:"b1x190", de:"Überstundenausgleich", art:"der", pl:"", en:"overtime compensation", topic:"work", level:"b1" },
{ id:"b1x191", de:"Gleitzeit", art:"die", pl:"", en:"flexitime", topic:"work", level:"b1" },
{ id:"b1x192", de:"Kernarbeitszeit", art:"die", pl:"-en", en:"core working hours", topic:"work", level:"b1" },
{ id:"b1x193", de:"Homeoffice-Regelung", art:"die", pl:"-en", en:"remote-work rule", topic:"work", level:"b1" },
{ id:"b1x194", de:"Diensthandy", art:"das", pl:"-s", en:"work phone", topic:"work", level:"b1" },
{ id:"b1x195", de:"Betriebsvereinbarung", art:"die", pl:"-en", en:"works agreement", topic:"work", level:"b1" },
{ id:"b1x196", de:"Abmahnung", art:"die", pl:"-en", en:"written warning", topic:"work", level:"b1" },
{ id:"b1x197", de:"Aufhebungsvertrag", art:"der", pl:"Aufhebungsverträge", en:"termination agreement", topic:"work", level:"b1" },
{ id:"b1x198", de:"Arbeitslosmeldung", art:"die", pl:"-en", en:"unemployment registration", topic:"work", level:"b1" },
{ id:"b1x199", de:"Sperrzeit", art:"die", pl:"-en", en:"benefit waiting period", topic:"work", level:"b1" },
{ id:"b1x200", de:"Weiterbildung", art:"die", pl:"-en", en:"continuing education", topic:"work", level:"b1" },
{ id:"b1x201", de:"Umschulung", art:"die", pl:"-en", en:"retraining", topic:"work", level:"b1" },
{ id:"b1x202", de:"Fortbildungsurlaub", art:"der", pl:"-e", en:"educational leave", topic:"work", level:"b1" },
{ id:"b1x203", de:"Zeitarbeit", art:"die", pl:"", en:"temporary agency work", topic:"work", level:"b1" },
{ id:"b1x204", de:"Leiharbeit", art:"die", pl:"", en:"agency labour", topic:"work", level:"b1" },
{ id:"b1x205", de:"Selbstständige", art:"der/die", pl:"-n", en:"self-employed person", topic:"work", level:"b1" },
{ id:"b1x206", de:"Gewerbeanmeldung", art:"die", pl:"-en", en:"trade registration", topic:"work", level:"b1" },
{ id:"b1x207", de:"Honorarkraft", art:"die", pl:"Honorarkräfte", en:"freelancer (fee-based)", topic:"work", level:"b1" },
{ id:"b1x208", de:"Gehaltabrechnung", art:"die", pl:"-en", en:"payslip", topic:"work", level:"b1" },
{ id:"b1x209", de:"Lohnsteuerklasse", art:"die", pl:"-n", en:"income-tax class", topic:"work", level:"b1" },
{ id:"b1x210", de:"Sozialversicherung", art:"die", pl:"-en", en:"social insurance", topic:"work", level:"b1" },
{ id:"b1x211", de:"Rentenversicherung", art:"die", pl:"-en", en:"pension insurance", topic:"work", level:"b1" },
{ id:"b1x212", de:"Arbeitslosenversicherung", art:"die", pl:"-en", en:"unemployment insurance", topic:"work", level:"b1" },
{ id:"b1x213", de:"Berufsgenossenschaft", art:"die", pl:"-en", en:"employers' liability insurer", topic:"work", level:"b1" },
{ id:"b1x214", de:"Mutterschutz", art:"der", pl:"", en:"maternity protection", topic:"work", level:"b1" },
{ id:"b1x215", de:"Elternzeit", art:"die", pl:"-en", en:"parental leave", topic:"work", level:"b1" },
{ id:"b1x216", de:"Elterngeld", art:"das", pl:"", en:"parental allowance", topic:"work", level:"b1" },
{ id:"b1x217", de:"Krankengeld", art:"das", pl:"", en:"sickness benefit", topic:"work", level:"b1" },
{ id:"b1x218", de:"Urlaubsanspruch", art:"der", pl:"Urlaubsansprüche", en:"holiday entitlement", topic:"work", level:"b1" },
{ id:"b1x219", de:"Resturlaub", art:"der", pl:"", en:"remaining holiday", topic:"work", level:"b1" },
{ id:"b1x220", de:"Dienstreiseantrag", art:"der", pl:"Dienstreiseanträge", en:"travel-on-duty request", topic:"work", level:"b1" },
{ id:"b1x221", de:"Zielvereinbarung", art:"die", pl:"-en", en:"target agreement", topic:"work", level:"b1" },
{ id:"b1x222", de:"Mitarbeitergespräch", art:"das", pl:"-e", en:"appraisal meeting", topic:"work", level:"b1" },
{ id:"b1x223", de:"Überlastungsanzeige", art:"die", pl:"-n", en:"overload notice", topic:"work", level:"b1" },
{ id:"b1x224", de:"Arbeitsschutz", art:"der", pl:"", en:"occupational safety", topic:"work", level:"b1" },
{ id:"b1x225", de:"Sicherheitsunterweisung", art:"die", pl:"-en", en:"safety briefing", topic:"work", level:"b1" },
{ id:"b1x226", de:"gesetzliche Krankenkasse", art:"die", pl:"-n", en:"statutory health insurer", topic:"health", level:"b1" },
{ id:"b1x227", de:"private Krankenversicherung", art:"die", pl:"-en", en:"private health insurance", topic:"health", level:"b1" },
{ id:"b1x228", de:"Versichertenkarte", art:"die", pl:"-n", en:"insurance card", topic:"health", level:"b1" },
{ id:"b1x229", de:"Versichertennummer", art:"die", pl:"-n", en:"insurance number", topic:"health", level:"b1" },
{ id:"b1x230", de:"Mitgliedsbescheinigung", art:"die", pl:"-en", en:"membership certificate", topic:"health", level:"b1" },
{ id:"b1x231", de:"Familienversicherung", art:"die", pl:"-en", en:"family insurance cover", topic:"health", level:"b1" },
{ id:"b1x232", de:"Zusatzversicherung", art:"die", pl:"-en", en:"supplementary insurance", topic:"health", level:"b1" },
{ id:"b1x233", de:"Selbstbeteiligung", art:"die", pl:"-en", en:"excess / copay", topic:"health", level:"b1" },
{ id:"b1x234", de:"Zuzahlungsbefreiung", art:"die", pl:"-en", en:"exemption from copay", topic:"health", level:"b1" },
{ id:"b1x235", de:"Heilmittel", art:"das", pl:"-", en:"remedy (physio etc.)", topic:"health", level:"b1" },
{ id:"b1x236", de:"Reha", art:"die", pl:"-s", en:"rehab", topic:"health", level:"b1" },
{ id:"b1x237", de:"Kur", art:"die", pl:"-en", en:"spa treatment", topic:"health", level:"b1" },
{ id:"b1x238", de:"AU-Bescheinigung", art:"die", pl:"-en", en:"certificate of incapacity", topic:"health", level:"b1" },
{ id:"b1x239", de:"elektronische AU", art:"die", pl:"-s", en:"electronic sick note", topic:"health", level:"b1" },
{ id:"b1x240", de:"Folgebescheinigung", art:"die", pl:"-en", en:"follow-up sick note", topic:"health", level:"b1" },
{ id:"b1x241", de:"Überweisungsschein", art:"der", pl:"-e", en:"referral form", topic:"health", level:"b1" },
{ id:"b1x242", de:"Facharztermin", art:"der", pl:"-e", en:"specialist appointment", topic:"health", level:"b1" },
{ id:"b1x243", de:"Terminservicestelle", art:"die", pl:"-n", en:"appointment service centre", topic:"health", level:"b1" },
{ id:"b1x244", de:"Bereitschaftsdienst", art:"der", pl:"-e", en:"on-call service", topic:"health", level:"b1" },
{ id:"b1x245", de:"Giftnotruf", art:"der", pl:"-e", en:"poison hotline", topic:"health", level:"b1" },
{ id:"b1x246", de:"Blutabnahme", art:"die", pl:"-n", en:"blood test", topic:"health", level:"b1" },
{ id:"b1x247", de:"Laborwerte", art:"die", pl:"", en:"lab results", topic:"health", level:"b1" },
{ id:"b1x248", de:"Befund", art:"der", pl:"-e", en:"findings / report", topic:"health", level:"b1" },
{ id:"b1x249", de:"Diagnose mitteilen", art:"", pl:"", en:"to communicate a diagnosis", topic:"health", level:"b1" },
{ id:"b1x250", de:"Therapieplan", art:"der", pl:"Therapiepläne", en:"treatment plan", topic:"health", level:"b1" },
{ id:"b1x251", de:"Nebenwirkung", art:"die", pl:"-en", en:"side effect", topic:"health", level:"b1" },
{ id:"b1x252", de:"Wechselwirkung", art:"die", pl:"-en", en:"interaction (drugs)", topic:"health", level:"b1" },
{ id:"b1x253", de:"Dosierung", art:"die", pl:"-en", en:"dosage", topic:"health", level:"b1" },
{ id:"b1x254", de:"Packungsbeilage", art:"die", pl:"-n", en:"patient information leaflet", topic:"health", level:"b1" },
{ id:"b1x255", de:"Rezeptgebühr", art:"die", pl:"-en", en:"prescription charge", topic:"health", level:"b1" },
{ id:"b1x256", de:"apothekenpflichtig", art:"", pl:"", en:"pharmacy-only", topic:"health", level:"b1" },
{ id:"b1x257", de:"rezeptfrei", art:"", pl:"", en:"over the counter", topic:"health", level:"b1" },
{ id:"b1x258", de:"Impfpass", art:"der", pl:"Impfpässe", en:"vaccination card", topic:"health", level:"b1" },
{ id:"b1x259", de:"Vorsorgeuntersuchung", art:"die", pl:"-en", en:"check-up", topic:"health", level:"b1" },
{ id:"b1x260", de:"Krebsvorsorge", art:"die", pl:"", en:"cancer screening", topic:"health", level:"b1" },
{ id:"b1x261", de:"Zahnersatz", art:"der", pl:"", en:"dental prosthesis", topic:"health", level:"b1" },
{ id:"b1x262", de:"Heil- und Kostenplan", art:"der", pl:"Heil- und Kostenpläne", en:"dental treatment plan", topic:"health", level:"b1" },
{ id:"b1x263", de:"psychotherapeutische Sprechstunde", art:"die", pl:"-n", en:"psychotherapy consultation", topic:"health", level:"b1" },
{ id:"b1x264", de:"Krankenkassenwechsel", art:"der", pl:"-", en:"change of insurer", topic:"health", level:"b1" },
{ id:"b1x265", de:"Kündigungsfrist der Kasse", art:"die", pl:"-en", en:"insurer notice period", topic:"health", level:"b1" },
{ id:"b1x266", de:"Bonusheft", art:"das", pl:"-e", en:"bonus booklet (dentist)", topic:"health", level:"b1" },
{ id:"b1x267", de:"Hausarztmodell", art:"das", pl:"-e", en:"GP-centred care model", topic:"health", level:"b1" },
{ id:"b1x268", de:"Notfallsprechstunde", art:"die", pl:"-n", en:"emergency clinic hours", topic:"health", level:"b1" },
{ id:"b1x269", de:"Rettungsdienst", art:"der", pl:"-e", en:"emergency medical service", topic:"health", level:"b1" },
{ id:"b1x270", de:"Notruf 112", art:"der", pl:"", en:"emergency number 112", topic:"health", level:"b1" },
{ id:"b1x271", de:"ärztlicher Bereitschaftsdienst 116117", art:"der", pl:"", en:"non-emergency doctor line", topic:"health", level:"b1" },
{ id:"b1x272", de:"Fahrgastrechte", art:"die", pl:"", en:"passenger rights", topic:"travel", level:"b1" },
{ id:"b1x273", de:"Entschädigung", art:"die", pl:"-en", en:"compensation", topic:"travel", level:"b1" },
{ id:"b1x274", de:"Fahrpreiserstattung", art:"die", pl:"-en", en:"fare refund", topic:"travel", level:"b1" },
{ id:"b1x275", de:"Verspätungsbescheinigung", art:"die", pl:"-en", en:"delay certificate", topic:"travel", level:"b1" },
{ id:"b1x276", de:"Zugausfall", art:"der", pl:"Zugausfälle", en:"cancelled train", topic:"travel", level:"b1" },
{ id:"b1x277", de:"Teilausfall", art:"der", pl:"Teilausfälle", en:"partial cancellation", topic:"travel", level:"b1" },
{ id:"b1x278", de:"Ersatzverkehr", art:"der", pl:"", en:"replacement service", topic:"travel", level:"b1" },
{ id:"b1x279", de:"Schienenersatzverkehr", art:"der", pl:"", en:"rail replacement bus", topic:"travel", level:"b1" },
{ id:"b1x280", de:"Gleisänderung", art:"die", pl:"-en", en:"platform change", topic:"travel", level:"b1" },
{ id:"b1x281", de:"Anschlussverlust", art:"der", pl:"Anschlussverluste", en:"missed connection", topic:"travel", level:"b1" },
{ id:"b1x282", de:"Reisekette", art:"die", pl:"-n", en:"journey chain", topic:"travel", level:"b1" },
{ id:"b1x283", de:"Durchgangszug", art:"der", pl:"Durchgangszüge", en:"through train", topic:"travel", level:"b1" },
{ id:"b1x284", de:"Regionalexpress", art:"der", pl:"-e", en:"regional express", topic:"travel", level:"b1" },
{ id:"b1x285", de:"Regionalbahn", art:"die", pl:"-en", en:"regional train", topic:"travel", level:"b1" },
{ id:"b1x286", de:"Fernzug", art:"der", pl:"Fernzüge", en:"long-distance train", topic:"travel", level:"b1" },
{ id:"b1x287", de:"Sitzplatzreservierung", art:"die", pl:"-en", en:"seat reservation", topic:"travel", level:"b1" },
{ id:"b1x288", de:"Fahrradabteil", art:"das", pl:"-e", en:"bike carriage", topic:"travel", level:"b1" },
{ id:"b1x289", de:"Familienabteil", art:"das", pl:"-e", en:"family compartment", topic:"travel", level:"b1" },
{ id:"b1x290", de:"Ruhebereich", art:"der", pl:"-e", en:"quiet zone", topic:"travel", level:"b1" },
{ id:"b1x291", de:"Kleinkindabteil", art:"das", pl:"-e", en:"toddler compartment", topic:"travel", level:"b1" },
{ id:"b1x292", de:"Fahrkartenkontrolle", art:"die", pl:"-n", en:"ticket inspection", topic:"travel", level:"b1" },
{ id:"b1x293", de:"erhöhtes Beförderungsentgelt", art:"das", pl:"-e", en:"penalty fare", topic:"travel", level:"b1" },
{ id:"b1x294", de:"Schwarzfahren", art:"das", pl:"", en:"fare evasion", topic:"travel", level:"b1" },
{ id:"b1x295", de:"Bahnsteigkante", art:"die", pl:"-n", en:"platform edge", topic:"travel", level:"b1" },
{ id:"b1x296", de:"Sicherheitshinweis", art:"der", pl:"-e", en:"safety notice", topic:"travel", level:"b1" },
{ id:"b1x297", de:"Durchsage", art:"die", pl:"-n", en:"announcement", topic:"travel", level:"b1" },
{ id:"b1x298", de:"Lautsprecheransage", art:"die", pl:"-n", en:"PA announcement", topic:"travel", level:"b1" },
{ id:"b1x299", de:"umleiten", art:"", pl:"", en:"to divert", topic:"travel", level:"b1" },
{ id:"b1x300", de:"halten", art:"", pl:"", en:"to stop (train)", topic:"travel", level:"b1" },
{ id:"b1x301", de:"durchfahren", art:"", pl:"", en:"to run through without stopping", topic:"travel", level:"b1" },
{ id:"b1x302", de:"Nahverkehr", art:"der", pl:"", en:"local transport", topic:"travel", level:"b1" },
{ id:"b1x303", de:"Verkehrsverbund", art:"der", pl:"Verkehrsverbünde", en:"transport association", topic:"travel", level:"b1" },
{ id:"b1x304", de:"Tarifzone", art:"die", pl:"-n", en:"fare zone", topic:"travel", level:"b1" },
{ id:"b1x305", de:"Anschlussfahrkarte", art:"die", pl:"-n", en:"extension ticket", topic:"travel", level:"b1" },
{ id:"b1x306", de:"Park-and-Ride", art:"das", pl:"", en:"park and ride", topic:"travel", level:"b1" },
{ id:"b1x307", de:"Mitfahrgelegenheit", art:"die", pl:"-en", en:"lift / ride share", topic:"travel", level:"b1" },
{ id:"b1x308", de:"Fahrgemeinschaft", art:"die", pl:"-en", en:"car pool", topic:"travel", level:"b1" },
{ id:"b1x309", de:"Stauwarnung", art:"die", pl:"-en", en:"traffic-jam warning", topic:"travel", level:"b1" },
{ id:"b1x310", de:"Baustelle", art:"die", pl:"-n", en:"roadworks", topic:"travel", level:"b1" },
{ id:"b1x311", de:"Sperrung", art:"die", pl:"-en", en:"closure", topic:"travel", level:"b1" },
{ id:"b1x312", de:"Umleitungsstrecke", art:"die", pl:"-n", en:"diversion route", topic:"travel", level:"b1" },
{ id:"b1x313", de:"Hotelstornierung", art:"die", pl:"-en", en:"hotel cancellation", topic:"travel", level:"b1" },
{ id:"b1x314", de:"Stornogebühr", art:"die", pl:"-en", en:"cancellation fee", topic:"travel", level:"b1" },
{ id:"b1x315", de:"No-Show", art:"der", pl:"-s", en:"no-show", topic:"travel", level:"b1" },
{ id:"b1x316", de:"Check-out", art:"der", pl:"-s", en:"check-out", topic:"travel", level:"b1" },
{ id:"b1x317", de:"Frühstücksbuffet", art:"das", pl:"-s", en:"breakfast buffet", topic:"travel", level:"b1" },
{ id:"b1x318", de:"Halbpension", art:"die", pl:"", en:"half board", topic:"travel", level:"b1" },
{ id:"b1x319", de:"All-inclusive", art:"", pl:"", en:"all-inclusive", topic:"travel", level:"b1" },
{ id:"b1x320", de:"Reisewarnung", art:"die", pl:"-en", en:"travel warning", topic:"travel", level:"b1" },
{ id:"b1x321", de:"Auslandsreisekrankenversicherung", art:"die", pl:"-en", en:"travel health insurance", topic:"travel", level:"b1" },
{ id:"b1x322", de:"VHS-Kurs", art:"der", pl:"-e", en:"VHS course", topic:"school", level:"b1" },
{ id:"b1x323", de:"Berufssprachkurs", art:"der", pl:"-e", en:"job-related language course", topic:"school", level:"b1" },
{ id:"b1x324", de:"Alphabetisierungskurs", art:"der", pl:"-e", en:"literacy course", topic:"school", level:"b1" },
{ id:"b1x325", de:"Einstufungstest", art:"der", pl:"-s", en:"placement test", topic:"school", level:"b1" },
{ id:"b1x326", de:"Sprachniveau", art:"das", pl:"-s", en:"language level", topic:"school", level:"b1" },
{ id:"b1x327", de:"Anwesenheitsliste", art:"die", pl:"-n", en:"attendance list", topic:"school", level:"b1" },
{ id:"b1x328", de:"Fehlstunde", art:"die", pl:"-n", en:"missed lesson", topic:"school", level:"b1" },
{ id:"b1x329", de:"Entschuldigung schreiben", art:"", pl:"", en:"to write an absence note", topic:"school", level:"b1" },
{ id:"b1x330", de:"Kursgebühr", art:"die", pl:"-en", en:"course fee", topic:"school", level:"b1" },
{ id:"b1x331", de:"Ermäßigung", art:"die", pl:"-en", en:"reduction (fee)", topic:"school", level:"b1" },
{ id:"b1x332", de:"Bildungsgutschein", art:"der", pl:"-e", en:"education voucher", topic:"school", level:"b1" },
{ id:"b1x333", de:"BAMF-Berechtigung", art:"die", pl:"-en", en:"BAMF entitlement", topic:"school", level:"b1" },
{ id:"b1x334", de:"Modul", art:"das", pl:"-e", en:"module", topic:"school", level:"b1" },
{ id:"b1x335", de:"Orientierungskurs", art:"der", pl:"-e", en:"orientation course", topic:"school", level:"b1" },
{ id:"b1x336", de:"Leben in Deutschland", art:"das", pl:"", en:"Life in Germany test", topic:"school", level:"b1" },
{ id:"b1x337", de:"Einbürgerungstest", art:"der", pl:"-s", en:"naturalisation test", topic:"school", level:"b1" },
{ id:"b1x338", de:"Nachholtermin", art:"der", pl:"-e", en:"resit date", topic:"school", level:"b1" },
{ id:"b1x339", de:"Nachprüfung", art:"die", pl:"-en", en:"resit exam", topic:"school", level:"b1" },
{ id:"b1x340", de:"Hörverstehen", art:"das", pl:"", en:"listening comprehension", topic:"school", level:"b1" },
{ id:"b1x341", de:"Leseverstehen", art:"das", pl:"", en:"reading comprehension", topic:"school", level:"b1" },
{ id:"b1x342", de:"Sprachbausteine", art:"die", pl:"", en:"language elements (exam)", topic:"school", level:"b1" },
{ id:"b1x343", de:"Ausdrucksfähigkeit", art:"die", pl:"", en:"ability to express oneself", topic:"school", level:"b1" },
{ id:"b1x344", de:"Wortschatzarbeit", art:"die", pl:"", en:"vocabulary work", topic:"school", level:"b1" },
{ id:"b1x345", de:"Grammatikübung", art:"die", pl:"-en", en:"grammar exercise", topic:"school", level:"b1" },
{ id:"b1x346", de:"Hausaufgabe abgeben", art:"", pl:"", en:"to hand in homework", topic:"school", level:"b1" },
{ id:"b1x347", de:"Nachhilfeunterricht", art:"der", pl:"", en:"tutoring", topic:"school", level:"b1" },
{ id:"b1x348", de:"Lernpartner", art:"der", pl:"-", en:"study partner", topic:"school", level:"b1" },
{ id:"b1x349", de:"Tandempartner", art:"der", pl:"-", en:"tandem partner", topic:"school", level:"b1" },
{ id:"b1x350", de:"Selbstlernzentrum", art:"das", pl:"Selbstlernzentren", en:"self-study centre", topic:"school", level:"b1" },
{ id:"b1x351", de:"Medienkompetenz", art:"die", pl:"", en:"media literacy", topic:"school", level:"b1" },
{ id:"b1x352", de:"Abschlussfeier", art:"die", pl:"-n", en:"graduation party", topic:"school", level:"b1" },
{ id:"b1x353", de:"Zeugniskonferenz", art:"die", pl:"-en", en:"grade conference", topic:"school", level:"b1" },
{ id:"b1x354", de:"Versetzung", art:"die", pl:"-en", en:"moving up a year", topic:"school", level:"b1" },
{ id:"b1x355", de:"Schulpflicht", art:"die", pl:"", en:"compulsory schooling", topic:"school", level:"b1" },
{ id:"b1x356", de:"Berufsschule", art:"die", pl:"-n", en:"vocational school", topic:"school", level:"b1" },
{ id:"b1x357", de:"Ausbildungsbetrieb", art:"der", pl:"-e", en:"training company", topic:"school", level:"b1" },
{ id:"b1x358", de:"Berichtsheft", art:"das", pl:"-e", en:"apprentice logbook", topic:"school", level:"b1" },
{ id:"b1x359", de:"Zwischenprüfung", art:"die", pl:"-en", en:"intermediate exam", topic:"school", level:"b1" },
{ id:"b1x360", de:"Gesellenprüfung", art:"die", pl:"-en", en:"journeyman exam", topic:"school", level:"b1" },
{ id:"b1x361", de:"Agentur für Arbeit", art:"die", pl:"-en", en:"employment agency", topic:"services", level:"b1" },
{ id:"b1x362", de:"Familienkasse", art:"die", pl:"-n", en:"family benefits office", topic:"services", level:"b1" },
{ id:"b1x363", de:"Rentenversicherungsträger", art:"der", pl:"-", en:"pension provider", topic:"services", level:"b1" },
{ id:"b1x364", de:"Finanzamt", art:"das", pl:"Finanzämter", en:"tax office", topic:"services", level:"b1" },
{ id:"b1x365", de:"Steuer-ID", art:"die", pl:"-s", en:"tax ID", topic:"services", level:"b1" },
{ id:"b1x366", de:"ELSTER", art:"das", pl:"", en:"online tax portal", topic:"services", level:"b1" },
{ id:"b1x367", de:"Kindergeldantrag", art:"der", pl:"Kindergeldanträge", en:"child-benefit application", topic:"services", level:"b1" },
{ id:"b1x368", de:"Wohngeldantrag", art:"der", pl:"Wohngeldanträge", en:"housing-benefit application", topic:"services", level:"b1" },
{ id:"b1x369", de:"Bürgergeld", art:"das", pl:"", en:"citizen's benefit", topic:"services", level:"b1" },
{ id:"b1x370", de:"Leistungsbescheid", art:"der", pl:"-e", en:"benefit decision", topic:"services", level:"b1" },
{ id:"b1x371", de:"Widerspruch", art:"der", pl:"Widersprüche", en:"formal objection", topic:"services", level:"b1" },
{ id:"b1x372", de:"Widerspruchsfrist", art:"die", pl:"-en", en:"objection deadline", topic:"services", level:"b1" },
{ id:"b1x373", de:"Widerspruch einlegen", art:"", pl:"", en:"to lodge an objection", topic:"services", level:"b1" },
{ id:"b1x374", de:"Beschwerdebrief", art:"der", pl:"-e", en:"letter of complaint", topic:"services", level:"b1" },
{ id:"b1x375", de:"Reklamation", art:"die", pl:"-en", en:"complaint about goods", topic:"services", level:"b1" },
{ id:"b1x376", de:"Umtausch", art:"der", pl:"Umtäusche", en:"exchange", topic:"services", level:"b1" },
{ id:"b1x377", de:"Rückerstattung", art:"die", pl:"-en", en:"refund", topic:"services", level:"b1" },
{ id:"b1x378", de:"Gewährleistung", art:"die", pl:"-en", en:"statutory warranty", topic:"services", level:"b1" },
{ id:"b1x379", de:"Garantie", art:"die", pl:"-n", en:"guarantee", topic:"services", level:"b1" },
{ id:"b1x380", de:"Kundenservice", art:"der", pl:"-s", en:"customer service", topic:"services", level:"b1" },
{ id:"b1x381", de:"Hotline", art:"die", pl:"-s", en:"hotline", topic:"services", level:"b1" },
{ id:"b1x382", de:"Ticket-Nummer", art:"die", pl:"-n", en:"ticket number (support)", topic:"services", level:"b1" },
{ id:"b1x383", de:"Vorgangsnummer", art:"die", pl:"-n", en:"case number", topic:"services", level:"b1" },
{ id:"b1x384", de:"Sachbearbeiterin", art:"die", pl:"-nen", en:"case officer (f)", topic:"services", level:"b1" },
{ id:"b1x385", de:"Aktenzeichen", art:"das", pl:"-", en:"file reference", topic:"services", level:"b1" },
{ id:"b1x386", de:"Vollmacht", art:"die", pl:"-en", en:"power of attorney", topic:"services", level:"b1" },
{ id:"b1x387", de:"beglaubigte Kopie", art:"die", pl:"-n", en:"certified copy", topic:"services", level:"b1" },
{ id:"b1x388", de:"Übersetzung", art:"die", pl:"-en", en:"translation", topic:"services", level:"b1" },
{ id:"b1x389", de:"Dolmetscher", art:"der", pl:"-", en:"interpreter", topic:"services", level:"b1" },
{ id:"b1x390", de:"Terminabsage", art:"die", pl:"-n", en:"appointment cancellation", topic:"services", level:"b1" },
{ id:"b1x391", de:"Wartenummer", art:"die", pl:"-n", en:"queue number", topic:"services", level:"b1" },
{ id:"b1x392", de:"Öffnungszeit", art:"die", pl:"-en", en:"opening hours", topic:"services", level:"b1" },
{ id:"b1x393", de:"Sprechzeit", art:"die", pl:"-en", en:"office hours", topic:"services", level:"b1" },
{ id:"b1x394", de:"Barrierefreiheit", art:"die", pl:"", en:"accessibility", topic:"services", level:"b1" },
{ id:"b1x395", de:"Online-Terminvergabe", art:"die", pl:"-n", en:"online appointment booking", topic:"services", level:"b1" },
{ id:"b1x396", de:"eID", art:"die", pl:"-s", en:"electronic ID function", topic:"services", level:"b1" },
{ id:"b1x397", de:"PIN-Brief", art:"der", pl:"-e", en:"PIN letter", topic:"services", level:"b1" },
{ id:"b1x398", de:"Kontoeröffnung", art:"die", pl:"-en", en:"account opening", topic:"services", level:"b1" },
{ id:"b1x399", de:"Girokonto", art:"das", pl:"-s", en:"current account", topic:"services", level:"b1" },
{ id:"b1x400", de:"Dispokredit", art:"der", pl:"-e", en:"overdraft", topic:"services", level:"b1" },
{ id:"b1x401", de:"Schufa-Auskunft", art:"die", pl:"-e", en:"credit report", topic:"services", level:"b1" },
{ id:"b1x402", de:"Lastschriftmandat", art:"das", pl:"-e", en:"direct-debit mandate", topic:"services", level:"b1" },
{ id:"b1x403", de:"SEPA-Überweisung", art:"die", pl:"-en", en:"SEPA transfer", topic:"services", level:"b1" },
{ id:"b1x404", de:"Zahlungsaufforderung", art:"die", pl:"-en", en:"payment request", topic:"services", level:"b1" },
{ id:"b1x405", de:"Mahnbescheid", art:"der", pl:"-e", en:"default summons", topic:"services", level:"b1" },
{ id:"b1x406", de:"Inkasso", art:"das", pl:"", en:"debt collection", topic:"services", level:"b1" },
{ id:"b1x407", de:"Ratenzahlung", art:"die", pl:"-en", en:"instalment payment", topic:"services", level:"b1" },
{ id:"b1x408", de:"Stundung", art:"die", pl:"-en", en:"deferral of payment", topic:"services", level:"b1" },
{ id:"b1x409", de:"Gebührenordnung", art:"die", pl:"-en", en:"fee schedule", topic:"services", level:"b1" },
{ id:"b1x410", de:"Bearbeitungsgebühr", art:"die", pl:"-en", en:"processing fee", topic:"services", level:"b1" },
{ id:"b1x411", de:"Porto", art:"das", pl:"", en:"postage", topic:"services", level:"b1" },
{ id:"b1x412", de:"Einschreiben mit Rückschein", art:"das", pl:"", en:"registered mail with receipt", topic:"services", level:"b1" },
{ id:"b1x413", de:"Nachsendeauftrag", art:"der", pl:"Nachsendeaufträge", en:"mail forwarding", topic:"services", level:"b1" },
{ id:"b1x414", de:"Postfach", art:"das", pl:"Postfächer", en:"PO box", topic:"services", level:"b1" },
{ id:"b1x415", de:"Packstationscode", art:"der", pl:"-s", en:"parcel-locker code", topic:"services", level:"b1" },
{ id:"b1x416", de:"Standpunkt vertreten", art:"", pl:"", en:"to take a position", topic:"opinions", level:"b1" },
{ id:"b1x417", de:"Argument vorbringen", art:"", pl:"", en:"to put forward an argument", topic:"opinions", level:"b1" },
{ id:"b1x418", de:"Gegenargument", art:"das", pl:"-e", en:"counter-argument", topic:"opinions", level:"b1" },
{ id:"b1x419", de:"abwägen", art:"", pl:"", en:"to weigh up", topic:"opinions", level:"b1" },
{ id:"b1x420", de:"zu einem Kompromiss kommen", art:"", pl:"", en:"to reach a compromise", topic:"opinions", level:"b1" },
{ id:"b1x421", de:"einer Meinung sein", art:"", pl:"", en:"to share an opinion", topic:"opinions", level:"b1" },
{ id:"b1x422", de:"anderer Meinung sein", art:"", pl:"", en:"to disagree", topic:"opinions", level:"b1" },
{ id:"b1x423", de:"einräumen", art:"", pl:"", en:"to concede", topic:"opinions", level:"b1" },
{ id:"b1x424", de:"betonen", art:"", pl:"", en:"to emphasise", topic:"opinions", level:"b1" },
{ id:"b1x425", de:"hervorheben", art:"", pl:"", en:"to highlight", topic:"opinions", level:"b1" },
{ id:"b1x426", de:"relativieren", art:"", pl:"", en:"to put into perspective", topic:"opinions", level:"b1" },
{ id:"b1x427", de:"verallgemeinern", art:"", pl:"", en:"to generalise", topic:"opinions", level:"b1" },
{ id:"b1x428", de:"differenzieren", art:"", pl:"", en:"to differentiate", topic:"opinions", level:"b1" },
{ id:"b1x429", de:"begründen", art:"", pl:"", en:"to give reasons", topic:"opinions", level:"b1" },
{ id:"b1x430", de:"schlussfolgern", art:"", pl:"", en:"to conclude", topic:"opinions", level:"b1" },
{ id:"b1x431", de:"zusammenfassend", art:"", pl:"", en:"in summary", topic:"opinions", level:"b1" },
{ id:"b1x432", de:"meiner Ansicht nach", art:"", pl:"", en:"in my view", topic:"opinions", level:"b1" },
{ id:"b1x433", de:"aus meiner Sicht", art:"", pl:"", en:"from my perspective", topic:"opinions", level:"b1" },
{ id:"b1x434", de:"es kommt darauf an", art:"", pl:"", en:"it depends", topic:"opinions", level:"b1" },
{ id:"b1x435", de:"einerseits … andererseits", art:"", pl:"", en:"on the one hand … on the other", topic:"opinions", level:"b1" },
{ id:"b1x436", de:"im Vergleich zu", art:"", pl:"", en:"compared with", topic:"opinions", level:"b1" },
{ id:"b1x437", de:"im Gegensatz zu", art:"", pl:"", en:"in contrast to", topic:"opinions", level:"b1" },
{ id:"b1x438", de:"vor allem", art:"", pl:"", en:"above all", topic:"opinions", level:"b1" },
{ id:"b1x439", de:"nicht zuletzt", art:"", pl:"", en:"not least", topic:"opinions", level:"b1" },
{ id:"b1x440", de:"zweifelsohne", art:"", pl:"", en:"undoubtedly", topic:"opinions", level:"b1" },
{ id:"b1x441", de:"fragwürdig", art:"", pl:"", en:"questionable", topic:"opinions", level:"b1" },
{ id:"b1x442", de:"überzeugend", art:"", pl:"", en:"convincing", topic:"opinions", level:"b1" },
{ id:"b1x443", de:"nachvollziehbar", art:"", pl:"", en:"understandable", topic:"opinions", level:"b1" },
{ id:"b1x444", de:"unstrittig", art:"", pl:"", en:"undisputed", topic:"opinions", level:"b1" },
{ id:"b1x445", de:"umstritten", art:"", pl:"", en:"controversial", topic:"opinions", level:"b1" },
{ id:"b1x446", de:"Nachrichtenquelle", art:"die", pl:"-n", en:"news source", topic:"media", level:"b1" },
{ id:"b1x447", de:"Leitartikel", art:"der", pl:"-", en:"editorial", topic:"media", level:"b1" },
{ id:"b1x448", de:"Leserbrief", art:"der", pl:"-e", en:"letter to the editor", topic:"media", level:"b1" },
{ id:"b1x449", de:"Pressemitteilung", art:"die", pl:"-en", en:"press release", topic:"media", level:"b1" },
{ id:"b1x450", de:"Faktencheck", art:"der", pl:"-s", en:"fact check", topic:"media", level:"b1" },
{ id:"b1x451", de:"Fake News", art:"die", pl:"", en:"fake news", topic:"media", level:"b1" },
{ id:"b1x452", de:"Desinformationskampagne", art:"die", pl:"-n", en:"disinformation campaign", topic:"media", level:"b1" },
{ id:"b1x453", de:"Meinungsbildung", art:"die", pl:"", en:"formation of opinion", topic:"media", level:"b1" },
{ id:"b1x454", de:"Pressefreiheit", art:"die", pl:"", en:"freedom of the press", topic:"media", level:"b1" },
{ id:"b1x455", de:"Zensur", art:"die", pl:"", en:"censorship", topic:"media", level:"b1" },
{ id:"b1x456", de:"Datenschutzgrundverordnung", art:"die", pl:"", en:"GDPR", topic:"media", level:"b1" },
{ id:"b1x457", de:"Einwilligung", art:"die", pl:"-en", en:"consent", topic:"media", level:"b1" },
{ id:"b1x458", de:"Cookies ablehnen", art:"", pl:"", en:"to refuse cookies", topic:"media", level:"b1" },
{ id:"b1x459", de:"Tracking", art:"das", pl:"", en:"tracking", topic:"media", level:"b1" },
{ id:"b1x460", de:"Algorithmen", art:"die", pl:"", en:"algorithms", topic:"media", level:"b1" },
{ id:"b1x461", de:"Filterblase", art:"die", pl:"-n", en:"filter bubble", topic:"media", level:"b1" },
{ id:"b1x462", de:"Hasskommentar", art:"der", pl:"-e", en:"hate comment", topic:"media", level:"b1" },
{ id:"b1x463", de:"Netiquette", art:"die", pl:"", en:"netiquette", topic:"media", level:"b1" },
{ id:"b1x464", de:"Impressum", art:"das", pl:"Impressen", en:"site legal notice", topic:"media", level:"b1" },
{ id:"b1x465", de:"Abonnement", art:"das", pl:"-s", en:"subscription", topic:"media", level:"b1" },
{ id:"b1x466", de:"Paywall", art:"die", pl:"-s", en:"paywall", topic:"media", level:"b1" },
{ id:"b1x467", de:"Podcast", art:"der", pl:"-s", en:"podcast", topic:"media", level:"b1" },
{ id:"b1x468", de:"Streamingdienst", art:"der", pl:"-e", en:"streaming service", topic:"media", level:"b1" },
{ id:"b1x469", de:"Klimaschutz", art:"der", pl:"", en:"climate protection", topic:"media", level:"b1" },
{ id:"b1x470", de:"Treibhausgasemission", art:"die", pl:"-en", en:"greenhouse-gas emission", topic:"media", level:"b1" },
{ id:"b1x471", de:"CO2-Fußabdruck", art:"der", pl:"CO2-Fußabdrücke", en:"carbon footprint", topic:"media", level:"b1" },
{ id:"b1x472", de:"erneuerbare Energie", art:"die", pl:"-n", en:"renewable energy", topic:"media", level:"b1" },
{ id:"b1x473", de:"Photovoltaik", art:"die", pl:"", en:"photovoltaics", topic:"media", level:"b1" },
{ id:"b1x474", de:"Windkraft", art:"die", pl:"", en:"wind power", topic:"media", level:"b1" },
{ id:"b1x475", de:"Energiesparen", art:"das", pl:"", en:"energy saving", topic:"media", level:"b1" },
{ id:"b1x476", de:"Wärmedämmung", art:"die", pl:"-en", en:"thermal insulation", topic:"media", level:"b1" },
{ id:"b1x477", de:"ÖPNV nutzen", art:"", pl:"", en:"to use public transport", topic:"media", level:"b1" },
{ id:"b1x478", de:"Fahrgemeinschaft bilden", art:"", pl:"", en:"to form a car pool", topic:"media", level:"b1" },
{ id:"b1x479", de:"Müllvermeidung", art:"die", pl:"", en:"waste prevention", topic:"media", level:"b1" },
{ id:"b1x480", de:"Einwegplastik", art:"das", pl:"", en:"single-use plastic", topic:"media", level:"b1" },
{ id:"b1x481", de:"Mehrwegflasche", art:"die", pl:"-n", en:"reusable bottle", topic:"media", level:"b1" },
{ id:"b1x482", de:"Pfandsystem", art:"das", pl:"-e", en:"deposit system", topic:"media", level:"b1" },
{ id:"b1x483", de:"Artensterben", art:"das", pl:"", en:"species extinction", topic:"media", level:"b1" },
{ id:"b1x484", de:"Biodiversität", art:"die", pl:"", en:"biodiversity", topic:"media", level:"b1" },
{ id:"b1x485", de:"Hochwasser", art:"das", pl:"", en:"flooding", topic:"media", level:"b1" },
{ id:"b1x486", de:"Dürre", art:"die", pl:"-n", en:"drought", topic:"media", level:"b1" },
{ id:"b1x487", de:"Hitzeschutzplan", art:"der", pl:"Hitzeschutzpläne", en:"heat-protection plan", topic:"media", level:"b1" },
{ id:"b1x488", de:"Luftqualität", art:"die", pl:"", en:"air quality", topic:"media", level:"b1" },
{ id:"b1x489", de:"Feinstaub", art:"der", pl:"", en:"fine particulate matter", topic:"media", level:"b1" },
{ id:"b1x490", de:"Lärmschutz", art:"der", pl:"", en:"noise protection", topic:"media", level:"b1" },
{ id:"b1x491", de:"Einlasskontrolle", art:"die", pl:"-n", en:"entry check", topic:"examday", level:"b1" },
{ id:"b1x492", de:"Personalausweis vorlegen", art:"", pl:"", en:"to show ID", topic:"examday", level:"b1" },
{ id:"b1x493", de:"Hilfsmittelverbot", art:"das", pl:"-e", en:"no-aids rule", topic:"examday", level:"b1" },
{ id:"b1x494", de:"Wörterbuch erlaubt", art:"", pl:"", en:"dictionary allowed", topic:"examday", level:"b1" },
{ id:"b1x495", de:"Antwortbogen ausfüllen", art:"", pl:"", en:"to fill in the answer sheet", topic:"examday", level:"b1" },
{ id:"b1x496", de:"Durchschlag behalten", art:"", pl:"", en:"to keep the carbon copy", topic:"examday", level:"b1" },
{ id:"b1x497", de:"Teilbewertung", art:"die", pl:"-en", en:"section score", topic:"examday", level:"b1" },
{ id:"b1x498", de:"mündlicher Prüfungsteil", art:"der", pl:"-e", en:"oral part", topic:"examday", level:"b1" },
{ id:"b1x499", de:"Partnerprüfung", art:"die", pl:"-en", en:"paired oral exam", topic:"examday", level:"b1" },
{ id:"b1x500", de:"Planungsaufgabe", art:"die", pl:"-n", en:"planning task", topic:"examday", level:"b1" },
{ id:"b1x501", de:"Redemittel", art:"das", pl:"-", en:"set phrase", topic:"examday", level:"b1" },
{ id:"b1x502", de:"Themenblatt", art:"das", pl:"Themenblätter", en:"topic sheet", topic:"examday", level:"b1" },
{ id:"b1x503", de:"Vorbereitungszeit", art:"die", pl:"-en", en:"prep time", topic:"examday", level:"b1" },
{ id:"b1x504", de:"Zeitüberschreitung", art:"die", pl:"-en", en:"overrunning time", topic:"examday", level:"b1" },
{ id:"b1x505", de:"Abgabe", art:"die", pl:"-n", en:"handover / submission", topic:"examday", level:"b1" },
{ id:"b1x506", de:"Nachteilsausgleich", art:"der", pl:"Nachteilsausgleiche", en:"reasonable adjustment", topic:"examday", level:"b1" },
{ id:"b1x507", de:"Attest einreichen", art:"", pl:"", en:"to submit a medical note", topic:"examday", level:"b1" },
{ id:"b1x508", de:"Rücktritt von der Prüfung", art:"der", pl:"Rücktritte", en:"withdrawal from the exam", topic:"examday", level:"b1" },
{ id:"b1x509", de:"Wiederholungsprüfung", art:"die", pl:"-en", en:"resit", topic:"examday", level:"b1" },
{ id:"b1x510", de:"Zertifikatsübergabe", art:"die", pl:"-n", en:"certificate handover", topic:"examday", level:"b1" },
{ id:"b1x511", de:"Notenschlüssel", art:"der", pl:"-", en:"grade scale", topic:"examday", level:"b1" },
{ id:"b1x512", de:"Punktevergabe", art:"die", pl:"-n", en:"marking scheme", topic:"examday", level:"b1" },
{ id:"b1x513", de:"beantragen", art:"", pl:"", en:"to apply for (officially)", topic:"verbs", level:"b1" },
{ id:"b1x514", de:"bewilligen", art:"", pl:"", en:"to approve (an application)", topic:"verbs", level:"b1" },
{ id:"b1x515", de:"ablehnen", art:"", pl:"", en:"to reject", topic:"verbs", level:"b1" },
{ id:"b1x516", de:"widersprechen", art:"", pl:"", en:"to object", topic:"verbs", level:"b1" },
{ id:"b1x517", de:"beschweren", art:"", pl:"", en:"to complain (sich beschweren)", topic:"verbs", level:"b1" },
{ id:"b1x518", de:"reklamieren", art:"", pl:"", en:"to make a complaint (goods)", topic:"verbs", level:"b1" },
{ id:"b1x519", de:"erstatten", art:"", pl:"", en:"to refund", topic:"verbs", level:"b1" },
{ id:"b1x520", de:"kündigen", art:"", pl:"", en:"to give notice / cancel", topic:"verbs", level:"b1" },
{ id:"b1x521", de:"verlängern", art:"", pl:"", en:"to extend", topic:"verbs", level:"b1" },
{ id:"b1x522", de:"unterschreiben", art:"", pl:"", en:"to sign", topic:"verbs", level:"b1" },
{ id:"b1x523", de:"ausfüllen", art:"", pl:"", en:"to fill in", topic:"verbs", level:"b1" },
{ id:"b1x524", de:"einreichen", art:"", pl:"", en:"to submit", topic:"verbs", level:"b1" },
{ id:"b1x525", de:"nachreichen", art:"", pl:"", en:"to submit later", topic:"verbs", level:"b1" },
{ id:"b1x526", de:"nachweisen", art:"", pl:"", en:"to prove", topic:"verbs", level:"b1" },
{ id:"b1x527", de:"bescheinigen", art:"", pl:"", en:"to certify", topic:"verbs", level:"b1" },
{ id:"b1x528", de:"beglaubigen", art:"", pl:"", en:"to officially certify", topic:"verbs", level:"b1" },
{ id:"b1x529", de:"überweisen", art:"", pl:"", en:"to transfer (money)", topic:"verbs", level:"b1" },
{ id:"b1x530", de:"abbuchen", art:"", pl:"", en:"to debit", topic:"verbs", level:"b1" },
{ id:"b1x531", de:"stornieren", art:"", pl:"", en:"to cancel (booking)", topic:"verbs", level:"b1" },
{ id:"b1x532", de:"umbuchen", art:"", pl:"", en:"to rebook", topic:"verbs", level:"b1" },
{ id:"b1x533", de:"entschädigen", art:"", pl:"", en:"to compensate", topic:"verbs", level:"b1" },
{ id:"b1x534", de:"melden", art:"", pl:"", en:"to report / register", topic:"verbs", level:"b1" },
{ id:"b1x535", de:"abmelden", art:"", pl:"", en:"to deregister", topic:"verbs", level:"b1" },
{ id:"b1x536", de:"ummelden", art:"", pl:"", en:"to change registration", topic:"verbs", level:"b1" },
{ id:"b1x537", de:"anmelden", art:"", pl:"", en:"to register", topic:"verbs", level:"b1" },
{ id:"b1x538", de:"absprechen", art:"", pl:"", en:"to agree / coordinate", topic:"verbs", level:"b1" },
{ id:"b1x539", de:"nachhaken", art:"", pl:"", en:"to follow up", topic:"verbs", level:"b1" },
{ id:"b1x540", de:"nachfragen", art:"", pl:"", en:"to ask again / enquire", topic:"verbs", level:"b1" },
{ id:"b1x541", de:"klären", art:"", pl:"", en:"to clarify", topic:"verbs", level:"b1" },
{ id:"b1x542", de:"erledigen", art:"", pl:"", en:"to deal with / finish", topic:"verbs", level:"b1" },
{ id:"b1x543", de:"bearbeiten", art:"", pl:"", en:"to process", topic:"verbs", level:"b1" },
{ id:"b1x544", de:"weiterleiten", art:"", pl:"", en:"to forward", topic:"verbs", level:"b1" },
{ id:"b1x545", de:"sich beschweren", art:"", pl:"", en:"to complain", topic:"verbs", level:"b1" },
{ id:"b1x546", de:"sich erkundigen", art:"", pl:"", en:"to enquire", topic:"verbs", level:"b1" },
{ id:"b1x547", de:"sich informieren", art:"", pl:"", en:"to find out", topic:"verbs", level:"b1" },
{ id:"b1x548", de:"sich krankmelden", art:"", pl:"", en:"to call in sick", topic:"verbs", level:"b1" },
{ id:"b1x549", de:"sich ummelden", art:"", pl:"", en:"to re-register one's address", topic:"verbs", level:"b1" },
{ id:"b1x550", de:"sich einigen", art:"", pl:"", en:"to come to an agreement", topic:"verbs", level:"b1" },
{ id:"b1x551", de:"sich durchsetzen", art:"", pl:"", en:"to assert oneself", topic:"verbs", level:"b1" },
{ id:"b1x552", de:"nachgeben", art:"", pl:"", en:"to give in", topic:"verbs", level:"b1" },
{ id:"b1x553", de:"ablehnen höflich", art:"", pl:"", en:"to decline politely", topic:"verbs", level:"b1" },
{ id:"b1x554", de:"zustimmen", art:"", pl:"", en:"to agree", topic:"verbs", level:"b1" },
{ id:"b1x555", de:"widersprechen höflich", art:"", pl:"", en:"to disagree politely", topic:"verbs", level:"b1" },
{ id:"b1x556", de:"teamfähig", art:"", pl:"", en:"a team player", topic:"adjectives", level:"b1" },
{ id:"b1x557", de:"flexibel", art:"", pl:"", en:"flexible", topic:"adjectives", level:"b1" },
{ id:"b1x558", de:"sorgfältig", art:"", pl:"", en:"careful", topic:"adjectives", level:"b1" },
{ id:"b1x559", de:"gründlich", art:"", pl:"", en:"thorough", topic:"adjectives", level:"b1" },
{ id:"b1x560", de:"freundlich", art:"", pl:"", en:"friendly", topic:"adjectives", level:"b1" },
{ id:"b1x561", de:"sachlich", art:"", pl:"", en:"factual / objective", topic:"adjectives", level:"b1" },
{ id:"b1x562", de:"höflich", art:"", pl:"", en:"polite", topic:"adjectives", level:"b1" },
{ id:"b1x563", de:"verbindlich", art:"", pl:"", en:"binding / committed", topic:"adjectives", level:"b1" },
{ id:"b1x564", de:"unverbindlich", art:"", pl:"", en:"non-binding", topic:"adjectives", level:"b1" },
{ id:"b1x565", de:"dringend", art:"", pl:"", en:"urgent", topic:"adjectives", level:"b1" },
{ id:"b1x566", de:"fristgerecht", art:"", pl:"", en:"on time (deadline)", topic:"adjectives", level:"b1" },
{ id:"b1x567", de:"verspätet", art:"", pl:"", en:"delayed", topic:"adjectives", level:"b1" },
{ id:"b1x568", de:"vollständig", art:"", pl:"", en:"complete", topic:"adjectives", level:"b1" },
{ id:"b1x569", de:"unvollständig", art:"", pl:"", en:"incomplete", topic:"adjectives", level:"b1" },
{ id:"b1x570", de:"gültig", art:"", pl:"", en:"valid", topic:"adjectives", level:"b1" },
{ id:"b1x571", de:"ungültig", art:"", pl:"", en:"invalid", topic:"adjectives", level:"b1" },
{ id:"b1x572", de:"zuständig", art:"", pl:"", en:"responsible (office)", topic:"adjectives", level:"b1" },
{ id:"b1x573", de:"unzuständig", art:"", pl:"", en:"not the right office", topic:"adjectives", level:"b1" },
{ id:"b1x574", de:"barrierefrei", art:"", pl:"", en:"accessible", topic:"adjectives", level:"b1" },
{ id:"b1x575", de:"nachhaltig", art:"", pl:"", en:"sustainable", topic:"adjectives", level:"b1" },
{ id:"b1x576", de:"energieeffizient", art:"", pl:"", en:"energy-efficient", topic:"adjectives", level:"b1" },
{ id:"b1x577", de:"bezahlbar", art:"", pl:"", en:"affordable", topic:"adjectives", level:"b1" },
{ id:"b1x578", de:"unzumutbar", art:"", pl:"", en:"unreasonable", topic:"adjectives", level:"b1" },
{ id:"b1x579", de:"zumutbar", art:"", pl:"", en:"reasonable", topic:"adjectives", level:"b1" },
{ id:"b1x580", de:"mangelhaft", art:"", pl:"", en:"defective", topic:"adjectives", level:"b1" },
{ id:"b1x581", de:"einwandfrei", art:"", pl:"", en:"faultless", topic:"adjectives", level:"b1" },
{ id:"b1x582", de:"unwahrscheinlich", art:"", pl:"", en:"unlikely", topic:"adjectives", level:"b1" },
{ id:"b1x583", de:"optional", art:"", pl:"", en:"optional", topic:"adjectives", level:"b1" },
{ id:"b1x584", de:"verbindlich zugesagt", art:"", pl:"", en:"firmly confirmed", topic:"adjectives", level:"b1" },
{ id:"b1x585", de:"vorläufig", art:"", pl:"", en:"provisional", topic:"adjectives", level:"b1" },
{ id:"b1x586", de:"soziale Ungleichheit", art:"die", pl:"", en:"social inequality", topic:"b2-society", level:"b1" },
{ id:"b1x587", de:"demografischer Wandel", art:"der", pl:"", en:"demographic change", topic:"b2-society", level:"b1" },
{ id:"b1x588", de:"Pflegenotstand", art:"der", pl:"", en:"care-worker shortage", topic:"b2-society", level:"b1" },
{ id:"b1x589", de:"Wohnungsbauoffensive", art:"die", pl:"-n", en:"housing construction drive", topic:"b2-society", level:"b1" },
{ id:"b1x590", de:"Mietendeckel", art:"der", pl:"", en:"rent cap", topic:"b2-society", level:"b1" },
{ id:"b1x591", de:"Bürgerbeteiligung", art:"die", pl:"-en", en:"citizen participation", topic:"b2-society", level:"b1" },
{ id:"b1x592", de:"Wahlbeteiligung", art:"die", pl:"-en", en:"voter turnout", topic:"b2-society", level:"b1" },
{ id:"b1x593", de:"Rechtsstaat", art:"der", pl:"-en", en:"constitutional state", topic:"b2-abstract", level:"b1" },
{ id:"b1x594", de:"Gewaltenteilung", art:"die", pl:"", en:"separation of powers", topic:"b2-abstract", level:"b1" },
{ id:"b1x595", de:"Grundrecht", art:"das", pl:"-e", en:"basic right", topic:"b2-abstract", level:"b1" },
{ id:"b1x596", de:"Automatisierung", art:"die", pl:"-en", en:"automation", topic:"b2-abstract", level:"b1" },
{ id:"b1x597", de:"Nachhaltigkeitsstrategie", art:"die", pl:"-n", en:"sustainability strategy", topic:"b2-abstract", level:"b1" },
{ id:"b1x598", de:"Kreislaufwirtschaft", art:"die", pl:"", en:"circular economy", topic:"b2-abstract", level:"b1" },
{ id:"b1x599", de:"Klimaneutralität", art:"die", pl:"", en:"climate neutrality", topic:"b2-abstract", level:"b1" }
  ]
};
