export default {
  vocab: [
  // people
  { id:"v1", de:"Mensch", art:"der", pl:"-en", en:"human / person", topic:"people", level:"b1" },
  { id:"v2", de:"Name", art:"der", pl:"-n", en:"name", topic:"people", level:"a2" },
  { id:"v3", de:"Vorname", art:"der", pl:"-n", en:"first name", topic:"people", level:"a2" },
  { id:"v4", de:"Nachname", art:"der", pl:"-n", en:"surname", topic:"people", level:"a2" },
  { id:"v5", de:"Adresse", art:"die", pl:"-n", en:"address", topic:"people", level:"a2" },
  { id:"v6", de:"Geburtstag", art:"der", pl:"-e", en:"birthday", topic:"people", level:"a2" },
  { id:"v7", de:"Familie", art:"die", pl:"-n", en:"family", topic:"people", level:"a2" },
  { id:"v8", de:"Eltern", art:"die", pl:"", en:"parents", topic:"people", level:"a2" },
  { id:"v9", de:"Vater", art:"der", pl:"Väter", en:"father", topic:"people", level:"a2" },
  { id:"v10", de:"Mutter", art:"die", pl:"Mütter", en:"mother", topic:"people", level:"a2" },
  { id:"v11", de:"Kind", art:"das", pl:"-er", en:"child", topic:"people", level:"a2" },
  { id:"v12", de:"Sohn", art:"der", pl:"Söhne", en:"son", topic:"people", level:"a2" },
  { id:"v13", de:"Tochter", art:"die", pl:"Töchter", en:"daughter", topic:"people", level:"a2" },
  { id:"v14", de:"Bruder", art:"der", pl:"Brüder", en:"brother", topic:"people", level:"a2" },
  { id:"v15", de:"Schwester", art:"die", pl:"-n", en:"sister", topic:"people", level:"a2" },
  { id:"v16", de:"Freund", art:"der", pl:"-e", en:"friend / boyfriend", topic:"people", level:"a2" },
  { id:"v17", de:"Freundin", art:"die", pl:"-nen", en:"friend / girlfriend", topic:"people", level:"a2" },
  { id:"v18", de:"Nachbar", art:"der", pl:"-n", en:"neighbour", topic:"people", level:"a2" },
  { id:"v19", de:"Kollege", art:"der", pl:"-n", en:"colleague", topic:"people", level:"b1" },
  { id:"v20", de:"Beziehung", art:"die", pl:"-en", en:"relationship", topic:"people", level:"b1" },
  { id:"v21", de:"Hochzeit", art:"die", pl:"-en", en:"wedding", topic:"people", level:"b1" },
  { id:"v22", de:"Nationalität", art:"die", pl:"-en", en:"nationality", topic:"people", level:"b1" },
  { id:"v23", de:"Ausweis", art:"der", pl:"-e", en:"ID card", topic:"people", level:"b1" },
  { id:"v24", de:"Pass", art:"der", pl:"Pässe", en:"passport", topic:"people", level:"b1" },
  { id:"v25", de:"Herkunft", art:"die", pl:"", en:"origin", topic:"people", level:"b1" },
  { id:"v26", de:"Wohnort", art:"der", pl:"-e", en:"place of residence", topic:"people", level:"b1" },
  { id:"v27", de:"Vertrauen", art:"das", pl:"", en:"trust", topic:"people", level:"b2" },
  { id:"v28", de:"Vorurteil", art:"das", pl:"-e", en:"prejudice", topic:"people", level:"b2" },
  { id:"v29", de:"Identität", art:"die", pl:"-en", en:"identity", topic:"people", level:"b2" },
  { id:"v30", de:"Generation", art:"die", pl:"-en", en:"generation", topic:"people", level:"b2" },

  // home
  { id:"h1", de:"Wohnung", art:"die", pl:"-en", en:"apartment", topic:"home", level:"a2" },
  { id:"h2", de:"Haus", art:"das", pl:"Häuser", en:"house", topic:"home", level:"a2" },
  { id:"h3", de:"Zimmer", art:"das", pl:"-", en:"room", topic:"home", level:"a2" },
  { id:"h4", de:"Küche", art:"die", pl:"-n", en:"kitchen", topic:"home", level:"a2" },
  { id:"h5", de:"Badezimmer", art:"das", pl:"-", en:"bathroom", topic:"home", level:"a2" },
  { id:"h6", de:"Miete", art:"die", pl:"-n", en:"rent", topic:"home", level:"b1" },
  { id:"h7", de:"Nebenkosten", art:"die", pl:"", en:"utilities", topic:"home", level:"b1" },
  { id:"h8", de:"Kaution", art:"die", pl:"-en", en:"deposit", topic:"home", level:"b1" },
  { id:"h9", de:"Vermieter", art:"der", pl:"-", en:"landlord", topic:"home", level:"b1" },
  { id:"h10", de:"Mieter", art:"der", pl:"-", en:"tenant", topic:"home", level:"b1" },
  { id:"h11", de:"Mietvertrag", art:"der", pl:"Mietverträge", en:"rental contract", topic:"home", level:"b1" },
  { id:"h12", de:"Heizung", art:"die", pl:"-en", en:"heating", topic:"home", level:"b1" },
  { id:"h13", de:"Umzug", art:"der", pl:"Umzüge", en:"house move", topic:"home", level:"b1" },
  { id:"h14", de:"Möbel", art:"die", pl:"", en:"furniture", topic:"home", level:"a2" },
  { id:"h15", de:"Schrank", art:"der", pl:"Schränke", en:"cupboard", topic:"home", level:"a2" },
  { id:"h16", de:"Kühlschrank", art:"der", pl:"Kühlschränke", en:"fridge", topic:"home", level:"a2" },
  { id:"h17", de:"Nachbarschaft", art:"die", pl:"-en", en:"neighbourhood", topic:"home", level:"b1" },
  { id:"h18", de:"Lage", art:"die", pl:"-n", en:"location", topic:"home", level:"b1" },
  { id:"h19", de:"Lärm", art:"der", pl:"", en:"noise", topic:"home", level:"b1" },
  { id:"h20", de:"Reparatur", art:"die", pl:"-en", en:"repair", topic:"home", level:"b1" },
  { id:"h21", de:"Kündigung", art:"die", pl:"-en", en:"notice (terminate)", topic:"home", level:"b1" },
  { id:"h22", de:"Wohnfläche", art:"die", pl:"-n", en:"living space", topic:"home", level:"b2" },
  { id:"h23", de:"Wohnungsnot", art:"die", pl:"", en:"housing shortage", topic:"home", level:"b2" },
  { id:"h24", de:"Eigentum", art:"das", pl:"", en:"property / ownership", topic:"home", level:"b2" },
  { id:"h25", de:"Sanierung", art:"die", pl:"-en", en:"renovation (major)", topic:"home", level:"b2" },

  // daily
  { id:"d1", de:"Alltag", art:"der", pl:"", en:"everyday life", topic:"daily", level:"b1" },
  { id:"d2", de:"Termin", art:"der", pl:"-e", en:"appointment", topic:"daily", level:"a2" },
  { id:"d3", de:"Uhrzeit", art:"die", pl:"-en", en:"time of day", topic:"daily", level:"a2" },
  { id:"d4", de:"Pause", art:"die", pl:"-n", en:"break", topic:"daily", level:"a2" },
  { id:"d5", de:"Freizeit", art:"die", pl:"", en:"free time", topic:"daily", level:"a2" },
  { id:"d6", de:"Wochenende", art:"das", pl:"-n", en:"weekend", topic:"daily", level:"a2" },
  { id:"d7", de:"Feiertag", art:"der", pl:"-e", en:"public holiday", topic:"daily", level:"b1" },
  { id:"d8", de:"Verspätung", art:"die", pl:"-en", en:"delay", topic:"daily", level:"b1" },
  { id:"d9", de:"Gewohnheit", art:"die", pl:"-en", en:"habit", topic:"daily", level:"b1" },
  { id:"d10", de:"Stress", art:"der", pl:"", en:"stress", topic:"daily", level:"b1" },
  { id:"d11", de:"Routine", art:"die", pl:"-n", en:"routine", topic:"daily", level:"b1" },
  { id:"d12", de:"Haushaltsarbeit", art:"die", pl:"-en", en:"housework", topic:"daily", level:"b1" },
  { id:"d13", de:"Zeitdruck", art:"der", pl:"", en:"time pressure", topic:"daily", level:"b2" },
  { id:"d14", de:"Work-Life-Balance", art:"die", pl:"", en:"work-life balance", topic:"daily", level:"b2" },
  { id:"d15", de:"Erholung", art:"die", pl:"-en", en:"recovery / rest", topic:"daily", level:"b2" },

  // food
  { id:"f1", de:"Mahlzeit", art:"die", pl:"-en", en:"meal", topic:"food", level:"b1" },
  { id:"f2", de:"Frühstück", art:"das", pl:"-e", en:"breakfast", topic:"food", level:"a2" },
  { id:"f3", de:"Gemüse", art:"das", pl:"", en:"vegetables", topic:"food", level:"a2" },
  { id:"f4", de:"Obst", art:"das", pl:"", en:"fruit", topic:"food", level:"a2" },
  { id:"f5", de:"Fleisch", art:"das", pl:"", en:"meat", topic:"food", level:"a2" },
  { id:"f6", de:"Rechnung", art:"die", pl:"-en", en:"bill", topic:"food", level:"a2" },
  { id:"f7", de:"Preis", art:"der", pl:"-e", en:"price", topic:"food", level:"a2" },
  { id:"f8", de:"Rabatt", art:"der", pl:"-e", en:"discount", topic:"food", level:"b1" },
  { id:"f9", de:"Qualität", art:"die", pl:"-en", en:"quality", topic:"food", level:"b1" },
  { id:"f10", de:"Zutat", art:"die", pl:"-en", en:"ingredient", topic:"food", level:"b1" },
  { id:"f11", de:"Rezept", art:"das", pl:"-e", en:"recipe / prescription", topic:"food", level:"b1" },
  { id:"f12", de:"Geschmack", art:"der", pl:"Geschmäcker", en:"taste", topic:"food", level:"b1" },
  { id:"f13", de:"Ernährung", art:"die", pl:"-en", en:"nutrition / diet", topic:"food", level:"b1" },
  { id:"f14", de:"Lebensmittelverschwendung", art:"die", pl:"", en:"food waste", topic:"food", level:"b2" },
  { id:"f15", de:"Nachhaltigkeit", art:"die", pl:"-en", en:"sustainability", topic:"food", level:"b2" },
  { id:"f16", de:"Bio-Produkt", art:"das", pl:"-e", en:"organic product", topic:"food", level:"b2" },
  { id:"f17", de:"Supermarkt", art:"der", pl:"Supermärkte", en:"supermarket", topic:"food", level:"a2" },
  { id:"f18", de:"Kundin", art:"die", pl:"-nen", en:"customer (f)", topic:"food", level:"a2" },

  // work
  { id:"w1", de:"Beruf", art:"der", pl:"-e", en:"profession", topic:"work", level:"a2" },
  { id:"w2", de:"Stelle", art:"die", pl:"-n", en:"job / position", topic:"work", level:"b1" },
  { id:"w3", de:"Bewerbung", art:"die", pl:"-en", en:"application", topic:"work", level:"b1" },
  { id:"w4", de:"Lebenslauf", art:"der", pl:"Lebensläufe", en:"CV", topic:"work", level:"b1" },
  { id:"w5", de:"Vorstellungsgespräch", art:"das", pl:"-e", en:"job interview", topic:"work", level:"b1" },
  { id:"w6", de:"Arbeitgeber", art:"der", pl:"-", en:"employer", topic:"work", level:"b1" },
  { id:"w7", de:"Arbeitnehmer", art:"der", pl:"-", en:"employee", topic:"work", level:"b1" },
  { id:"w8", de:"Gehalt", art:"das", pl:"Gehälter", en:"salary", topic:"work", level:"b1" },
  { id:"w9", de:"Vertrag", art:"der", pl:"Verträge", en:"contract", topic:"work", level:"b1" },
  { id:"w10", de:"Ausbildung", art:"die", pl:"-en", en:"apprenticeship / training", topic:"work", level:"b1" },
  { id:"w11", de:"Erfahrung", art:"die", pl:"-en", en:"experience", topic:"work", level:"b1" },
  { id:"w12", de:"Fähigkeit", art:"die", pl:"-en", en:"ability / skill", topic:"work", level:"b1" },
  { id:"w13", de:"Verantwortung", art:"die", pl:"-en", en:"responsibility", topic:"work", level:"b1" },
  { id:"w14", de:"Kündigung", art:"die", pl:"-en", en:"dismissal / resignation", topic:"work", level:"b1" },
  { id:"w15", de:"Arbeitslosigkeit", art:"die", pl:"", en:"unemployment", topic:"work", level:"b1" },
  { id:"w16", de:"Praktikum", art:"das", pl:"Praktika", en:"internship", topic:"work", level:"b1" },
  { id:"w17", de:"Fortbildung", art:"die", pl:"-en", en:"further training", topic:"work", level:"b1" },
  { id:"w18", de:"Probezeit", art:"die", pl:"-en", en:"probation period", topic:"work", level:"b1" },
  { id:"w19", de:"Beförderung", art:"die", pl:"-en", en:"promotion", topic:"work", level:"b2" },
  { id:"w20", de:"Tarifvertrag", art:"der", pl:"Tarifverträge", en:"collective agreement", topic:"work", level:"b2" },
  { id:"w21", de:"Work-Life-Balance", art:"die", pl:"", en:"work-life balance", topic:"work", level:"b2" },
  { id:"w22", de:"Fachkräftemangel", art:"der", pl:"", en:"skilled labour shortage", topic:"work", level:"b2" },
  { id:"w23", de:"Selbstständigkeit", art:"die", pl:"", en:"self-employment", topic:"work", level:"b2" },
  { id:"w24", de:"Überstunden", art:"die", pl:"", en:"overtime", topic:"work", level:"b1" },
  { id:"w25", de:"Abteilung", art:"die", pl:"-en", en:"department", topic:"work", level:"b1" },

  // health
  { id:"he1", de:"Gesundheit", art:"die", pl:"", en:"health", topic:"health", level:"b1" },
  { id:"he2", de:"Krankheit", art:"die", pl:"-en", en:"illness", topic:"health", level:"a2" },
  { id:"he3", de:"Arzt", art:"der", pl:"Ärzte", en:"doctor", topic:"health", level:"a2" },
  { id:"he4", de:"Apotheke", art:"die", pl:"-n", en:"pharmacy", topic:"health", level:"a2" },
  { id:"he5", de:"Medikament", art:"das", pl:"-e", en:"medicine", topic:"health", level:"b1" },
  { id:"he6", de:"Rezept", art:"das", pl:"-e", en:"prescription", topic:"health", level:"b1" },
  { id:"he7", de:"Schmerz", art:"der", pl:"-en", en:"pain", topic:"health", level:"a2" },
  { id:"he8", de:"Untersuchung", art:"die", pl:"-en", en:"examination", topic:"health", level:"b1" },
  { id:"he9", de:"Krankenkasse", art:"die", pl:"-n", en:"health insurance fund", topic:"health", level:"b1" },
  { id:"he10", de:"Unfall", art:"der", pl:"Unfälle", en:"accident", topic:"health", level:"b1" },
  { id:"he11", de:"Verletzung", art:"die", pl:"-en", en:"injury", topic:"health", level:"b1" },
  { id:"he12", de:"Impfung", art:"die", pl:"-en", en:"vaccination", topic:"health", level:"b1" },
  { id:"he13", de:"Krankschreibung", art:"die", pl:"-en", en:"sick note", topic:"health", level:"b1" },
  { id:"he14", de:"Prävention", art:"die", pl:"-en", en:"prevention", topic:"health", level:"b2" },
  { id:"he15", de:"Diagnose", art:"die", pl:"-n", en:"diagnosis", topic:"health", level:"b2" },
  { id:"he16", de:"Behandlung", art:"die", pl:"-en", en:"treatment", topic:"health", level:"b2" },
  { id:"he17", de:"Sucht", art:"die", pl:"Süchte", en:"addiction", topic:"health", level:"b2" },
  { id:"he18", de:"psychische Gesundheit", art:"die", pl:"", en:"mental health", topic:"health", level:"b2" },

  // travel
  { id:"t1", de:"Reise", art:"die", pl:"-n", en:"trip", topic:"travel", level:"a2" },
  { id:"t2", de:"Fahrkarte", art:"die", pl:"-n", en:"ticket", topic:"travel", level:"a2" },
  { id:"t3", de:"Bahnhof", art:"der", pl:"Bahnhöfe", en:"station", topic:"travel", level:"a2" },
  { id:"t4", de:"Flugzeug", art:"das", pl:"-e", en:"plane", topic:"travel", level:"a2" },
  { id:"t5", de:"Verspätung", art:"die", pl:"-en", en:"delay", topic:"travel", level:"b1" },
  { id:"t6", de:"Anschluss", art:"der", pl:"Anschlüsse", en:"connection", topic:"travel", level:"b1" },
  { id:"t7", de:"Unterkunft", art:"die", pl:"Unterkünfte", en:"accommodation", topic:"travel", level:"b1" },
  { id:"t8", de:"Buchung", art:"die", pl:"-en", en:"booking", topic:"travel", level:"b1" },
  { id:"t9", de:"Gepäck", art:"das", pl:"", en:"luggage", topic:"travel", level:"b1" },
  { id:"t10", de:"Sehenswürdigkeit", art:"die", pl:"-en", en:"sight", topic:"travel", level:"b1" },
  { id:"t11", de:"Wetter", art:"das", pl:"", en:"weather", topic:"travel", level:"a2" },
  { id:"t12", de:"Stau", art:"der", pl:"-s", en:"traffic jam", topic:"travel", level:"b1" },
  { id:"t13", de:"Führerschein", art:"der", pl:"-e", en:"driving licence", topic:"travel", level:"b1" },
  { id:"t14", de:"Nachhaltiger Tourismus", art:"der", pl:"", en:"sustainable tourism", topic:"travel", level:"b2" },
  { id:"t15", de:"Fernverkehr", art:"der", pl:"", en:"long-distance transport", topic:"travel", level:"b2" },
  { id:"t16", de:"Haltestelle", art:"die", pl:"-n", en:"stop", topic:"travel", level:"a2" },

  // school
  { id:"s1", de:"Kurs", art:"der", pl:"-e", en:"course", topic:"school", level:"a2" },
  { id:"s2", de:"Prüfung", art:"die", pl:"-en", en:"exam", topic:"school", level:"a2" },
  { id:"s3", de:"Anmeldung", art:"die", pl:"-en", en:"registration", topic:"school", level:"b1" },
  { id:"s4", de:"Gebühr", art:"die", pl:"-en", en:"fee", topic:"school", level:"b1" },
  { id:"s5", de:"Wortschatz", art:"der", pl:"Wortschätze", en:"vocabulary", topic:"school", level:"b1" },
  { id:"s6", de:"Grammatik", art:"die", pl:"-en", en:"grammar", topic:"school", level:"b1" },
  { id:"s7", de:"Aussprache", art:"die", pl:"-n", en:"pronunciation", topic:"school", level:"b1" },
  { id:"s8", de:"Niveau", art:"das", pl:"-s", en:"level", topic:"school", level:"b1" },
  { id:"s9", de:"Abschluss", art:"der", pl:"Abschlüsse", en:"qualification", topic:"school", level:"b1" },
  { id:"s10", de:"Volkshochschule", art:"die", pl:"-n", en:"adult education centre", topic:"school", level:"b1" },
  { id:"s11", de:"Integrationskurs", art:"der", pl:"-e", en:"integration course", topic:"school", level:"b1" },
  { id:"s12", de:"Zertifikat", art:"das", pl:"-e", en:"certificate", topic:"school", level:"b1" },
  { id:"s13", de:"Bildungschance", art:"die", pl:"-n", en:"educational opportunity", topic:"school", level:"b2" },
  { id:"s14", de:"Hochschulzugang", art:"der", pl:"Hochschulzugänge", en:"university entrance", topic:"school", level:"b2" },
  { id:"s15", de:"Lebenslanges Lernen", art:"das", pl:"", en:"lifelong learning", topic:"school", level:"b2" },

  // services
  { id:"sv1", de:"Behörde", art:"die", pl:"-n", en:"authority / office", topic:"services", level:"b1" },
  { id:"sv2", de:"Antrag", art:"der", pl:"Anträge", en:"application / form", topic:"services", level:"b1" },
  { id:"sv3", de:"Formular", art:"das", pl:"-e", en:"form", topic:"services", level:"b1" },
  { id:"sv4", de:"Konto", art:"das", pl:"Konten", en:"account", topic:"services", level:"b1" },
  { id:"sv5", de:"Überweisung", art:"die", pl:"-en", en:"bank transfer", topic:"services", level:"b1" },
  { id:"sv6", de:"Versicherung", art:"die", pl:"-en", en:"insurance", topic:"services", level:"b1" },
  { id:"sv7", de:"Paket", art:"das", pl:"-e", en:"parcel", topic:"services", level:"a2" },
  { id:"sv8", de:"Steuer", art:"die", pl:"-n", en:"tax", topic:"services", level:"b1" },
  { id:"sv9", de:"Bürgeramt", art:"das", pl:"Bürgerämter", en:"citizens' office", topic:"services", level:"b1" },
  { id:"sv10", de:"Meldebescheinigung", art:"die", pl:"-en", en:"registration certificate", topic:"services", level:"b1" },
  { id:"sv11", de:"Datenschutz", art:"der", pl:"", en:"data protection", topic:"services", level:"b2" },
  { id:"sv12", de:"Bürokratie", art:"die", pl:"-n", en:"bureaucracy", topic:"services", level:"b2" },
  { id:"sv13", de:"Anspruch", art:"der", pl:"Ansprüche", en:"entitlement / claim", topic:"services", level:"b2" },
  { id:"sv14", de:"Bescheid", art:"der", pl:"-e", en:"official notice", topic:"services", level:"b2" },

  // opinions
  { id:"o1", de:"Meinung", art:"die", pl:"-en", en:"opinion", topic:"opinions", level:"b1" },
  { id:"o2", de:"Vorschlag", art:"der", pl:"Vorschläge", en:"suggestion", topic:"opinions", level:"b1" },
  { id:"o3", de:"Grund", art:"der", pl:"Gründe", en:"reason", topic:"opinions", level:"b1" },
  { id:"o4", de:"Vorteil", art:"der", pl:"-e", en:"advantage", topic:"opinions", level:"b1" },
  { id:"o5", de:"Nachteil", art:"der", pl:"-e", en:"disadvantage", topic:"opinions", level:"b1" },
  { id:"o6", de:"Lösung", art:"die", pl:"-en", en:"solution", topic:"opinions", level:"b1" },
  { id:"o7", de:"Möglichkeit", art:"die", pl:"-en", en:"possibility", topic:"opinions", level:"b1" },
  { id:"o8", de:"Entscheidung", art:"die", pl:"-en", en:"decision", topic:"opinions", level:"b1" },
  { id:"o9", de:"Entwicklung", art:"die", pl:"-en", en:"development", topic:"opinions", level:"b1" },
  { id:"o10", de:"Unterschied", art:"der", pl:"-e", en:"difference", topic:"opinions", level:"b1" },
  { id:"o11", de:"Vergleich", art:"der", pl:"-e", en:"comparison", topic:"opinions", level:"b1" },
  { id:"o12", de:"Ziel", art:"das", pl:"-e", en:"goal", topic:"opinions", level:"b1" },
  { id:"o13", de:"Erfolg", art:"der", pl:"-e", en:"success", topic:"opinions", level:"b1" },
  { id:"o14", de:"Hoffnung", art:"die", pl:"-en", en:"hope", topic:"opinions", level:"b1" },
  { id:"o15", de:"Argument", art:"das", pl:"-e", en:"argument", topic:"opinions", level:"b2" },
  { id:"o16", de:"Standpunkt", art:"der", pl:"-e", en:"point of view", topic:"opinions", level:"b2" },
  { id:"o17", de:"Kompromiss", art:"der", pl:"-e", en:"compromise", topic:"opinions", level:"b2" },
  { id:"o18", de:"Auswirkung", art:"die", pl:"-en", en:"effect / impact", topic:"opinions", level:"b2" },

  // media
  { id:"m1", de:"Nachricht", art:"die", pl:"-en", en:"message / news item", topic:"media", level:"b1" },
  { id:"m2", de:"Zeitung", art:"die", pl:"-en", en:"newspaper", topic:"media", level:"a2" },
  { id:"m3", de:"Werbung", art:"die", pl:"-en", en:"advertising", topic:"media", level:"b1" },
  { id:"m4", de:"Privatsphäre", art:"die", pl:"-n", en:"privacy", topic:"media", level:"b1" },
  { id:"m5", de:"Umwelt", art:"die", pl:"-en", en:"environment", topic:"media", level:"b1" },
  { id:"m6", de:"Klimawandel", art:"der", pl:"", en:"climate change", topic:"media", level:"b1" },
  { id:"m7", de:"Müll", art:"der", pl:"", en:"rubbish", topic:"media", level:"b1" },
  { id:"m8", de:"Abhängigkeit", art:"die", pl:"-en", en:"addiction / dependence", topic:"media", level:"b2" },
  { id:"m9", de:"Meinungsfreiheit", art:"die", pl:"-en", en:"freedom of opinion", topic:"media", level:"b2" },
  { id:"m10", de:"Desinformation", art:"die", pl:"-en", en:"disinformation", topic:"media", level:"b2" },
  { id:"m11", de:"Öffentlichkeit", art:"die", pl:"-en", en:"the public", topic:"media", level:"b2" },
  { id:"m12", de:"Verbraucher", art:"der", pl:"-", en:"consumer", topic:"media", level:"b2" },

  // b2 abstract
  { id:"b21", de:"Gesellschaft", art:"die", pl:"-en", en:"society", topic:"b2-abstract", level:"b2" },
  { id:"b22", de:"Gleichberechtigung", art:"die", pl:"-en", en:"equal rights", topic:"b2-abstract", level:"b2" },
  { id:"b23", de:"Integration", art:"die", pl:"-en", en:"integration", topic:"b2-abstract", level:"b2" },
  { id:"b24", de:"Migration", art:"die", pl:"-en", en:"migration", topic:"b2-abstract", level:"b2" },
  { id:"b25", de:"Demokratie", art:"die", pl:"-n", en:"democracy", topic:"b2-abstract", level:"b2" },
  { id:"b26", de:"Wahl", art:"die", pl:"-en", en:"election / choice", topic:"b2-abstract", level:"b2" },
  { id:"b27", de:"Gesetz", art:"das", pl:"-e", en:"law", topic:"b2-abstract", level:"b2" },
  { id:"b28", de:"Recht", art:"das", pl:"-e", en:"right / law", topic:"b2-abstract", level:"b2" },
  { id:"b29", de:"Pflicht", art:"die", pl:"-en", en:"duty", topic:"b2-abstract", level:"b1" },
  { id:"b210", de:"Freiheit", art:"die", pl:"-en", en:"freedom", topic:"b2-abstract", level:"b2" },
  { id:"b211", de:"Gerechtigkeit", art:"die", pl:"-en", en:"justice", topic:"b2-abstract", level:"b2" },
  { id:"b212", de:"Forschung", art:"die", pl:"-en", en:"research", topic:"b2-abstract", level:"b2" },
  { id:"b213", de:"Wissenschaft", art:"die", pl:"-en", en:"science", topic:"b2-abstract", level:"b2" },
  { id:"b214", de:"Technologie", art:"die", pl:"-n", en:"technology", topic:"b2-abstract", level:"b2" },
  { id:"b215", de:"künstliche Intelligenz", art:"die", pl:"", en:"artificial intelligence", topic:"b2-abstract", level:"b2" },
  { id:"b216", de:"Herausforderung", art:"die", pl:"-en", en:"challenge", topic:"b2-abstract", level:"b2" },
  { id:"b217", de:"Voraussetzung", art:"die", pl:"-en", en:"prerequisite", topic:"b2-abstract", level:"b2" },
  { id:"b218", de:"Zusammenhang", art:"der", pl:"Zusammenhänge", en:"connection / context", topic:"b2-abstract", level:"b2" },
  { id:"b219", de:"Maßnahme", art:"die", pl:"-n", en:"measure (action)", topic:"b2-abstract", level:"b2" },
  { id:"b220", de:"Bedeutung", art:"die", pl:"-en", en:"meaning / importance", topic:"b2-abstract", level:"b2" },

  // b2 society
  { id:"bs1", de:"Bevölkerung", art:"die", pl:"-en", en:"population", topic:"b2-society", level:"b2" },
  { id:"bs2", de:"Rente", art:"die", pl:"-n", en:"pension", topic:"b2-society", level:"b2" },
  { id:"bs3", de:"Kinderbetreuung", art:"die", pl:"-en", en:"childcare", topic:"b2-society", level:"b2" },
  { id:"bs4", de:"Mindestlohn", art:"der", pl:"Mindestlöhne", en:"minimum wage", topic:"b2-society", level:"b2" },
  { id:"bs5", de:"Wohnungsbau", art:"der", pl:"", en:"housing construction", topic:"b2-society", level:"b2" },
  { id:"bs6", de:"Öffentlicher Nahverkehr", art:"der", pl:"", en:"local public transport", topic:"b2-society", level:"b1" },
  { id:"bs7", de:"Energiewende", art:"die", pl:"-n", en:"energy transition", topic:"b2-society", level:"b2" },
  { id:"bs8", de:"Treibhausgas", art:"das", pl:"-e", en:"greenhouse gas", topic:"b2-society", level:"b2" },
  { id:"bs9", de:"Ehrenamt", art:"das", pl:"Ehrenämter", en:"volunteering", topic:"b2-society", level:"b2" },
  { id:"bs10", de:"Chancengleichheit", art:"die", pl:"", en:"equal opportunity", topic:"b2-society", level:"b2" },
  { id:"bs11", de:"Diskriminierung", art:"die", pl:"-en", en:"discrimination", topic:"b2-society", level:"b2" },
  { id:"bs12", de:"Globalisierung", art:"die", pl:"-en", en:"globalisation", topic:"b2-society", level:"b2" },
  { id:"bs13", de:"Wirtschaft", art:"die", pl:"-en", en:"economy", topic:"b2-society", level:"b2" },
  { id:"bs14", de:"Arbeitsmarkt", art:"der", pl:"Arbeitsmärkte", en:"labour market", topic:"b2-society", level:"b2" },
  { id:"bs15", de:"Inflation", art:"die", pl:"-en", en:"inflation", topic:"b2-society", level:"b2" },
  { id:"cv1", de:"anfangen", art:"", pl:"hat angefangen", en:"to begin", topic:"verbs", level:"a2" },
  { id:"cv2", de:"aufhören", art:"", pl:"hat aufgehört", en:"to stop", topic:"verbs", level:"a2" },
  { id:"cv3", de:"bekommen", art:"", pl:"hat bekommen", en:"to receive / get", topic:"verbs", level:"a2" },
  { id:"cv4", de:"besuchen", art:"", pl:"hat besucht", en:"to visit", topic:"verbs", level:"a2" },
  { id:"cv5", de:"bestehen", art:"", pl:"hat bestanden", en:"to pass (an exam)", topic:"verbs", level:"b1" },
  { id:"cv6", de:"erzählen", art:"", pl:"hat erzählt", en:"to tell (a story)", topic:"verbs", level:"a2" },
  { id:"cv7", de:"erklären", art:"", pl:"hat erklärt", en:"to explain", topic:"verbs", level:"b1" },
  { id:"cv8", de:"empfehlen", art:"", pl:"hat empfohlen", en:"to recommend", topic:"verbs", level:"b1" },
  { id:"cv9", de:"entscheiden", art:"", pl:"hat entschieden", en:"to decide", topic:"verbs", level:"b1" },
  { id:"cv10", de:"gefallen", art:"", pl:"hat gefallen", en:"to please / like", topic:"verbs", level:"a2" },
  { id:"cv11", de:"gehören", art:"", pl:"hat gehört", en:"to belong", topic:"verbs", level:"a2" },
  { id:"cv12", de:"hoffen", art:"", pl:"hat gehofft", en:"to hope", topic:"verbs", level:"a2" },
  { id:"cv13", de:"kennen", art:"", pl:"hat gekannt", en:"to know a person/place", topic:"verbs", level:"a2" },
  { id:"cv14", de:"wissen", art:"", pl:"hat gewusst", en:"to know a fact", topic:"verbs", level:"a2" },
  { id:"cv15", de:"lassen", art:"", pl:"hat gelassen", en:"to let / have something done", topic:"verbs", level:"b1" },
  { id:"cv16", de:"passieren", art:"", pl:"ist passiert", en:"to happen", topic:"verbs", level:"a2" },
  { id:"cv17", de:"schaffen", art:"", pl:"hat geschafft", en:"to manage / succeed", topic:"verbs", level:"b1" },
  { id:"cv18", de:"stattfinden", art:"", pl:"hat stattgefunden", en:"to take place", topic:"verbs", level:"b1" },
  { id:"cv19", de:"vereinbaren", art:"", pl:"hat vereinbart", en:"to arrange / agree", topic:"verbs", level:"b1" },
  { id:"cv20", de:"vergleichen", art:"", pl:"hat verglichen", en:"to compare", topic:"verbs", level:"b1" },
  { id:"cv21", de:"verlieren", art:"", pl:"hat verloren", en:"to lose", topic:"verbs", level:"a2" },
  { id:"cv22", de:"vermeiden", art:"", pl:"hat vermieden", en:"to avoid", topic:"verbs", level:"b1" },
  { id:"cv23", de:"versuchen", art:"", pl:"hat versucht", en:"to try", topic:"verbs", level:"a2" },
  { id:"cv24", de:"vorschlagen", art:"", pl:"hat vorgeschlagen", en:"to suggest", topic:"verbs", level:"b1" },
  { id:"cv25", de:"umziehen", art:"", pl:"ist umgezogen", en:"to move house", topic:"verbs", level:"b1" },
  { id:"cv26", de:"sich bewerben", art:"", pl:"hat sich beworben", en:"to apply (for a job)", topic:"verbs", level:"b1" },
  { id:"cv27", de:"sich erinnern", art:"", pl:"hat sich erinnert", en:"to remember", topic:"verbs", level:"b1" },
  { id:"cv28", de:"sich freuen", art:"", pl:"hat sich gefreut", en:"to be glad", topic:"verbs", level:"a2" },
  { id:"cv29", de:"sich interessieren", art:"", pl:"hat sich interessiert", en:"to be interested", topic:"verbs", level:"b1" },
  { id:"cv30", de:"überzeugen", art:"", pl:"hat überzeugt", en:"to convince", topic:"verbs", level:"b2" },
  { id:"cv31", de:"berücksichtigen", art:"", pl:"hat berücksichtigt", en:"to take into account", topic:"verbs", level:"b2" },
  { id:"cv32", de:"verursachen", art:"", pl:"hat verursacht", en:"to cause", topic:"verbs", level:"b2" },
  { id:"aj1", de:"wichtig", art:"", pl:"wichtiger / am wichtigsten", en:"important", topic:"adjectives", level:"a2" },
  { id:"aj2", de:"möglich", art:"", pl:"", en:"possible", topic:"adjectives", level:"a2" },
  { id:"aj3", de:"nötig", art:"", pl:"", en:"necessary", topic:"adjectives", level:"b1" },
  { id:"aj4", de:"günstig", art:"", pl:"", en:"good value / favourable", topic:"adjectives", level:"b1" },
  { id:"aj5", de:"zuverlässig", art:"", pl:"", en:"reliable", topic:"adjectives", level:"b1" },
  { id:"aj6", de:"pünktlich", art:"", pl:"", en:"punctual / on time", topic:"adjectives", level:"a2" },
  { id:"aj7", de:"geeignet", art:"", pl:"", en:"suitable", topic:"adjectives", level:"b1" },
  { id:"aj8", de:"erforderlich", art:"", pl:"", en:"required", topic:"adjectives", level:"b2" },
  { id:"aj9", de:"umweltfreundlich", art:"", pl:"", en:"environmentally friendly", topic:"adjectives", level:"b1" },
  { id:"aj10", de:"überzeugt", art:"", pl:"", en:"convinced", topic:"adjectives", level:"b2" },
  { id:"aj11", de:"verantwortlich", art:"", pl:"", en:"responsible", topic:"adjectives", level:"b1" },
  { id:"aj12", de:"selbstständig", art:"", pl:"", en:"independent / self-employed", topic:"adjectives", level:"b1" },
  { id:"aj13", de:"belastbar", art:"", pl:"", en:"resilient", topic:"adjectives", level:"b2" },
  { id:"aj14", de:"spannend", art:"", pl:"", en:"exciting", topic:"adjectives", level:"a2" },
  { id:"aj15", de:"langweilig", art:"", pl:"", en:"boring", topic:"adjectives", level:"a2" },
  { id:"aj16", de:"zufrieden", art:"", pl:"", en:"satisfied", topic:"adjectives", level:"b1" },
  { id:"aj17", de:"enttäuscht", art:"", pl:"", en:"disappointed", topic:"adjectives", level:"b1" },
  { id:"aj18", de:"wahrscheinlich", art:"", pl:"", en:"probable", topic:"adjectives", level:"b2" },
  { id:"aj19", de:"notwendig", art:"", pl:"", en:"necessary", topic:"adjectives", level:"b2" },
  { id:"aj20", de:"erfolgreich", art:"", pl:"", en:"successful", topic:"adjectives", level:"b1" },

  // exam-day / Amt survival (high yield for B1 letters + Lesen)
  { id:"ex1", de:"Ausweis", art:"der", pl:"-e", en:"ID card", topic:"examday", level:"a2" },
  { id:"ex2", de:"Anmeldung", art:"die", pl:"-en", en:"registration / sign-up", topic:"examday", level:"b1" },
  { id:"ex3", de:"Termin", art:"der", pl:"-e", en:"appointment", topic:"examday", level:"a2" },
  { id:"ex4", de:"Wartezimmer", art:"das", pl:"-", en:"waiting room", topic:"examday", level:"a2" },
  { id:"ex5", de:"Prüfungsordnung", art:"die", pl:"-en", en:"exam regulations", topic:"examday", level:"b1" },
  { id:"ex6", de:"Antwortbogen", art:"der", pl:"-bögen", en:"answer sheet", topic:"examday", level:"b1" },
  { id:"ex7", de:"Durchschlag", art:"der", pl:"-schläge", en:"carbon copy / duplicate", topic:"examday", level:"b2" },
  { id:"ex8", de:"Bearbeitungszeit", art:"die", pl:"-en", en:"processing / working time", topic:"examday", level:"b1" },
  { id:"ex9", de:"Hilfsmittel", art:"das", pl:"-", en:"aids / allowed materials", topic:"examday", level:"b1" },
  { id:"ex10", de:"Bestehen", art:"das", pl:"", en:"passing (an exam)", topic:"examday", level:"b1" },
  { id:"ex11", de:"Durchfallen", art:"das", pl:"", en:"failing", topic:"examday", level:"b1" },
  { id:"ex12", de:"Mündliche Prüfung", art:"die", pl:"-en", en:"oral exam", topic:"examday", level:"b1" },
  { id:"ex13", de:"Schriftliche Prüfung", art:"die", pl:"-en", en:"written exam", topic:"examday", level:"b1" },
  { id:"ex14", de:"Punktzahl", art:"die", pl:"-en", en:"score / points", topic:"examday", level:"b1" },
  { id:"ex15", de:"Zertifikat", art:"das", pl:"-e", en:"certificate", topic:"examday", level:"b1" },
  { id:"ex16", de:"Personalausweis", art:"der", pl:"-e", en:"national ID card", topic:"examday", level:"a2" },
  { id:"ex17", de:"Passfoto", art:"das", pl:"-s", en:"passport photo", topic:"examday", level:"a2" },
  { id:"ex18", de:"Behörde", art:"die", pl:"-n", en:"authority / office", topic:"examday", level:"b1" },
  { id:"ex19", de:"Formular", art:"das", pl:"-e", en:"form", topic:"examday", level:"a2" },
  { id:"ex20", de:"Unterschrift", art:"die", pl:"-en", en:"signature", topic:"examday", level:"a2" },
  { id:"ex21", de:"Frist", art:"die", pl:"-en", en:"deadline", topic:"examday", level:"b1" },
  { id:"ex22", de:"Verlängerung", art:"die", pl:"-en", en:"extension", topic:"examday", level:"b1" },
  { id:"ex23", de:"Bescheinigung", art:"die", pl:"-en", en:"certificate / confirmation", topic:"examday", level:"b1" },
  { id:"ex24", de:"Krankheit", art:"die", pl:"-en", en:"illness", topic:"examday", level:"a2" },
  { id:"ex25", de:"Attest", art:"das", pl:"-e", en:"doctor's note", topic:"examday", level:"b1" },

  // extra housing / Amt / work high-frequency
  { id:"hx1", de:"Kaution", art:"die", pl:"-en", en:"deposit (rent)", topic:"home", level:"b1" },
  { id:"hx2", de:"Nebenkosten", art:"die", pl:"", en:"additional rent costs", topic:"home", level:"b1" },
  { id:"hx3", de:"Vermieter", art:"der", pl:"-", en:"landlord", topic:"home", level:"b1" },
  { id:"hx4", de:"Mieter", art:"der", pl:"-", en:"tenant", topic:"home", level:"b1" },
  { id:"hx5", de:"Kündigung", art:"die", pl:"-en", en:"notice / termination", topic:"home", level:"b1" },
  { id:"hx6", de:"Renovierung", art:"die", pl:"-en", en:"renovation", topic:"home", level:"b1" },
  { id:"hx7", de:"Hausverwaltung", art:"die", pl:"-en", en:"property management", topic:"home", level:"b1" },
  { id:"hx8", de:"Stockwerk", art:"das", pl:"-e", en:"floor / storey", topic:"home", level:"a2" },
  { id:"hx9", de:"Keller", art:"der", pl:"-", en:"basement", topic:"home", level:"a2" },
  { id:"hx10", de:"Dachboden", art:"der", pl:"-böden", en:"attic", topic:"home", level:"b1" },

  { id:"wx1", de:"Bewerbung", art:"die", pl:"-en", en:"application", topic:"work", level:"b1" },
  { id:"wx2", de:"Lebenslauf", art:"der", pl:"-läufe", en:"CV / résumé", topic:"work", level:"b1" },
  { id:"wx3", de:"Vorstellungsgespräch", art:"das", pl:"-e", en:"job interview", topic:"work", level:"b1" },
  { id:"wx4", de:"Probezeit", art:"die", pl:"-en", en:"probation period", topic:"work", level:"b1" },
  { id:"wx5", de:"Überstunde", art:"die", pl:"-n", en:"overtime hour", topic:"work", level:"b1" },
  { id:"wx6", de:"Gehalt", art:"das", pl:"Gehälter", en:"salary", topic:"work", level:"b1" },
  { id:"wx7", de:"Kündigungsschutz", art:"der", pl:"", en:"employment protection", topic:"work", level:"b2" },
  { id:"wx8", de:"Teilzeit", art:"die", pl:"", en:"part-time work", topic:"work", level:"b1" },
  { id:"wx9", de:"Vollzeit", art:"die", pl:"", en:"full-time work", topic:"work", level:"b1" },
  { id:"wx10", de:"Zeugnis", art:"das", pl:"-se", en:"reference / report", topic:"work", level:"b1" },

  { id:"sx1", de:"Überweisung", art:"die", pl:"-en", en:"bank transfer", topic:"services", level:"b1" },
  { id:"sx2", de:"Lastschrift", art:"die", pl:"-en", en:"direct debit", topic:"services", level:"b1" },
  { id:"sx3", de:"Konto", art:"das", pl:"Konten", en:"account", topic:"services", level:"a2" },
  { id:"sx4", de:"PIN", art:"die", pl:"-s", en:"PIN code", topic:"services", level:"a2" },
  { id:"sx5", de:"Steuererklärung", art:"die", pl:"-en", en:"tax return", topic:"services", level:"b2" },
  { id:"sx6", de:"Kindergeld", art:"das", pl:"", en:"child benefit", topic:"services", level:"b1" },
  { id:"sx7", de:"Wohngeld", art:"das", pl:"", en:"housing benefit", topic:"services", level:"b1" },
  { id:"sx8", de:"Bürgeramt", art:"das", pl:"-ämter", en:"citizens' office", topic:"services", level:"b1" },
  { id:"sx9", de:"Meldebescheinigung", art:"die", pl:"-en", en:"registration certificate", topic:"services", level:"b1" },
  { id:"sx10", de:"Krankenkasse", art:"die", pl:"-n", en:"health insurance fund", topic:"services", level:"b1" },

  { id:"tx1", de:"Verspätung", art:"die", pl:"-en", en:"delay", topic:"travel", level:"a2" },
  { id:"tx2", de:"Umleitung", art:"die", pl:"-en", en:"detour / diversion", topic:"travel", level:"b1" },
  { id:"tx3", de:"Gleis", art:"das", pl:"-e", en:"platform / track", topic:"travel", level:"a2" },
  { id:"tx4", de:"Fahrkarte", art:"die", pl:"-n", en:"ticket", topic:"travel", level:"a2" },
  { id:"tx5", de:"Reservierung", art:"die", pl:"-en", en:"reservation", topic:"travel", level:"b1" },
  { id:"tx6", de:"Anschluss", art:"der", pl:"Anschlüsse", en:"connection (train)", topic:"travel", level:"b1" },
  { id:"tx7", de:"Streik", art:"der", pl:"-s", en:"strike", topic:"travel", level:"b1" },
  { id:"tx8", de:"Stau", art:"der", pl:"-s", en:"traffic jam", topic:"travel", level:"a2" },

  { id:"ox1", de:"Vorteil", art:"der", pl:"-e", en:"advantage", topic:"opinions", level:"b1" },
  { id:"ox2", de:"Nachteil", art:"der", pl:"-e", en:"disadvantage", topic:"opinions", level:"b1" },
  { id:"ox3", de:"Meinung", art:"die", pl:"-en", en:"opinion", topic:"opinions", level:"a2" },
  { id:"ox4", de:"Vorschlag", art:"der", pl:"Vorschläge", en:"suggestion", topic:"opinions", level:"b1" },
  { id:"ox5", de:"Einigung", art:"die", pl:"-en", en:"agreement", topic:"opinions", level:"b1" },
  { id:"ox6", de:"Kompromiss", art:"der", pl:"-e", en:"compromise", topic:"opinions", level:"b1" },
  { id:"ox7", de:"Argument", art:"das", pl:"-e", en:"argument", topic:"opinions", level:"b1" },
  { id:"ox8", de:"Standpunkt", art:"der", pl:"-e", en:"point of view", topic:"opinions", level:"b2" },

  { id:"b2x1", de:"Nachhaltigkeit", art:"die", pl:"", en:"sustainability", topic:"b2-abstract", level:"b2" },
  { id:"b2x2", de:"Gleichberechtigung", art:"die", pl:"", en:"equal rights", topic:"b2-abstract", level:"b2" },
  { id:"b2x3", de:"Digitalisierung", art:"die", pl:"", en:"digitalisation", topic:"b2-abstract", level:"b2" },
  { id:"b2x4", de:"Fachkräftemangel", art:"der", pl:"", en:"skilled-labour shortage", topic:"b2-society", level:"b2" },
  { id:"b2x5", de:"Mindestlohn", art:"der", pl:"-löhne", en:"minimum wage", topic:"b2-society", level:"b2" },
  { id:"b2x6", de:"Wohnungsnot", art:"die", pl:"", en:"housing shortage", topic:"b2-society", level:"b2" },
  { id:"b2x7", de:"Energiewende", art:"die", pl:"", en:"energy transition", topic:"b2-society", level:"b2" },
  { id:"b2x8", de:"Rente", art:"die", pl:"-n", en:"pension", topic:"b2-society", level:"b2" },
  { id:"b2x9", de:"Inflation", art:"die", pl:"-en", en:"inflation", topic:"b2-society", level:"b2" },
  { id:"b2x10", de:"Klimawandel", art:"der", pl:"", en:"climate change", topic:"b2-society", level:"b2" },
  { id:"hx11", de:"Schimmel", art:"der", pl:"", en:"mould", topic:"home", level:"b1" },
  { id:"hx12", de:"Hausmeister", art:"der", pl:"-", en:"caretaker / janitor", topic:"home", level:"b1" },
  { id:"hx13", de:"Wohngemeinschaft", art:"die", pl:"-en", en:"shared flat (WG)", topic:"home", level:"b1" },
  { id:"hx14", de:"Balkon", art:"der", pl:"-e", en:"balcony", topic:"home", level:"a2" },
  { id:"hx15", de:"Treppenhaus", art:"das", pl:"Treppenhäuser", en:"stairwell", topic:"home", level:"b1" },
  { id:"hx16", de:"Mülltrennung", art:"die", pl:"", en:"waste separation", topic:"home", level:"b1" },
  { id:"hx17", de:"Wohnungsbesichtigung", art:"die", pl:"-en", en:"flat viewing", topic:"home", level:"b1" },
  { id:"hx18", de:"Nachmieter", art:"der", pl:"-", en:"follow-on tenant", topic:"home", level:"b1" },
  { id:"hx19", de:"Heizkosten", art:"die", pl:"", en:"heating costs", topic:"home", level:"b1" },
  { id:"hx20", de:"Einbauküche", art:"die", pl:"-n", en:"fitted kitchen", topic:"home", level:"b1" },

  { id:"wx10", de:"Schicht", art:"die", pl:"-en", en:"shift", topic:"work", level:"b1" },
  { id:"wx11", de:"Arbeitszeugnis", art:"das", pl:"-se", en:"employment reference", topic:"work", level:"b1" },
  { id:"wx12", de:"Minijob", art:"der", pl:"-s", en:"mini-job", topic:"work", level:"b1" },
  { id:"wx13", de:"Krankmeldung", art:"die", pl:"-en", en:"sick-leave notification", topic:"work", level:"b1" },
  { id:"wx14", de:"Arbeitsvertrag", art:"der", pl:"Arbeitsverträge", en:"employment contract", topic:"work", level:"b1" },
  { id:"wx15", de:"Bewerbungsfrist", art:"die", pl:"-en", en:"application deadline", topic:"work", level:"b1" },
  { id:"wx16", de:"Qualifikation", art:"die", pl:"-en", en:"qualification", topic:"work", level:"b1" },
  { id:"wx17", de:"Aushilfe", art:"die", pl:"-n", en:"temp / helper", topic:"work", level:"b1" },
  { id:"wx18", de:"Schichtarbeit", art:"die", pl:"", en:"shift work", topic:"work", level:"b1" },
  { id:"wx19", de:"Betriebsrat", art:"der", pl:"Betriebsräte", en:"works council", topic:"work", level:"b2" },

  { id:"he19", de:"Hausarzt", art:"der", pl:"Hausärzte", en:"GP / family doctor", topic:"health", level:"b1" },
  { id:"he20", de:"Notaufnahme", art:"die", pl:"-n", en:"A&E / ER", topic:"health", level:"b1" },
  { id:"he21", de:"Allergie", art:"die", pl:"-n", en:"allergy", topic:"health", level:"b1" },
  { id:"he22", de:"Fieber", art:"das", pl:"", en:"fever", topic:"health", level:"a2" },
  { id:"he23", de:"Blutdruck", art:"der", pl:"", en:"blood pressure", topic:"health", level:"b1" },
  { id:"he24", de:"Sprechstunde", art:"die", pl:"-n", en:"surgery hours / clinic", topic:"health", level:"b1" },
  { id:"he25", de:"Wartezeit", art:"die", pl:"-en", en:"waiting time", topic:"health", level:"b1" },
  { id:"he26", de:"Tablette", art:"die", pl:"-n", en:"tablet / pill", topic:"health", level:"a2" },
  { id:"he27", de:"Krankengymnastik", art:"die", pl:"-en", en:"physiotherapy", topic:"health", level:"b1" },
  { id:"he28", de:"Überweisung", art:"die", pl:"-en", en:"referral (doctor)", topic:"health", level:"b1" },

  { id:"s16", de:"Prüfungsangst", art:"die", pl:"", en:"exam nerves", topic:"school", level:"b1" },
  { id:"s17", de:"Nachhilfe", art:"die", pl:"-n", en:"tutoring", topic:"school", level:"b1" },
  { id:"s18", de:"Unterricht", art:"der", pl:"", en:"lessons / teaching", topic:"school", level:"a2" },
  { id:"s19", de:"Hausaufgabe", art:"die", pl:"-n", en:"homework", topic:"school", level:"a2" },
  { id:"s20", de:"Dozent", art:"der", pl:"-en", en:"lecturer / course tutor", topic:"school", level:"b1" },
  { id:"s21", de:"Anmeldefrist", art:"die", pl:"-en", en:"registration deadline", topic:"school", level:"b1" },
  { id:"s22", de:"Teilnahmebescheinigung", art:"die", pl:"-en", en:"certificate of attendance", topic:"school", level:"b1" },
  { id:"s23", de:"Vokabelheft", art:"das", pl:"-e", en:"vocab notebook", topic:"school", level:"a2" },
  { id:"s24", de:"Sprachstand", art:"der", pl:"", en:"language level (status)", topic:"school", level:"b1" },
  { id:"s25", de:"Modelltest", art:"der", pl:"-s", en:"practice / model exam", topic:"school", level:"b1" },

  { id:"sv15", de:"Führerschein", art:"der", pl:"-e", en:"driving licence", topic:"services", level:"b1" },
  { id:"sv16", de:"Kindergeld", art:"das", pl:"", en:"child benefit", topic:"services", level:"b1" },
  { id:"sv17", de:"Wohngeld", art:"das", pl:"", en:"housing benefit", topic:"services", level:"b1" },
  { id:"sv18", de:"Jobcenter", art:"das", pl:"-", en:"job centre", topic:"services", level:"b1" },
  { id:"sv19", de:"Ausländerbehörde", art:"die", pl:"-n", en:"immigration office", topic:"services", level:"b1" },
  { id:"sv20", de:"Terminvereinbarung", art:"die", pl:"-en", en:"appointment booking", topic:"services", level:"b1" },
  { id:"sv21", de:"Kontoauszug", art:"der", pl:"Kontoauszüge", en:"bank statement", topic:"services", level:"b1" },
  { id:"sv22", de:"Lastschrift", art:"die", pl:"-en", en:"direct debit", topic:"services", level:"b1" },
  { id:"sv23", de:"Beschwerde", art:"die", pl:"-n", en:"complaint", topic:"services", level:"b1" },
  { id:"sv24", de:"Kulanz", art:"die", pl:"", en:"goodwill (customer service)", topic:"services", level:"b1" },

  { id:"ex26", de:"Bestehensgrenze", art:"die", pl:"-n", en:"pass mark", topic:"examday", level:"b1" },
  { id:"ex27", de:"Leitpunkt", art:"der", pl:"-e", en:"bullet / content point (letter)", topic:"examday", level:"b1" },
  { id:"ex28", de:"Prüfungszentrum", art:"das", pl:"Prüfungszentren", en:"exam centre", topic:"examday", level:"b1" },
  { id:"ex29", de:"Einlass", art:"der", pl:"Einlässe", en:"admission / entry", topic:"examday", level:"b1" },
  { id:"ex30", de:"Bewertung", art:"die", pl:"-en", en:"marking / assessment", topic:"examday", level:"b1" },
  { id:"ex31", de:"Täuschungsversuch", art:"der", pl:"-e", en:"cheating attempt", topic:"examday", level:"b1" },

],
  vocabTopics: [
  { id: "people", title: "People and family", blurb: "Personal data, relatives, character." },
  { id: "home", title: "Housing", blurb: "Rent, rooms, repairs, moving." },
  { id: "daily", title: "Daily life and time", blurb: "Routine, appointments, stress." },
  { id: "food", title: "Food and shopping", blurb: "Meals, shops, quality, nutrition." },
  { id: "work", title: "Work", blurb: "Jobs, applications, contracts." },
  { id: "health", title: "Health", blurb: "Doctor, insurance, body, prevention." },
  { id: "travel", title: "Travel and city", blurb: "Tickets, hotel, weather, delays." },
  { id: "school", title: "School and courses", blurb: "Exams, VHS, certificates." },
  { id: "services", title: "Money, Amt, services", blurb: "Bank, forms, post, tax." },
  { id: "opinions", title: "Opinions and abstract B1", blurb: "Advantage, decision, goal." },
  { id: "media", title: "Media and environment", blurb: "News, privacy, climate." },
  { id: "examday", title: "Exam day and Amt", blurb: "Answer sheet, ID, deadlines, certificates." },
  { id: "b2-abstract", title: "B2 abstract", blurb: "Society, law, science, AI." },
  { id: "b2-society", title: "B2 society and news", blurb: "Pension, energy, labour market." },
  { id: "verbs", title: "Power verbs", blurb: "The verbs you must produce automatically." },
  { id: "adjectives", title: "High-value adjectives", blurb: "wichtig, geeignet, zuverlässig…" },
  { id: "function", title: "Function words (grammar vocab)", blurb: "da-/wo-compounds, jemand/niemand, two-part connectors, erst/schon." },
  { id: "civic", title: "Society and volunteering (B1)", blurb: "Ehrenamt, Verein, Bürgeramt, house rules — personal, not theory." },
  { id: "world", title: "World knowledge groups", blurb: "Directions, holidays, measures, school subjects, colours, article-countries." },
  { id: "feelings", title: "Feelings and attitudes", blurb: "Angst, Sorge, sich ärgern, sich freuen auf/über — Sprechen and letters." },
  { id: "body", title: "Body and symptoms", blurb: "Kopf, Rücken, Fieber, AU — doctor letters and Hören." },
  { id: "clothing", title: "Clothes and shopping returns", blurb: "Jacke, Größe, umtauschen, Kassenbon." },
  { id: "letters", title: "Letter formulas", blurb: "Anrede, weil-opener, Könnten Sie, Mit freundlichen Grüßen." },
]
};
