export default {
  vocab: [
{ id:"a2x1", de:"Schwiegermutter", art:"die", pl:"Schwiegermütter", en:"mother-in-law", topic:"people", level:"a2" },
{ id:"a2x2", de:"Schwiegervater", art:"der", pl:"Schwiegerväter", en:"father-in-law", topic:"people", level:"a2" },
{ id:"a2x3", de:"Schwager", art:"der", pl:"Schwäger", en:"brother-in-law", topic:"people", level:"a2" },
{ id:"a2x4", de:"Schwägerin", art:"die", pl:"-nen", en:"sister-in-law", topic:"people", level:"a2" },
{ id:"a2x5", de:"Stiefkind", art:"das", pl:"-er", en:"stepchild", topic:"people", level:"a2" },
{ id:"a2x6", de:"Patenonkel", art:"der", pl:"-", en:"godfather", topic:"people", level:"a2" },
{ id:"a2x7", de:"Verwandtschaft", art:"die", pl:"-en", en:"relatives as a group", topic:"people", level:"a2" },
{ id:"a2x8", de:"Bekanntenkreis", art:"der", pl:"-e", en:"circle of acquaintances", topic:"people", level:"a2" },
{ id:"a2x9", de:"WG", art:"die", pl:"-s", en:"shared flat", topic:"people", level:"a2" },
{ id:"a2x10", de:"Mitbewohner", art:"der", pl:"-", en:"flatmate", topic:"people", level:"a2" },
{ id:"a2x11", de:"Mitbewohnerin", art:"die", pl:"-nen", en:"flatmate (f)", topic:"people", level:"a2" },
{ id:"a2x12", de:"getrennt", art:"", pl:"", en:"separated", topic:"people", level:"a2" },
{ id:"a2x13", de:"verlobt", art:"", pl:"", en:"engaged", topic:"people", level:"a2" },
{ id:"a2x14", de:"Single", art:"der/die", pl:"-s", en:"single person", topic:"people", level:"a2" },
{ id:"a2x15", de:"Charakterzug", art:"der", pl:"Charakterzüge", en:"character trait", topic:"people", level:"a2" },
{ id:"a2x16", de:"zuverlässig", art:"", pl:"", en:"reliable", topic:"people", level:"a2" },
{ id:"a2x17", de:"hilfsbereit", art:"", pl:"", en:"helpful", topic:"people", level:"a2" },
{ id:"a2x18", de:"ungeduldig", art:"", pl:"", en:"impatient", topic:"people", level:"a2" },
{ id:"a2x19", de:"offenherzig", art:"", pl:"", en:"open-hearted", topic:"people", level:"a2" },
{ id:"a2x20", de:"kontaktfreudig", art:"", pl:"", en:"outgoing", topic:"people", level:"a2" },
{ id:"a2x21", de:"sich streiten", art:"", pl:"", en:"to argue", topic:"people", level:"a2" },
{ id:"a2x22", de:"sich versöhnen", art:"", pl:"", en:"to make up", topic:"people", level:"a2" },
{ id:"a2x23", de:"einladen", art:"", pl:"", en:"to invite", topic:"people", level:"a2" },
{ id:"a2x24", de:"absagen", art:"", pl:"", en:"to cancel (an invitation)", topic:"people", level:"a2" },
{ id:"a2x25", de:"Gruß", art:"der", pl:"Grüße", en:"greeting", topic:"people", level:"a2" },
{ id:"a2x26", de:"Geburtstagskarte", art:"die", pl:"-n", en:"birthday card", topic:"people", level:"a2" },
{ id:"a2x27", de:"Glückwunsch", art:"der", pl:"Glückwünsche", en:"congratulation", topic:"people", level:"a2" },
{ id:"a2x28", de:"Beileid", art:"das", pl:"", en:"condolence", topic:"people", level:"a2" },
{ id:"a2x29", de:"Vorstellungsrunde", art:"die", pl:"-n", en:"round of introductions", topic:"people", level:"a2" },
{ id:"a2x30", de:"Spitzname", art:"der", pl:"-n", en:"nickname", topic:"people", level:"a2" },
{ id:"a2x31", de:"Wohnungsanzeige", art:"die", pl:"-n", en:"housing advert", topic:"home", level:"a2" },
{ id:"a2x32", de:"Wohnungsbesichtigung", art:"die", pl:"-en", en:"flat viewing", topic:"home", level:"a2" },
{ id:"a2x33", de:"Kaution", art:"die", pl:"-en", en:"deposit", topic:"home", level:"a2" },
{ id:"a2x34", de:"Nebenkosten", art:"die", pl:"", en:"service charges", topic:"home", level:"a2" },
{ id:"a2x35", de:"Kaltmiete", art:"die", pl:"-n", en:"rent excluding bills", topic:"home", level:"a2" },
{ id:"a2x36", de:"Warmmiete", art:"die", pl:"-n", en:"rent including bills", topic:"home", level:"a2" },
{ id:"a2x37", de:"Mietvertrag", art:"der", pl:"Mietverträge", en:"tenancy agreement", topic:"home", level:"a2" },
{ id:"a2x38", de:"Hausordnung", art:"die", pl:"-en", en:"house rules", topic:"home", level:"a2" },
{ id:"a2x39", de:"Hausmeister", art:"der", pl:"-", en:"caretaker", topic:"home", level:"a2" },
{ id:"a2x40", de:"Treppenhaus", art:"das", pl:"Treppenhäuser", en:"stairwell", topic:"home", level:"a2" },
{ id:"a2x41", de:"Kellerraum", art:"der", pl:"Kellerräume", en:"cellar room", topic:"home", level:"a2" },
{ id:"a2x42", de:"Dachboden", art:"der", pl:"Dachböden", en:"attic", topic:"home", level:"a2" },
{ id:"a2x43", de:"Einbauküche", art:"die", pl:"-n", en:"fitted kitchen", topic:"home", level:"a2" },
{ id:"a2x44", de:"Herdplatte", art:"die", pl:"-n", en:"hob", topic:"home", level:"a2" },
{ id:"a2x45", de:"Backofen", art:"der", pl:"Backöfen", en:"oven", topic:"home", level:"a2" },
{ id:"a2x46", de:"Spülmaschine", art:"die", pl:"-n", en:"dishwasher", topic:"home", level:"a2" },
{ id:"a2x47", de:"Staubsauger", art:"der", pl:"-", en:"vacuum cleaner", topic:"home", level:"a2" },
{ id:"a2x48", de:"Heizkörper", art:"der", pl:"-", en:"radiator", topic:"home", level:"a2" },
{ id:"a2x49", de:"Thermostat", art:"das", pl:"-e", en:"thermostat", topic:"home", level:"a2" },
{ id:"a2x50", de:"Rollladen", art:"der", pl:"Rollläden", en:"roller shutter", topic:"home", level:"a2" },
{ id:"a2x51", de:"Vorhang", art:"der", pl:"Vorhänge", en:"curtain", topic:"home", level:"a2" },
{ id:"a2x52", de:"Teppich", art:"der", pl:"-e", en:"carpet", topic:"home", level:"a2" },
{ id:"a2x53", de:"Nachttisch", art:"der", pl:"-e", en:"bedside table", topic:"home", level:"a2" },
{ id:"a2x54", de:"Kommode", art:"die", pl:"-n", en:"chest of drawers", topic:"home", level:"a2" },
{ id:"a2x55", de:"Briefkasten", art:"der", pl:"Briefkästen", en:"letterbox", topic:"home", level:"a2" },
{ id:"a2x56", de:"Klingel", art:"die", pl:"-n", en:"doorbell", topic:"home", level:"a2" },
{ id:"a2x57", de:"möbliert", art:"", pl:"", en:"furnished", topic:"home", level:"a2" },
{ id:"a2x58", de:"unmöbliert", art:"", pl:"", en:"unfurnished", topic:"home", level:"a2" },
{ id:"a2x59", de:"hellhörig", art:"", pl:"", en:"thin-walled / noisy building", topic:"home", level:"a2" },
{ id:"a2x60", de:"renovieren", art:"", pl:"", en:"to renovate", topic:"home", level:"a2" },
{ id:"a2x61", de:"lüften", art:"", pl:"", en:"to air (a room)", topic:"home", level:"a2" },
{ id:"a2x62", de:"Mülltonne", art:"die", pl:"-n", en:"bin", topic:"home", level:"a2" },
{ id:"a2x63", de:"Wertstoffhof", art:"der", pl:"Wertstoffhöfe", en:"recycling centre", topic:"home", level:"a2" },
{ id:"a2x64", de:"Zwischenmiete", art:"die", pl:"-n", en:"temporary tenancy", topic:"home", level:"a2" },
{ id:"a2x65", de:"Untermiete", art:"die", pl:"", en:"sublet", topic:"home", level:"a2" },
{ id:"a2x66", de:"Wecker", art:"der", pl:"-", en:"alarm clock", topic:"daily", level:"a2" },
{ id:"a2x67", de:"verschlafen", art:"", pl:"", en:"to oversleep", topic:"daily", level:"a2" },
{ id:"a2x68", de:"pendeln", art:"", pl:"", en:"to commute", topic:"daily", level:"a2" },
{ id:"a2x69", de:"Feierabend machen", art:"", pl:"", en:"to finish work for the day", topic:"daily", level:"a2" },
{ id:"a2x70", de:"Freizeitbeschäftigung", art:"die", pl:"-en", en:"hobby / pastime", topic:"daily", level:"a2" },
{ id:"a2x71", de:"Mitglied", art:"das", pl:"-er", en:"member", topic:"daily", level:"a2" },
{ id:"a2x72", de:"Mitgliedsbeitrag", art:"der", pl:"Mitgliedsbeiträge", en:"membership fee", topic:"daily", level:"a2" },
{ id:"a2x73", de:"Trainingszeit", art:"die", pl:"-en", en:"training time", topic:"daily", level:"a2" },
{ id:"a2x74", de:"Schwimmbad", art:"das", pl:"Schwimmbäder", en:"swimming pool", topic:"daily", level:"a2" },
{ id:"a2x75", de:"Fitnessstudio", art:"das", pl:"-s", en:"gym", topic:"daily", level:"a2" },
{ id:"a2x76", de:"Spaziergang", art:"der", pl:"Spaziergänge", en:"walk", topic:"daily", level:"a2" },
{ id:"a2x77", de:"Geburtstag feiern", art:"", pl:"", en:"to celebrate a birthday", topic:"daily", level:"a2" },
{ id:"a2x78", de:"absagen müssen", art:"", pl:"", en:"to have to cancel", topic:"daily", level:"a2" },
{ id:"a2x79", de:"sich beeilen", art:"", pl:"", en:"to hurry", topic:"daily", level:"a2" },
{ id:"a2x80", de:"Zeit haben", art:"", pl:"", en:"to have time", topic:"daily", level:"a2" },
{ id:"a2x81", de:"keine Lust haben", art:"", pl:"", en:"to not feel like it", topic:"daily", level:"a2" },
{ id:"a2x82", de:"langweilen", art:"", pl:"", en:"to bore", topic:"daily", level:"a2" },
{ id:"a2x83", de:"interessieren", art:"", pl:"", en:"to interest", topic:"daily", level:"a2" },
{ id:"a2x84", de:"planen", art:"", pl:"", en:"to plan", topic:"daily", level:"a2" },
{ id:"a2x85", de:"verschieben", art:"", pl:"", en:"to postpone", topic:"daily", level:"a2" },
{ id:"a2x86", de:"Terminkalender", art:"der", pl:"-", en:"diary / planner", topic:"daily", level:"a2" },
{ id:"a2x87", de:"Erinnerung", art:"die", pl:"-en", en:"reminder", topic:"daily", level:"a2" },
{ id:"a2x88", de:"Freizeitpark", art:"der", pl:"-s", en:"theme park", topic:"daily", level:"a2" },
{ id:"a2x89", de:"Bibliotheksausweis", art:"der", pl:"-e", en:"library card", topic:"daily", level:"a2" },
{ id:"a2x90", de:"ausleihen", art:"", pl:"", en:"to borrow", topic:"daily", level:"a2" },
{ id:"a2x91", de:"zurückgeben", art:"", pl:"", en:"to return (an item)", topic:"daily", level:"a2" },
{ id:"a2x92", de:"Nachtisch", art:"der", pl:"-e", en:"dessert", topic:"food", level:"a2" },
{ id:"a2x93", de:"Beilage", art:"die", pl:"-n", en:"side dish", topic:"food", level:"a2" },
{ id:"a2x94", de:"Soße", art:"die", pl:"-n", en:"sauce", topic:"food", level:"a2" },
{ id:"a2x95", de:"Gewürz", art:"das", pl:"-e", en:"spice", topic:"food", level:"a2" },
{ id:"a2x96", de:"Öl", art:"das", pl:"-e", en:"oil", topic:"food", level:"a2" },
{ id:"a2x97", de:"Essig", art:"der", pl:"", en:"vinegar", topic:"food", level:"a2" },
{ id:"a2x98", de:"Mehl", art:"das", pl:"", en:"flour", topic:"food", level:"a2" },
{ id:"a2x99", de:"Hefe", art:"die", pl:"", en:"yeast", topic:"food", level:"a2" },
{ id:"a2x100", de:"Sahne", art:"die", pl:"", en:"cream", topic:"food", level:"a2" },
{ id:"a2x101", de:"Joghurt", art:"der/das", pl:"-s", en:"yoghurt", topic:"food", level:"a2" },
{ id:"a2x102", de:"Marmelade", art:"die", pl:"-n", en:"jam", topic:"food", level:"a2" },
{ id:"a2x103", de:"Honig", art:"der", pl:"", en:"honey", topic:"food", level:"a2" },
{ id:"a2x104", de:"Wurst", art:"die", pl:"Würste", en:"sausage", topic:"food", level:"a2" },
{ id:"a2x105", de:"Schinken", art:"der", pl:"", en:"ham", topic:"food", level:"a2" },
{ id:"a2x106", de:"Hähnchen", art:"das", pl:"-", en:"chicken", topic:"food", level:"a2" },
{ id:"a2x107", de:"Kartoffel", art:"die", pl:"-n", en:"potato", topic:"food", level:"a2" },
{ id:"a2x108", de:"Zwiebel", art:"die", pl:"-n", en:"onion", topic:"food", level:"a2" },
{ id:"a2x109", de:"Knoblauch", art:"der", pl:"", en:"garlic", topic:"food", level:"a2" },
{ id:"a2x110", de:"Tomate", art:"die", pl:"-n", en:"tomato", topic:"food", level:"a2" },
{ id:"a2x111", de:"Gurke", art:"die", pl:"-n", en:"cucumber", topic:"food", level:"a2" },
{ id:"a2x112", de:"Paprika", art:"die", pl:"-s", en:"pepper (veg)", topic:"food", level:"a2" },
{ id:"a2x113", de:"Erdbeere", art:"die", pl:"-n", en:"strawberry", topic:"food", level:"a2" },
{ id:"a2x114", de:"Traube", art:"die", pl:"-n", en:"grape", topic:"food", level:"a2" },
{ id:"a2x115", de:"Orange", art:"die", pl:"-n", en:"orange", topic:"food", level:"a2" },
{ id:"a2x116", de:"glutenfrei", art:"", pl:"", en:"gluten-free", topic:"food", level:"a2" },
{ id:"a2x117", de:"laktosefrei", art:"", pl:"", en:"lactose-free", topic:"food", level:"a2" },
{ id:"a2x118", de:"Allergiehinweis", art:"der", pl:"-e", en:"allergen notice", topic:"food", level:"a2" },
{ id:"a2x119", de:"Tagesgericht", art:"das", pl:"-e", en:"dish of the day", topic:"food", level:"a2" },
{ id:"a2x120", de:"Mittagstisch", art:"der", pl:"-e", en:"set lunch", topic:"food", level:"a2" },
{ id:"a2x121", de:"Reservierung", art:"die", pl:"-en", en:"reservation", topic:"food", level:"a2" },
{ id:"a2x122", de:"Platz frei", art:"", pl:"", en:"seat free", topic:"food", level:"a2" },
{ id:"a2x123", de:"getrennt zahlen", art:"", pl:"", en:"to split the bill", topic:"food", level:"a2" },
{ id:"a2x124", de:"zusammen zahlen", art:"", pl:"", en:"to pay together", topic:"food", level:"a2" },
{ id:"a2x125", de:"Nachschlag", art:"der", pl:"Nachschläge", en:"second helping", topic:"food", level:"a2" },
{ id:"a2x126", de:"Rest", art:"der", pl:"-e", en:"leftover", topic:"food", level:"a2" },
{ id:"a2x127", de:"einkaufen gehen", art:"", pl:"", en:"to go shopping (food)", topic:"food", level:"a2" },
{ id:"a2x128", de:"Haltbarkeitsdatum", art:"das", pl:"-daten", en:"best-before date", topic:"food", level:"a2" },
{ id:"a2x129", de:"Arbeitsplatz", art:"der", pl:"Arbeitsplätze", en:"workplace / job", topic:"work", level:"a2" },
{ id:"a2x130", de:"Teilzeit", art:"die", pl:"", en:"part-time", topic:"work", level:"a2" },
{ id:"a2x131", de:"Vollzeit", art:"die", pl:"", en:"full-time", topic:"work", level:"a2" },
{ id:"a2x132", de:"Minijob", art:"der", pl:"-s", en:"mini-job", topic:"work", level:"a2" },
{ id:"a2x133", de:"Aushilfe", art:"die", pl:"-n", en:"temp / helper", topic:"work", level:"a2" },
{ id:"a2x134", de:"Schichtarbeit", art:"die", pl:"", en:"shift work", topic:"work", level:"a2" },
{ id:"a2x135", de:"Frühschicht", art:"die", pl:"-en", en:"early shift", topic:"work", level:"a2" },
{ id:"a2x136", de:"Spätschicht", art:"die", pl:"-en", en:"late shift", topic:"work", level:"a2" },
{ id:"a2x137", de:"Nachtarbeit", art:"die", pl:"", en:"night work", topic:"work", level:"a2" },
{ id:"a2x138", de:"Arbeitsvertrag", art:"der", pl:"Arbeitsverträge", en:"employment contract", topic:"work", level:"a2" },
{ id:"a2x139", de:"Probezeit", art:"die", pl:"-en", en:"probation", topic:"work", level:"a2" },
{ id:"a2x140", de:"Kündigungsfrist", art:"die", pl:"-en", en:"notice period", topic:"work", level:"a2" },
{ id:"a2x141", de:"Zeugnis", art:"das", pl:"-se", en:"reference / school report", topic:"work", level:"a2" },
{ id:"a2x142", de:"Qualifikation", art:"die", pl:"-en", en:"qualification", topic:"work", level:"a2" },
{ id:"a2x143", de:"Fähigkeit", art:"die", pl:"-en", en:"skill", topic:"work", level:"a2" },
{ id:"a2x144", de:"Vorstellungsgespräch", art:"das", pl:"-e", en:"job interview", topic:"work", level:"a2" },
{ id:"a2x145", de:"Stellenanzeige", art:"die", pl:"-n", en:"job advert", topic:"work", level:"a2" },
{ id:"a2x146", de:"sich bewerben", art:"", pl:"", en:"to apply", topic:"work", level:"a2" },
{ id:"a2x147", de:"einstellen", art:"", pl:"", en:"to hire", topic:"work", level:"a2" },
{ id:"a2x148", de:"entlassen", art:"", pl:"", en:"to dismiss", topic:"work", level:"a2" },
{ id:"a2x149", de:"Betriebsrat", art:"der", pl:"Betriebsräte", en:"works council", topic:"work", level:"a2" },
{ id:"a2x150", de:"Kollegium", art:"das", pl:"Kollegien", en:"staff (school)", topic:"work", level:"a2" },
{ id:"a2x151", de:"Pause machen", art:"", pl:"", en:"to take a break", topic:"work", level:"a2" },
{ id:"a2x152", de:"überstunden machen", art:"", pl:"", en:"to work overtime", topic:"work", level:"a2" },
{ id:"a2x153", de:"Dienstreise", art:"die", pl:"-n", en:"business trip", topic:"work", level:"a2" },
{ id:"a2x154", de:"Fortbildung", art:"die", pl:"-en", en:"further training", topic:"work", level:"a2" },
{ id:"a2x155", de:"Umschulung", art:"die", pl:"-en", en:"retraining", topic:"work", level:"a2" },
{ id:"a2x156", de:"Arbeitslosengeld", art:"das", pl:"", en:"unemployment benefit", topic:"work", level:"a2" },
{ id:"a2x157", de:"Jobcenter", art:"das", pl:"-", en:"job centre", topic:"work", level:"a2" },
{ id:"a2x158", de:"pünktlich erscheinen", art:"", pl:"", en:"to arrive on time", topic:"work", level:"a2" },
{ id:"a2x159", de:"verantwortlich sein", art:"", pl:"", en:"to be responsible", topic:"work", level:"a2" },
{ id:"a2x160", de:"Hausarzt", art:"der", pl:"Hausärzte", en:"GP", topic:"health", level:"a2" },
{ id:"a2x161", de:"Facharzt", art:"der", pl:"Fachärzte", en:"specialist", topic:"health", level:"a2" },
{ id:"a2x162", de:"Kinderarzt", art:"der", pl:"Kinderärzte", en:"paediatrician", topic:"health", level:"a2" },
{ id:"a2x163", de:"Hautarzt", art:"der", pl:"Hautärzte", en:"dermatologist", topic:"health", level:"a2" },
{ id:"a2x164", de:"Krankmeldung", art:"die", pl:"-en", en:"sick note", topic:"health", level:"a2" },
{ id:"a2x165", de:"Attest", art:"das", pl:"-e", en:"medical certificate", topic:"health", level:"a2" },
{ id:"a2x166", de:"Blutdruck", art:"der", pl:"", en:"blood pressure", topic:"health", level:"a2" },
{ id:"a2x167", de:"Puls", art:"der", pl:"", en:"pulse", topic:"health", level:"a2" },
{ id:"a2x168", de:"Temperatur messen", art:"", pl:"", en:"to take someone's temperature", topic:"health", level:"a2" },
{ id:"a2x169", de:"sich krank fühlen", art:"", pl:"", en:"to feel ill", topic:"health", level:"a2" },
{ id:"a2x170", de:"sich erholen", art:"", pl:"", en:"to recover", topic:"health", level:"a2" },
{ id:"a2x171", de:"Schmerzmittel", art:"das", pl:"-", en:"painkiller", topic:"health", level:"a2" },
{ id:"a2x172", de:"Hustensaft", art:"der", pl:"Hustensäfte", en:"cough syrup", topic:"health", level:"a2" },
{ id:"a2x173", de:"Salbe", art:"die", pl:"-n", en:"ointment", topic:"health", level:"a2" },
{ id:"a2x174", de:"Verband", art:"der", pl:"Verbände", en:"bandage", topic:"health", level:"a2" },
{ id:"a2x175", de:"Bruch", art:"der", pl:"Brüche", en:"fracture", topic:"health", level:"a2" },
{ id:"a2x176", de:"Verstauchung", art:"die", pl:"-en", en:"sprain", topic:"health", level:"a2" },
{ id:"a2x177", de:"Schnittwunde", art:"die", pl:"-n", en:"cut", topic:"health", level:"a2" },
{ id:"a2x178", de:"Allergiepass", art:"der", pl:"Allergiepässe", en:"allergy card", topic:"health", level:"a2" },
{ id:"a2x179", de:"Krankenkassenkarte", art:"die", pl:"-n", en:"health insurance card", topic:"health", level:"a2" },
{ id:"a2x180", de:"Zuzahlung", art:"die", pl:"-en", en:"co-payment", topic:"health", level:"a2" },
{ id:"a2x181", de:"Rezeptgebühr", art:"die", pl:"-en", en:"prescription charge", topic:"health", level:"a2" },
{ id:"a2x182", de:"Wartezimmer", art:"das", pl:"-", en:"waiting room", topic:"health", level:"a2" },
{ id:"a2x183", de:"Wartezeit", art:"die", pl:"-en", en:"waiting time", topic:"health", level:"a2" },
{ id:"a2x184", de:"Notdienst", art:"der", pl:"-e", en:"out-of-hours service", topic:"health", level:"a2" },
{ id:"a2x185", de:"Rettungswagen", art:"der", pl:"-", en:"ambulance", topic:"health", level:"a2" },
{ id:"a2x186", de:"Notruf", art:"der", pl:"-e", en:"emergency call", topic:"health", level:"a2" },
{ id:"a2x187", de:"sich schonen", art:"", pl:"", en:"to take it easy", topic:"health", level:"a2" },
{ id:"a2x188", de:"vorbeugen", art:"", pl:"", en:"to prevent", topic:"health", level:"a2" },
{ id:"a2x189", de:"Fahrkartenautomat", art:"der", pl:"-en", en:"ticket machine", topic:"travel", level:"a2" },
{ id:"a2x190", de:"Einzelkarte", art:"die", pl:"-n", en:"single ticket", topic:"travel", level:"a2" },
{ id:"a2x191", de:"Tageskarte", art:"die", pl:"-n", en:"day ticket", topic:"travel", level:"a2" },
{ id:"a2x192", de:"Monatskarte", art:"die", pl:"-n", en:"monthly pass", topic:"travel", level:"a2" },
{ id:"a2x193", de:"Bahncard", art:"die", pl:"-s", en:"rail discount card", topic:"travel", level:"a2" },
{ id:"a2x194", de:"Sitzplatzreservierung", art:"die", pl:"-en", en:"seat reservation", topic:"travel", level:"a2" },
{ id:"a2x195", de:"Wagen", art:"der", pl:"", en:"carriage", topic:"travel", level:"a2" },
{ id:"a2x196", de:"Abteil", art:"das", pl:"-e", en:"compartment", topic:"travel", level:"a2" },
{ id:"a2x197", de:"Umleitung", art:"die", pl:"-en", en:"diversion", topic:"travel", level:"a2" },
{ id:"a2x198", de:"Gleiswechsel", art:"der", pl:"-", en:"platform change", topic:"travel", level:"a2" },
{ id:"a2x199", de:"Anschlusszug", art:"der", pl:"Anschlusszüge", en:"connecting train", topic:"travel", level:"a2" },
{ id:"a2x200", de:"verpassen", art:"", pl:"", en:"to miss (a train)", topic:"travel", level:"a2" },
{ id:"a2x201", de:"verspätet", art:"", pl:"", en:"delayed", topic:"travel", level:"a2" },
{ id:"a2x202", de:"pünktlich ankommen", art:"", pl:"", en:"to arrive on time", topic:"travel", level:"a2" },
{ id:"a2x203", de:"Fahrgast", art:"der", pl:"Fahrgäste", en:"passenger", topic:"travel", level:"a2" },
{ id:"a2x204", de:"Schaffner", art:"der", pl:"-", en:"conductor", topic:"travel", level:"a2" },
{ id:"a2x205", de:"Kontrolleur", art:"der", pl:"-e", en:"ticket inspector", topic:"travel", level:"a2" },
{ id:"a2x206", de:"Zuschlag", art:"der", pl:"Zuschläge", en:"surcharge", topic:"travel", level:"a2" },
{ id:"a2x207", de:"Gepäckaufbewahrung", art:"die", pl:"-en", en:"left luggage", topic:"travel", level:"a2" },
{ id:"a2x208", de:"Koffer", art:"der", pl:"-", en:"suitcase", topic:"travel", level:"a2" },
{ id:"a2x209", de:"Rucksack", art:"der", pl:"Rucksäcke", en:"backpack", topic:"travel", level:"a2" },
{ id:"a2x210", de:"Reiseversicherung", art:"die", pl:"-en", en:"travel insurance", topic:"travel", level:"a2" },
{ id:"a2x211", de:"Check-in", art:"der", pl:"-s", en:"check-in", topic:"travel", level:"a2" },
{ id:"a2x212", de:"Abflug", art:"der", pl:"Abflüge", en:"departure (flight)", topic:"travel", level:"a2" },
{ id:"a2x213", de:"Landung", art:"die", pl:"-en", en:"landing", topic:"travel", level:"a2" },
{ id:"a2x214", de:"Gate", art:"das", pl:"-s", en:"gate", topic:"travel", level:"a2" },
{ id:"a2x215", de:"Frühstück inklusive", art:"", pl:"", en:"breakfast included", topic:"travel", level:"a2" },
{ id:"a2x216", de:"Halbpension", art:"die", pl:"", en:"half board", topic:"travel", level:"a2" },
{ id:"a2x217", de:"Vollpension", art:"die", pl:"", en:"full board", topic:"travel", level:"a2" },
{ id:"a2x218", de:"Stadtführung", art:"die", pl:"-en", en:"city tour", topic:"travel", level:"a2" },
{ id:"a2x219", de:"Reiseführer", art:"der", pl:"-", en:"guidebook / guide", topic:"travel", level:"a2" },
{ id:"a2x220", de:"Souvenir", art:"das", pl:"-s", en:"souvenir", topic:"travel", level:"a2" },
{ id:"a2x221", de:"Stau", art:"der", pl:"-s", en:"traffic jam", topic:"travel", level:"a2" },
{ id:"a2x222", de:"Umleitung folgen", art:"", pl:"", en:"follow the diversion", topic:"travel", level:"a2" },
{ id:"a2x223", de:"Sparkasse", art:"die", pl:"-n", en:"savings bank", topic:"services", level:"a2" },
{ id:"a2x224", de:"Geldautomat", art:"der", pl:"-en", en:"cash machine", topic:"services", level:"a2" },
{ id:"a2x225", de:"Kontonummer", art:"die", pl:"-n", en:"account number", topic:"services", level:"a2" },
{ id:"a2x226", de:"IBAN", art:"die", pl:"-s", en:"IBAN", topic:"services", level:"a2" },
{ id:"a2x227", de:"Überweisungsformular", art:"das", pl:"-e", en:"transfer form", topic:"services", level:"a2" },
{ id:"a2x228", de:"Lastschrift", art:"die", pl:"-en", en:"direct debit", topic:"services", level:"a2" },
{ id:"a2x229", de:"Dauerauftrag", art:"der", pl:"Daueraufträge", en:"standing order", topic:"services", level:"a2" },
{ id:"a2x230", de:"Kontoauszug", art:"der", pl:"Kontoauszüge", en:"bank statement", topic:"services", level:"a2" },
{ id:"a2x231", de:"Dispozins", art:"der", pl:"-en", en:"overdraft interest", topic:"services", level:"a2" },
{ id:"a2x232", de:"Gebühr", art:"die", pl:"-en", en:"fee", topic:"services", level:"a2" },
{ id:"a2x233", de:"Postfiliale", art:"die", pl:"-n", en:"post office branch", topic:"services", level:"a2" },
{ id:"a2x234", de:"Einschreiben", art:"das", pl:"-", en:"registered mail", topic:"services", level:"a2" },
{ id:"a2x235", de:"Paketabholung", art:"die", pl:"-en", en:"parcel collection", topic:"services", level:"a2" },
{ id:"a2x236", de:"Packstation", art:"die", pl:"-en", en:"parcel locker", topic:"services", level:"a2" },
{ id:"a2x237", de:"Bürgerbüro", art:"das", pl:"-s", en:"citizens' office", topic:"services", level:"a2" },
{ id:"a2x238", de:"Einwohnermeldeamt", art:"das", pl:"Einwohnermeldeämter", en:"registration office", topic:"services", level:"a2" },
{ id:"a2x239", de:"Meldebescheinigung", art:"die", pl:"-en", en:"registration certificate", topic:"services", level:"a2" },
{ id:"a2x240", de:"Ummeldung", art:"die", pl:"-en", en:"change of address", topic:"services", level:"a2" },
{ id:"a2x241", de:"Abmeldung", art:"die", pl:"-en", en:"deregistration", topic:"services", level:"a2" },
{ id:"a2x242", de:"Terminvereinbarung", art:"die", pl:"-en", en:"appointment booking", topic:"services", level:"a2" },
{ id:"a2x243", de:"Warte Nummer", art:"die", pl:"-n", en:"queue number", topic:"services", level:"a2" },
{ id:"a2x244", de:"Sachbearbeiter", art:"der", pl:"-", en:"case worker", topic:"services", level:"a2" },
{ id:"a2x245", de:"Sachbearbeiterin", art:"die", pl:"-nen", en:"case worker (f)", topic:"services", level:"a2" },
{ id:"a2x246", de:"Bescheid", art:"der", pl:"-e", en:"official notice", topic:"services", level:"a2" },
{ id:"a2x247", de:"Nachweis", art:"der", pl:"-e", en:"proof", topic:"services", level:"a2" },
{ id:"a2x248", de:"Kopie", art:"die", pl:"-n", en:"copy", topic:"services", level:"a2" },
{ id:"a2x249", de:"Original", art:"das", pl:"-e", en:"original", topic:"services", level:"a2" },
{ id:"a2x250", de:"beglaubigen", art:"", pl:"", en:"to certify", topic:"services", level:"a2" },
{ id:"a2x251", de:"übersetzen lassen", art:"", pl:"", en:"to have translated", topic:"services", level:"a2" },
{ id:"a2x252", de:"Steuernummer", art:"die", pl:"-n", en:"tax number", topic:"services", level:"a2" },
{ id:"a2x253", de:"Kindergeld", art:"das", pl:"", en:"child benefit", topic:"services", level:"a2" },
{ id:"a2x254", de:"Wohngeld", art:"das", pl:"", en:"housing benefit", topic:"services", level:"a2" },
{ id:"a2x255", de:"meiner Meinung nach", art:"", pl:"", en:"in my opinion", topic:"opinions", level:"a2" },
{ id:"a2x256", de:"ich finde, dass", art:"", pl:"", en:"I think that", topic:"opinions", level:"a2" },
{ id:"a2x257", de:"ich glaube, dass", art:"", pl:"", en:"I believe that", topic:"opinions", level:"a2" },
{ id:"a2x258", de:"ich bin der Meinung", art:"", pl:"", en:"I am of the opinion", topic:"opinions", level:"a2" },
{ id:"a2x259", de:"das stimmt", art:"", pl:"", en:"that's true", topic:"opinions", level:"a2" },
{ id:"a2x260", de:"das stimmt nicht", art:"", pl:"", en:"that's not true", topic:"opinions", level:"a2" },
{ id:"a2x261", de:"einverstanden sein", art:"", pl:"", en:"to agree", topic:"opinions", level:"a2" },
{ id:"a2x262", de:"nicht einverstanden sein", art:"", pl:"", en:"to disagree", topic:"opinions", level:"a2" },
{ id:"a2x263", de:"Vorschlag machen", art:"", pl:"", en:"to make a suggestion", topic:"opinions", level:"a2" },
{ id:"a2x264", de:"dafür sein", art:"", pl:"", en:"to be in favour", topic:"opinions", level:"a2" },
{ id:"a2x265", de:"dagegen sein", art:"", pl:"", en:"to be against", topic:"opinions", level:"a2" },
{ id:"a2x266", de:"Vor- und Nachteile", art:"die", pl:"", en:"pros and cons", topic:"opinions", level:"a2" },
{ id:"a2x267", de:"allerdings", art:"", pl:"", en:"however / admittedly", topic:"opinions", level:"a2" },
{ id:"a2x268", de:"sonst", art:"", pl:"", en:"otherwise", topic:"opinions", level:"a2" },
{ id:"a2x269", de:"wahrscheinlich", art:"", pl:"", en:"probably", topic:"opinions", level:"a2" },
{ id:"a2x270", de:"unmöglich", art:"", pl:"", en:"impossible", topic:"opinions", level:"a2" },
{ id:"a2x271", de:"möglich", art:"", pl:"", en:"possible", topic:"opinions", level:"a2" },
{ id:"a2x272", de:"wichtig finden", art:"", pl:"", en:"to find important", topic:"opinions", level:"a2" },
{ id:"a2x273", de:"besser finden", art:"", pl:"", en:"to prefer / find better", topic:"opinions", level:"a2" },
{ id:"a2x274", de:"schlecht finden", art:"", pl:"", en:"to find bad", topic:"opinions", level:"a2" },
{ id:"a2x275", de:"ein Argument", art:"das", pl:"-e", en:"an argument", topic:"opinions", level:"a2" },
{ id:"a2x276", de:"ein Beispiel geben", art:"", pl:"", en:"to give an example", topic:"opinions", level:"a2" },
{ id:"a2x277", de:"zusammenfassen", art:"", pl:"", en:"to summarise", topic:"opinions", level:"a2" },
{ id:"a2x278", de:"Nachrichtensendung", art:"die", pl:"-en", en:"news programme", topic:"media", level:"a2" },
{ id:"a2x279", de:"Radiosender", art:"der", pl:"-", en:"radio station", topic:"media", level:"a2" },
{ id:"a2x280", de:"Fernsehsender", art:"der", pl:"-", en:"TV channel", topic:"media", level:"a2" },
{ id:"a2x281", de:"Artikel", art:"der", pl:"-", en:"article", topic:"media", level:"a2" },
{ id:"a2x282", de:"Überschrift", art:"die", pl:"-en", en:"headline", topic:"media", level:"a2" },
{ id:"a2x283", de:"Kommentar", art:"der", pl:"-e", en:"comment", topic:"media", level:"a2" },
{ id:"a2x284", de:"teilen", art:"", pl:"", en:"to share (online)", topic:"media", level:"a2" },
{ id:"a2x285", de:"liken", art:"", pl:"", en:"to like (online)", topic:"media", level:"a2" },
{ id:"a2x286", de:"hochladen", art:"", pl:"", en:"to upload", topic:"media", level:"a2" },
{ id:"a2x287", de:"herunterladen", art:"", pl:"", en:"to download", topic:"media", level:"a2" },
{ id:"a2x288", de:"Benutzername", art:"der", pl:"-n", en:"username", topic:"media", level:"a2" },
{ id:"a2x289", de:"Passwort vergessen", art:"", pl:"", en:"forgot password", topic:"media", level:"a2" },
{ id:"a2x290", de:"Datenschutz", art:"der", pl:"", en:"data protection", topic:"media", level:"a2" },
{ id:"a2x291", de:"Werbung ausschalten", art:"", pl:"", en:"to turn off ads", topic:"media", level:"a2" },
{ id:"a2x292", de:"Wetterbericht", art:"der", pl:"-e", en:"weather forecast", topic:"media", level:"a2" },
{ id:"a2x293", de:"Wettervorhersage", art:"die", pl:"-n", en:"weather forecast", topic:"media", level:"a2" },
{ id:"a2x294", de:"Hitzewelle", art:"die", pl:"-n", en:"heatwave", topic:"media", level:"a2" },
{ id:"a2x295", de:"Unwetter", art:"das", pl:"-", en:"severe weather", topic:"media", level:"a2" },
{ id:"a2x296", de:"Glätte", art:"die", pl:"", en:"icy roads", topic:"media", level:"a2" },
{ id:"a2x297", de:"Starkregen", art:"der", pl:"", en:"heavy rain", topic:"media", level:"a2" },
{ id:"a2x298", de:"Recyclinghof", art:"der", pl:"Recyclinghöfe", en:"recycling yard", topic:"media", level:"a2" },
{ id:"a2x299", de:"Mülltrennung", art:"die", pl:"", en:"waste separation", topic:"media", level:"a2" },
{ id:"a2x300", de:"Papiertonne", art:"die", pl:"-n", en:"paper bin", topic:"media", level:"a2" },
{ id:"a2x301", de:"Biotonne", art:"die", pl:"-n", en:"organic waste bin", topic:"media", level:"a2" },
{ id:"a2x302", de:"Restmüll", art:"der", pl:"", en:"residual waste", topic:"media", level:"a2" },
{ id:"a2x303", de:"Pfand", art:"das", pl:"", en:"deposit (bottle)", topic:"media", level:"a2" },
{ id:"a2x304", de:"Pfandflasche", art:"die", pl:"-n", en:"deposit bottle", topic:"media", level:"a2" },
{ id:"a2x305", de:"Strom sparen", art:"", pl:"", en:"to save electricity", topic:"media", level:"a2" },
{ id:"a2x306", de:"Heizung runterdrehen", art:"", pl:"", en:"to turn the heating down", topic:"media", level:"a2" },
{ id:"a2x307", de:"umweltfreundlich", art:"", pl:"", en:"environmentally friendly", topic:"media", level:"a2" },
{ id:"a2x308", de:"angerufen", art:"", pl:"", en:"called (participle)", topic:"verbs", level:"a2" },
{ id:"a2x309", de:"eingekauft", art:"", pl:"", en:"shopped (participle)", topic:"verbs", level:"a2" },
{ id:"a2x310", de:"aufgestanden", art:"", pl:"", en:"got up (participle)", topic:"verbs", level:"a2" },
{ id:"a2x311", de:"angekommen", art:"", pl:"", en:"arrived (participle)", topic:"verbs", level:"a2" },
{ id:"a2x312", de:"eingestiegen", art:"", pl:"", en:"got on (participle)", topic:"verbs", level:"a2" },
{ id:"a2x313", de:"ausgestiegen", art:"", pl:"", en:"got off (participle)", topic:"verbs", level:"a2" },
{ id:"a2x314", de:"umgestiegen", art:"", pl:"", en:"changed trains (participle)", topic:"verbs", level:"a2" },
{ id:"a2x315", de:"eingeladen", art:"", pl:"", en:"invited (participle)", topic:"verbs", level:"a2" },
{ id:"a2x316", de:"vorgeschlagen", art:"", pl:"", en:"suggested (participle)", topic:"verbs", level:"a2" },
{ id:"a2x317", de:"besucht", art:"", pl:"", en:"visited (participle)", topic:"verbs", level:"a2" },
{ id:"a2x318", de:"erzählt", art:"", pl:"", en:"told (participle)", topic:"verbs", level:"a2" },
{ id:"a2x319", de:"reserviert", art:"", pl:"", en:"reserved (participle)", topic:"verbs", level:"a2" },
{ id:"a2x320", de:"bestellt", art:"", pl:"", en:"ordered (participle)", topic:"verbs", level:"a2" },
{ id:"a2x321", de:"bezahlt", art:"", pl:"", en:"paid (participle)", topic:"verbs", level:"a2" },
{ id:"a2x322", de:"geöffnet", art:"", pl:"", en:"opened (participle)", topic:"verbs", level:"a2" },
{ id:"a2x323", de:"geschlossen", art:"", pl:"", en:"closed (participle)", topic:"verbs", level:"a2" },
{ id:"a2x324", de:"geworden", art:"", pl:"", en:"become (participle)", topic:"verbs", level:"a2" },
{ id:"a2x325", de:"eingeschlafen", art:"", pl:"", en:"fallen asleep (participle)", topic:"verbs", level:"a2" },
{ id:"a2x326", de:"aufgewacht", art:"", pl:"", en:"woken up (participle)", topic:"verbs", level:"a2" },
{ id:"a2x327", de:"kennengelernt", art:"", pl:"", en:"got to know (participle)", topic:"verbs", level:"a2" },
{ id:"a2x328", de:"mitgekommen", art:"", pl:"", en:"come along (participle)", topic:"verbs", level:"a2" },
{ id:"a2x329", de:"zugemacht", art:"", pl:"", en:"closed (sep. participle)", topic:"verbs", level:"a2" },
{ id:"a2x330", de:"aufgemacht", art:"", pl:"", en:"opened (sep. participle)", topic:"verbs", level:"a2" },
{ id:"a2x331", de:"fernsehen", art:"", pl:"", en:"to watch TV", topic:"verbs", level:"a2" },
{ id:"a2x332", de:"anrufen", art:"", pl:"", en:"to call", topic:"verbs", level:"a2" },
{ id:"a2x333", de:"ankommen", art:"", pl:"", en:"to arrive", topic:"verbs", level:"a2" },
{ id:"a2x334", de:"anfangen", art:"", pl:"", en:"to start", topic:"verbs", level:"a2" },
{ id:"a2x335", de:"aufhören", art:"", pl:"", en:"to stop", topic:"verbs", level:"a2" },
{ id:"a2x336", de:"mitbringen", art:"", pl:"", en:"to bring along", topic:"verbs", level:"a2" },
{ id:"a2x337", de:"nachfragen", art:"", pl:"", en:"to enquire", topic:"verbs", level:"a2" },
{ id:"a2x338", de:"weiterfahren", art:"", pl:"", en:"to continue travelling", topic:"verbs", level:"a2" },
{ id:"a2x339", de:"schließlich", art:"", pl:"", en:"finally", topic:"connectors", level:"a2" },
{ id:"a2x340", de:"deswegen", art:"", pl:"", en:"that's why", topic:"connectors", level:"a2" },
{ id:"a2x341", de:"darum", art:"", pl:"", en:"that's why", topic:"connectors", level:"a2" },
{ id:"a2x342", de:"seitdem", art:"", pl:"", en:"since (then)", topic:"connectors", level:"a2" },
{ id:"a2x343", de:"während", art:"", pl:"", en:"while / during", topic:"connectors", level:"a2" },
{ id:"a2x344", de:"bis", art:"", pl:"", en:"until", topic:"connectors", level:"a2" },
{ id:"a2x345", de:"falls", art:"", pl:"", en:"in case / if", topic:"connectors", level:"a2" },
{ id:"a2x346", de:"ob", art:"", pl:"", en:"whether", topic:"connectors", level:"a2" },
{ id:"a2x347", de:"nämlich", art:"", pl:"", en:"namely / you see", topic:"connectors", level:"a2" },
{ id:"a2x348", de:"außerdem", art:"", pl:"", en:"besides / also", topic:"connectors", level:"a2" },
{ id:"a2x349", de:"nicht nur … sondern auch", art:"", pl:"", en:"not only … but also", topic:"connectors", level:"a2" },
{ id:"a2x350", de:"entweder … oder", art:"", pl:"", en:"either … or", topic:"connectors", level:"a2" },
{ id:"a2x351", de:"sowohl … als auch", art:"", pl:"", en:"both … and", topic:"connectors", level:"a2" }
  ]
};
