export default {
  vocab: [
  {
    "id": "a2v1",
    "de": "Verwandte",
    "art": "die",
    "pl": "",
    "en": "relatives",
    "topic": "people",
    "level": "a2",
    "ex": "Hier sind die Verwandte.",
    "exEn": "Here are the relatives."
  },
  {
    "id": "a2v2",
    "de": "Kollege",
    "art": "der",
    "pl": "-n",
    "en": "colleague",
    "topic": "people",
    "level": "a2",
    "ex": "Das ist der Kollege.",
    "exEn": "This is colleague."
  },
  {
    "id": "a2v3",
    "de": "Bekannte",
    "art": "der/die",
    "pl": "-n",
    "en": "acquaintance",
    "topic": "people",
    "level": "a2",
    "ex": "Das ist der Bekannte.",
    "exEn": "This is acquaintance."
  },
  {
    "id": "a2v4",
    "de": "Gast",
    "art": "der",
    "pl": "Gäste",
    "en": "guest",
    "topic": "people",
    "level": "a2",
    "ex": "Das ist der Gast.",
    "exEn": "This is guest."
  },
  {
    "id": "a2v5",
    "de": "Einladung",
    "art": "die",
    "pl": "-en",
    "en": "invitation",
    "topic": "people",
    "level": "a2",
    "ex": "Das ist die Einladung.",
    "exEn": "This is invitation."
  },
  {
    "id": "a2v6",
    "de": "Geburtstag",
    "art": "der",
    "pl": "-e",
    "en": "birthday",
    "topic": "people",
    "level": "a2",
    "ex": "Das ist der Geburtstag.",
    "exEn": "This is birthday."
  },
  {
    "id": "a2v7",
    "de": "Hochzeit",
    "art": "die",
    "pl": "-en",
    "en": "wedding",
    "topic": "people",
    "level": "a2",
    "ex": "Das ist die Hochzeit.",
    "exEn": "This is wedding."
  },
  {
    "id": "a2v8",
    "de": "Charakter",
    "art": "der",
    "pl": "-e",
    "en": "character",
    "topic": "people",
    "level": "a2",
    "ex": "Das ist der Charakter.",
    "exEn": "This is character."
  },
  {
    "id": "a2v9",
    "de": "freundlich",
    "art": "",
    "pl": "",
    "en": "friendly",
    "topic": "people",
    "level": "a2",
    "ex": "Der Termin ist freundlich.",
    "exEn": "The appointment is friendly."
  },
  {
    "id": "a2v10",
    "de": "nett",
    "art": "",
    "pl": "",
    "en": "nice",
    "topic": "people",
    "level": "a2",
    "ex": "Der Termin ist nett.",
    "exEn": "The appointment is nice."
  },
  {
    "id": "a2v11",
    "de": "streng",
    "art": "",
    "pl": "",
    "en": "strict",
    "topic": "people",
    "level": "a2",
    "ex": "Der Termin ist streng.",
    "exEn": "The appointment is strict."
  },
  {
    "id": "a2v12",
    "de": "lustig",
    "art": "",
    "pl": "",
    "en": "funny",
    "topic": "people",
    "level": "a2",
    "ex": "Der Termin ist lustig.",
    "exEn": "The appointment is funny."
  },
  {
    "id": "a2v13",
    "de": "schüchtern",
    "art": "",
    "pl": "",
    "en": "shy",
    "topic": "people",
    "level": "a2",
    "ex": "Ich möchte heute schüchtern.",
    "exEn": "I would like shy today."
  },
  {
    "id": "a2v14",
    "de": "ehrlich",
    "art": "",
    "pl": "",
    "en": "honest",
    "topic": "people",
    "level": "a2",
    "ex": "Der Termin ist ehrlich.",
    "exEn": "The appointment is honest."
  },
  {
    "id": "a2v15",
    "de": "Geduld",
    "art": "die",
    "pl": "",
    "en": "patience",
    "topic": "people",
    "level": "a2",
    "ex": "Das ist die Geduld.",
    "exEn": "This is patience."
  },
  {
    "id": "a2v16",
    "de": "Hilfe",
    "art": "die",
    "pl": "-n",
    "en": "help",
    "topic": "people",
    "level": "a2",
    "ex": "Das ist die Hilfe.",
    "exEn": "This is help."
  },
  {
    "id": "a2v17",
    "de": "Streit",
    "art": "der",
    "pl": "-e",
    "en": "argument",
    "topic": "people",
    "level": "a2",
    "ex": "Das ist der Streit.",
    "exEn": "This is argument."
  },
  {
    "id": "a2v18",
    "de": "sich freuen",
    "art": "",
    "pl": "",
    "en": "to be happy",
    "topic": "people",
    "level": "a2",
    "ex": "Wir wollen uns nicht freuen.",
    "exEn": "We do not want to be happy."
  },
  {
    "id": "a2v19",
    "de": "kennenlernen",
    "art": "",
    "pl": "",
    "en": "to get to know",
    "topic": "people",
    "level": "a2",
    "ex": "Ich möchte heute kennenlernen.",
    "exEn": "I would like to get to know today."
  },
  {
    "id": "a2v20",
    "de": "besuchen",
    "art": "",
    "pl": "",
    "en": "to visit",
    "topic": "people",
    "level": "a2",
    "ex": "Ich möchte heute besuchen.",
    "exEn": "I would like to visit today."
  },
  {
    "id": "a2v21",
    "de": "Miete",
    "art": "die",
    "pl": "-n",
    "en": "rent",
    "topic": "home",
    "level": "a2",
    "ex": "Wo ist die Miete?",
    "exEn": "Where is the rent?"
  },
  {
    "id": "a2v22",
    "de": "Vermieter",
    "art": "der",
    "pl": "-",
    "en": "landlord",
    "topic": "home",
    "level": "a2",
    "ex": "Wo ist der Vermieter?",
    "exEn": "Where is the landlord?"
  },
  {
    "id": "a2v23",
    "de": "Mieter",
    "art": "der",
    "pl": "-",
    "en": "tenant",
    "topic": "home",
    "level": "a2",
    "ex": "Wo ist der Mieter?",
    "exEn": "Where is the tenant?"
  },
  {
    "id": "a2v24",
    "de": "Möbel",
    "art": "die",
    "pl": "",
    "en": "furniture",
    "topic": "home",
    "level": "a2",
    "ex": "Hier sind die Möbel.",
    "exEn": "Here are the furniture."
  },
  {
    "id": "a2v25",
    "de": "Regal",
    "art": "das",
    "pl": "-e",
    "en": "shelf",
    "topic": "home",
    "level": "a2",
    "ex": "Wo ist das Regal?",
    "exEn": "Where is the shelf?"
  },
  {
    "id": "a2v26",
    "de": "Schrank",
    "art": "der",
    "pl": "Schränke",
    "en": "cupboard",
    "topic": "home",
    "level": "a2",
    "ex": "Wo ist der Schrank?",
    "exEn": "Where is the cupboard?"
  },
  {
    "id": "a2v27",
    "de": "Lampe",
    "art": "die",
    "pl": "-n",
    "en": "lamp",
    "topic": "home",
    "level": "a2",
    "ex": "Wo ist die Lampe?",
    "exEn": "Where is the lamp?"
  },
  {
    "id": "a2v28",
    "de": "Heizung",
    "art": "die",
    "pl": "-en",
    "en": "heating",
    "topic": "home",
    "level": "a2",
    "ex": "Wo ist die Heizung?",
    "exEn": "Where is the heating?"
  },
  {
    "id": "a2v29",
    "de": "Nachbarschaft",
    "art": "die",
    "pl": "-en",
    "en": "neighbourhood",
    "topic": "home",
    "level": "a2",
    "ex": "Wo ist die Nachbarschaft?",
    "exEn": "Where is the neighbourhood?"
  },
  {
    "id": "a2v30",
    "de": "ruhig",
    "art": "",
    "pl": "",
    "en": "quiet",
    "topic": "home",
    "level": "a2",
    "ex": "Der Termin ist ruhig.",
    "exEn": "The appointment is quiet."
  },
  {
    "id": "a2v31",
    "de": "laut",
    "art": "",
    "pl": "",
    "en": "loud",
    "topic": "home",
    "level": "a2",
    "ex": "Der Termin ist laut.",
    "exEn": "The appointment is loud."
  },
  {
    "id": "a2v32",
    "de": "umziehen",
    "art": "",
    "pl": "",
    "en": "to move house",
    "topic": "home",
    "level": "a2",
    "ex": "Ich möchte heute umziehen.",
    "exEn": "I would like to move house today."
  },
  {
    "id": "a2v33",
    "de": "einziehen",
    "art": "",
    "pl": "",
    "en": "to move in",
    "topic": "home",
    "level": "a2",
    "ex": "Ich möchte heute einziehen.",
    "exEn": "I would like to move in today."
  },
  {
    "id": "a2v34",
    "de": "ausziehen",
    "art": "",
    "pl": "",
    "en": "to move out",
    "topic": "home",
    "level": "a2",
    "ex": "Ich möchte heute ausziehen.",
    "exEn": "I would like to move out today."
  },
  {
    "id": "a2v35",
    "de": "Schlüssel",
    "art": "der",
    "pl": "-",
    "en": "key",
    "topic": "home",
    "level": "a2",
    "ex": "Wo ist der Schlüssel?",
    "exEn": "Where is the key?"
  },
  {
    "id": "a2v36",
    "de": "Reparatur",
    "art": "die",
    "pl": "-en",
    "en": "repair",
    "topic": "home",
    "level": "a2",
    "ex": "Wo ist die Reparatur?",
    "exEn": "Where is the repair?"
  },
  {
    "id": "a2v37",
    "de": "Waschmaschine",
    "art": "die",
    "pl": "-n",
    "en": "washing machine",
    "topic": "home",
    "level": "a2",
    "ex": "Wo ist die Waschmaschine?",
    "exEn": "Where is the washing machine?"
  },
  {
    "id": "a2v38",
    "de": "Internet",
    "art": "das",
    "pl": "",
    "en": "internet",
    "topic": "home",
    "level": "a2",
    "ex": "Wo ist das Internet?",
    "exEn": "Where is the internet?"
  },
  {
    "id": "a2v39",
    "de": "Stock",
    "art": "der",
    "pl": "Stockwerke",
    "en": "floor",
    "topic": "home",
    "level": "a2",
    "ex": "Wo ist der Stock?",
    "exEn": "Where is the floor?"
  },
  {
    "id": "a2v40",
    "de": "Balkon",
    "art": "der",
    "pl": "-e",
    "en": "balcony",
    "topic": "home",
    "level": "a2",
    "ex": "Wo ist der Balkon?",
    "exEn": "Where is the balcony?"
  },
  {
    "id": "a2v41",
    "de": "Routine",
    "art": "die",
    "pl": "-n",
    "en": "routine",
    "topic": "daily",
    "level": "a2",
    "ex": "Heute geht es um die Routine.",
    "exEn": "Today it is about the routine."
  },
  {
    "id": "a2v42",
    "de": "aufstehen",
    "art": "",
    "pl": "",
    "en": "to get up",
    "topic": "daily",
    "level": "a2",
    "ex": "Ich möchte heute aufstehen.",
    "exEn": "I would like to get up today."
  },
  {
    "id": "a2v43",
    "de": "einkaufen",
    "art": "",
    "pl": "",
    "en": "to shop",
    "topic": "daily",
    "level": "a2",
    "ex": "Ich möchte heute einkaufen.",
    "exEn": "I would like to shop today."
  },
  {
    "id": "a2v44",
    "de": "spazieren gehen",
    "art": "",
    "pl": "",
    "en": "to go for a walk",
    "topic": "daily",
    "level": "a2",
    "ex": "Ich möchte heute spazieren gehen.",
    "exEn": "I would like to go for a walk today."
  },
  {
    "id": "a2v45",
    "de": "Sport treiben",
    "art": "",
    "pl": "",
    "en": "to do sport",
    "topic": "daily",
    "level": "a2",
    "ex": "Ich möchte heute Sport treiben.",
    "exEn": "I would like to do sport today."
  },
  {
    "id": "a2v46",
    "de": "verabreden",
    "art": "",
    "pl": "",
    "en": "to arrange to meet",
    "topic": "daily",
    "level": "a2",
    "ex": "Ich möchte heute verabreden.",
    "exEn": "I would like to arrange to meet today."
  },
  {
    "id": "a2v47",
    "de": "Termin",
    "art": "der",
    "pl": "-e",
    "en": "appointment",
    "topic": "daily",
    "level": "a2",
    "ex": "Heute geht es um den Termin.",
    "exEn": "Today it is about the appointment."
  },
  {
    "id": "a2v48",
    "de": "Stress",
    "art": "der",
    "pl": "",
    "en": "stress",
    "topic": "daily",
    "level": "a2",
    "ex": "Heute geht es um den Stress.",
    "exEn": "Today it is about the stress."
  },
  {
    "id": "a2v49",
    "de": "entspannen",
    "art": "",
    "pl": "",
    "en": "to relax",
    "topic": "daily",
    "level": "a2",
    "ex": "Ich möchte heute entspannen.",
    "exEn": "I would like to relax today."
  },
  {
    "id": "a2v50",
    "de": "Wochenende",
    "art": "das",
    "pl": "-n",
    "en": "weekend",
    "topic": "daily",
    "level": "a2",
    "ex": "Heute geht es um das Wochenende.",
    "exEn": "Today it is about the weekend."
  },
  {
    "id": "a2v51",
    "de": "Feiertag",
    "art": "der",
    "pl": "-e",
    "en": "public holiday",
    "topic": "daily",
    "level": "a2",
    "ex": "Heute geht es um den Feiertag.",
    "exEn": "Today it is about the public holiday."
  },
  {
    "id": "a2v52",
    "de": "Hobby",
    "art": "das",
    "pl": "-s",
    "en": "hobby",
    "topic": "daily",
    "level": "a2",
    "ex": "Heute geht es um das Hobby.",
    "exEn": "Today it is about the hobby."
  },
  {
    "id": "a2v53",
    "de": "Verein",
    "art": "der",
    "pl": "-e",
    "en": "club",
    "topic": "daily",
    "level": "a2",
    "ex": "Heute geht es um den Verein.",
    "exEn": "Today it is about the club."
  },
  {
    "id": "a2v54",
    "de": "Kino",
    "art": "das",
    "pl": "-s",
    "en": "cinema",
    "topic": "daily",
    "level": "a2",
    "ex": "Heute geht es um das Kino.",
    "exEn": "Today it is about the cinema."
  },
  {
    "id": "a2v55",
    "de": "Konzert",
    "art": "das",
    "pl": "-e",
    "en": "concert",
    "topic": "daily",
    "level": "a2",
    "ex": "Heute geht es um das Konzert.",
    "exEn": "Today it is about the concert."
  },
  {
    "id": "a2v56",
    "de": "Museum",
    "art": "das",
    "pl": "Museen",
    "en": "museum",
    "topic": "daily",
    "level": "a2",
    "ex": "Heute geht es um das Museum.",
    "exEn": "Today it is about the museum."
  },
  {
    "id": "a2v57",
    "de": "langweilig",
    "art": "",
    "pl": "",
    "en": "boring",
    "topic": "daily",
    "level": "a2",
    "ex": "Der Termin ist langweilig.",
    "exEn": "The appointment is boring."
  },
  {
    "id": "a2v58",
    "de": "spannend",
    "art": "",
    "pl": "",
    "en": "exciting",
    "topic": "daily",
    "level": "a2",
    "ex": "Der Termin ist spannend.",
    "exEn": "The appointment is exciting."
  },
  {
    "id": "a2v59",
    "de": "müde",
    "art": "",
    "pl": "",
    "en": "tired",
    "topic": "daily",
    "level": "a2",
    "ex": "Der Termin ist müde.",
    "exEn": "The appointment is tired."
  },
  {
    "id": "a2v60",
    "de": "beschäftigt",
    "art": "",
    "pl": "",
    "en": "busy",
    "topic": "daily",
    "level": "a2",
    "ex": "Der Termin ist beschäftigt.",
    "exEn": "The appointment is busy."
  },
  {
    "id": "a2v61",
    "de": "Gericht",
    "art": "das",
    "pl": "-e",
    "en": "dish",
    "topic": "food",
    "level": "a2",
    "ex": "Ich kaufe das Gericht.",
    "exEn": "I am buying the dish."
  },
  {
    "id": "a2v62",
    "de": "Vorspeise",
    "art": "die",
    "pl": "-n",
    "en": "starter",
    "topic": "food",
    "level": "a2",
    "ex": "Ich kaufe die Vorspeise.",
    "exEn": "I am buying the starter."
  },
  {
    "id": "a2v63",
    "de": "Hauptgericht",
    "art": "das",
    "pl": "-e",
    "en": "main course",
    "topic": "food",
    "level": "a2",
    "ex": "Ich kaufe das Hauptgericht.",
    "exEn": "I am buying the main course."
  },
  {
    "id": "a2v64",
    "de": "Nachspeise",
    "art": "die",
    "pl": "-n",
    "en": "dessert",
    "topic": "food",
    "level": "a2",
    "ex": "Ich kaufe die Nachspeise.",
    "exEn": "I am buying the dessert."
  },
  {
    "id": "a2v65",
    "de": "Zutat",
    "art": "die",
    "pl": "-en",
    "en": "ingredient",
    "topic": "food",
    "level": "a2",
    "ex": "Ich kaufe die Zutat.",
    "exEn": "I am buying the ingredient."
  },
  {
    "id": "a2v66",
    "de": "Rezept",
    "art": "das",
    "pl": "-e",
    "en": "recipe",
    "topic": "food",
    "level": "a2",
    "ex": "Ich kaufe das Rezept.",
    "exEn": "I am buying the recipe."
  },
  {
    "id": "a2v67",
    "de": "bestellen",
    "art": "",
    "pl": "",
    "en": "to order",
    "topic": "food",
    "level": "a2",
    "ex": "Ich möchte heute bestellen.",
    "exEn": "I would like to order today."
  },
  {
    "id": "a2v68",
    "de": "empfehlen",
    "art": "",
    "pl": "",
    "en": "to recommend",
    "topic": "food",
    "level": "a2",
    "ex": "Ich möchte heute empfehlen.",
    "exEn": "I would like to recommend today."
  },
  {
    "id": "a2v69",
    "de": "lecker",
    "art": "",
    "pl": "",
    "en": "tasty",
    "topic": "food",
    "level": "a2",
    "ex": "Der Termin ist lecker.",
    "exEn": "The appointment is tasty."
  },
  {
    "id": "a2v70",
    "de": "scharf",
    "art": "",
    "pl": "",
    "en": "spicy",
    "topic": "food",
    "level": "a2",
    "ex": "Der Termin ist scharf.",
    "exEn": "The appointment is spicy."
  },
  {
    "id": "a2v71",
    "de": "vegetarisch",
    "art": "",
    "pl": "",
    "en": "vegetarian",
    "topic": "food",
    "level": "a2",
    "ex": "Der Termin ist vegetarisch.",
    "exEn": "The appointment is vegetarian."
  },
  {
    "id": "a2v72",
    "de": "Rechnung",
    "art": "die",
    "pl": "-en",
    "en": "bill",
    "topic": "food",
    "level": "a2",
    "ex": "Ich kaufe die Rechnung.",
    "exEn": "I am buying the bill."
  },
  {
    "id": "a2v73",
    "de": "Trinkgeld",
    "art": "das",
    "pl": "-er",
    "en": "tip",
    "topic": "food",
    "level": "a2",
    "ex": "Ich kaufe das Trinkgeld.",
    "exEn": "I am buying the tip."
  },
  {
    "id": "a2v74",
    "de": "Allergie",
    "art": "die",
    "pl": "-n",
    "en": "allergy",
    "topic": "food",
    "level": "a2",
    "ex": "Ich kaufe die Allergie.",
    "exEn": "I am buying the allergy."
  },
  {
    "id": "a2v75",
    "de": "Geschmack",
    "art": "der",
    "pl": "Geschmäcker",
    "en": "taste",
    "topic": "food",
    "level": "a2",
    "ex": "Ich kaufe den Geschmack.",
    "exEn": "I am buying the taste."
  },
  {
    "id": "a2v76",
    "de": "Restaurant",
    "art": "das",
    "pl": "-s",
    "en": "restaurant",
    "topic": "food",
    "level": "a2",
    "ex": "Ich kaufe das Restaurant.",
    "exEn": "I am buying the restaurant."
  },
  {
    "id": "a2v77",
    "de": "Imbiss",
    "art": "der",
    "pl": "-e",
    "en": "snack bar",
    "topic": "food",
    "level": "a2",
    "ex": "Ich kaufe den Imbiss.",
    "exEn": "I am buying the snack bar."
  },
  {
    "id": "a2v78",
    "de": "kochen",
    "art": "",
    "pl": "",
    "en": "to cook",
    "topic": "food",
    "level": "a2",
    "ex": "Ich möchte heute kochen.",
    "exEn": "I would like to cook today."
  },
  {
    "id": "a2v79",
    "de": "backen",
    "art": "",
    "pl": "",
    "en": "to bake",
    "topic": "food",
    "level": "a2",
    "ex": "Ich möchte heute backen.",
    "exEn": "I would like to bake today."
  },
  {
    "id": "a2v80",
    "de": "probieren",
    "art": "",
    "pl": "",
    "en": "to try",
    "topic": "food",
    "level": "a2",
    "ex": "Ich möchte heute probieren.",
    "exEn": "I would like to try today."
  },
  {
    "id": "a2v81",
    "de": "Stelle",
    "art": "die",
    "pl": "-n",
    "en": "job / position",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche die Stelle morgen.",
    "exEn": "I need the job / position tomorrow."
  },
  {
    "id": "a2v82",
    "de": "Bewerbung",
    "art": "die",
    "pl": "-en",
    "en": "application",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche die Bewerbung morgen.",
    "exEn": "I need the application tomorrow."
  },
  {
    "id": "a2v83",
    "de": "Lebenslauf",
    "art": "der",
    "pl": "-läufe",
    "en": "CV",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche den Lebenslauf morgen.",
    "exEn": "I need the CV tomorrow."
  },
  {
    "id": "a2v84",
    "de": "Gehalt",
    "art": "das",
    "pl": "Gehälter",
    "en": "salary",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche das Gehalt morgen.",
    "exEn": "I need the salary tomorrow."
  },
  {
    "id": "a2v85",
    "de": "Schicht",
    "art": "die",
    "pl": "-en",
    "en": "shift",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche die Schicht morgen.",
    "exEn": "I need the shift tomorrow."
  },
  {
    "id": "a2v86",
    "de": "Pause",
    "art": "die",
    "pl": "-n",
    "en": "break",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche die Pause morgen.",
    "exEn": "I need the break tomorrow."
  },
  {
    "id": "a2v87",
    "de": "Überstunde",
    "art": "die",
    "pl": "-n",
    "en": "overtime",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche die Überstunde morgen.",
    "exEn": "I need the overtime tomorrow."
  },
  {
    "id": "a2v88",
    "de": "Kollegin",
    "art": "die",
    "pl": "-nen",
    "en": "colleague (f)",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche die Kollegin morgen.",
    "exEn": "I need the colleague (f) tomorrow."
  },
  {
    "id": "a2v89",
    "de": "Chef",
    "art": "der",
    "pl": "-s",
    "en": "boss",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche den Chef morgen.",
    "exEn": "I need the boss tomorrow."
  },
  {
    "id": "a2v90",
    "de": "Chefin",
    "art": "die",
    "pl": "-nen",
    "en": "boss (f)",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche die Chefin morgen.",
    "exEn": "I need the boss (f) tomorrow."
  },
  {
    "id": "a2v91",
    "de": "Praktikum",
    "art": "das",
    "pl": "Praktika",
    "en": "internship",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche das Praktikum morgen.",
    "exEn": "I need the internship tomorrow."
  },
  {
    "id": "a2v92",
    "de": "Ausbildung",
    "art": "die",
    "pl": "-en",
    "en": "apprenticeship",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche die Ausbildung morgen.",
    "exEn": "I need the apprenticeship tomorrow."
  },
  {
    "id": "a2v93",
    "de": "kündigen",
    "art": "",
    "pl": "",
    "en": "to resign / terminate",
    "topic": "work",
    "level": "a2",
    "ex": "Ich möchte heute kündigen.",
    "exEn": "I would like to resign / terminate today."
  },
  {
    "id": "a2v94",
    "de": "übernehmen",
    "art": "",
    "pl": "",
    "en": "to take on",
    "topic": "work",
    "level": "a2",
    "ex": "Ich möchte heute übernehmen.",
    "exEn": "I would like to take on today."
  },
  {
    "id": "a2v95",
    "de": "verantwortlich",
    "art": "",
    "pl": "",
    "en": "responsible",
    "topic": "work",
    "level": "a2",
    "ex": "Der Termin ist verantwortlich.",
    "exEn": "The appointment is responsible."
  },
  {
    "id": "a2v96",
    "de": "pünktlich",
    "art": "",
    "pl": "",
    "en": "punctual",
    "topic": "work",
    "level": "a2",
    "ex": "Der Termin ist pünktlich.",
    "exEn": "The appointment is punctual."
  },
  {
    "id": "a2v97",
    "de": "Erfahrung",
    "art": "die",
    "pl": "-en",
    "en": "experience",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche die Erfahrung morgen.",
    "exEn": "I need the experience tomorrow."
  },
  {
    "id": "a2v98",
    "de": "Aufgabe",
    "art": "die",
    "pl": "-n",
    "en": "task",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche die Aufgabe morgen.",
    "exEn": "I need the task tomorrow."
  },
  {
    "id": "a2v99",
    "de": "Besprechung",
    "art": "die",
    "pl": "-en",
    "en": "meeting",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche die Besprechung morgen.",
    "exEn": "I need the meeting tomorrow."
  },
  {
    "id": "a2v100",
    "de": "Homeoffice",
    "art": "das",
    "pl": "",
    "en": "working from home",
    "topic": "work",
    "level": "a2",
    "ex": "Ich brauche das Homeoffice morgen.",
    "exEn": "I need the working from home tomorrow."
  },
  {
    "id": "a2v101",
    "de": "Versicherung",
    "art": "die",
    "pl": "-en",
    "en": "insurance",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche die Versicherung.",
    "exEn": "I am looking for the insurance."
  },
  {
    "id": "a2v102",
    "de": "Krankenkasse",
    "art": "die",
    "pl": "-n",
    "en": "health insurer",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche die Krankenkasse.",
    "exEn": "I am looking for the health insurer."
  },
  {
    "id": "a2v103",
    "de": "Rezept",
    "art": "das",
    "pl": "-e",
    "en": "prescription",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche das Rezept.",
    "exEn": "I am looking for the prescription."
  },
  {
    "id": "a2v104",
    "de": "Tablette",
    "art": "die",
    "pl": "-n",
    "en": "tablet",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche die Tablette.",
    "exEn": "I am looking for the tablet."
  },
  {
    "id": "a2v105",
    "de": "Fieber",
    "art": "das",
    "pl": "",
    "en": "fever",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche das Fieber.",
    "exEn": "I am looking for the fever."
  },
  {
    "id": "a2v106",
    "de": "Husten",
    "art": "der",
    "pl": "",
    "en": "cough",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche den Husten.",
    "exEn": "I am looking for the cough."
  },
  {
    "id": "a2v107",
    "de": "Schnupfen",
    "art": "der",
    "pl": "",
    "en": "cold (runny nose)",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche den Schnupfen.",
    "exEn": "I am looking for the cold (runny nose)."
  },
  {
    "id": "a2v108",
    "de": "Verletzung",
    "art": "die",
    "pl": "-en",
    "en": "injury",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche die Verletzung.",
    "exEn": "I am looking for the injury."
  },
  {
    "id": "a2v109",
    "de": "Untersuchung",
    "art": "die",
    "pl": "-en",
    "en": "examination",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche die Untersuchung.",
    "exEn": "I am looking for the examination."
  },
  {
    "id": "a2v110",
    "de": "Überweisung",
    "art": "die",
    "pl": "-en",
    "en": "referral",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche die Überweisung.",
    "exEn": "I am looking for the referral."
  },
  {
    "id": "a2v111",
    "de": "Notaufnahme",
    "art": "die",
    "pl": "-n",
    "en": "ER",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche die Notaufnahme.",
    "exEn": "I am looking for the ER."
  },
  {
    "id": "a2v112",
    "de": "gesund",
    "art": "",
    "pl": "",
    "en": "healthy",
    "topic": "health",
    "level": "a2",
    "ex": "Der Termin ist gesund.",
    "exEn": "The appointment is healthy."
  },
  {
    "id": "a2v113",
    "de": "krankschreiben",
    "art": "",
    "pl": "",
    "en": "to sign off sick",
    "topic": "health",
    "level": "a2",
    "ex": "Ich möchte heute krankschreiben.",
    "exEn": "I would like to sign off sick today."
  },
  {
    "id": "a2v114",
    "de": "sich ausruhen",
    "art": "",
    "pl": "",
    "en": "to rest",
    "topic": "health",
    "level": "a2",
    "ex": "Wir wollen uns nicht ausruhen.",
    "exEn": "We do not want to rest."
  },
  {
    "id": "a2v115",
    "de": "weh tun",
    "art": "",
    "pl": "",
    "en": "to hurt",
    "topic": "health",
    "level": "a2",
    "ex": "Ich möchte heute weh tun.",
    "exEn": "I would like to hurt today."
  },
  {
    "id": "a2v116",
    "de": "Impfung",
    "art": "die",
    "pl": "-en",
    "en": "vaccination",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche die Impfung.",
    "exEn": "I am looking for the vaccination."
  },
  {
    "id": "a2v117",
    "de": "Allergie",
    "art": "die",
    "pl": "-n",
    "en": "allergy",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche die Allergie.",
    "exEn": "I am looking for the allergy."
  },
  {
    "id": "a2v118",
    "de": "Augenarzt",
    "art": "der",
    "pl": "-ärzte",
    "en": "eye doctor",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche den Augenarzt.",
    "exEn": "I am looking for the eye doctor."
  },
  {
    "id": "a2v119",
    "de": "Zahnarzt",
    "art": "der",
    "pl": "-ärzte",
    "en": "dentist",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche den Zahnarzt.",
    "exEn": "I am looking for the dentist."
  },
  {
    "id": "a2v120",
    "de": "Apotheke",
    "art": "die",
    "pl": "-n",
    "en": "pharmacy",
    "topic": "health",
    "level": "a2",
    "ex": "Ich suche die Apotheke.",
    "exEn": "I am looking for the pharmacy."
  },
  {
    "id": "a2v121",
    "de": "Reise",
    "art": "die",
    "pl": "-n",
    "en": "trip",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist die Reise?",
    "exEn": "Where is the trip?"
  },
  {
    "id": "a2v122",
    "de": "Fahrplan",
    "art": "der",
    "pl": "-pläne",
    "en": "timetable",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist der Fahrplan?",
    "exEn": "Where is the timetable?"
  },
  {
    "id": "a2v123",
    "de": "Verspätung",
    "art": "die",
    "pl": "-en",
    "en": "delay",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist die Verspätung?",
    "exEn": "Where is the delay?"
  },
  {
    "id": "a2v124",
    "de": "Anschluss",
    "art": "der",
    "pl": "Anschlüsse",
    "en": "connection",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist der Anschluss?",
    "exEn": "Where is the connection?"
  },
  {
    "id": "a2v125",
    "de": "umsteigen",
    "art": "",
    "pl": "",
    "en": "to change trains",
    "topic": "travel",
    "level": "a2",
    "ex": "Ich möchte heute umsteigen.",
    "exEn": "I would like to change trains today."
  },
  {
    "id": "a2v126",
    "de": "buchen",
    "art": "",
    "pl": "",
    "en": "to book",
    "topic": "travel",
    "level": "a2",
    "ex": "Ich möchte heute buchen.",
    "exEn": "I would like to book today."
  },
  {
    "id": "a2v127",
    "de": "Stornierung",
    "art": "die",
    "pl": "-en",
    "en": "cancellation",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist die Stornierung?",
    "exEn": "Where is the cancellation?"
  },
  {
    "id": "a2v128",
    "de": "Gepäck",
    "art": "das",
    "pl": "",
    "en": "luggage",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist das Gepäck?",
    "exEn": "Where is the luggage?"
  },
  {
    "id": "a2v129",
    "de": "Ausweis",
    "art": "der",
    "pl": "-e",
    "en": "ID",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist der Ausweis?",
    "exEn": "Where is the ID?"
  },
  {
    "id": "a2v130",
    "de": "Pass",
    "art": "der",
    "pl": "Pässe",
    "en": "passport",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist der Pass?",
    "exEn": "Where is the passport?"
  },
  {
    "id": "a2v131",
    "de": "Jugendherberge",
    "art": "die",
    "pl": "-n",
    "en": "youth hostel",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist die Jugendherberge?",
    "exEn": "Where is the youth hostel?"
  },
  {
    "id": "a2v132",
    "de": "Einzelzimmer",
    "art": "das",
    "pl": "-",
    "en": "single room",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist das Einzelzimmer?",
    "exEn": "Where is the single room?"
  },
  {
    "id": "a2v133",
    "de": "Doppelzimmer",
    "art": "das",
    "pl": "-",
    "en": "double room",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist das Doppelzimmer?",
    "exEn": "Where is the double room?"
  },
  {
    "id": "a2v134",
    "de": "Sehenswürdigkeit",
    "art": "die",
    "pl": "-en",
    "en": "sight",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist die Sehenswürdigkeit?",
    "exEn": "Where is the sight?"
  },
  {
    "id": "a2v135",
    "de": "Stadtplan",
    "art": "der",
    "pl": "-pläne",
    "en": "city map",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist der Stadtplan?",
    "exEn": "Where is the city map?"
  },
  {
    "id": "a2v136",
    "de": "Ampel",
    "art": "die",
    "pl": "-n",
    "en": "traffic light",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist die Ampel?",
    "exEn": "Where is the traffic light?"
  },
  {
    "id": "a2v137",
    "de": "Tankstelle",
    "art": "die",
    "pl": "-n",
    "en": "petrol station",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist die Tankstelle?",
    "exEn": "Where is the petrol station?"
  },
  {
    "id": "a2v138",
    "de": "Maut",
    "art": "die",
    "pl": "-en",
    "en": "toll",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist die Maut?",
    "exEn": "Where is the toll?"
  },
  {
    "id": "a2v139",
    "de": "Streik",
    "art": "der",
    "pl": "-s",
    "en": "strike",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist der Streik?",
    "exEn": "Where is the strike?"
  },
  {
    "id": "a2v140",
    "de": "Ausflug",
    "art": "der",
    "pl": "Ausflüge",
    "en": "outing",
    "topic": "travel",
    "level": "a2",
    "ex": "Wo ist der Ausflug?",
    "exEn": "Where is the outing?"
  },
  {
    "id": "a2v141",
    "de": "Konto",
    "art": "das",
    "pl": "Konten",
    "en": "account",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie das Konto mit.",
    "exEn": "Please bring the account with you."
  },
  {
    "id": "a2v142",
    "de": "Überweisung",
    "art": "die",
    "pl": "-en",
    "en": "transfer",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie die Überweisung mit.",
    "exEn": "Please bring the transfer with you."
  },
  {
    "id": "a2v143",
    "de": "Bargeld",
    "art": "das",
    "pl": "",
    "en": "cash",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie das Bargeld mit.",
    "exEn": "Please bring the cash with you."
  },
  {
    "id": "a2v144",
    "de": "Karte",
    "art": "die",
    "pl": "-n",
    "en": "card",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie die Karte mit.",
    "exEn": "Please bring the card with you."
  },
  {
    "id": "a2v145",
    "de": "PIN",
    "art": "die",
    "pl": "-s",
    "en": "PIN",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie die PIN mit.",
    "exEn": "Please bring the PIN with you."
  },
  {
    "id": "a2v146",
    "de": "Post",
    "art": "die",
    "pl": "",
    "en": "post office / mail",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie die Post mit.",
    "exEn": "Please bring the post office / mail with you."
  },
  {
    "id": "a2v147",
    "de": "Paket",
    "art": "das",
    "pl": "-e",
    "en": "parcel",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie das Paket mit.",
    "exEn": "Please bring the parcel with you."
  },
  {
    "id": "a2v148",
    "de": "Brief",
    "art": "der",
    "pl": "-e",
    "en": "letter",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie den Brief mit.",
    "exEn": "Please bring the letter with you."
  },
  {
    "id": "a2v149",
    "de": "Formular",
    "art": "das",
    "pl": "-e",
    "en": "form",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie das Formular mit.",
    "exEn": "Please bring the form with you."
  },
  {
    "id": "a2v150",
    "de": "Antrag",
    "art": "der",
    "pl": "Anträge",
    "en": "application form",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie den Antrag mit.",
    "exEn": "Please bring the application form with you."
  },
  {
    "id": "a2v151",
    "de": "Behörde",
    "art": "die",
    "pl": "-n",
    "en": "authority",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie die Behörde mit.",
    "exEn": "Please bring the authority with you."
  },
  {
    "id": "a2v152",
    "de": "Bürgeramt",
    "art": "das",
    "pl": "-ämter",
    "en": "citizens' office",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie das Bürgeramt mit.",
    "exEn": "Please bring the citizens' office with you."
  },
  {
    "id": "a2v153",
    "de": "Anmeldung",
    "art": "die",
    "pl": "-en",
    "en": "registration",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie die Anmeldung mit.",
    "exEn": "Please bring the registration with you."
  },
  {
    "id": "a2v154",
    "de": "Steuer",
    "art": "die",
    "pl": "-n",
    "en": "tax",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie die Steuer mit.",
    "exEn": "Please bring the tax with you."
  },
  {
    "id": "a2v155",
    "de": "Rechnung",
    "art": "die",
    "pl": "-en",
    "en": "invoice",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie die Rechnung mit.",
    "exEn": "Please bring the invoice with you."
  },
  {
    "id": "a2v156",
    "de": "Mahnung",
    "art": "die",
    "pl": "-en",
    "en": "reminder / dunning letter",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie die Mahnung mit.",
    "exEn": "Please bring the reminder / dunning letter with you."
  },
  {
    "id": "a2v157",
    "de": "Frist",
    "art": "die",
    "pl": "-en",
    "en": "deadline",
    "topic": "services",
    "level": "a2",
    "ex": "Bitte bringen Sie die Frist mit.",
    "exEn": "Please bring the deadline with you."
  },
  {
    "id": "a2v158",
    "de": "unterschreiben",
    "art": "",
    "pl": "",
    "en": "to sign",
    "topic": "services",
    "level": "a2",
    "ex": "Ich möchte heute unterschreiben.",
    "exEn": "I would like to sign today."
  },
  {
    "id": "a2v159",
    "de": "ausfüllen",
    "art": "",
    "pl": "",
    "en": "to fill in",
    "topic": "services",
    "level": "a2",
    "ex": "Ich möchte heute ausfüllen.",
    "exEn": "I would like to fill in today."
  },
  {
    "id": "a2v160",
    "de": "beantragen",
    "art": "",
    "pl": "",
    "en": "to apply for",
    "topic": "services",
    "level": "a2",
    "ex": "Ich möchte heute beantragen.",
    "exEn": "I would like to apply for today."
  },
  {
    "id": "a2v161",
    "de": "Meinung",
    "art": "die",
    "pl": "-en",
    "en": "opinion",
    "topic": "opinions",
    "level": "a2",
    "ex": "Die Meinung ist wichtig.",
    "exEn": "The opinion is important."
  },
  {
    "id": "a2v162",
    "de": "Vorschlag",
    "art": "der",
    "pl": "Vorschläge",
    "en": "suggestion",
    "topic": "opinions",
    "level": "a2",
    "ex": "Der Vorschlag ist wichtig.",
    "exEn": "The suggestion is important."
  },
  {
    "id": "a2v163",
    "de": "Vorteil",
    "art": "der",
    "pl": "-e",
    "en": "advantage",
    "topic": "opinions",
    "level": "a2",
    "ex": "Der Vorteil ist wichtig.",
    "exEn": "The advantage is important."
  },
  {
    "id": "a2v164",
    "de": "Nachteil",
    "art": "der",
    "pl": "-e",
    "en": "disadvantage",
    "topic": "opinions",
    "level": "a2",
    "ex": "Der Nachteil ist wichtig.",
    "exEn": "The disadvantage is important."
  },
  {
    "id": "a2v165",
    "de": "finden",
    "art": "",
    "pl": "",
    "en": "to find / think",
    "topic": "opinions",
    "level": "a2",
    "ex": "Wie finden Sie den Kurs?",
    "exEn": "How do you find the course?"
  },
  {
    "id": "a2v166",
    "de": "glauben",
    "art": "",
    "pl": "",
    "en": "to believe",
    "topic": "opinions",
    "level": "a2",
    "ex": "Glauben Sie, dass der Termin stimmt?",
    "exEn": "Do you believe that the appointment is correct?"
  },
  {
    "id": "a2v167",
    "de": "stimmen",
    "art": "",
    "pl": "",
    "en": "to be correct",
    "topic": "opinions",
    "level": "a2",
    "ex": "Die Adresse muss stimmen.",
    "exEn": "The address has to be correct."
  },
  {
    "id": "a2v168",
    "de": "einverstanden",
    "art": "",
    "pl": "",
    "en": "agreed",
    "topic": "opinions",
    "level": "a2",
    "ex": "Ich bin einverstanden mit dem Termin am Dienstag.",
    "exEn": "I agree with the appointment on Tuesday."
  },
  {
    "id": "a2v169",
    "de": "vielleicht",
    "art": "",
    "pl": "",
    "en": "maybe",
    "topic": "opinions",
    "level": "a2",
    "ex": "Der Termin ist vielleicht.",
    "exEn": "The appointment is maybe."
  },
  {
    "id": "a2v170",
    "de": "bestimmt",
    "art": "",
    "pl": "",
    "en": "certainly",
    "topic": "opinions",
    "level": "a2",
    "ex": "Der Termin ist bestimmt.",
    "exEn": "The appointment is certainly."
  },
  {
    "id": "a2v171",
    "de": "leider",
    "art": "",
    "pl": "",
    "en": "unfortunately",
    "topic": "opinions",
    "level": "a2",
    "ex": "Der Termin ist leider.",
    "exEn": "The appointment is unfortunately."
  },
  {
    "id": "a2v172",
    "de": "hoffentlich",
    "art": "",
    "pl": "",
    "en": "hopefully",
    "topic": "opinions",
    "level": "a2",
    "ex": "Der Termin ist hoffentlich.",
    "exEn": "The appointment is hopefully."
  },
  {
    "id": "a2v173",
    "de": "eigentlich",
    "art": "",
    "pl": "",
    "en": "actually",
    "topic": "opinions",
    "level": "a2",
    "ex": "Der Termin ist eigentlich.",
    "exEn": "The appointment is actually."
  },
  {
    "id": "a2v174",
    "de": "trotzdem",
    "art": "",
    "pl": "",
    "en": "nevertheless",
    "topic": "opinions",
    "level": "a2",
    "ex": "Der Bus hat Verspätung, trotzdem komme ich später.",
    "exEn": "The bus is delayed, nevertheless I arrive later."
  },
  {
    "id": "a2v175",
    "de": "deshalb",
    "art": "",
    "pl": "",
    "en": "therefore",
    "topic": "opinions",
    "level": "a2",
    "ex": "Der Zug hat Verspätung, deshalb komme ich später.",
    "exEn": "The train is delayed, so I will arrive later."
  },
  {
    "id": "a2v176",
    "de": "weil",
    "art": "",
    "pl": "",
    "en": "because",
    "topic": "opinions",
    "level": "a2",
    "ex": "Ich bleibe zu Hause, weil ich krank bin.",
    "exEn": "I am staying home because I am ill."
  },
  {
    "id": "a2v177",
    "de": "dass",
    "art": "",
    "pl": "",
    "en": "that",
    "topic": "opinions",
    "level": "a2",
    "ex": "Ich hoffe, dass der Bus pünktlich kommt.",
    "exEn": "I hope that the bus arrives on time."
  },
  {
    "id": "a2v178",
    "de": "wenn",
    "art": "",
    "pl": "",
    "en": "if / when",
    "topic": "opinions",
    "level": "a2",
    "ex": "Wenn der Brief kommt, rufe ich Sie an.",
    "exEn": "If the letter arrives, I will call you."
  },
  {
    "id": "a2v179",
    "de": "obwohl",
    "art": "",
    "pl": "",
    "en": "although",
    "topic": "opinions",
    "level": "a2",
    "ex": "Ich bleibe zu Hause, obwohl ich krank bin.",
    "exEn": "I am staying home although I am ill."
  },
  {
    "id": "a2v180",
    "de": "dann",
    "art": "",
    "pl": "",
    "en": "then",
    "topic": "opinions",
    "level": "a2",
    "ex": "Zuerst der Ausweis, dann das Formular.",
    "exEn": "First the ID card, then the form."
  },
  {
    "id": "a2v181",
    "de": "Nachricht",
    "art": "die",
    "pl": "-en",
    "en": "news / message",
    "topic": "media",
    "level": "a2",
    "ex": "Die Nachricht ist wichtig.",
    "exEn": "The news / message is important."
  },
  {
    "id": "a2v182",
    "de": "Zeitung",
    "art": "die",
    "pl": "-en",
    "en": "newspaper",
    "topic": "media",
    "level": "a2",
    "ex": "Die Zeitung ist wichtig.",
    "exEn": "The newspaper is important."
  },
  {
    "id": "a2v183",
    "de": "Zeitschrift",
    "art": "die",
    "pl": "-en",
    "en": "magazine",
    "topic": "media",
    "level": "a2",
    "ex": "Die Zeitschrift ist wichtig.",
    "exEn": "The magazine is important."
  },
  {
    "id": "a2v184",
    "de": "Internet",
    "art": "das",
    "pl": "",
    "en": "internet",
    "topic": "media",
    "level": "a2",
    "ex": "Das Internet ist wichtig.",
    "exEn": "The internet is important."
  },
  {
    "id": "a2v185",
    "de": "Website",
    "art": "die",
    "pl": "-s",
    "en": "website",
    "topic": "media",
    "level": "a2",
    "ex": "Die Website ist wichtig.",
    "exEn": "The website is important."
  },
  {
    "id": "a2v186",
    "de": "Passwort",
    "art": "das",
    "pl": "-wörter",
    "en": "password",
    "topic": "media",
    "level": "a2",
    "ex": "Das Passwort ist wichtig.",
    "exEn": "The password is important."
  },
  {
    "id": "a2v187",
    "de": "Daten",
    "art": "die",
    "pl": "",
    "en": "data",
    "topic": "media",
    "level": "a2",
    "ex": "Hier sind die Daten.",
    "exEn": "Here are the data."
  },
  {
    "id": "a2v188",
    "de": "Werbung",
    "art": "die",
    "pl": "-en",
    "en": "advertising",
    "topic": "media",
    "level": "a2",
    "ex": "Die Werbung ist wichtig.",
    "exEn": "The advertising is important."
  },
  {
    "id": "a2v189",
    "de": "Wetter",
    "art": "das",
    "pl": "",
    "en": "weather",
    "topic": "media",
    "level": "a2",
    "ex": "Das Wetter ist wichtig.",
    "exEn": "The weather is important."
  },
  {
    "id": "a2v190",
    "de": "Regen",
    "art": "der",
    "pl": "",
    "en": "rain",
    "topic": "media",
    "level": "a2",
    "ex": "Der Regen ist wichtig.",
    "exEn": "The rain is important."
  },
  {
    "id": "a2v191",
    "de": "Sonne",
    "art": "die",
    "pl": "",
    "en": "sun",
    "topic": "media",
    "level": "a2",
    "ex": "Die Sonne ist wichtig.",
    "exEn": "The sun is important."
  },
  {
    "id": "a2v192",
    "de": "Wolke",
    "art": "die",
    "pl": "-n",
    "en": "cloud",
    "topic": "media",
    "level": "a2",
    "ex": "Die Wolke ist wichtig.",
    "exEn": "The cloud is important."
  },
  {
    "id": "a2v193",
    "de": "Temperatur",
    "art": "die",
    "pl": "-en",
    "en": "temperature",
    "topic": "media",
    "level": "a2",
    "ex": "Die Temperatur ist wichtig.",
    "exEn": "The temperature is important."
  },
  {
    "id": "a2v194",
    "de": "Umwelt",
    "art": "die",
    "pl": "",
    "en": "environment",
    "topic": "media",
    "level": "a2",
    "ex": "Die Umwelt ist wichtig.",
    "exEn": "The environment is important."
  },
  {
    "id": "a2v195",
    "de": "Müll",
    "art": "der",
    "pl": "",
    "en": "rubbish",
    "topic": "media",
    "level": "a2",
    "ex": "Der Müll ist wichtig.",
    "exEn": "The rubbish is important."
  },
  {
    "id": "a2v196",
    "de": "recyceln",
    "art": "",
    "pl": "",
    "en": "to recycle",
    "topic": "media",
    "level": "a2",
    "ex": "Ich möchte heute recyceln.",
    "exEn": "I would like to recycle today."
  },
  {
    "id": "a2v197",
    "de": "sparen",
    "art": "",
    "pl": "",
    "en": "to save",
    "topic": "media",
    "level": "a2",
    "ex": "Ich möchte heute sparen.",
    "exEn": "I would like to save today."
  },
  {
    "id": "a2v198",
    "de": "Strom",
    "art": "der",
    "pl": "",
    "en": "electricity",
    "topic": "media",
    "level": "a2",
    "ex": "Der Strom ist wichtig.",
    "exEn": "The electricity is important."
  },
  {
    "id": "a2v199",
    "de": "Heizung",
    "art": "die",
    "pl": "-en",
    "en": "heating",
    "topic": "media",
    "level": "a2",
    "ex": "Die Heizung ist wichtig.",
    "exEn": "The heating is important."
  },
  {
    "id": "a2v200",
    "de": "Klimaanlage",
    "art": "die",
    "pl": "-n",
    "en": "air conditioning",
    "topic": "media",
    "level": "a2",
    "ex": "Die Klimaanlage ist wichtig.",
    "exEn": "The air conditioning is important."
  },
  {
    "id": "a2v201",
    "de": "gewesen",
    "art": "",
    "pl": "",
    "en": "been (sein)",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute gewesen.",
    "exEn": "I would like been (sein) today."
  },
  {
    "id": "a2v202",
    "de": "gehabt",
    "art": "",
    "pl": "",
    "en": "had",
    "topic": "verbs",
    "level": "a2",
    "ex": "Der Termin ist gehabt.",
    "exEn": "The appointment is had."
  },
  {
    "id": "a2v203",
    "de": "gegangen",
    "art": "",
    "pl": "",
    "en": "gone",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute gegangen.",
    "exEn": "I would like gone today."
  },
  {
    "id": "a2v204",
    "de": "gekommen",
    "art": "",
    "pl": "",
    "en": "come",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute gekommen.",
    "exEn": "I would like come today."
  },
  {
    "id": "a2v205",
    "de": "gemacht",
    "art": "",
    "pl": "",
    "en": "done",
    "topic": "verbs",
    "level": "a2",
    "ex": "Der Termin ist gemacht.",
    "exEn": "The appointment is done."
  },
  {
    "id": "a2v206",
    "de": "gesehen",
    "art": "",
    "pl": "",
    "en": "seen",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute gesehen.",
    "exEn": "I would like seen today."
  },
  {
    "id": "a2v207",
    "de": "gesprochen",
    "art": "",
    "pl": "",
    "en": "spoken",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute gesprochen.",
    "exEn": "I would like spoken today."
  },
  {
    "id": "a2v208",
    "de": "geschrieben",
    "art": "",
    "pl": "",
    "en": "written",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute geschrieben.",
    "exEn": "I would like written today."
  },
  {
    "id": "a2v209",
    "de": "gelesen",
    "art": "",
    "pl": "",
    "en": "read",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute gelesen.",
    "exEn": "I would like read today."
  },
  {
    "id": "a2v210",
    "de": "gegessen",
    "art": "",
    "pl": "",
    "en": "eaten",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute gegessen.",
    "exEn": "I would like eaten today."
  },
  {
    "id": "a2v211",
    "de": "getrunken",
    "art": "",
    "pl": "",
    "en": "drunk",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute getrunken.",
    "exEn": "I would like drunk today."
  },
  {
    "id": "a2v212",
    "de": "gefahren",
    "art": "",
    "pl": "",
    "en": "driven",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute gefahren.",
    "exEn": "I would like driven today."
  },
  {
    "id": "a2v213",
    "de": "getroffen",
    "art": "",
    "pl": "",
    "en": "met",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute getroffen.",
    "exEn": "I would like met today."
  },
  {
    "id": "a2v214",
    "de": "genommen",
    "art": "",
    "pl": "",
    "en": "taken",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute genommen.",
    "exEn": "I would like taken today."
  },
  {
    "id": "a2v215",
    "de": "gegeben",
    "art": "",
    "pl": "",
    "en": "given",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute gegeben.",
    "exEn": "I would like given today."
  },
  {
    "id": "a2v216",
    "de": "gefunden",
    "art": "",
    "pl": "",
    "en": "found",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute gefunden.",
    "exEn": "I would like found today."
  },
  {
    "id": "a2v217",
    "de": "gedacht",
    "art": "",
    "pl": "",
    "en": "thought",
    "topic": "verbs",
    "level": "a2",
    "ex": "Der Termin ist gedacht.",
    "exEn": "The appointment is thought."
  },
  {
    "id": "a2v218",
    "de": "gebracht",
    "art": "",
    "pl": "",
    "en": "brought",
    "topic": "verbs",
    "level": "a2",
    "ex": "Der Termin ist gebracht.",
    "exEn": "The appointment is brought."
  },
  {
    "id": "a2v219",
    "de": "gewusst",
    "art": "",
    "pl": "",
    "en": "known",
    "topic": "verbs",
    "level": "a2",
    "ex": "Der Termin ist gewusst.",
    "exEn": "The appointment is known."
  },
  {
    "id": "a2v220",
    "de": "geblieben",
    "art": "",
    "pl": "",
    "en": "stayed",
    "topic": "verbs",
    "level": "a2",
    "ex": "Ich möchte heute geblieben.",
    "exEn": "I would like stayed today."
  },
  {
    "id": "a2v221",
    "de": "weil",
    "art": "",
    "pl": "",
    "en": "because",
    "topic": "connectors",
    "level": "a2",
    "ex": "Ich bleibe zu Hause, weil ich krank bin.",
    "exEn": "I am staying home because I am ill."
  },
  {
    "id": "a2v222",
    "de": "dass",
    "art": "",
    "pl": "",
    "en": "that",
    "topic": "connectors",
    "level": "a2",
    "ex": "Ich hoffe, dass der Bus pünktlich kommt.",
    "exEn": "I hope that the bus arrives on time."
  },
  {
    "id": "a2v223",
    "de": "wenn",
    "art": "",
    "pl": "",
    "en": "if/when",
    "topic": "connectors",
    "level": "a2",
    "ex": "Wenn der Brief kommt, rufe ich Sie an.",
    "exEn": "If the letter arrives, I will call you."
  },
  {
    "id": "a2v224",
    "de": "als",
    "art": "",
    "pl": "",
    "en": "when (past once)",
    "topic": "connectors",
    "level": "a2",
    "ex": "Als ich ankam, war das Amt schon zu.",
    "exEn": "When I arrived, the office was already closed."
  },
  {
    "id": "a2v225",
    "de": "denn",
    "art": "",
    "pl": "",
    "en": "because (V2)",
    "topic": "connectors",
    "level": "a2",
    "ex": "Ich bleibe hier, denn ich warte auf den Arzt.",
    "exEn": "I am staying here, because I am waiting for the doctor."
  },
  {
    "id": "a2v226",
    "de": "deshalb",
    "art": "",
    "pl": "",
    "en": "therefore",
    "topic": "connectors",
    "level": "a2",
    "ex": "Der Zug hat Verspätung, deshalb komme ich später.",
    "exEn": "The train is delayed, so I will arrive later."
  },
  {
    "id": "a2v227",
    "de": "dann",
    "art": "",
    "pl": "",
    "en": "then",
    "topic": "connectors",
    "level": "a2",
    "ex": "Zuerst der Ausweis, dann das Formular.",
    "exEn": "First the ID card, then the form."
  },
  {
    "id": "a2v228",
    "de": "danach",
    "art": "",
    "pl": "",
    "en": "after that",
    "topic": "connectors",
    "level": "a2",
    "ex": "Wir unterschreiben, danach bekommen wir den Schlüssel.",
    "exEn": "We sign, after that we get the key."
  },
  {
    "id": "a2v229",
    "de": "zuerst",
    "art": "",
    "pl": "",
    "en": "first",
    "topic": "connectors",
    "level": "a2",
    "ex": "Der Termin ist zuerst.",
    "exEn": "The appointment is first."
  },
  {
    "id": "a2v230",
    "de": "später",
    "art": "",
    "pl": "",
    "en": "later",
    "topic": "connectors",
    "level": "a2",
    "ex": "Der Termin ist später.",
    "exEn": "The appointment is later."
  },
  {
    "id": "a2v231",
    "de": "bevor",
    "art": "",
    "pl": "",
    "en": "before",
    "topic": "connectors",
    "level": "a2",
    "ex": "Ich bleibe zu Hause, bevor ich krank bin.",
    "exEn": "I am staying home before I am ill."
  },
  {
    "id": "a2v232",
    "de": "nachdem",
    "art": "",
    "pl": "",
    "en": "after",
    "topic": "connectors",
    "level": "a2",
    "ex": "Ich bleibe zu Hause, nachdem ich krank bin.",
    "exEn": "I am staying home after I am ill."
  },
  {
    "id": "a2v233",
    "de": "obwohl",
    "art": "",
    "pl": "",
    "en": "although",
    "topic": "connectors",
    "level": "a2",
    "ex": "Ich bleibe zu Hause, obwohl ich krank bin.",
    "exEn": "I am staying home although I am ill."
  },
  {
    "id": "a2v234",
    "de": "aber",
    "art": "",
    "pl": "",
    "en": "but",
    "topic": "connectors",
    "level": "a2",
    "ex": "Der Termin ist aber.",
    "exEn": "The appointment is but."
  },
  {
    "id": "a2v235",
    "de": "oder",
    "art": "",
    "pl": "",
    "en": "or",
    "topic": "connectors",
    "level": "a2",
    "ex": "Der Termin ist oder.",
    "exEn": "The appointment is or."
  },
  {
    "id": "a2v236",
    "de": "und",
    "art": "",
    "pl": "",
    "en": "and",
    "topic": "connectors",
    "level": "a2",
    "ex": "Der Termin ist und.",
    "exEn": "The appointment is and."
  },
  {
    "id": "a2v237",
    "de": "sondern",
    "art": "",
    "pl": "",
    "en": "but rather",
    "topic": "connectors",
    "level": "a2",
    "ex": "Ich möchte heute sondern.",
    "exEn": "I would like but rather today."
  },
  {
    "id": "a2v238",
    "de": "trotzdem",
    "art": "",
    "pl": "",
    "en": "still",
    "topic": "connectors",
    "level": "a2",
    "ex": "Der Bus hat Verspätung, trotzdem komme ich später.",
    "exEn": "The bus is delayed, still I arrive later."
  },
  {
    "id": "a2v239",
    "de": "also",
    "art": "",
    "pl": "",
    "en": "so / therefore",
    "topic": "connectors",
    "level": "a2",
    "ex": "Der Bus hat Verspätung, also komme ich später.",
    "exEn": "The bus is delayed, so / therefore I arrive later."
  },
  {
    "id": "a2v240",
    "de": "zum Beispiel",
    "art": "",
    "pl": "",
    "en": "for example",
    "topic": "connectors",
    "level": "a2",
    "ex": "Zum Beispiel — das sage ich oft im Amt.",
    "exEn": "For example — I often say that at the office."
  }
],
  vocabTopics: [
  {
    "id": "people",
    "title": "People and relationships",
    "blurb": "Family, character, invitations."
  },
  {
    "id": "home",
    "title": "Housing and living",
    "blurb": "Rent, furniture, neighbours."
  },
  {
    "id": "daily",
    "title": "Daily life and free time",
    "blurb": "Routine, hobbies, plans."
  },
  {
    "id": "food",
    "title": "Food and restaurants",
    "blurb": "Recipes, orders, preferences."
  },
  {
    "id": "work",
    "title": "Work and education",
    "blurb": "Jobs, CV basics, courses."
  },
  {
    "id": "health",
    "title": "Health",
    "blurb": "Symptoms, insurance, pharmacy."
  },
  {
    "id": "travel",
    "title": "Travel and transport",
    "blurb": "Tickets, hotels, problems."
  },
  {
    "id": "services",
    "title": "Bank, post, Amt",
    "blurb": "Forms, appointments, money."
  },
  {
    "id": "opinions",
    "title": "Opinions",
    "blurb": "finden, meiner Meinung nach."
  },
  {
    "id": "media",
    "title": "Media and weather",
    "blurb": "News, phone, climate basics."
  },
  {
    "id": "verbs",
    "title": "Power verbs + Perfekt",
    "blurb": "Participles you must know."
  },
  {
    "id": "connectors",
    "title": "Connector words",
    "blurb": "weil, dass, dann, deshalb."
  },
  {
    "id": "shopping",
    "title": "Shopping and returns",
    "blurb": "Size, receipt, Umtausch, Bestellnummer."
  }
]
};
